### ISSUE TITLE
[INSTALL]: openmpi support on nautilus  

### ISSUE THREAD

**Issue by areinecke** [JCSDA/spack-stack#1006]
### Package name

spack-stack 1.6 on nautilus

### Package version/tag

1.6

### Build options

current

### Installation timeframe

Before openmpi 4.1.5rc2 is removed "near future"

### Other information

From nautilus admins:

It looks like you're using the 4.1.5rc2 (release candidate 2) OpenMPI.  I
would recommend moving to the full release 4.1.5 or 4.1.6.  That rc2 version
was a stepping stone / test install.  We will likely remove it in the near
future.

### WCOSS2

- [ ] Check this box if and only if your package should be installed on WCOSS2 Cactus and Dogwood (all spack-stack packages will be installed on Acorn). If not, you may disregard the rest of the items below and submit this request.

### WCOSS2: Technical & security review list

- [ ] The code is mature, stable, and production ready
- [ ] The code is does not and cannot use the internet, and does not contain URLs (http, https, ftp, etc.) except in comments
- [ ] The package does not contain prebuilt binary files that have not been approved by NCO security review
- [ ] The code has no publicly disclosed cybersecurity vulnerabilities and exposures (search https://cve.mitre.org/cve/)
- [ ] The code is not prohibited by DHS, DOC, NOAA, or NWS
- [ ] The code comes from a trusted source. Trusted sources include other NWS, NOAA, or DOC, agencies, or other Federal agencies that operate at a FISMA high or equivalent level. Additionally, trusted sources could be third-party agencies through which there is an existing SLA on file (such as RedHat).
- [ ] The code is actively maintained and supported (it continues to get updates, patches, etc.)
- [ ] The code is not maintained by a private entity operating in a foreign country (if it is, make a note below)
- [ ] There is sufficient documentation to support maintenance
- [ ] There are no known security vulnerabilities or weaknesses
- [ ] Installing and running the code does not require privileged processes/users
- [ ] There are no software dependencies that are unapproved or have security concerns (if there are, make a note below)
- [ ] There are no concerns related to SA, SI, and SC NIST control families

**Comment by climbfuji** [comment]
Thanks for the heads-up @areinecke. I'll look at this in the next two weeks.

**Comment by climbfuji** [comment]
@areinecke @sking112 I built the current spack-stack develop successfully on Nautilus with openmpi@4.1.6. In addition to submitting the update site config, do you want me to rebuild a particular version or several versions of spack-stack on the system with that OpenMPI version (I am going built separate environments of course, leaving the existing openmpi@4.1.5rc2 installs in place)?

**Comment by climbfuji** [comment]
@areinecke I installed an openmpi-4.1.6 environment for the spack-stack-1.6.0 release and made the same modifications as for the existng unified-env environment (https://github.com/JCSDA/spack-stack/issues/941: netlib, fftw, sp link).

The PR with the site config and documentation changes for spack-stack is: https://github.com/JCSDA/spack-stack/pull/1014
