### ISSUE TITLE
Build an old version of soca-science using spack-stack-1.4.1 on gaea C5/F5

### ISSUE THREAD

**Issue by jieshunzhu** [JCSDA/spack-stack#1007]
I was able to build the same version using spack-stack-1.4.0 on C5 following @climbfuji 's instruction. I could not find spack-stack-1.4.0 on F5, but see 1.4.1. I tried it and got problems in compilations. My log files are here:
/gpfs/f5/cfsrl/scratch/JieShun.Zhu/ng-godas/CODEs/stable-nightly.20220729_iodaconvert_20240102c5spack1.4.1F5/build/**ecbuild.out** and **make.out**

Can anyone help me check my problems? Thanks a lot.

My configure file is copied here:
+++++++++
source /ncrc/home1/JieShun.Zhu/tool/Lmod_init_C5.sh
module unload intel cray-mpich
module unload darshan-runtime
module load PrgEnv-intel/8.3.3
module load intel-classic/2022.2.1
module load cray-mpich/8.1.25
module load python/3.9.12

module use /ncrc/proj/epic/spack-stack/modulefiles
module load ecflow/5.8.4
module load mysql/8.0.36

module use /ncrc/proj/epic/spack-stack/spack-stack-1.4.1/envs/unified-env/install/modulefiles/Core
module load stack-intel/2022.2.1
module load stack-cray-mpich/8.1.25
module load stack-python/3.9.12
#module -t available

module load soca-env/unified-dev
module load fms/release-jcsda

#Set env variables
export MPIRUN=$(which srun)
export WORKLOAD_MANAGER=slurm
+++++++++

**Comment by jieshunzhu** [comment]
@climbfuji I just built spack-stack1.4.0 on C5. Now I am able to build the soca-science version I used before. So the issue can be closed.

**Comment by climbfuji** [comment]
Thanks for resolving this issue yourself! Very much appreciated.
