### ISSUE TITLE
[INSTALL]: ip@5

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#1020]
### Package name

ip

### Package version/tag

5.0.0

### Build options

(existing) +deprecated

### Installation timeframe

1.7.0

### Other information

sp no longer needed; dependent recipes will need updating

**Comment by AlexanderRichert-NOAA** [comment]
Holding off due to openmp/ufs issue

**Comment by climbfuji** [comment]
Closed via https://github.com/JCSDA/spack-stack/pull/1052
