### ISSUE TITLE
Add GSI needed libraries fro Rocky 8 OS 

### ISSUE THREAD

**Issue by hu5970** [JCSDA/spack-stack#1024]
### Package name

unified-env-rocky8

### Package version/tag

unified-env-rocky8

### Build options

none

### Installation timeframe

I am compiling GSI with Rocky 8 on Hera for RRFS.  I see there are spack-stack-1.5.1 and spack-stack-1.6.0:

/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.1/envs/unified-env-rocky8
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/unified-env-rocky8

But there are no "gsi-addon-env-rocky8" that we can use for GSI and RRFS compiling. For example, the one we are using for old OS is:
"/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.1/envs/gsi-addon/install/modulefiles/Core"

Could you add "gsi-addon" to "spack-stack-1.5.1" and "spack-stack-1.6.0"?

### WCOSS2

- [ ] Check this box if and only if your package should be installed on WCOSS2 Cactus and Dogwood (all spack-stack packages will be installed on Acorn). If not, you may disregard the rest of the items below and submit this request.

### WCOSS2: Technical & security review list

- [ ] The code is mature, stable, and production ready
- [ ] The code is does not and cannot use the internet, and does not contain URLs (http, https, ftp, etc.) except in comments
- [ ] The package does not contain prebuilt binary files that have not been approved by NCO security review
- [ ] The code has no publicly disclosed cybersecurity vulnerabilities and exposures (search https://cve.mitre.org/cve/)
- [ ] The code is not prohibited by DHS, DOC, NOAA, or NWS
- [ ] The code comes from a trusted source. Trusted sources include other NWS, NOAA, or DOC, agencies, or other Federal agencies that operate at a FISMA high or equivalent level. Additionally, trusted sources could be third-party agencies through which there is an existing SLA on file (such as RedHat).
- [ ] The code is actively maintained and supported (it continues to get updates, patches, etc.)
- [ ] The code is not maintained by a private entity operating in a foreign country (if it is, make a note below)
- [ ] There is sufficient documentation to support maintenance
- [ ] There are no known security vulnerabilities or weaknesses
- [ ] Installing and running the code does not require privileged processes/users
- [ ] There are no software dependencies that are unapproved or have security concerns (if there are, make a note below)
- [ ] There are no concerns related to SA, SI, and SC NIST control families

**Comment by hu5970** [comment]
@climbfuji We are running RRFS with spack-stack-1.5.1 we we need to have matched Rocky 8 for spack-stack-1.5.1 for GSI. Could you make a Rocky 8 version:
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.1/envs/gsi-addon/install/modulefiles/Core
as soon as possible?

**Comment by RatkoVasic-NOAA** [comment]
@hu5970 gsi addon libraries are compiled under:
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.1/envs/gsi-addon-env-rocky8/install/modulefiles/Core
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/gsi-addon-dev-rocky8/install/modulefiles/Core

Note!!! gsi addon environment names are gsi-addon-**env**-rocky8 (for 1.5.1) and gsi-addon-**dev**-rocky8 (for 1.6.0)

**Comment by hu5970** [comment]
@RatkoVasic-NOAA Thanks, I can use "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.1/envs/gsi-addon-env-rocky8/install/modulefiles/Core" to compile the RRFS now.

**Comment by climbfuji** [comment]
Ok to close?

**Comment by climbfuji** [comment]
@hu5970 Is this ok to close?

**Comment by climbfuji** [comment]
Based on https://github.com/JCSDA/spack-stack/issues/1024#issuecomment-1986627398, I assume we can close this as done.
