### ISSUE TITLE
building error: Error: Terminating after first install failure: FetchError: All fetchers failed for spack-stage-patch-070b1f3aa87f2b56f83aff38afc42157e1692bfaa580276ecdbad2048b818ed7

### ISSUE THREAD

**Issue by sunweihao1997** [JCSDA/spack-stack#1026]
**Describe the bug**
I followed the tutorial of installing new environment on ubuntu22.04, given in the https://spack-stack.readthedocs.io/en/1.6.0/NewSiteConfigs.html. While conduct the command 'spack install [--verbose] [--fail-fast] 2>&1 | tee log.install', during this process it encountered error message as following:

----------------------------------------------------------------------
[+] /home/sun/spack-stack/envs/unified-env.mylinux/install/gcc/11.4.0/gsl-2.7.1-3ygttwk
==> Installing libffi-3.4.4-tbkulaommxepdaiys6sh7ot6xmsvcv3x [40/433]
==> No binary for libffi-3.4.4-tbkulaommxepdaiys6sh7ot6xmsvcv3x found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/d6/d66c56ad259a82cf2a9dfc408b32bf5da52371500b84745f7fb8b645712df676.tar.gz
==> Fetching https://github.com/libffi/libffi/commit/ce077e5565366171aa1b4438749b0922fce887a4.patch?full_index=1
==> Error: FetchError: All fetchers failed for spack-stage-patch-070b1f3aa87f2b56f83aff38afc42157e1692bfaa580276ecdbad2048b818ed7
==> Warning: Skipping build of gobject-introspection-1.78.1-2sfzfbc7w5imy47tudxhtbjmy5vwzyc6 since libffi-3.4.4-tbkulaommxepdaiys6sh7ot6xmsvcv3x failed
......
==> Error: Terminating after first install failure: FetchError: All fetchers failed for spack-stage-patch-070b1f3aa87f2b56f83aff38afc42157e1692bfaa580276ecdbad2048b818ed7

**To Reproduce**
spack install 2>&1 | tee log.install

**Expected behavior**
It seems this error rooted in fetching the libffi? I am not sure how to resolve it.

**System:**
What system(s) are you running the code on?
ubuntu 22.04 (docker)

**Additional context**

**Comment by climbfuji** [comment]
Please try `spack clean -a` and then run `spack install --verbose` again. Does that help?

**Comment by sunweihao1997** [comment]
Hi, thanks for your reply. I have run the command spack clean -a and spack install --verbose 2>&1 | tee log.install. However, it still failed for installing serveral package, as the following picture shows. When look through the log.install, it seems that the common problem for the failed packages is "Error: FetchError: All fetchers failed for.......“

 
![image](https://github.com/JCSDA/spack-stack/assets/108570939/51237085-6b77-4dde-a6e3-0af4f9e0b698)

![image](https://github.com/JCSDA/spack-stack/assets/108570939/dbfd4651-a618-46f5-a6d5-861fc53bd95e)


> Please try `spack clean -a` and then run `spack install --verbose` again. Does that help?

**Comment by climbfuji** [comment]
Is it possible that you are blocked by a firewall?

**Comment by sunweihao1997** [comment]
> Is it possible that you are blocked by a firewall?

Thanks for your reply. Yes, it is. I thought it should be due to the Internet problem, while I try again it finished the installing process successfully. But in the last step I encounter another problem. When I command `spack stack setup-meta-modules`, it gives error message like following:
![image](https://github.com/JCSDA/spack-stack/assets/108570939/42ea3a53-802d-4539-8333-17ec96ae7e57)

I have no idea why it appears. It seems that the environment can not find the compiler, but when I typed the `gcc --version` it do shows:

![image](https://github.com/JCSDA/spack-stack/assets/108570939/f5ffdf85-44dc-42ba-bc34-8e23417f834e)



I also check the configuration which may be relevant,

the result of the command `spack config edit`:
![image](https://github.com/JCSDA/spack-stack/assets/108570939/86ef19c9-52b4-48a6-8d99-73a2901b64f8)

/etc/spack/compilers.yaml:
![image](https://github.com/JCSDA/spack-stack/assets/108570939/2615e6c6-4bc9-4a74-b1cb-d966955a2120)

**Comment by climbfuji** [comment]
Did you run these steps from the instructions?
```
# Check your gcc version then add it to your site compiler config.
gcc --version
spack config add "packages:all:compiler:[gcc@YOUR-VERSION]"

# Example for Red Hat 8 following the above instructions
spack config add "packages:all:providers:mpi:[openmpi@4.1.6]"

# Example for Ubuntu 20.04 or 22.04 following the above instructions
spack config add "packages:all:providers:mpi:[mpich@4.1.1]"
```

**Comment by sunweihao1997** [comment]
> Did you run these steps from the instructions?
> 
> ```
> # Check your gcc version then add it to your site compiler config.
> gcc --version
> spack config add "packages:all:compiler:[gcc@YOUR-VERSION]"
> 
> # Example for Red Hat 8 following the above instructions
> spack config add "packages:all:providers:mpi:[openmpi@4.1.6]"
> 
> # Example for Ubuntu 20.04 or 22.04 following the above instructions
> spack config add "packages:all:providers:mpi:[mpich@4.1.1]"
> ```

Yes I have run this process and it can be find in the spack.yaml
![image](https://github.com/JCSDA/spack-stack/assets/108570939/6e63c6b9-ac12-47f0-a917-4e2b7f839b4b)

**Comment by climbfuji** [comment]
I think the error is that you updated core compilers. You are not supposed to do that and the documentation doesn't tell you to. The core compiler must be something outlandish like the value configured as default (`gcc@4.6`?).

**Comment by sunweihao1997** [comment]
> I think the error is that you updated core compilers. You are not supposed to do that and the documentation doesn't tell you to. The core compiler must be something outlandish like the value configured as default (`gcc@4.6`?).

Hello! The problem has been resolved.

This problem was due to the 9th step in the tutorial, which is not required for ubuntu or redhat and I wrongly conducted that command. Thanks for your help! Hope you have a nice day!
