### ISSUE TITLE
[INSTALL]: Nautilus

### ISSUE THREAD

**Issue by areinecke** [JCSDA/spack-stack#1034]
### Package name

spack-stack

### Package version/tag

1.6

### Build options

use /penguin/openmpi/4.1.6

### Installation timeframe

ASAP

### Other information

1.6 and all previous version of spack-stack have been built with /penguin/openmpi/4.1.5rc2.  This version is no longer supported.  The recommend /penguin/openmpi/4.1.6

### WCOSS2

- [ ] Check this box if and only if your package should be installed on WCOSS2 Cactus and Dogwood (all spack-stack packages will be installed on Acorn). If not, you may disregard the rest of the items below and submit this request.

### WCOSS2: Technical & security review list

- [ ] The code is mature, stable, and production ready
- [ ] The code is does not and cannot use the internet, and does not contain URLs (http, https, ftp, etc.) except in comments
- [ ] The package does not contain prebuilt binary files that have not been approved by NCO security review
- [ ] The code has no publicly disclosed cybersecurity vulnerabilities and exposures (search https://cve.mitre.org/cve/)
- [ ] The code is not prohibited by DHS, DOC, NOAA, or NWS
- [ ] The code comes from a trusted source. Trusted sources include other NWS, NOAA, or DOC, agencies, or other Federal agencies that operate at a FISMA high or equivalent level. Additionally, trusted sources could be third-party agencies through which there is an existing SLA on file (such as RedHat).
- [ ] The code is actively maintained and supported (it continues to get updates, patches, etc.)
- [ ] The code is not maintained by a private entity operating in a foreign country (if it is, make a note below)
- [ ] There is sufficient documentation to support maintenance
- [ ] There are no known security vulnerabilities or weaknesses
- [ ] Installing and running the code does not require privileged processes/users
- [ ] There are no software dependencies that are unapproved or have security concerns (if there are, make a note below)
- [ ] There are no concerns related to SA, SI, and SC NIST control families

**Comment by climbfuji** [comment]
I built spack-stack-1.6.0 (but none of the earlier versions) with openmpi@4.1.6 here a couple of weeks ago:
```
/p/app/projects/NEPTUNE/spack-stack/spack-stack-1.6.0/envs/ue-openmpi416/
```
All that is needed is to replace the `module use` command and the `module load openmpi` command from spack-stack-1.6.0 with the following (after loading the usual modules):
```
module use /p/app/projects/NEPTUNE/spack-stack/spack-stack-1.6.0/envs/ue-openmpi416/install/modulefiles/Core
module load stack-intel/2021.5.0
module load stack-openmpi/4.1.6
module load stack-python/3.10.13
```
See also the latest spack-stack documentation (https://spack-stack.readthedocs.io/en/latest/PreConfiguredSites.html#navy-hpcmp-nautilus)

Can you check if that works? Do you also need that for earlier versions of spack-stack, or is 1.6.0 enough?

**Comment by areinecke** [comment]
When I load stack-openmpi/4.16, I get the following message:

> 20 nautilus08:~/neptune_atmos1/drivers> module load stack-openmpi/4.1.6
> Loading stack-openmpi/4.1.6
>   Loading requirement: penguin/openmpi/4.1.6/intel-classic-2022.0.2 slurm

Just want to make sure that that is the expected behavior

**Comment by climbfuji** [comment]
I think that is correct. I get this, which worked for testing with jedi-bundle:
```
$ umask 0022
$ module purge

$ module load slurm
$ module load intel/compiler/2022.0.2
Loading compiler version 2022.0.2
Loading tbb version 2021.9.0
Loading compiler-rt version 2023.1.0
Loading oclfpga version 2023.1.0
  Load "debugger" to debug DPC++ applications with the gdb-oneapi debugger.
  Load "dpl" for additional DPC++ APIs: https://github.com/oneapi-src/oneDPL

Loading intel/compiler/2022.0.2
  Loading requirement: intel/tbb/latest intel/compiler-rt/latest intel/oclfpga/latest
$ module load penguin/openmpi/4.1.6/intel-classic-2022.0.2

$ module use /p/app/projects/NEPTUNE/spack-stack/modulefiles
$ module load ecflow/5.8.4
$ module use /p/app/projects/NEPTUNE/spack-stack/spack-stack-1.6.0/envs/ue-openmpi416/install/modulefiles/Core
$ module load stack-intel/2021.5.0
$ module load stack-openmpi/4.1.6
$ module load stack-python/3.10.13
Loading stack-python/3.10.13
  Loading requirement: tar/1.30 gettext/0.21.1 libxcrypt/4.4.35 zlib/1.2.13 sqlite/3.43.2 util-linux-uuid/2.38.1 python/3.10.13

$ module li
Currently Loaded Modulefiles:
 1) slurm                      4) intel/oclfpga/latest                           7) ecflow/5.8.4          10) tar/1.30          13) zlib/1.2.13             16) python/3.10.13
 2) intel/tbb/latest           5) intel/compiler/2022.0.2                        8) stack-intel/2021.5.0  11) gettext/0.21.1    14) sqlite/3.43.2           17) stack-python/3.10.13
 3) intel/compiler-rt/latest   6) penguin/openmpi/4.1.6/intel-classic-2022.0.2   9) stack-openmpi/4.1.6   12) libxcrypt/4.4.35  15) util-linux-uuid/2.38.1
```

**Comment by areinecke** [comment]
the NEPTUNE build failed with in the compilation of CCPP.  Not sure why it's trying to install the ccpp_framework library into /usr/local/lib or why the version of spack-stack should make a difference, unless it's some CMAKE thing?

```
Install the project...
/p/app/projects/NEPTUNE/spack-stack/spack-stack-1.6.0/envs/ue-openmpi416/install/intel/2021.5.0/cmake-3.23.1-l5uiid2/bin/cmake -P cmake_install.cmake
-- Install configuration: "Release"
-- Installing: /usr/local/lib/libccpp_framework.a
CMake Error at ccpp-framework/src/cmake_install.cmake:46 (file):
  file INSTALL cannot copy file
  "/p/home/reinecke/neptune_atmos1/external/ccpp/build/ccpp-framework/src/libccpp_framework.a"
  to "/usr/local/lib/libccpp_framework.a": Permission denied.
Call Stack (most recent call first):
  ccpp-framework/cmake_install.cmake:47 (include)
  cmake_install.cmake:47 (include)
```

**Comment by climbfuji** [comment]
> the NEPTUNE build failed with in the compilation of CCPP. Not sure why it's trying to install the ccpp_framework library into /usr/local/lib or why the version of spack-stack should make a difference, unless it's some CMAKE thing?
> 
> ```
> Install the project...
> /p/app/projects/NEPTUNE/spack-stack/spack-stack-1.6.0/envs/ue-openmpi416/install/intel/2021.5.0/cmake-3.23.1-l5uiid2/bin/cmake -P cmake_install.cmake
> -- Install configuration: "Release"
> -- Installing: /usr/local/lib/libccpp_framework.a
> CMake Error at ccpp-framework/src/cmake_install.cmake:46 (file):
>   file INSTALL cannot copy file
>   "/p/home/reinecke/neptune_atmos1/external/ccpp/build/ccpp-framework/src/libccpp_framework.a"
>   to "/usr/local/lib/libccpp_framework.a": Permission denied.
> Call Stack (most recent call first):
>   ccpp-framework/cmake_install.cmake:47 (include)
>   cmake_install.cmake:47 (include)
> ```

That is weird. cmake version is the same between 1.6.0 unified-env and 1.6.0 ue-openmpi416. Wondering what is triggering the install, usually this only gets triggered by `make install`. Any changes to CCPP between what used to work and now?

**Comment by areinecke** [comment]
The code is the same that built with the previous spack-stack version.  Here is a partial diff between the cmake_install.cmake file that is throwing the error.  The only difference is the version of spack-stack that is loaded.

```
10 nautilus05:~/neptune_atmos1/external/ccpp> diff ~/neptune_atmos{1,2}/external/ccpp/build/ccpp-framework/src/cmake_install.cmake
5c5
<   set(q"/usr/local")
---
>   set(CMAKE_INSTALL_PREFIX "/p/home/reinecke/neptune_atmos2")
```

`CMAKE_INSTALL_PREFIX ` is set in the `build_ccpp.sh` script where it sets
```
CCPP_CMAKE_FLAGS="-DCMAKE_INSTALL_PREFIX=${CCPP_DIR} -DNETCDF_DIR=${NETCDF} -DMPI=ON"
```

**Comment by climbfuji** [comment]
This is difficult to debug for me - once I have access to the code (and know the steps how to build it), I can help. I am puzzled because I don't see how changing the openmpi version can have any effect on where cmake wants to install code.

**Comment by areinecke** [comment]
This works for me now.

**Comment by climbfuji** [comment]
Yay. Closing, thanks for letting me know.
