### ISSUE TITLE
Support for Nvidia compilers

### ISSUE THREAD

**Issue by dustinswales** [JCSDA/spack-stack#1036]
**Overview**
We want to be able to build a limited software stack for the UFS Weather Model, consisting of just the pieces that are needed for the Atmospheric component. 
Some dependencies in the UFS spack-stack are only needed for coupled simulations and/or inline post-processing, which we don't need for ATM only. (This is fortunate since some of these dependencies aren't currently compatible with Nvidia.)

The [UFS common software stack](https://github.com/ufs-community/ufs-weather-model/blob/develop/modulefiles/ufs_common.lua) (below), with the dependencies of only the atmospheric component highlighted in bold.
 
  jasper			@ “2.0.32"			-- inline post dependency
  **_zlib			@ "1.2.13"_**
  libpng			@ “1.6.37"			-- inline post dependency
  _**hdf5			@ "1.14.0"
  netcdf-c		@ "4.9.2"},
  netcdf-fortran	@ "4.6.0"
  parallelio		@ "2.5.10"
  esmf			@ "8.5.0"
  fms			@ "2023.02.01"
  bacio			@ "2.4.1"**_
  crtm			@ "2.4.0"			-- inline post dependency
  g2				@ "3.4.5"			-- inline post dependency
  g2tmpl			@ "1.10.2"			-- inline post dependency
  ip				@ "4.3.0"				-- inline post dependency
  **_sp				@ "2.3.3"
  w3emc			@ "2.10.0"_**
  gftl-shared		@ "1.6.1"				-- coupled model dependency
  mapl			@ "2.40.3-esmf-8.5.0"	-- coupled model dependency
  scotch			@ "7.0.4"				-- coupled model dependency

For the CCPP SCM, which has a smaller list of dependencies (zlib, hdf5, netcdf-c, netcdf-fortran, bacio, sp, w3emc, bufr), we were able to build the dependencies with Nvidia on Hera to test GPU offloading within the physics schemes. 

The other three dependencies, ParallelIO, FMS, and ESMF, can be built with nvhpc/24.1 (The latest version on Hera), we just need some expertise/assistance, and ultimately these all be bundled together.

**Desired outcome**
A Nvidia spack-stack installed on Hera with these highlighted libraries.
I notice that all the supported spack-stacks are Intel/GNU. How feasible is it to extend to support Nvidia?

@DusanJovic-NOAA @grantfirl

**Comment by climbfuji** [comment]
nvidia is currently not a top priority for JCSDA, therefore I can't commit to anything here. But maybe our EPIC and EMC colleagues can?

**Comment by climbfuji** [comment]
@dustinswales Note that I recently merged a PR for an `mpas-jedi-nvidia` environment that builds everything required for `mpas-jedi` with `nvhpc`. May be worth taking a look? https://github.com/JCSDA/spack-stack/pull/1084

**Comment by climbfuji** [comment]
@dustinswales Any updates on this? Did the mpas-jedi-nvidia template help that I created?

**Comment by dustinswales** [comment]
@climbfuji No updates.
This project came to an end, and I'm not sure of it's future.

**Comment by climbfuji** [comment]
Ok, then let me close this issue for now.
