### ISSUE TITLE
Update ESMF url_for_version to support new tagging scheme

### ISSUE THREAD

**Issue by kgerheiser** [JCSDA/spack-stack#104]
ESMF has changed it beta snapshot tagging scheme is now something like v8.3.0b09, compared to ESMF_8_3_0_beta_snapshot_09. This necessitates a change in `url_for_version` in its `package.py`.

I've sent a query to ESMF support to ask whether this will apply to all new releases going forward.

**Comment by climbfuji** [comment]
@kgerheiser Looks like this has been done?

**Comment by kgerheiser** [comment]
Yes
