### ISSUE TITLE
dask module for advanced xarray use

### ISSUE THREAD

**Issue by Dooruk** [JCSDA/spack-stack#1043]
xarray's reading multiple datasets (`open_mfdataset`) function requires `dask` module which is currently not available with the Discover spack-stack modules.

@mathomp4 pointed me to the following issue where `dask` is mentioned briefly: https://github.com/JCSDA/spack-stack/issues/242

@asewnath mentioned `EVA` would also benefit from using `dask`.

**Comment by climbfuji** [comment]
We can look into this for spack-stack-1.8.0 release scheduled around June. We are currently in the process of releasing 1.7.0 and it's too late to include such a change. But we can make a test install available in between those three months.

**Comment by Dooruk** [comment]
Thanks @climbfuji, that works for us!

**Comment by climbfuji** [comment]
FYI, I started working on this
