### ISSUE TITLE
cprnc fails on hercules SS/1.6 w/ intel and "big" files but works fine for gnu

### ISSUE THREAD

**Issue by DeniseWorthen** [JCSDA/spack-stack#1053]
**Describe the bug**

On Hercules, comparing files w/ cprnc fails if I use intel for "large" files but works w/ "small" files. Using GNU works for both. In this case, "large" files are not actually large...only 500M. The "small" file is 40M.

**To Reproduce**
log in to hercules in a clean environment and load the 1.6 stack

```
hercules:~> module list
No modules loaded
hercules:~> module use /work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-1.6.0/envs/unified-env/install/modulefiles/Core/
hercules:~> module spider cprnc

----------------------------------------------------------------------------------------------------------------------------------
  cprnc: cprnc/1.0.3
----------------------------------------------------------------------------------------------------------------------------------

    You will need to load all module(s) on any one of the lines below before the "cprnc/1.0.3" module is available to load.

      stack-gcc/12.2.0  mvapich2/2.3.7
      stack-gcc/12.2.0  stack-mvapich2/2.3.7
      stack-intel/2021.9.0  stack-intel-oneapi-mpi/2021.9.0

hercules:~> module load stack-intel/2021.9.0  stack-intel-oneapi-mpi/2021.9.0 cprnc/1.0.3

hercules:~> cprnc -m small.file1.nc small.file2.nc 
...generates expected output

hercules:~> cprnc -m big.file1.nc big.file2.nc
 file 1=big.file1.nc
 file 2=big.file2.nc
 Attribute history from file1:
 created on 20240403 from /work/noaa/global/glopara/fix/mom6/20220805/025/ocean_
 hgrid.nc does not match that found on file2:
 created on 20240402 from /work/noaa/global/glopara/fix/mom6/20220805/025/ocean_
 hgrid.nc
 Dimension ni matches
 Dimension nj matches
 Dimension nv matches
 Could not find match for file2 variable angle in file1
 Could not find match for file2 variable angchk in file1
 wet   (ni,nj)
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
libc.so.6          00007FFB39106D90  Unknown               Unknown  Unknown
libnetcdff.so.7.2  00007FFB3969B89B  netcdf_mp_nf90_ge     Unknown  Unknown
cprnc              00000000004219AC  Unknown               Unknown  Unknown
cprnc              0000000000420A3E  Unknown               Unknown  Unknown
cprnc              00000000004132F3  Unknown               Unknown  Unknown
cprnc              0000000000412C7D  Unknown               Unknown  Unknown
libc.so.6          00007FFB390F1EB0  Unknown               Unknown  Unknown
libc.so.6          00007FFB390F1F60  __libc_start_main     Unknown  Unknown
cprnc              0000000000412B95  Unknown               Unknown  Unknown
```

Repeating the procedure, but loading the GNU modules 

```
hercules:~> module load stack-gcc/12.2.0  stack-mvapich2/2.3.7 cprnc/1.0.3
hercules:~> cprnc -m small.file1.nc small.file2.nc 
...generates expected output

hercules:~> cprnc -m big.file1.nc big.file2.nc
...generates expected output
```
**Expected behavior**
Both intel and GNU should work for cprnc.

**System:**
Hercules and Hera (R8)

**Additional context**
Repeating the steps for Hera both intel and gnu work as expected for the same set of files. 

On hera

```
module use /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/unified-env-rocky8/install/modulefiles/Core/

then
module load stack-intel/2021.5.0  stack-intel-oneapi-mpi/2021.5.1 cprnc/1.0.3
or 
module load stack-gcc/9.2.0  stack-openmpi/4.1.5 cprnc/1.0.3
```

**Comment by climbfuji** [comment]
Have you looked at `ulimit`, in particular the stacksize?

**Comment by DeniseWorthen** [comment]
@climbfuji Good catch. Yes, I can set ``ulimit -s unlimited`` on Hercules w/ intel and it works. Is this something we should have in our bashrc? And if yes, should it be unlimited?

**Comment by climbfuji** [comment]
I remember that the sysadmins have a large yet not "unlimited" default on hera. I assume this will also work for that testcase on Hercules. "unlimited" is usually save to use, though, but there are certain pieces of software that trip over it - therefore I don't typically recommend it as a default setting. That said, in my 20 years in this business, I've come across one single software (an ancient FTP client) that thought there was no memory left when I used "unlimited".

**Comment by DeniseWorthen** [comment]
On Hera, I see
```
[Hera: hfe08] /scratch1/NCEPDEV/climate/Denise.Worthen: ulimit -a
stack size              (kbytes, -s) 300000
```

On Hercules I see

```
hercules:~> ulimit -a
stack size                  (kbytes, -s) 16384
```

edit: @climbfuji How is this/can it be set in a user's bashrc? I tried add ``ulimit -s 300000`` and it complains.

**Comment by climbfuji** [comment]
What does "it complains" mean? An error message would be more useful.

**Comment by DeniseWorthen** [comment]
I added to my .bashrc

ulimit -s 300000

Then
```
hercules:~> source .bashrc
-bash: ulimit: stack size: cannot modify limit: Operation not permitted
```

I also tried (after looking at heradocs) ``ulimit -S -s 300000`` and got

```
-bash: ulimit: stack size: cannot modify limit: Invalid argument
```

**Comment by climbfuji** [comment]
That has probably nothing to do with it being in `.bashrc`. Can you run it by hand? If not, sysadmins may not allow you to do set it to that particular number and your only option is `unlimited`.

Regardless, my recommendation is to not add these things in `.bashrc` - you forget that you have a bunch of settings in there and then suddenly you can't figure out why something isn't working.

I usually have little `setenv_*` scripts in my default path that I source *intentionally* for the given workload, for example on my macOS:
```
-rwxr-xr-x@ 1 heinzell  1202617992  1347 Apr  2 09:21 /Users/heinzell/bin/setenv_develop_homebrew_arch64-spack-stack-1.6.0.sh
-rwxr-xr-x@ 1 heinzell  1202617992  1347 Apr  2 09:21 /Users/heinzell/bin/setenv_develop_homebrew_arch64-spack-stack-1.7.0.sh
-rwxr-xr-x@ 1 heinzell  1202617992  1017 Oct  4 16:51 /Users/heinzell/bin/setenv_develop_homebrew_arch64.sh
-rwxr-xr-x@ 1 heinzell  1202617992   782 Aug 14  2023 /Users/heinzell/bin/setenv_develop_homebrew_x86_64.sh
```
As part of these setenv scripts, I am also modifying the prompt (`PS1`) that then tells be immediately what my current shell is configured for. It's one more command to run after logging in (`source /path/to/setenv_xyz.sh`) but it's worth it in my opinion. But that's just my 2c.

**Comment by DeniseWorthen** [comment]
@climbfuji Thanks. Your 2c is more like 25c....I've definitely fallen into the trap of forgetting something was set in my bashrc.  

At least at this point I have 2 options on hercules, either setting the gnu stack or manually resetting the ulimit. If you want to consider this resolved, that is OK. It seems odd intel fails, but there is a known work-around.

**Comment by climbfuji** [comment]
Ok, I'll close this. Thanks!
