### ISSUE TITLE
Problems of zlib-ng with intel@2021.5.0 on some - not all - systems

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#1055]
**Describe the bug**

We have noted problems on some - not all - platforms with ``intel@2021.5.0`` when we switched from ``zlib`` to ``zlib-ng`` in spack-stack-1.7.0. These issues went away when using a different version of the compiler (anything between 2021.3.0 and 2021.11.0).

One problem users have reported is errors when using `git clone`:
```
fatal: The remote end hung up unexpectedly
```
Another problem seems to be running `pip install`.

It is therefore recommended to avoid using ``intel@2021.5.0`` unless it is the only option - add this to our compiler compatibility table.

**To Reproduce**
On Discover SCU16 or S4, build unified environment for spack-stack-1.7.0 with `intel@2021.5.0` and try to run `git clone`

**Expected behavior**
None of the errors described above

**System:**
Discover SCU16 and S4 (these are the one we know are affected), potentially others

**Additional context**
n/a

**Comment by AlexanderRichert-NOAA** [comment]
Any chance the affected systems are Rocky/RHEL derivatives? :upside_down_face:

**Comment by climbfuji** [comment]
One is SLES12 and another is CentOS 7.9 - Rocky 8 and Penguin seem to be fine ?!??!

**Comment by climbfuji** [comment]
This has been resolved by
- moving to intel@2021.6.0 on Discover SCU16
- modifying the `zlib-api` provider on S4 only to `zlib` instead of `zlib-ng`
- checking that none of the other platforms using `intel@2021.5.0` is affected
