### ISSUE TITLE
Add support for gcc@13

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#1061]
**Is your feature request related to a problem? Please describe.**
Make all packages compile with gcc@13 (13.2, 13.1?)

**Describe the solution you'd like**
See above

**Additional context**
n/a

**Comment by ulmononian** [comment]
@RatkoVasic-NOAA @natalie-perlin fyi

**Comment by climbfuji** [comment]
FWIW, I was able to build `neptune-env +python` with `gcc@13.1.0`. I was also able to build it with `gcc@14.1.0` (except `hdf@4.2.15`). There are a lot of Python packages included in this environment, so I am hopeful that we can build most of the unified environment out of the box with `gcc@13`.

**Comment by natalie-perlin** [comment]
There are only a couple of packages that give the ICE (internal compiler error). Unless these packages are not required in a given environment, the rest of the installation may go OK.

**Comment by climbfuji** [comment]
Closed via  https://github.com/JCSDA/spack/pull/457
