### ISSUE TITLE
Spack-stack 1.7.0 failing with Intel 2018.4 on Orion

### ISSUE THREAD

**Issue by RatkoVasic-NOAA** [JCSDA/spack-stack#1063]
**Describe the bug**
Spack-stack 1.7.0 failing with Intel 2018.4 on Orion

**To Reproduce**
Install spack-stack 1.7.0 on Orion, Intel environment

**Expected behavior**
Fails with "internal compiler error"

**System:**
Orion

**Additional context**
Fixed by removing 2018.4 from compilers.yaml and package.yaml files.

**Comment by climbfuji** [comment]
Closed via https://github.com/JCSDA/spack-stack/pull/1064 - thanks @RatkoVasic-NOAA
