### ISSUE TITLE
Update shapely from 1.8.0 to latest version 2.x.y

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#1065]
**Is your feature request related to a problem? Please describe.**

We should update `py-shapely` to the latest version 2.x.y. It's currently pinned to 1.8.0 because of JEDI-EWOK. I created an issue in the JCSDA-internal skylab repo to update the plotting scripts to work with new versions of the package (https://github.com/JCSDA-internal/skylab/issues/439).

Let's try to target spack-stack-1.8.0 for this update. It will hopefully allow us to use newer versions of dependencies for `py-shapely`, too.

**Describe the solution you'd like**
See above

**Additional context**
n/a

**Comment by shlyaeva** [comment]
I can not find `shapely` used anywhere in the jcsda workflow repos (except for the environment yaml in ewok: https://github.com/JCSDA-internal/ewok/blame/develop/environment.yml#L17). Since I'm not an expert, I'll see if I can get more info on this from workflow developers. cc @srherbener @eap.

**Comment by climbfuji** [comment]
> I can not find `shapely` used anywhere in the jcsda workflow repos (except for the environment yaml in ewok: https://github.com/JCSDA-internal/ewok/blame/develop/environment.yml#L17). Since I'm not an expert, I'll see if I can get more info on this from workflow developers. cc @srherbener @eap.

It's used for plotting (I believe the diagplots package used for the web display of skylab stuff?) Need to ask @ericlingerfelt

**Comment by ericlingerfelt** [comment]
Hi All - 

It was required to create plots on the Earth in SIMOBS. Other versions failed to create the plots. 

See https://github.com/JCSDA-internal/SIMOBS/blob/develop/setup.py. 

Eric

**Comment by climbfuji** [comment]
Thanks. That code will need to be updated when we update shapely to the latest version in spack-stack-1.8.0.

**Comment by srherbener** [comment]
@BenjaminRuston could you help us get this issue resolved. For spack-stack-1.9.0, we would like to upgrade shapely to the latest version: 2.0.6. Could someone from the OBS team look into this and get the simobs dependency (see https://github.com/JCSDA/spack-stack/issues/1065#issuecomment-2231624971 above) on version 1.8.0 removed? Thank you for your help with this!

**Comment by climbfuji** [comment]
I'll have a PR going very soon for this and other version updates. I'll ping you once it is ready
