### ISSUE TITLE
Fix bug for mapl in 1.7.0

### ISSUE THREAD

**Issue by RatkoVasic-NOAA** [JCSDA/spack-stack#1070]
**Describe the bug**
Wrong version of mapl was installed on Orion, Hercules, Gaea and Derecho.

**To Reproduce**
Install spack-stack 1.7.0 on Orion, Hercules, Gaea or Derecho
mapl@2.43.0 intead of mapl@2.40.3 was installed

**Expected behavior**
Fixx was applied and problem was solved

**System:**
Orion, Hercules, Gaea and Derecho

**Comment by climbfuji** [comment]
Closed via https://github.com/JCSDA/spack-stack/pull/1071
