### ISSUE TITLE
[INSTALL]: ESMF 8.7.0 beta snapshot 4 (NRL machines only)

### ISSUE THREAD

**Issue by areinecke** [JCSDA/spack-stack#1079]
### Package name

ESMF 

### Package version/tag

8.7.0 

### Build options

Need to install snapshot

### Installation timeframe

No specific timeline for a release.

### Other information

This is only needed on the NRL machines. Once the official release 8.7.1 is out, we can add it to the 1.7.0 release everywhere (or defer to 1.8.0, depending on the timeline).

### WCOSS2

- [ ] Check this box if and only if your package should be installed on WCOSS2 Cactus and Dogwood (all spack-stack packages will be installed on Acorn). If not, you may disregard the rest of the items below and submit this request.

### WCOSS2: Technical & security review list

- [ ] The code is mature, stable, and production ready
- [ ] The code is does not and cannot use the internet, and does not contain URLs (http, https, ftp, etc.) except in comments
- [ ] The package does not contain prebuilt binary files that have not been approved by NCO security review
- [ ] The code has no publicly disclosed cybersecurity vulnerabilities and exposures (search https://cve.mitre.org/cve/)
- [ ] The code is not prohibited by DHS, DOC, NOAA, or NWS
- [ ] The code comes from a trusted source. Trusted sources include other NWS, NOAA, or DOC, agencies, or other Federal agencies that operate at a FISMA high or equivalent level. Additionally, trusted sources could be third-party agencies through which there is an existing SLA on file (such as RedHat).
- [ ] The code is actively maintained and supported (it continues to get updates, patches, etc.)
- [ ] The code is not maintained by a private entity operating in a foreign country (if it is, make a note below)
- [ ] There is sufficient documentation to support maintenance
- [ ] There are no known security vulnerabilities or weaknesses
- [ ] Installing and running the code does not require privileged processes/users
- [ ] There are no software dependencies that are unapproved or have security concerns (if there are, make a note below)
- [ ] There are no concerns related to SA, SI, and SC NIST control families

**Comment by climbfuji** [comment]
@areinecke I have the PRs open for spack-stack develop. You can cherry-pick those commits in your spack-stack-1.7.0 clone:
```
cd spack
git remote update
git cherry-pick 705f514e1b68de861e8683f540f11e37d7216f9a
cd ..
git remote update
git cherry-pick 854b1d5af1faf0d08bdd8b2536359ac69d1d7ea9
```
and then add the following two lines to the list of packages in `envs/your-env-name/spack.yaml`, like this:
```
...
  definitions:
  - compilers: ['%apple-clang']
  - packages:
    ...
    - esmf@8.7.0b04 snapshot=b04
```
Then run `spack concretize` again, followed by `spack install`. Please let me know how that goes!

**Comment by climbfuji** [comment]
@areinecke I merged the PR for spack-develop. When you've confirmed that cherry-picking the commits as described above works, then we can close the issue. Thanks!

**Comment by climbfuji** [comment]
We can close this as done. esmf@8.7.0b04 is installed on the relevant NRL platforms and works as expected.
