### ISSUE TITLE
eckit (1.18.0) fails to build with intel on macOS

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#108]
Here is the original issue posted by @kgerheiser in the eckit github repository: https://github.com/ecmwf/eckit/issues/44. Having an issue here will help us remember.

**Comment by climbfuji** [comment]
We are using eckit@1.19.0 - need to check if this is still a problem.

**Comment by climbfuji** [comment]
The next version of spack-stack will have `eckit@1.20.2` as default. We haven't tried yet whether newer versions than 1.18.0 build on macOS with Intel

**Comment by rjdave** [comment]
**OS:** MacOS Big Sur
**Compiler:** Intel 2022.2.1 (oneAPI 2021.7.1 and how spack sees it)

I can attest that the problem persists with 1.20.2. As a workaround, I created a patch (hack really), placed it in `spack/var/spack/repos/builtin/packages/eckit`, and added it to the eckit `package.py` file and eckit built correctly. It really needs either conditionals in the `package.py` file around the `patch()` command for platform and compiler, or logic like @kgerheiser suggested in the Log.cc source file of eckit. 

**Notes:**

I'm sure this is explained in the documentation, but it took me a while to realize that once you add a patch or change a package.py file you need to rerun `concretize` with the `-f` flag for spack to pickup that you made changes.

I also found it necessary to add:
```
        if self.spec.satisfies("platform=darwin"):
            env.append_flags("CXXFLAGS", " -DNO_CLANG_BUILTIN ")
```

to the `    def setup_build_environment(self, env):` section at the bottom of `spack/var/spack/repos/builtin/packages/eckit/package.py` to prevent eckit from expecting __builtin_rotateleft64 (a clang builtin) to be available in `src/eckit/utils/xxHashing.cc` (line 15) via the third party include `src/eckit/contrib/xxhash/xxhash.h` (line 1594).

My patch file is the follow simple hack I only expect to work for MacOS using the Intel Compilers and would break any other configuration:
```
--- a/src/eckit/log/Log.cc 2023-01-12 13:41:47.000000000 -0500
+++ b/src/eckit/log/Log.cc 2023-01-12 14:22:26.000000000 -0500
@@ -33,6 +33,9 @@

 //----------------------------------------------------------------------------------------------------------------------

+#undef _GNU_SOURCE
+#define _POSIX_VERSION 200112L
+
 #if defined(_GNU_SOURCE)

 /* To use with GNU libc strerror_r */
```

**Comment by climbfuji** [comment]
Thanks a lot, @rjdave ! Do you mind creating a PR with those bug fixes?

**Comment by rjdave** [comment]
What I've done is really just hacks that I fear may cause more harm than good. Even the `-DNO_CLANG_BUILTIN` should likely also depend on using the Intel compiler and possibly other constraints.

**Comment by climbfuji** [comment]
@rjdave Since Intel has decided to stop supporting macOS with its new LLVM-based compilers (`icx`, `icpx`, `ifx`) and since `icc` and `icpc` will be deprecated in the second half of 2023 (`ifort` will follow later), we decided to not support Intel on macOS in spack-stack / spack.

You may want to try seeking help from the spack user community by submitting an issue on their github page (https://github.com/spack/spack) or by joining their slack channel.
