### ISSUE TITLE
FMS and MAPL builds fail on MacOS Sonoma 14 when using Xcode 15.1

### ISSUE THREAD

**Issue by srherbener** [JCSDA/spack-stack#1083]
**Describe the bug**

FMS and MAPL builds fail due to the inability to find the OpenMP Fortran component. Both of these packages use the mpi wrappers and when I removed the usage of the mpi wrappers, the builds completed successfully. I did try a variety of other solutions including exporting OpenMP_ROOT which did not fix the problem. Both of these packages use CMake which should be fine building without the use of the wrappers, so there is a general desire to not use the mpi wrappers.

**To Reproduce**

On a Mac with Sonoma installed, and with Xcode 15.1 (apple-clang@15.0.0) and GNU Fortran 12.3.0, follow the instructions in the spack-stack doc for building on the MacOS platform.

**Expected behavior**

The build described above should complete successfully.

**System:**

See above

**Additional context**

**Comment by climbfuji** [comment]
The spack develop PR was merged, @srherbener can you bring this change down to our fork when you have time please?
