### ISSUE TITLE
MAPL build produces a blank argument for cmake duirng the build process

### ISSUE THREAD

**Issue by srherbener** [JCSDA/spack-stack#1086]
**Describe the bug**

This isn't preventing the build from working, but thought I would submit this issue to help remind us to clean this up. The symptom is that when `cmake` is run to configure the build for MAPL, a blank argument appears in the cmake command:
```
cmake '... opt/curl;/opt/homebrew' '' '-DBUILD_WITH_ PFLOGGER:BOOL=ON' '-DBUILD_WITH_FARGPARSE:BOOL=ON' '-DBUILD_SHARED_MAPL:BOOL=ON' '-DUSE_EXTDATA2G:BOOL=ON' '-DUSE_F2PY:BOOL=OFF' '-DCMAKE_MODULE_PATH:STRING=/Users/steveherbener/spack-stack/envs/unified-env.mymacos/install/apple-clang/15.0.0/esmf-8.6.0-arh6774/cmake' '-DCMAKE_Fortran_FLAGS:STRING=-ffree-line-length-none -fallow-invalid-boz -fallow-argument-mismatch' '/Users/steveherbener/spack-stack/cache/build_stage/spack-stage-mapl-2.40.3-7y27wlepvd76j5cvhogy7ey7vskf6xar/spack-src'
```
Note the empty argument ('') right before the '-DBUILD_WITH_ PFLOGGER:BOOL=ON' argument. 

A quick look in the package.py script for MAPL shows:
https://github.com/JCSDA/spack/blob/66e9ce432da4a88fe075b9f9a8c3d4fb5e42da73/var/spack/repos/builtin/packages/mapl/package.py#L253-L260

It seems that the `flap` variant is not set and then an empty string gets set in the cmake arguments.

**To Reproduce**

set up and build MAPL

**Expected behavior**
The empty cmake argument is eliminated

**System:**
What system(s) are you running the code on?
MacOS, apple-clang@15.0.0, GNU fortran 12.3.0

**Additional context**

**Comment by climbfuji** [comment]
If it's not a problem then send it straight to the icebox :-)

**Comment by mathomp4** [comment]
I think I've figured this out and it'll be included in my updated MAPL package when 2.46 (and ESMF 8.6.1) are out.

**Comment by climbfuji** [comment]
@mathomp4 Was this just fixed with adding mapl@2.46 ?

**Comment by mathomp4** [comment]
Yes. I believe this should be fixed by [this bit of code](https://github.com/JCSDA/spack/blob/9e4f6f8f2572cd29f722ad436fedab6ea88c3a4a/var/spack/repos/builtin/packages/mapl/package.py#L305-L308):
```python
        # We only want to add BUILD_WITH_FLAP if we are @:2.39 otherwise
        # there is a weird empty string that gets added to the CMake command
        if self.spec.satisfies("@:2.39"):
            args.append(self.define("BUILD_WITH_FLAP", self.spec.satisfies("+flap")))
```

Though I guess @srherbener will let me know if I got it right next time he builds 😄

**Comment by climbfuji** [comment]
Perfect, thanks! Closing.
