### ISSUE TITLE
Drop support for Casper?

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#1094]
**Is your feature request related to a problem? Please describe.**
Trying to find out if anybody is using Casper. If not, we should consider dropping spack-stack support for it.

**Describe the solution you'd like**
See above.

**Additional context**
n/a

**Comment by climbfuji** [comment]
@liujake Checking if MMM is using Casper for JEDI-MPAS (i.e. with spack-stack)?

**Comment by climbfuji** [comment]
@RatkoVasic-NOAA @natalie-perlin @ulmononian Checking with you as well if EPIC is using Casper.

**Comment by RatkoVasic-NOAA** [comment]
I don't have account on Casper.

**Comment by liujake** [comment]
> @liujake Checking if MMM is using Casper for JEDI-MPAS (i.e. with spack-stack)?

So far, we rarely use JEDI-MPAS on casper.

**Comment by climbfuji** [comment]
> > @liujake Checking if MMM is using Casper for JEDI-MPAS (i.e. with spack-stack)?
> 
> So far, we rarely use JEDI-MPAS on casper.

Would it be ok for your team if we dropped supporting spack-stack on Casper from our end? MMM could take care of the system, of course, we are trying to cut down the number of systems we need to support. Thanks!

**Comment by liujake** [comment]
@climbfuji That is ok.
