### ISSUE TITLE
WGRIB is not defined in grib-util's module file

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [JCSDA/spack-stack#1097]
**Describe the bug**
Instead of declaring `WGRIB` in the `grib-util` module file, `WGRIB2` is and points to the non-existent `wgrib2` application.

**To Reproduce**
Build spack-stack 1.6.0 or 1.7.0 (possibly others) and generate the module files.

**Expected behavior**
`WGRIB` would be a declared environment variable and would point to the `wgrib` application.

**System:**
At least Hera.

**Additional context**
N/A

**Comment by DavidHuber-NOAA** [comment]
If possible, could the `WGRIB` environment variable be defined in existing module files?

**Comment by climbfuji** [comment]
That can be done (unless it breaks someone else's code) - we'd have to go back and regenerate the modules for the installations affected.

**Comment by AlexanderRichert-NOAA** [comment]
Looks like we removed the WGRIB2 entry in the 1.7.0 release process but the change didn't make it into all the installations. In any case, I'm thinking once I test #1101, we can go back and make the change to the existing 1.6.0 and 1.7.0 installations. I think changing WGRIB2->WGRIB in the existing installations is a pretty low-risk change.

**Comment by climbfuji** [comment]
PR https://github.com/JCSDA/spack-stack/pull/1101 was merged. We need to (manually) backport these changes into the release/1.5.1 and 1.6.0 installations on the following systems:

@AlexanderRichert-NOAA @RatkoVasic-NOAA @srherbener @natalie-perlin @climbfuji - please add your name to the platforms you are taking care of. See https://github.com/JCSDA/spack-stack/pull/1101 for the one-liner change that needs to be made in each `envs/*/common/modules.yaml` file, then activate the environment, rerun the module generation for the system (`spack module [lmod|tcl] refresh`), followed by `spack stack setup-meta-modules` if `tcl` is used.

- [x] MSU Orion - @AlexanderRichert-NOAA 
- [x] MSU Hercules - @AlexanderRichert-NOAA 
- [x] ~~NASA Discover SCU16~~ not needed
- [x] ~~NASA Discover SCU17~~ not needed
- [x] ~~NAVY HPCMP Narwhal~~ not needed
- [x] ~~NAVY HPCMP Nautilus~~ not needed
- [x] ~~NCAR-Wyoming Derecho~~ not needed
- [x] NOAA Acorn (WCOSS2 test system) - @AlexanderRichert-NOAA 
- [x] ~~NOAA Parallel Works EPIC (AWS, Azure, Gcloud)~~ not needed
- [x] ~~NOAA Parallel Works JCSDA (Gcloud)~~ not needed
- [x] NOAA RDHPCS Gaea - @AlexanderRichert-NOAA 
- [x] NOAA RDHPCS Hera - @RatkoVasic-NOAA 
- [x] NOAA RDHPCS Jet - @AlexanderRichert-NOAA 
- [x] UW (Univ. of Wisconsin) S4
- [x] ~~Amazon Web Services Parallelcluster Ubuntu 20.04~~ not needed
- [x] ~~Amazon Web Services Red Hat 8~~ not needed

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA @DavidHuber-NOAA JCSDA updated the grib-util modules on S4 for 1.5.1 and 1.6.0, unified-env and gsi-addon-env

**Comment by climbfuji** [comment]
@RatkoVasic-NOAA @DavidHuber-NOAA Can we complete the work and close this issue? Only Hera, Derecho, and Parallel Works EPIC are missing.

**Comment by DavidHuber-NOAA** [comment]
@climbfuji I'm OK with this on being on Derecho and Parallel Works as they do not support the global workflow yet, but Hera does need it.

**Comment by RatkoVasic-NOAA** [comment]
@climbfuji I'll take a look on Hera.

**Comment by climbfuji** [comment]
Thanks @RatkoVasic-NOAA and @DavidHuber-NOAA . I updated the list of machines above.

**Comment by RatkoVasic-NOAA** [comment]
@DavidHuber-NOAA @climbfuji @AlexanderRichert-NOAA 
while doing this on Hera (1.5.1 and 1.6.0) , I realized that also 1.7.0 is wrong (on all machines).
We cannot close this issue yet.
I will do this patch for 1.7.0 on Hera, Gaea, Jet, Orion and Hercules.

**Comment by RatkoVasic-NOAA** [comment]
### Patch for 1.7.0:
- [x] MSU Orion -  @RatkoVasic-NOAA (redone by @climbfuji after Rocky9 OS upgrade)
- [x] MSU Hercules -  @RatkoVasic-NOAA
- [x] NOAA Acorn  - @AlexanderRichert-NOAA 
- [x] NOAA RDHPCS Gaea -  @RatkoVasic-NOAA
- [x] NOAA RDHPCS Hera - @RatkoVasic-NOAA 
- [x] NOAA RDHPCS Jet -  @RatkoVasic-NOAA
- [x] UW (Univ. of Wisconsin) S4 - @climbfuji

**Comment by climbfuji** [comment]
@DavidHuber-NOAA Please chime in, but for some reason that I don't remember we concluded that this isn't needed for 1.7.0?

**Comment by climbfuji** [comment]
> @DavidHuber-NOAA Please chime in, but for some reason that I don't remember we concluded that this isn't needed for 1.7.0?

Scrap that. 1.7.0 is explicitly mentioned above. Sorry! We'll go back and do that on S4. @srherbener do you want to or should I?

**Comment by climbfuji** [comment]
@srherbener I did 1.7.0 on S4

**Comment by srherbener** [comment]
> @srherbener I did 1.7.0 on S4

Thanks @climbfuji !

**Comment by climbfuji** [comment]
is this all done?

**Comment by climbfuji** [comment]
@RatkoVasic-NOAA Circling back to this issue, is the grib-utils module fixed on Hera? That's the last one on the list. Thanks!

**Comment by RatkoVasic-NOAA** [comment]
Oh, yes, as in table above:
https://github.com/JCSDA/spack-stack/issues/1097#issuecomment-2161382923
Not sure about Acorn.

**Comment by RatkoVasic-NOAA** [comment]
> @RatkoVasic-NOAA Circling back to this issue, is the grib-utils module fixed on Hera? That's the last one on the list. Thanks!

BTW, just checked, on Hera all environments in versions of spack-stack 1.5.1 and newer are corrected, and all from 1.5.0 and earlier were not touched - I guess nobody's using that old versions.

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA Did you do acorn?

**Comment by climbfuji** [comment]
> @AlexanderRichert-NOAA Did you do acorn?

Ignore that. The table at the very top says yes. So we are done here, closing! Thanks everyone.
