### ISSUE TITLE
Update common/packages.yaml

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#1115]
For the 1.8.0 release, I think it would be a good idea to run the check_package_config utility on a couple machines and go through the output to reconcile the versions/variants in there against what actually gets concretized. For example, in testing #1109, concretizing unified-dev led to py-h5py@3.11.0 being spec'd in spite of 3.7.0 being preferred in common/packages.yaml. In those sorts of situations, we should either require the older version if needed, or just move to the/a newer version.

Some mismatches:
 - py-h5py version
 - proj version
 - scotch `metis` variant (see https://github.com/spack/spack/issues/44676)

**Comment by climbfuji** [comment]
I think we should (1) remove version and variant requirements when we don't really need them, and (2) require the rest via `require` to make sure they are being used.
