### ISSUE TITLE
[INSTALL]: ESMF 8.6.1 for 1.7.0 release

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#1117]
### Package name

esmf

### Package version/tag

8.6.1

### Build options

current

### Installation timeframe

In existing 1.7.0 release at Discover at the minimum, preferably everywhere

After merging the corresponding PR, we want to install `8.6.1` on all supported tier-1 platforms before closing this issue. @AlexanderRichert-NOAA @RatkoVasic-NOAA @natalie-perlin @srherbener @climbfuji 

- [x] MSU Orion (@climbfuji; after OS upgrade to Rocky9)
- [x] MSU Hercules (@AlexanderRichert-NOAA)
- [x] NASA Discover SCU16
- [x] NASA Discover SCU17
- [x] NAVY HPCMP Narwhal (@climbfuji)
- [x] NAVY HPCMP Nautilus (@climbfuji)
- [x] NCAR-Wyoming Derecho (@climbfuji)
- [x] NOAA Acorn (WCOSS2 test system; @AlexanderRichert-NOAA)
- [x] NOAA Parallel Works EPIC (AWS, Azure, Gcloud) (@natalie-perlin )
- [x] NOAA Parallel Works JCSDA (Gcloud)
- [x] NOAA RDHPCS Gaea (@AlexanderRichert-NOAA)
- [x] NOAA RDHPCS Hera (@AlexanderRichert-NOAA)
- [x] NOAA RDHPCS Jet (@AlexanderRichert-NOAA)
- [x] UW (Univ. of Wisconsin) S4
- [ ] Amazon Web Services Parallelcluster Ubuntu 22.04
- [x] Ubuntu CI runner for skylab, simobs, ... (@climbfuji)
- [x] ~~Amazon Web Services Red Hat 8~~ NOT NEEDED

### Other information

~~We should consider adding a version of MAPL that goes with this ESMF at the same time. Otherwise, we have to go back and add MAPL at a later time. So far, `esmf@8.6.1` is only needed for GEOS (which builds its own MAPL), but if the UFS wants to use that version of ESMF it will need a MAPL version as well. The recommended version of MAPL for `esmf@8.6.1` is `mapl@2.46.2`.~~ **note - skipping for now, since it is not clear it's needed**

We also need to add this version of ESMF (and possibly MAPL) to spack-stack develop. **done**

### WCOSS2

- [ ] Check this box if and only if your package should be installed on WCOSS2 Cactus and Dogwood (all spack-stack packages will be installed on Acorn). If not, you may disregard the rest of the items below and submit this request.

### WCOSS2: Technical & security review list

- [ ] The code is mature, stable, and production ready
- [ ] The code is does not and cannot use the internet, and does not contain URLs (http, https, ftp, etc.) except in comments
- [ ] The package does not contain prebuilt binary files that have not been approved by NCO security review
- [ ] The code has no publicly disclosed cybersecurity vulnerabilities and exposures (search https://cve.mitre.org/cve/)
- [ ] The code is not prohibited by DHS, DOC, NOAA, or NWS
- [ ] The code comes from a trusted source. Trusted sources include other NWS, NOAA, or DOC, agencies, or other Federal agencies that operate at a FISMA high or equivalent level. Additionally, trusted sources could be third-party agencies through which there is an existing SLA on file (such as RedHat).
- [ ] The code is actively maintained and supported (it continues to get updates, patches, etc.)
- [ ] The code is not maintained by a private entity operating in a foreign country (if it is, make a note below)
- [ ] There is sufficient documentation to support maintenance
- [ ] There are no known security vulnerabilities or weaknesses
- [ ] Installing and running the code does not require privileged processes/users
- [ ] There are no software dependencies that are unapproved or have security concerns (if there are, make a note below)
- [ ] There are no concerns related to SA, SI, and SC NIST control families

**Comment by fmahebert** [comment]
Installed on NOAA Parallel Works JCSDA (Gcloud) via this set of actions,
```
# purge and reload basic modules
cd /path/to/spack-stack-1.7.0
# check git remote correct
# 'git status' to determine if there are changes that should be stashed
git checkout release/1.7.0
git pull  # and manually check clean repo
git submodule update --recursive  # and manually check spack submodule
source setup.sh
spack env activate -p envs/<envname>
vim envs/<envname>/spack.yaml  # to add esmf@=8.6.1 at end of packages list (note @= for strict equality to avoid 8.6.1b04)
spack concretize 2>&1 | tee log.concretize_esmf.8.6.1
spack install --verbose 2>&1 | tee log.install_esmf.8.6.1
spack module lmod refresh esmf@8.6.1
```

(but I don't have edit permissions to tick the checkbox in the issue description)

**Comment by srherbener** [comment]
JCSDA has updated S4 according to the formula reported above by @fmahebert.

**Comment by mathomp4** [comment]
@climbfuji I looked and in spack-stack 1.7 on discover I see `mapl/2.40.3-esmf-8.6.0`. Thus, you should probably also build [MAPL 2.40.5](https://github.com/GEOS-ESM/MAPL/releases/tag/v2.40.5) which had a fix for NOAA. I guess with ESMF 8.6.0 for consistency.

**Comment by climbfuji** [comment]
> @climbfuji I looked and in spack-stack 1.7 on discover I see `mapl/2.40.3-esmf-8.6.0`. Thus, you should probably also build [MAPL 2.40.5](https://github.com/GEOS-ESM/MAPL/releases/tag/v2.40.5) which had a fix for NOAA. I guess with ESMF 8.6.0 for consistency.

Thanks, but I suggest skipping this combination unless explicitly requested by EMC in the next weeks. They are still on spack-stack-1.6.0 (just moved there last week) and it is not clear to me if they are going to use 1.7.0 at all, or go straight to 1.8.0 once it is release in August/September.

**Comment by climbfuji** [comment]
@fmahebert @srherbener We need to revisit this issue and build mapl@2.46.2 on top of esmf@8.6.1 on the platforms we rolled out esmf@8.6.1 so far. I'll create the PRs for adding mapl@2.46.2 to the spack-stack-1.7.0 release branch and then provide you with instructions.

**Comment by climbfuji** [comment]
@mathomp4 I realized that backporting mapl@2.46.2 is a bit of a problem, because (a) the package recipe has changed a lot, and (b) there are other dependencies that all need updating (pflogger, etc). Maybe we have to abandon this idea and say that anything newer than mapl@2.40.5 will come with spack-stack-1.8.0; instead of adding 2.46.2 to spack-stack-1.7.0 with esmf@8.6.1, can we use 2.40.5 (right now 1.7.0 has 2.40.3).

**Comment by climbfuji** [comment]
or skip the idea of adding a mapl to go with esmf 8.6.1 in spack-stack-1.7.0 altogether (we only added 8.6.1 for the JEDI-GEOS work)

**Comment by climbfuji** [comment]
alright, I am making an "executive decision" that we will install esmf@8.6.1 standalone, i.e. without an accompanying mapl version. We can create a separate issue if it turns out that we need it. @fmahebert @srherbener therefore nothing to do on your end.

@RatkoVasic-NOAA @AlexanderRichert-NOAA @natalie-perlin Can you please install esmf@8.6.1 from the spack-stack-1.7.0 release branch on "your" platform (see list above in the PR description). Instructions are here: https://github.com/JCSDA/spack-stack/issues/1117#issuecomment-2128032442

Thank you!

**Comment by climbfuji** [comment]
@RatkoVasic-NOAA @AlexanderRichert-NOAA @natalie-perlin Can we make some progress here, please? All that is needed is installing esmf@8.6.1 in the existing 1.7.0 release on the HPCs (see list above). Thank you!

**Comment by AlexanderRichert-NOAA** [comment]
I'll start putting my name by systems. In the future I'd prefer to do this as a chained env with a separate recipe/repo, but I'll do it as shown above for consistency.

**Comment by climbfuji** [comment]
> I'll start putting my name by systems. In the future I'd prefer to do this as a chained env with a separate recipe/repo, but I'll do it as shown above for consistency.

Thanks @AlexanderRichert-NOAA - noted. Let's do chained environments in the future.

**Comment by climbfuji** [comment]
@natalie-perlin and @srherbener According to the issue description (https://github.com/JCSDA/spack-stack/issues/1117#issue-2300985130) only the EPIC ParallelWorks and the AWS RedHat AMI are missing the new esmf 8.6.1 in spack-stack-1.7.0.

Natalie, can you do this please? Steve, can you decide whether the AMI needs to be updated or if it isn't really used and therefore it doesn't make sense to update?

Also, @eap, when this issue was created AWS ParallelCluster was down, therefore we didn't include the system in the list at the top of the issue. Now that it's up and running spack-stack-1.7.0, it would make sense to add esmf@8.6.1 to be consistent with all the other platforms? Same goes for the self-hosted CI runner for skylab, simobs, ... (I can take care of the latter).

**Comment by srherbener** [comment]
@climbfuji I haven't got any responses about the AWS Red Hat 8 AMI so it's not clear to me if we need to update. I'm inclined to think no one is using it and to not worry about this AMI, unless @eap knows better.

**Comment by natalie-perlin** [comment]
> @natalie-perlin and @srherbener According to the issue description ([#1117 (comment)](https://github.com/JCSDA/spack-stack/issues/1117#issue-2300985130)) only the EPIC ParallelWorks and the AWS RedHat AMI are missing the new esmf 8.6.1 in spack-stack-1.7.0.
> 
> Natalie, can you do this please? Steve, can you decide whether the AMI needs to be updated or if it isn't really used and therefore it doesn't make sense to update?
> 
> Also, @eap, when this issue was created AWS ParallelCluster was down, therefore we didn't include the system in the list at the top of the issue. Now that it's up and running spack-stack-1.7.0, it would make sense to add esmf@8.6.1 to be consistent with all the other platforms? Same goes for the self-hosted CI runner for skylab, simobs, ... (I can take care of the latter).

@climbfuji 
 - sure, I will check the status of esmf 8.6.1 in spack-stack-1.7.0 on Centos 7 on NOAA Cloud platforms.

**Comment by natalie-perlin** [comment]
esmf/8.6.1 is currently being installed in /contrib/spack-stack-1.7.0/envs/ue-intel on AWS, GCP and Azure.
Using a similar approach as given here: https://github.com/JCSDA/spack-stack/issues/1117#issuecomment-2128032442
UPDATE: All installed OK, eventually just this one package, no additional packages needed.

**Comment by srherbener** [comment]
@climbfuji, I still have no responses about the Red Hat AMIs. I think we should skip this update. I'll mark this as completed in the issue description.

I've pinged @eap about the AWS Pcluster. Perhaps his work to restore it was recent enough to already include ESMF 8.6.1?

So you are aware, I am currently totally swamped with ioda work and I was told that the ioda work has priority over spack-stack. I'm happy to work on spack-stack tasks, but I will not always be able to give quick responses. I'm sorry about this situation and my slow response as of late.

**Comment by climbfuji** [comment]
> @climbfuji, I still have no responses about the Red Hat AMIs. I think we should skip this update. I'll mark this as completed in the issue description.
> 
> I've pinged @eap about the AWS Pcluster. Perhaps his work to restore it was recent enough to already include ESMF 8.6.1?

Probably not

> So you are aware, I am currently totally swamped with ioda work and I was told that the ioda work has priority over spack-stack. I'm happy to work on spack-stack tasks, but I will not always be able to give quick responses. I'm sorry about this situation and my slow response as of late.

**Comment by climbfuji** [comment]
I'll close this as done. If someone tries to run GEOS on AWS ParallelCluster, they'll notice that `esmf@8.6.1` is missing ;-)
