### ISSUE TITLE
[INSTALL]:  NEPTUNE stand-alone on narwhal 

### ISSUE THREAD

**Issue by areinecke** [JCSDA/spack-stack#1127]
### Package name

neptune stand alone

### Package version/tag

1.5

### Build options

current

### Installation timeframe

as soon as possible

### Other information

N/A

### WCOSS2

- [ ] Check this box if and only if your package should be installed on WCOSS2 Cactus and Dogwood (all spack-stack packages will be installed on Acorn). If not, you may disregard the rest of the items below and submit this request.

### WCOSS2: Technical & security review list

- [ ] The code is mature, stable, and production ready
- [ ] The code is does not and cannot use the internet, and does not contain URLs (http, https, ftp, etc.) except in comments
- [ ] The package does not contain prebuilt binary files that have not been approved by NCO security review
- [ ] The code has no publicly disclosed cybersecurity vulnerabilities and exposures (search https://cve.mitre.org/cve/)
- [ ] The code is not prohibited by DHS, DOC, NOAA, or NWS
- [ ] The code comes from a trusted source. Trusted sources include other NWS, NOAA, or DOC, agencies, or other Federal agencies that operate at a FISMA high or equivalent level. Additionally, trusted sources could be third-party agencies through which there is an existing SLA on file (such as RedHat).
- [ ] The code is actively maintained and supported (it continues to get updates, patches, etc.)
- [ ] The code is not maintained by a private entity operating in a foreign country (if it is, make a note below)
- [ ] There is sufficient documentation to support maintenance
- [ ] There are no known security vulnerabilities or weaknesses
- [ ] Installing and running the code does not require privileged processes/users
- [ ] There are no software dependencies that are unapproved or have security concerns (if there are, make a note below)
- [ ] There are no concerns related to SA, SI, and SC NIST control families

**Comment by climbfuji** [comment]
Working on this now

**Comment by climbfuji** [comment]
@areinecke I built the standalone env on Narwhal with Intel (same commit hash as on Nautilus). I compiled neptune_atmos with it (making the necessary sp -> ip changes).
```
umask 0022
module unload PrgEnv-cray
module load PrgEnv-intel/8.3.2
module unload intel
module load intel-classic/2021.4.0
module unload cray-mpich
module load cray-mpich/8.1.14
module unload cray-python
module load cray-python/3.9.7.1
module unload cray-libsci
module load cray-libsci/22.08.1.1

module use /p/app/projects/NEPTUNE/spack-stack/spack-stack-dev-20240523-neptune-env/envs/ne-intel-2021.4.0/install/modulefiles/Core
module load stack-intel/2021.4.0
module load stack-cray-mpich/8.1.14
module load stack-python/3.10.13
module load neptune-env/1.4.0
```
I did see an odd warning or two about libz, because the standalone env comes with zlib-ng and both are shared libraries. I think it is ok for now, but going forward we either want to revert to zlib (possible performance hit when using compression), or build zlib-ng static only.

**Comment by areinecke** [comment]
> @areinecke I built the standalone env on Narwhal with Intel (same commit hash as on Nautilus). I compiled neptune_atmos with it (making the necessary sp -> ip changes).
> 
> ```
> umask 0022
> module unload PrgEnv-cray
> module load PrgEnv-intel/8.3.2
> module unload intel
> module load intel-classic/2021.4.0
> module unload cray-mpich
> module load cray-mpich/8.1.14
> module unload cray-python
> module load cray-python/3.9.7.1
> module unload cray-libsci
> module load cray-libsci/22.08.1.1
> 
> module use /p/app/projects/NEPTUNE/spack-stack/spack-stack-dev-20240523-neptune-env/envs/ne-intel-2021.4.0/install/modulefiles/Core
> module load stack-intel/2021.4.0
> module load stack-cray-mpich/8.1.14
> module load stack-python/3.10.13
> module load neptune-env/1.4.0
> ```
> 
> I did see an odd warning or two about libz, because the standalone env comes with zlib-ng and both are shared libraries. I think it is ok for now, but going forward we either want to revert to zlib (possible performance hit when using compression), or build zlib-ng static only.

Thanks, Dom.  I test it out.

**Comment by areinecke** [comment]
I tested this on narwhal and it worked as expected.

**Comment by climbfuji** [comment]
Thanks for the quick turnaround! Closing.
