### ISSUE TITLE
[INSTALL]: spack-stack on Gaea C6

### ISSUE THREAD

**Issue by BijuThomas-NOAA** [JCSDA/spack-stack#1130]
### Package name

spack-stack

### Package version/tag

1.6.0

### Build options

current

### Installation timeframe

HAFS team would like to install UFS weather model and HAFS on Gaea C6 sooner.

**Comment by BijuThomas-NOAA** [comment]
We request to install spack-stack libraries on Gaea C6 for us to build and run the HAFS system

**Comment by AlexanderRichert-NOAA** [comment]
I'll work on a C6 config based on 1.6.0 then work on adding to develop for 1.8.0.

**Comment by AlexanderRichert-NOAA** [comment]
@BijuThomas-NOAA can you test with /autofs/ncrc-svm1_proj/epic/spack-stack/spack-stack-1.6.0/envs/unified-env-c6/install/modulefiles/Core and let me know if there are any issues?

**Comment by BijuThomas-NOAA** [comment]
@AlexanderRichert-NOAA Thank you. I will test HAFS system on Gaea and let you know.

**Comment by BijuThomas-NOAA** [comment]
@AlexanderRichert-NOAA I see the following error: 
```
module purge
module load /autofs/ncrc-svm1_proj/epic/spack-stack/spack-stack-1.6.0/envs/unified-env-c6/install/modulefiles/Core
module load PrgEnv-intel/8.3.3
module load stack-intel/2023.2.0
```
_Lmod has detected the following error:  The following module(s) are unknown: "PrgEnv-intel/8.5.0" "intel-classic/2023.2.0" "craype/2.7.30"_

Am I loading modules correctly?

**Comment by AlexanderRichert-NOAA** [comment]
The following works for me on gaea60:
```console
module use /autofs/ncrc-svm1_proj/epic/spack-stack/spack-stack-1.6.0/envs/unified-env-c6/install/modulefiles/Core
module load stack-intel
module load stack-cray-mpich
```

I'm having some trouble getting ecmwf-atlas, seemingly related to the wrong libstdc++ being used, but otherwise things seem to be going okay...

**Comment by climbfuji** [comment]
@BijuThomas-NOAA Is this now working for you?

**Comment by BijuThomas-NOAA** [comment]
The build is successful. Need more time to run HAFS.

**Comment by climbfuji** [comment]
@BijuThomas-NOAA Were you able to run HAFS with this installation of spack-stack?

**Comment by BijuThomas-NOAA** [comment]
@climbfuji I could run the HAFS system with the installed spack-stack on C6. 

Thanks,

**Comment by climbfuji** [comment]
Great to hear, thanks! Closing.
