### ISSUE TITLE
Some changes that need to be pushed to main Spack

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#1140]
Packages in our fork's `builtin` repo but not main Spack:
- [x] py-pyhdf @climbfuji - https://github.com/spack/spack/pull/44877
- [x] mepo @mathomp4  - https://github.com/spack/spack/pull/44879
- [x] py-globus-cli @climbfuji - https://github.com/spack/spack/pull/44881

Changes that (probably) need to be pushed:
- [x] fontconfig (pic) @AlexanderRichert-NOAA - https://github.com/spack/spack/pull/44884
- [x] openblas (noavx512) @AlexanderRichert-NOAA - https://github.com/spack/spack/pull/44883
- [x] openmpi (two_level_namespace) @srherbener  - https://github.com/spack/spack/pull/47202
- [x] pixman (pic) @AlexanderRichert-NOAA - https://github.com/spack/spack/pull/44889

**Comment by mathomp4** [comment]
I will work on mepo. We have an RC in PyPi now (https://pypi.org/project/mepo/), so the package was easy to make. I'll work on our side to see if we are ready to move on with a release.

(We have to be a bit more cautious internally as the mepo state file is moving from pickle to json, so existing clones throw some warnings. We want to let users know.)

**Comment by climbfuji** [comment]
> I will work on mepo. We have an RC in PyPi now (https://pypi.org/project/mepo/), so the package was easy to make. I'll work on our side to see if we are ready to move on with a release.
> 
> (We have to be a bit more cautious internally as the mepo state file is moving from pickle to json, so existing clones throw some warnings. We want to let users know.)

Thanks very much @mathomp4! Yes, I remembered our previous conversation and that's why assigned this to you rather than me pushing what is in our branch.

**Comment by mathomp4** [comment]
@climbfuji Well, first we see if spack mainline likes it:

https://github.com/spack/spack/pull/44879

if so, I can work to get it into JSCDA spack.

ETA: Or if they take too long, I'll do the same here tomorrow or something. :)

**Comment by climbfuji** [comment]
Both of my packages are merged into spack develop. Both of them received updates=improvements as part of the process, which will come back to spack-stack-dev with the next merge from spack develop. I updated the list above.

**Comment by mathomp4** [comment]
Well, something weird is happening with spack mainline and mepo, so let me try and bring it in here.

ETA: Okay https://github.com/JCSDA/spack/pull/447 has the updates from my two spack mainline PRs for mepo. Just in case.

**Comment by mathomp4** [comment]
Well, https://github.com/spack/spack/pull/44879 is now in mainline spack so... 🤷🏼 

The changes will get in some way :)

**Comment by AlexanderRichert-NOAA** [comment]
@srherbener can you take a look at the openmpi recipe and push changes to main spack?

**Comment by srherbener** [comment]
My apologies for the slow response. I've been buried with getting spack-stack-1.8.0 to build on Mac Sonoma. I'm planning on getting to the openmpi recipe next week.

**Comment by climbfuji** [comment]
The openblas update was merged upstream. Last one on the list is openmpi (two-level namespace)

**Comment by srherbener** [comment]
Sorry about the delay in getting to this.

I initially tried to cherry-pick the openmpi, macos, two-level-namespace updates but there is enough divergence since the last time we sync'd with the authoritative spack repo that the cherry picked commits are pulling in a bunch of other changes not related to the macos openmpi update. So I have created a PR by manually adding in the code in the openmpi package.py script to introduce the two_level_namespace variant: https://github.com/spack/spack/pull/47202
