### ISSUE TITLE
Hera rocky8 unified env broken for spack-stack-1.6.0

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#1146]
**Describe the bug**
OpenMPI versions don't match-- spack-stack meta module expects 4.1.5, system offers 4.1.6. See https://github.com/ufs-community/UFS_UTILS/issues/962

**To Reproduce**
```console
hfe09:~ $ module use /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/unified-env-rocky8/install/modulefiles/Core
hfe09:~ $ module load stack-gcc
hfe09:~ $ module load stack-openmpi
Lmod has detected the following error:  The following module(s) are unknown: "openmpi/4.1.5"

Please check the spelling or version number. Also try "module spider ..."
```

**Expected behavior**
openmpi module should load and work

**System:**
Hera (tested on hfe09)

**Comment by AlexanderRichert-NOAA** [comment]
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/unified-env-rocky8-ompi416

**Comment by climbfuji** [comment]
Updates on this? Fixed?

**Comment by AlexanderRichert-NOAA** [comment]
The ompi416 stack appears to work. Closing.
