### ISSUE TITLE
mapl ^cray-mpich fails

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#1153]
After the latest updates, the MAPL recipe can't be built with ^cray-mpich for the MPI provider. This problem is addressed by https://github.com/spack/spack/pull/44796.

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA https://github.com/JCSDA/spack-stack/pull/1169 should resolve this?

**Comment by AlexanderRichert-NOAA** [comment]
Correct

**Comment by climbfuji** [comment]
then please review ;-)
