### ISSUE TITLE
OOPS PR #2670 requires Atlas tagged version 0.38

### ISSUE THREAD

**Issue by odlomax** [JCSDA/spack-stack#1155]
OOPS PR [#2670](https://github.com/JCSDA-internal/oops/pull/2670) requires Atlas 0.38 to run.

From @srherbener: I've heard requests for updating Altals from several sources, so we should get the full version number agreed upon. There currently exists versions 0.38.0 and 0.38.1. Is there any reason why we shouldn't go to the latests version: 0.38.1? Or are we waiting for another update?

Is version 0.38.1 good for your needs?
- [x] OOPS PR 2670 (@odlomax, @DJDavies2)
- [x] JEDI model interface work (@fmahebert)
- [x] SOCA (@travissluka)

**Comment by travissluka** [comment]
All I need is something newer than the current 0.36, beyond that I don't think it matters to the oops::Diffusion

**Comment by srherbener** [comment]
@fmahebert could you pull the latest Atlas version (0.38.1) and test to make sure it will be okay for your (and Liam's) needs with the GPU work. Thanks!

**Comment by srherbener** [comment]
@odlomax just want to double check - when you say version 0.38, then 0.38.1 would be acceptable? Thanks!

**Comment by fmahebert** [comment]
@srherbener I will test the jedi-bundle with atlas 0.38.1 and confirm everything looks ok.

**Comment by fmahebert** [comment]
@srherbener I have tested jedi-bundle with atlas 0.38.1 and all looks good. It'd be great if @odlomax can confirm it looks good from the UKMO side as well.

Note that 0.38.1 is a minor bugfix on 0.38, so I see no reason to prefer 0.38.

In addition to the interpolator improvements that motivated the OOPS PR 2670 and this particular spack-stack issue, atlas 0.38+ also brings GPU related improvements, so we'll be happy to see this version for the GPU project too (though regardless we may end up working on custom branches).

**Comment by fmahebert** [comment]
I don't have edit permissions on the original issue, but please go ahead and check the "JEDI model interface work" box on my behalf. I am satisfied with this version.

As soon as we agree on a version here for spack-stack, I'll open a discussion so partners using their own envs know to prepare for a future atlas update.

**Comment by srherbener** [comment]
> I don't have edit permissions on the original issue, but please go ahead and check the "JEDI model interface work" box on my behalf. I am satisfied with this version.
> 
> As soon as we agree on a version here for spack-stack, I'll open a discussion so partners using their own envs know to prepare for a future atlas update.

@fmahebert thank you for testing 0.38.1! I checked the box. Also thank you for your upcoming help with coordinating the switch to the new atlas version!

**Comment by odlomax** [comment]
> @srherbener I have tested jedi-bundle with atlas 0.38.1 and all looks good. It'd be great if @odlomax can confirm it looks good from the UKMO side as well.
> 
> Note that 0.38.1 is a minor bugfix on 0.38, so I see no reason to prefer 0.38.
> 
> In addition to the interpolator improvements that motivated the OOPS PR 2670 and this particular spack-stack issue, atlas 0.38+ also brings GPU related improvements, so we'll be happy to see this version for the GPU project too (though regardless we may end up working on custom branches).

This all going well from my point of view now. I think there's a known orca issue. @twsearle, could you comment?

**Comment by twsearle** [comment]
> This all going well from my point of view now. I think there's a known orca issue. @twsearle, could you comment?

This is not so much an orca-jedi issue, as a deployment issue - we need to update our CI as the results of orca-jedi tests are impacted by the fixes in atlas 0.38.1. The changes are in progress and I don't think they should be a blocker.

**Comment by srherbener** [comment]
@twsearle thank you for the response. Sounds like atlas 0.38.1 will be acceptable.

I propose that we target atlas 0.38.1 for spack-stack-1.8.0. Any objections?

**Comment by srherbener** [comment]
> @twsearle thank you for the response. Sounds like atlas 0.38.1 will be acceptable.
> 
> I propose that we target atlas 0.38.1 for spack-stack-1.8.0. Any objections?

I take the silence as "no objections" so the plan is to move to atlas 0.38.1 for spack-stack-1.8.0.

**Comment by twsearle** [comment]
@srherbener just FYI we have fixed our orca-jedi CI issue so there are definitely no blockers from us now.

**Comment by srherbener** [comment]
@twsearle thanks for the update
