### ISSUE TITLE
Update esmf and mapl packages in spack-stack-dev

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#1157]
**Is your feature request related to a problem? Please describe.**
A few important updates were/are being merged for esmf and mapl into spack develop; best to bring those updated packages down to our spack-stack-dev branch.

**Describe the solution you'd like**
Once https://github.com/spack/spack/pull/44796, update esmf and mapl from spack develop by cherry-picking the relevant commits.

**Additional context**
n/a

**Comment by climbfuji** [comment]
We can do this now

**Comment by junwang-noaa** [comment]
@climbfuji may I ask which version of ESMF and MAL will be installed? We hope to get ESMF 8.6.1 and MAPL 2.46.2 in spack-stack 1.6.0, should I open a separate issue for it? Thanks

**Comment by climbfuji** [comment]
This issue is about updating the package recipes in our spack fork from the upstream spack develop - no installs/changes. We are currently targeting esm@8.6.1 and mapl@2.46.2 for spack-stack-1.8.0, but this can change based on user input and how many versions they produce until then.

If you want 8.6.1 and 2.46.2 in 1.6.0, then please create an INSTALL issue for that; this issue here still needs to be worked on first so that we have all new versions and bugfixes available for spack-stack.
