### ISSUE TITLE
Turn off cylc variant for ewok-env by default, but make sure we test building cylc regularly

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#1162]
**Is your feature request related to a problem? Please describe.**
The cylc packages introduce a lot of Python dependencies that make concretization and building difficult and lengthy in the unified environment. Nobody so far is using the spack-stack cylc installation.

**Describe the solution you'd like**
NRL has an interest in using cylc from spack-stack, but doesn't need the full unified environment. We want to make sure that we continue testing the build of the cylc packages, so maybe it's possible to add it to the neptune environment (as a variant or as default). Or found another way (a chained environment tested in CI?).

**Additional context**
n/a

**Comment by climbfuji** [comment]
PR https://github.com/JCSDA/spack-stack/pull/1191 disables the `cylc` variant for `ewok-env` in the `unified-dev` and `skylab-dev` templates. That's step 1 - we now need a way to test building `cylc` regularly elsewhere.

**Comment by BenjaminRuston** [comment]
agree.. @fcvdb and I literally just started poking around with `cylc` today, to just help with other busy work tasks

hopefully can get some basic functional tests ready to help test the elsewhere `cylc`

**Comment by climbfuji** [comment]
Re-opening this since it was NOT resolved. Only the first part was done (turn off cylc variant by default). The second part (make sure we test elsewhere) is still missing.
