### ISSUE TITLE
[INSTALL]: ESMPy

### ISSUE THREAD

**Issue by BijuThomas-NOAA** [JCSDA/spack-stack#1163]
### Package name

esmpy

### Package version/tag

8.*.*

### Build options

current

### Installation timeframe

spack-stack release

### Other information

Wondering if ESMPy can be added to spack-stack.  HAFS uses ESMPy for regridding

### WCOSS2

- [ ] Check this box if and only if your package should be installed on WCOSS2 Cactus and Dogwood (all spack-stack packages will be installed on Acorn). If not, you may disregard the rest of the items below and submit this request.

### WCOSS2: Technical & security review list

- [ ] The code is mature, stable, and production ready
- [ ] The code is does not and cannot use the internet, and does not contain URLs (http, https, ftp, etc.) except in comments
- [ ] The package does not contain prebuilt binary files that have not been approved by NCO security review
- [ ] The code has no publicly disclosed cybersecurity vulnerabilities and exposures (search https://cve.mitre.org/cve/)
- [ ] The code is not prohibited by DHS, DOC, NOAA, or NWS
- [ ] The code comes from a trusted source. Trusted sources include other NWS, NOAA, or DOC, agencies, or other Federal agencies that operate at a FISMA high or equivalent level. Additionally, trusted sources could be third-party agencies through which there is an existing SLA on file (such as RedHat).
- [ ] The code is actively maintained and supported (it continues to get updates, patches, etc.)
- [ ] The code is not maintained by a private entity operating in a foreign country (if it is, make a note below)
- [ ] There is sufficient documentation to support maintenance
- [ ] There are no known security vulnerabilities or weaknesses
- [ ] Installing and running the code does not require privileged processes/users
- [ ] There are no software dependencies that are unapproved or have security concerns (if there are, make a note below)
- [ ] There are no concerns related to SA, SI, and SC NIST control families

**Comment by climbfuji** [comment]
Do you know what the prerequisites are?

**Comment by BijuThomas-NOAA** [comment]
My understanding is:

- ESMF
- python
- numpy

https://earthsystemmodeling.org/esmpy_doc/release/latest/html/install.html

**Comment by climbfuji** [comment]
Thanks. We'll try to add this to spack-stack-1.8.0.

**Comment by RoyCaitSith** [comment]
That's great! Recently, I wanted to run HAFS on Derecho. I encountered the same problem. The hafs_ocn_pre requires the ESMPY package.

**Comment by RoyCaitSith** [comment]
I try to use '/glade/work/epicufsrt/contrib/spack-stack/derecho/spack-stack-1.5.1/envs/unified-env/install/intel/2021.10.0/python-3.10.8-kk2syzk/bin/python3.10 -m pip install' to install esmpy today. It works. The esmpy was installed successfully. However, when importing esmpy, the error information shows that /glade/work/epicufsrt/contrib/spack-stack/derecho/spack-stack-1.5.1/envs/unified-env/install/intel/2021.10.0/esmf-8.5.0-oxudzw2/lib/libesmf_fullylinked.so: cannot open shared object file: No such file or directory

**Comment by climbfuji** [comment]
Is this the same as the esmf python variant that just got added to spack develop?

**Comment by BijuThomas-NOAA** [comment]
It is an interface to the ESMF regridding utility
```
Installing ESMPy from Source

When installing from source, ESMPy uses [pip](https://pypi.org/project/pip//) to build and install the package. An installation of ESMPy in the default location for Python packages can be done with the following command issued from the top level ESMPy directory (src/addon/esmpy):

python3 -m pip install
```

**Comment by climbfuji** [comment]
@BijuThomas-NOAA I spent a bit of time to figure out what esmpy is and how it works. There are two open PRs in spack for this, one is stale (from 2023) that adds esmpy as a separate package https://github.com/spack/spack/pull/36124. The other is new and adds the ESMF Python interface (which is esmpy I think) as a variant to the esmf package.

Given that both are open and still under review, I suggest we push out this install request to the following release 1.9.0, not the imminent release 1.8.0.

**Comment by BijuThomas-NOAA** [comment]
@climbfuji Thanks for the update. That is fine with me.
