### ISSUE TITLE
[INSTALL]: g2tmpl/1.12.0 is needed for Rocky-9 environment

### ISSUE THREAD

**Issue by WenMeng-NOAA** [JCSDA/spack-stack#1164]
### Package name

g2tmpl

### Package version/tag

1.12.0

### Build options

None

### Installation timeframe

Please install g2tmpl/1.12.0 at the spack-stack-1.6.0 for Rocky9 environment.

### WCOSS2

- [ ] Check this box if and only if your package should be installed on WCOSS2 Cactus and Dogwood (all spack-stack packages will be installed on Acorn). If not, you may disregard the rest of the items below and submit this request.

### WCOSS2: Technical & security review list

- [ ] The code is mature, stable, and production ready
- [ ] The code is does not and cannot use the internet, and does not contain URLs (http, https, ftp, etc.) except in comments
- [ ] The package does not contain prebuilt binary files that have not been approved by NCO security review
- [ ] The code has no publicly disclosed cybersecurity vulnerabilities and exposures (search https://cve.mitre.org/cve/)
- [ ] The code is not prohibited by DHS, DOC, NOAA, or NWS
- [ ] The code comes from a trusted source. Trusted sources include other NWS, NOAA, or DOC, agencies, or other Federal agencies that operate at a FISMA high or equivalent level. Additionally, trusted sources could be third-party agencies through which there is an existing SLA on file (such as RedHat).
- [ ] The code is actively maintained and supported (it continues to get updates, patches, etc.)
- [ ] The code is not maintained by a private entity operating in a foreign country (if it is, make a note below)
- [ ] There is sufficient documentation to support maintenance
- [ ] There are no known security vulnerabilities or weaknesses
- [ ] Installing and running the code does not require privileged processes/users
- [ ] There are no software dependencies that are unapproved or have security concerns (if there are, make a note below)
- [ ] There are no concerns related to SA, SI, and SC NIST control families

**Comment by WenMeng-NOAA** [comment]
May I get the status of g2tmpl/1.12.0 installation at the spack-stack -1.6.0? The UPP side has been waiting for this installation to update for supporting the upcoming GFS HR4. Thanks!

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA @ulmononian pinging you on this one. Cam, should I continue bothering you while @RatkoVasic-NOAA is on leave, or someone else?

**Comment by AlexanderRichert-NOAA** [comment]
Please try /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.6.0/envs/upp-addon-env/install/modulefiles/Core and let me know if that works for you.

**Comment by WenMeng-NOAA** [comment]
@AlexanderRichert-NOAA Thanks for installation. 
@DavidHuber-NOAA Can you test the UPP compiling with g2tmpl/1.12.0? Thanks!

**Comment by DavidHuber-NOAA** [comment]
It looks like it works.  I'll have a UPP PR in shortly.  Thanks @AlexanderRichert-NOAA!

**Comment by climbfuji** [comment]
Thanks indeed @AlexanderRichert-NOAA - can we close this?

**Comment by WenMeng-NOAA** [comment]
Thanks for installation.
