### ISSUE TITLE
Install Intel Classic 2023.2.4 on various systems

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#1170]
UFS S2S needs Intel Classic 2023.2.1+, and it's a good idea to have the last Classic release anyway. I've put in requests for install on Orion, Hercules, and Gaea C5, but intend to install our own at least for short term use (1.6.0). Related to #1147.

2023.2.4 is _the last_ Intel Classic release.

2023.2.x is already on Hera, Jet, and Gaea C6.

- [x] Gaea C5
- [x] Hercules/Orion
- [x] S4

Steps:
Under /path/to/platform/spack-stack:
```console
mkdir compilers
cd compilers

wget https://registrationcenter-download.intel.com/akdlm/IRC_NAS/b00a4b0e-bd21-41fa-ab34-19e8e2a77c5a/l_dpcpp-cpp-compiler_p_2023.2.4.24_offline.sh
wget https://registrationcenter-download.intel.com/akdlm/IRC_NAS/5bfaa204-689d-4bf1-9656-e37e35ea3fc2/l_fortran-compiler_p_2023.2.4.31_offline.sh
wget https://registrationcenter-download.intel.com/akdlm/IRC_NAS/4f5871da-0533-4f62-b563-905edfb2e9b7/l_mpi_oneapi_p_2021.10.0.49374_offline.sh

if [[ $(sha256sum l_dpcpp-cpp-compiler_p_2023.2.4.24_offline.sh | awk '{print $1}') != f143a764adba04a41e49ec405856ad781e5c3754812e90a7ffe06d08cd07f684 ]]; then echo "DOES NOT MATCH"; fi
if [[ $(sha256sum l_fortran-compiler_p_2023.2.4.31_offline.sh | awk '{print $1}') != 2f327d67cd207399b327df5b7c912baae800811d0180485ef5431f106686c94b ]]; then echo "DOES NOT MATCH"; fi
if [[ $(sha256sum l_mpi_oneapi_p_2021.10.0.49374_offline.sh | awk '{print $1}') != ab2e97d87b139201a2e7dab9a61ac6e8927b7783b459358c4ad69a1b1c064f40 ]]; then echo "DOES NOT MATCH"; fi

chmod u+x l_dpcpp-cpp-compiler_p_2023.2.4.24_offline.sh l_fortran-compiler_p_2023.2.4.31_offline.sh l_mpi_oneapi_p_2021.10.0.49374_offline.sh

./l_dpcpp-cpp-compiler_p_2023.2.4.24_offline.sh --extract-folder $PWD/cache -s -a -s --action install --eula accept --install-dir $PWD/oneapi --download-cache $PWD/cache
./l_fortran-compiler_p_2023.2.4.31_offline.sh --extract-folder $PWD/cache -s -a -s --action install --eula accept --install-dir $PWD/oneapi --download-cache $PWD/cache
./l_mpi_oneapi_p_2021.10.0.49374_offline.sh --extract-folder $PWD/cache -s -a -s --action install --eula accept --install-dir $PWD/oneapi --download-cache $PWD/cache

# Generate modulefiles and in stack-intel module, manually add a prepend_path to MODULEPATH with the intel module file root
```

**Comment by AlexanderRichert-NOAA** [comment]
Since ostensibly we don't need a new compiler installation with each release, I'm thinking in each platform's spack-stack directory, I'll have 'spack-compilers/' with a copy of Spack and 'compilers/' for the installation directory to keep the paths short-ish.

**Comment by climbfuji** [comment]
> Since ostensibly we don't need a new compiler installation with each release, I'm thinking in each platform's spack-stack directory, I'll have 'spack-compilers/' with a copy of Spack and 'compilers/' for the installation directory to keep the paths short-ish.

Are you planning to install the compilers using spack? I wasn't going to do that.

**Comment by AlexanderRichert-NOAA** [comment]
That was the plan. Any reason not to?

**Comment by climbfuji** [comment]
Personal preference. I do `wget link-to-oneapi-basekit` and `wget link-to-oneapi-hpckit`, `sh each of them` and then run the module generator that comes with oneAPI.

**Comment by srherbener** [comment]
Everyone and @climbfuji. I'm in Michigan now working remotely, and I am going to take next week off on vacation. I am not going to have time to look at this until after I get back (July 8).

Plus, I am getting swamped with IODA requests which are a higher priority for me. We are trying to get this sorted out at JCSDA, but for now the time that I can dedicate to spack-stack is quite limited. I'm sorry about this situation, but I wanted to let you know what's going on. Thank you for your patience (I know my response time hasn't be very quick lately).

**Comment by climbfuji** [comment]
> Everyone and @climbfuji. I'm in Michigan now working remotely, and I am going to take next week off on vacation. I am not going to have time to look at this until after I get back (July 8).
> 
> Plus, I am getting swamped with IODA requests which are a higher priority for me. We are trying to get this sorted out at JCSDA, but for now the time that I can dedicate to spack-stack is quite limited. I'm sorry about this situation, but I wanted to let you know what's going on. Thank you for your patience (I know my response time hasn't be very quick lately).

I can take care of S4 after hours

**Comment by AlexanderRichert-NOAA** [comment]
@climbfuji fine by me, I'll take a crack at it on, say, Gaea C5 and see how it goes.

**Comment by AlexanderRichert-NOAA** [comment]
@climbfuji do the installer URLs in the description look right to you?

**Comment by AlexanderRichert-NOAA** [comment]
Addendum- I can't access the "basekit" installers since I don't have "priority support" or whatever.

**Comment by climbfuji** [comment]
wget doesn't work? Maybe you are blocked by the firewall?

**Comment by AlexanderRichert-NOAA** [comment]
Can you supply the full URLs?

**Comment by climbfuji** [comment]
Turns out I can't either. we'll have to get those from our Intel partners. Next week - sorry. Alternatively, download everything you need mkl, tbb, compilers, mpi from the spack urls that you pasted above.

**Comment by AlexanderRichert-NOAA** [comment]
I've got this more or less figured out for the moment, so it's just a matter of testing. Would you be able to put a ticket for S4 to see if they can install system wide? I've put in tickets for Gaea C5, Hercules, and Orion asking for 2023.2.4 (2021.10.0 20230609). Meanwhile I'll keep pushing ahead with doing our own installs.

**Comment by climbfuji** [comment]
> I've got this more or less figured out for the moment, so it's just a matter of testing. Would you be able to put a ticket for S4 to see if they can install system wide? I've put in tickets for Gaea C5, Hercules, and Orion asking for 2023.2.4 (2021.10.0 20230609). Meanwhile I'll keep pushing ahead with doing our own installs.

I sent an email to the S4 help desk and cc-ed Steve

**Comment by climbfuji** [comment]
I heard back from S4 - they are planning to do this after the update to Rocky 8, which is scheduled for some time in August this year.

**Comment by AlexanderRichert-NOAA** [comment]
@junwang-noaa can you comment on the timeline you're shooting for (especially relative to the August timeline for S4)?

**Comment by junwang-noaa** [comment]
It is good if the Intel compiler update can be done by the end of August, 2024. Thank you!

**Comment by climbfuji** [comment]
Thanks Jun. That also makes sense from a spack-stack perspective, since we are planning to release 1.8.0 end of August/beginning of September. We can then use the last release of the classic Intel compilers for the 1.8.0 release.

**Comment by AlexanderRichert-NOAA** [comment]
From Gaea folks, re: C5: "The system upgrade would be August at the soonest, but that the actual date will depend on the testing being currently being done by the NOAA folks before the system upgrade is done."

**Comment by AlexanderRichert-NOAA** [comment]
No news from Gaea C5.

@RatkoVasic-NOAA @ulmononian are you okay with using the existing compilers for Orion/Hercules/C5 for the 1.8.0 release, then add another stack (possibly a subset, for supporting UFS S2S) using the 2023.2.x compilers that we installed?

**Comment by RatkoVasic-NOAA** [comment]
> No news from Gaea C5.
> 
> @RatkoVasic-NOAA @ulmononian are you okay with using the existing compilers for Orion/Hercules/C5 for the 1.8.0 release, then add another stack (possibly a subset, for supporting UFS S2S) using the 2023.2.x compilers that we installed?

Works for me.

**Comment by AlexanderRichert-NOAA** [comment]
Then I guess same question applies to Hera and Jet (whereas C6 is already set to use 2023.2)-- should we advance the compiler version for 1.8.0, or just add a second environment after the release that uses the 2023.2 system-wide installations? @climbfuji any opinion? I don't want to disrupt users so if those doing the installations don't mind the extra work then I'm good with that, but I'm not against updating those site configs for the release either.

**Comment by climbfuji** [comment]
All of these systems are maintained by EPIC, therefore I'll leave that up to the EPIC folks and you to decide

**Comment by ulmononian** [comment]
> Then I guess same question applies to Hera and Jet (whereas C6 is already set to use 2023.2)-- should we advance the compiler version for 1.8.0, or just add a second environment after the release that uses the 2023.2 system-wide installations? @climbfuji any opinion? I don't want to disrupt users so if those doing the installations don't mind the extra work then I'm good with that, but I'm not against updating those site configs for the release either.

in the name of avoiding potentially unforeseen consequences of migrating to the new compilers this close to the release, doing post-release envs w/ the new intel compiler version probably makes sense on all of these platforms. i do start to worry about storage capacity, though. @RatkoVasic-NOAA will be doing the installations (potentially along w/ @rickgrubin-noaa), so if they don't mind doing two installs, i tend to think maintaining two compiler envs right now is safest. thoughts @RatkoVasic-NOAA @rickgrubin-noaa?

**Comment by RatkoVasic-NOAA** [comment]
We can add new compilers as new environments after the release. As for storage capacity, we are moving on most machines to the new space (like /contrib), I don't think storage will be a problem there.

**Comment by rickgrubin-noaa** [comment]
Prefer two installations, for consistency with other hosts / installations, and to maintain integrity with respect to the `v1.8.0` release.

**Comment by AlexanderRichert-NOAA** [comment]
Gaea C5: "The requested change is projected to occur on the next system upgrade which is planned for October 14-16."

**Comment by climbfuji** [comment]
The S4 update is done, and spack-stack-1.8.0 was installed in a test location (official install running now):
```
$ which icc
/opt/intel/oneapi/2023.2/compiler/2023.2.0/linux/bin/intel64/icc
```
I see all boxes checked in the PR description, but I am wondering about C5 because of comment https://github.com/JCSDA/spack-stack/issues/1170#issuecomment-2329560593?

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA @RatkoVasic-NOAA Any updates on Gaea C5? Are we going to defer this system to the next release of spack-stack (not so far out)?

**Comment by AlexanderRichert-NOAA** [comment]
Since we're installing our own compilers all over anyway, I don't know if I have any preference as to you using the system-wide one versus our copy.

**Comment by AlexanderRichert-NOAA** [comment]
I'll close this for now, but that doesn't preclude us from using a system-wide install if/when it becomes available.
