### ISSUE TITLE
CI container builds broken after merging https://github.com/JCSDA/spack-stack/pull/1138 (Overhaul packages.yaml)

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#1173]
**Describe the bug**
I will provide more details shortly.

**To Reproduce**

**Expected behavior**

**System:**
What system(s) are you running the code on?

**Additional context**

**Comment by BenjaminRuston** [comment]
this one ... any implication for UFO and JEDI repos in general?

**Comment by climbfuji** [comment]
Not immediately, since the containers aren't updated automatically. But we'll fix it this week, no worries

**Comment by BenjaminRuston** [comment]
This is then CI for spack-stack... nothing to worry about if we are not
using develop for that.

**Comment by climbfuji** [comment]
Well, technically JCSDA isthe only user of the CI containers ... others may not fix the containers every time the need maintenance.
