### ISSUE TITLE
Update g2tmpl to 1.12.0 on NOAA-Cloud (CSPs)

### ISSUE THREAD

**Issue by weihuang-jedi** [JCSDA/spack-stack#1183]
Can we update g2tmpl within spack-stack on CSPs to 1.12.0?

The current develop branch on CSPs has problem to compile:

./compile_upp.sh
Building for machine noaacloud, compiler intel
Lmod has detected the following error: The following module(s) are unknown: "g2tmpl/1.12.0"
Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
$ module --ignore_cache load "g2tmpl/1.12.0"

Also make sure that all modulefiles written in TCL start with the string #%Module

Executing this command requires loading "g2tmpl/1.12.0" which failed while processing the following module(s):

Module fullname  Module Filename
---------------  ---------------
upp_common       /contrib/Wei.Huang/src/global-workflow-cloud/sorc/ufs_model.fd/FV3/upp/modulefiles/upp_common.lua
noaacloud        /contrib/Wei.Huang/src/global-workflow-cloud/sorc/ufs_model.fd/FV3/upp/modulefiles/noaacloud.lua
Current on CSPs, we have:
[Wei.Huang@wei1epic2azure3slurm-85 c48atm]$ module spider g2tmpl

g2tmpl: g2tmpl/1.10.2

If we force to use g2tmpl/1.10.2, we got error:
/contrib/Wei.Huang/src/global-workflow-cloud/sorc/ufs_model.fd/FV3/upp/sorc/ncep_post.fd/grib2_module.f(502): error #6580: Name in only-list does not exist or is not accessible. [G2SEC4_TEMP9]
g2sec4_temp0,g2sec4_temp8,g2sec4_temp9,g2sec4_temp44, &
-----------------------------------------------------^
/contrib/Wei.Huang/src/global-workflow-cloud/sorc/ufs_model.fd/FV3/upp/sorc/ncep_post.fd/grib2_module.f(503): error #6580: Name in only-list does not exist or is not accessible. [G2SEC4_TEMP46]
g2sec4_temp46,g2sec4_temp48,g2sec5_temp0,g2sec5_temp2, &
---------------------------^
compilation aborted for /contrib/Wei.Huang/src/global-workflow-cloud/sorc/ufs_model.fd/FV3/upp/sorc/ncep_post.fd/grib2_module.f (code 1)
make[2]: *** [sorc/ncep_post.fd/CMakeFiles/upp.dir/grib2_module.f.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [sorc/ncep_post.fd/CMakeFiles/upp.dir/all] Error 2
make: *** [all] Error 2

**Comment by climbfuji** [comment]
@weihuang-jedi This request was made to us in the past, and for this purpose we installed an addon environment called `upp-env` for spack-stack-1.6.0. I don't have access to your NOAA CSPs, but on S4 these directories = environments exist in `spack-stack-1.6.0/envs`:
```
-bash-4.2$ ls -l envs/
total 46
drwxr-xr-x 6 jedipara domain users 11776 Jan  3  2024 gsi-addon-env
drwxr-xr-x 6 jedipara domain users 11776 Jan  2  2024 unified-env
drwxr-xr-x 7 jedipara domain users 11776 Apr 24 17:13 upp-addon-env
```
This should be the same on ParallelWorks. If you can locate `upp-addon-env`, please try to use that. It's the same as `unified-env`, except that it has `g2tmpl@1.12.0`.

**Comment by weihuang-jedi** [comment]
@Dom Heinzeller ***@***.***> I do not see upp-addon-env on AWS:

***@***.*** modulefiles]$ pwd
/contrib/Wei.Huang/src/global-workflow-cloud/sorc/ufs_model.fd/FV3/upp/modulefiles
***@***.*** modulefiles]$ ls -l
/contrib/spack-stack/spack-stack-1.6.0/envs
total 8
drwxr-xr-x. 6 root root 6144 Apr 17 23:04 gsi-addon-env
drwxr-xr-x. 6 root root 6144 Jun 11 14:37 unified-env

**Comment by climbfuji** [comment]
@natalie-perlin Can you fix this, please?

**Comment by natalie-perlin** [comment]
@climbfuji - somebody from the SI team will install upp-addon-env on NOAA CSP. Where is the best place to find directions (any specific PRs?)

**Comment by climbfuji** [comment]
See https://github.com/JCSDA/spack-stack/issues/1087

**Comment by weihuang-jedi** [comment]
On CSPs, please install at: /contrib/spack-stack/spack-stack-1.6.0/envs

**Comment by natalie-perlin** [comment]
@weihuang-jedi  @climbfuji - 
Installation of upp-addon-env completed for AWS, GCloud, and Azure ( for CentOS )

A chained environment with g2tmpl/1.12.0 is installed in 
`/contrib/spack-stack/spack-stack-1.6.0/envs/upp-addon-env `

**Comment by climbfuji** [comment]
Thanks @natalie-perlin ! Closing this, please reopen if there are still issues.

**Comment by weihuang-jedi** [comment]
Thank you @natalie-perlin !
