### ISSUE TITLE
Update spack submodule to release v0.17.2

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#119]
spack v0.17.2 was released: https://github.com/spack/spack/releases/tag/v0.17.2

Let's update to this version (including all our changes).

**Comment by climbfuji** [comment]
@kgerheiser I looked at the diffs between v0.17.2 and our version, which is pretty close to develop (on track to become v0.18 at some point). There are many more differences than I expected. I would suggest to keep pulling in develop until v0.18 is released, and use spack releases from that point on.

**Comment by kgerheiser** [comment]
I had the same idea of updating Spack to v0.17.2 after seeing the release yesterday, but yeah staying until v0.18 sounds good.
