### ISSUE TITLE
eccodes command line utilities missing

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#1196]
**Is your feature request related to a problem? Please describe.**
The eccodes command line utilities aren't built by default (e.g. `grib_ls`, ....). I think this is because the `tools` variant is off by default (to be confirmed).
https://github.com/JCSDA/spack/blob/0605595991483f122b024a7f96975d901f87dae7/var/spack/repos/builtin/packages/eccodes/package.py#L70
The variant doesn't introduce any new dependencies.

**Describe the solution you'd like**
Try to enable the `tools` variant, and if it all builds check if the missing command line utilities are installed. Let's try to do this before the spack-stack-1.8.0 release.

**Additional context**
n/a

**Comment by AlexanderRichert-NOAA** [comment]
Is this needed for a particular code/application?

**Comment by climbfuji** [comment]
> Is this needed for a particular code/application?

NRL was asking for it, yes
