### ISSUE TITLE
[INSTALL]: Update to wgrib2 3.3.0?

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#1199]
### Package name

wgrib2

### Package version/tag

3.3.0 - https://github.com/NOAA-EMC/wgrib2/releases/tag/v3.3.0

### Build options

Need to be checked - this is a new build system

### Installation timeframe

See https://github.com/NOAA-EMC/wgrib2/releases/tag/v3.2.0 - is it possible to include this in spack-stack-1.8.0?

### Other information

My hope is that the new cmake build system will solve the constant problems we've had with building wgrib2.

### WCOSS2

- [X] Check this box if and only if your package should be installed on WCOSS2 Cactus and Dogwood (all spack-stack packages will be installed on Acorn). If not, you may disregard the rest of the items below and submit this request.

### WCOSS2: General questions

Already approved for wcoss2, and developed by NOAA-EMC

### WCOSS2: Technical & security review list

- [ ] The code is mature, stable, and production ready
- [ ] The code is does not and cannot use the internet, and does not contain URLs (http, https, ftp, etc.) except in comments
- [ ] The package does not contain prebuilt binary files that have not been approved by NCO security review
- [ ] The code has no publicly disclosed cybersecurity vulnerabilities and exposures (search https://cve.mitre.org/cve/)
- [ ] The code is not prohibited by DHS, DOC, NOAA, or NWS
- [ ] The code comes from a trusted source. Trusted sources include other NWS, NOAA, or DOC, agencies, or other Federal agencies that operate at a FISMA high or equivalent level. Additionally, trusted sources could be third-party agencies through which there is an existing SLA on file (such as RedHat).
- [ ] The code is actively maintained and supported (it continues to get updates, patches, etc.)
- [ ] The code is not maintained by a private entity operating in a foreign country (if it is, make a note below)
- [ ] There is sufficient documentation to support maintenance
- [ ] There are no known security vulnerabilities or weaknesses
- [ ] Installing and running the code does not require privileged processes/users
- [ ] There are no software dependencies that are unapproved or have security concerns (if there are, make a note below)
- [ ] There are no concerns related to SA, SI, and SC NIST control families

**Comment by AlexanderRichert-NOAA** [comment]
Per @edwardhartnett's suggestion, it's probably best to stick with 3.1.1 for now while some of the wrinkles are still being ironed out of the CMake-based wgrib2. It may take a couple more releases to have a version that's ready to replace the legacy (@:3.1.1) version. I'm going to close this for now but feel free to reopen if you feel strongly, or when 3.4 or 3.5 or whatever is ready to go.
