### ISSUE TITLE
Ubuntu CI runner ran out of disk space again

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#1202]
**Describe the bug**
Despite moving various run/build directories to `/mnt/addon` on the Ubuntu CI runner, the spack-stack tests still fail occasionally (just happened a few minutes ago). We need more space on the root filesystem! Unfortunately, I no longer control the instance.

**To Reproduce**
Watch CI and you may be able to see it at some point

**Expected behavior**
Enough disk space so that these unnecessary errors don't happen again.

**System:**
Self-hosted Ubuntu CI runner

**Additional context**

**Comment by climbfuji** [comment]
A workaround is proposed for simobs: similar to ufs-bundle, move the "jedi-run" directory to the addon disk:

https://github.com/JCSDA-internal/SIMOBS/pull/294

I checked the available disk space there, and even after moving that run directory, there is still a buffer of about 70Gb currently. That should buy us enough time until I return from leave early August and we can work on a more permanent solution.

**Comment by edwardhartnett** [comment]
A more permanent solution would be to move testing to a jenkins server. Then there are no space limitations and it would be a lot faster.

Can EPIC supply us with a jenkins instance we can use, and all have log-ins to?

**Comment by eap** [comment]
I updated the root volume to be larger and I'm moving back simobs but leaving ufs-bundle alone, this should take care of things for the forseeable future (until our dependencies, testing data, and build artifacts grow far beyond the current state)

**Comment by climbfuji** [comment]
perfect, thanks!
