### ISSUE TITLE
Need shared (dynamic) libraries for FMS on MacOS

### ISSUE THREAD

**Issue by srherbener** [JCSDA/spack-stack#1211]
**Is your feature request related to a problem? Please describe.**

When we moved to FMS@2023.04, many ctests started to fail on MacOS. We discovered that the issue was using static FMS libraries along with the Mac two-level namespace linker/loader scheme. Using shared FMS libraries (built manually) fixed this issue. For details, see: https://github.com/JCSDA-internal/fv3-jedi/issues/1237.

I submitted a PR to the NOAA-GFDL FMS repo to add in the option to build shared libraries: https://github.com/NOAA-GFDL/FMS/pull/1559

I've put a workaround in place for JCSDA to get us by for now: https://github.com/JCSDA/FMS/blob/feature/mac-fms-2023.04/JEDI_BUNDLE_BUILD_ON_MACOS.md

We need to apply an equivalent patch/workaround to the build process for FMS@2023.04 when building on MacOS to hold us over until we move to whatever version of FMS will have the shared library option in the above PR. 

**Describe the solution you'd like**

I was thinking of creating a "shared" variant that would apply a patch to have FMS build shared libraries, which would be off by default and turned on for the macos build.

**Additional context**

**Comment by eap** [comment]
We may push this feature out to 1.9: this is currently covered by a workaround. It would be nice to have this but there's enough needed for the 1.8 release.
