### ISSUE TITLE
Is spack-stack 1.7.0 GNU broken on Orion/Hercules after maintenance on 2024/07/24?

### ISSUE THREAD

**Issue by fabiolrdiniz** [JCSDA/spack-stack#1212]
**Describe the bug**
People are reporting what looks like a broken MPI-related environment for spack-stack 1.7.0 GNU broken on Orion/Hercules after maintenance on 2024/07/24.

**To Reproduce**

- Orion:

```console
$ module purge
$ module use /work/noaa/epic/role-epic/spack-stack/orion/modulefiles
$ module load ecflow/5.8.4

$ module use /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.7.0/envs/ue-gcc/install/modulefiles/Core
$ module load stack-gcc/12.2.0
$ module load stack-openmpi/4.1.6

$ mpicc
mpicc: error while loading shared libraries: libslurm_pmi.so: cannot open shared object file: No such file or directory
```

**System:**
MSU machines

**Comment by fabiolrdiniz** [comment]
@AlexanderRichert-NOAA and @RatkoVasic-NOAA, I've seen your involvement on https://github.com/JCSDA/spack-stack/issues/981, so I was wondering if at least one of you should be aware of this one.

**Comment by srherbener** [comment]
@fabiolrdiniz, thanks for reporting this. I can get it to work by adding `/opt/slurm/lib/slurm` to my LD_LIBRARY_PATH. For example:

```
(venv) orion-login-2[60] herbener$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/slurm/lib/slurm
(venv) orion-login-2[61] herbener$ mpicc --version
gcc (GCC) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(venv) orion-login-2[62] herbener$ 
```

Not sure why this is necessary, or what changed. Any ideas about what has happened, and the proper way to fix?  Thanks!

**Comment by climbfuji** [comment]
The sysadmins probably removed/changed the slurm installation - they've done that in the past and that broke the OpenMPI builds.

**Comment by climbfuji** [comment]
You could add the workaround to https://github.com/JCSDA/spack-stack/wiki and be done with it. Future spack-stack releases may need to include the LD_LIBRARY_PATH modification in the meta modules (for example by adding them in the compiler config), or in the openmpi modulefile (ourselves if we built them, or ask the sysadmins if we use their OpenMPI).

**Comment by srherbener** [comment]
Thanks for the pointer to the spack-stack wiki page Dom. I've added the LD_LIBRARY_PATH workaround so all the tips are in one spot.

**Comment by RatkoVasic-NOAA** [comment]
I added new path to LD_LIBRARY_PATH in openmpi/4.1.6.lua.
@fabiolrdiniz can you please try with same loading procedure.

**Comment by fabiolrdiniz** [comment]
Thank you for the quick replies.

@srherbener and @climbfuji, thanks for the suggestions.

@RatkoVasic-NOAA, yes, I can confirm it now runs fine with the commands above, and the path is augmented (please, notice the two locations... should be fine):

```console
$ echo -e ${LD_LIBRARY_PATH//:/\\n}
/opt/slurm/lib/slurm
/work/noaa/epic/role-epic/spack-stack/orion/installs/openmpi/4.1.6/lib
/work/noaa/epic/role-epic/spack-stack/orion/installs/gcc/12.2.0/lib
/work/noaa/epic/role-epic/spack-stack/orion/ecflow-5.8.4/lib64
/work/noaa/epic/role-epic/spack-stack/orion/ecflow-5.8.4/lib
/usr/lib64
/usr/lib
/opt/slurm/lib
```

Closing this one, but feel free to re-open if needed.

**Comment by fabiolrdiniz** [comment]
@RatkoVasic-NOAA, looks like we need to do the same change on Hercules (not Orion only). Thanks.

**Comment by RatkoVasic-NOAA** [comment]
@fabiolrdiniz is that same thing like on Orion?

**Comment by fabiolrdiniz** [comment]
Unfortunately, yes. Thanks for asking.

**Comment by huishao-r** [comment]
Yes, I still have the same MPI issue on the hercules

**Comment by RatkoVasic-NOAA** [comment]
I'm looking into that.

**Comment by huston-rogers** [comment]
Spack has a behavior where if an external package is a link, then it fully resolves the link when it goes to the linking stage of compiling, i.e. /opt/slurm -> /opt/slurm-XX.yy at build time gets the full path hard coded. You can see this by ldd -ing the executable. When we upgrade slurm for security patches and remove the old slurm, it breaks mpi builds.

Our helpdesk/admin team has created a non-production node where slurm isn't a link, and that has fixed this spack behavior. If you need a different openmpi, send us a ticket and we'll get it created. gcc-12.2.0+openmpi-4.1.4 should be working now, following the previous rebuild issues.

**Comment by RatkoVasic-NOAA** [comment]
@fabiolrdiniz and @huishao-r 
Please check if this change works for you:
I renamed required openmpi from `4.1.6-gcc-12.2.0-spack` to `4.1.4` in `gcc/12.2.0/stack-openmpi/4.1.6.lua` modulefile.

**Comment by huishao-r** [comment]
I didn't have the original MPI issues. But I got the following message during build: 
```
CMake Warning at /work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-1.7.0/envs/ue-gcc/install/gcc/12.2.0/ecbuild-3.7.2-nnjboq2/share/ecbuild/cmake/ecbuild_add_executable.cmake:209 (add_executable):
  Cannot generate a safe runtime search path for target
  test_fv3jedi_variablechange.x because there is a cycle in the constraint
  graph:

    dir 0 is [/work2/noaa/jcsda/hshao/hercules/JEDI_ROOT_gnu/ufs-bundle.HailingVersion+ROPP_202407/build/Depends/lib]
    dir 1 is [/work2/noaa/jcsda/hshao/hercules/JEDI_ROOT_gnu/ufs-bundle.HailingVersion+ROPP_202407/build/lib]
    dir 2 is [/work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-1.7.0/envs/ue-gcc/install/gcc/12.2.0/ecmwf-atlas-0.36.0-tgmbvjc/lib64]
    dir 3 is [/work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-1.7.0/envs/ue-gcc/install/gcc/12.2.0/fckit-0.11.0-njbdjuc/lib64]
    dir 4 is [/work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-1.7.0/envs/ue-gcc/install/gcc/12.2.0/eckit-1.24.5-a4uan4t/lib64]
```

**Comment by fabiolrdiniz** [comment]
@RatkoVasic-NOAA, it seems to be working fine now. Please, see below:

```console
$ module purge
$ module use /work/noaa/epic/role-epic/spack-stack/orion/modulefiles
$ module load ecflow/5.8.4
$ module use /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.7.0/envs/ue-gcc/install/modulefiles/Core
$ module load stack-gcc/12.2.0
$ module load stack-openmpi/4.1.6

$ mpicc
gcc: fatal error: no input files
compilation terminated.

$ echo -e ${LD_LIBRARY_PATH//:/\\n}
/opt/slurm/lib/slurm
/work/noaa/epic/role-epic/spack-stack/orion/installs/openmpi/4.1.6/lib
/work/noaa/epic/role-epic/spack-stack/orion/installs/gcc/12.2.0/lib
/work/noaa/epic/role-epic/spack-stack/orion/ecflow-5.8.4/lib64
/work/noaa/epic/role-epic/spack-stack/orion/ecflow-5.8.4/lib
/usr/lib64
/usr/lib
/opt/slurm/lib
```

**Comment by fabiolrdiniz** [comment]
Thanks again to everyone involved. Closing it... reopen if needed.
