### ISSUE TITLE
[INSTALL]: Add crtm@3.1.1 to spack-stack-1.8.0

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#1227]
### Package name

crtm

### Package version/tag

3.1.1

### Build options

current

### Installation timeframe

For spack-stack-1.8.0 - the crtm 3.1.1 release will be tagget this week. EMC requested CRTMv3 in spack-stack, therefore it makes sense to use the latest bug fix release in spack-stack-1.8.0.

**Comment by climbfuji** [comment]
@BenjaminTJohnson and @Hang-Lei-NOAA - can you confirm that CRTM v3.1.1 https://github.com/JCSDA/CRTMv3/releases/tag/v3.1.1 is a good version to install in spack-stack-1.8.0 for EMC?

**Comment by BenjaminTJohnson** [comment]
It was just released last night, let's give it a minute for EMC to work
through it.

**Comment by BenjaminTJohnson** [comment]
@BenjaminRuston FYI

**Comment by BenjaminRuston** [comment]
thanks @BenjaminTJohnson and @climbfuji ,,, please keep me in the loop regarding inclusion of CRTM in stack in the future think there could be reasons either way

**Comment by climbfuji** [comment]
This is a duplicate of #1185 - let's continue the discussion there.
