### ISSUE TITLE
Duplicate packages being build with different hashes because of different Autoconf provider

### ISSUE THREAD

**Issue by kgerheiser** [JCSDA/spack-stack#123]
See https://github.com/spack/spack/issues/29930

I found this on the NOAA Cloud platforms. Pkgconf is defined as an external, but it's not being used in all instances, and `pkg-config` is being used, resulting in different hashes for NetCDF. My solution was to set `pkg-config` to `buildable: False`.

**Comment by climbfuji** [comment]
@kgerheiser Is this still an issue after updating to spack v0.18? If so, should that be in release v1 or later?

**Comment by kgerheiser** [comment]
This is still an issue. I think we should set `pkgconfig` to not buildable. All platforms seems to have `pkg-conf`.

**Comment by climbfuji** [comment]
Closed via https://github.com/NOAA-EMC/spack-stack/pull/214
