### ISSUE TITLE
Orion config contains faulty paths (eg, git-lfs) to external packages

### ISSUE THREAD

**Issue by srherbener** [JCSDA/spack-stack#1235]
**Describe the bug**

Recent testing revealed that the wrong path to git-lfs is entered in the site packages incorrectly for Orion. The current path is:
- /apps/spack-managed/gcc-11.3.1/git-lfs-3.1.2

and the correct path is:
- /apps/spack-managed/gcc-11.3.1/git-lfs-3.1.2-sjfqfgha27na65g3lrcqamncnryjoa7l

Are there any other places that the path to git-lfs needs to be updated? 

Also, as @climbfuji noted, we should inspect the Orion configuration to make sure all the faulty paths (if there are any more) are fixed.

**To Reproduce**
On Orion:
1. build spack-stack from the develop branches
2. load modules for using the spack-stack from step 1 to build jedi-bundle
3. run ecbuild

The ecbuild run fails with an error saying it cannot find the git-lfs command.

**Expected behavior**

The steps outlined above work correctly

**System:**
What system(s) are you running the code on?
Orion

**Additional context**

**Comment by srherbener** [comment]
I'll start a PR now with the new path. Reviewers please let me know if I need to make other changes to fix this issue. Thanks!

**Comment by climbfuji** [comment]
I am getting worried that more updates of the site config are missing from the Rocky 9 transition. Can you check the site configs for the spack-stack-1.7.0 Rocky9 installs and make sure that what's in spack-stack develop matches it? Or ask @RatkoVasic-NOAA to help out?

**Comment by srherbener** [comment]
I just created a feature branch with the git-lfs path update. I can make a draft PR from that branch and it can be used for the basis of getting all of the paths in the Orion config fixed. I'll update the title of this issue too.

After making this change I was able to build jedi-bundle with one workaround for one more issue that is more general than Orion. This issue is with the latest json and json-scheme-validator upgrade, and is impacting jedi-bundle builds no matter what platform. I'll open a new ticket for that json issue.

**Comment by srherbener** [comment]
There is a draft PR now (#1236) that we can build upon if we find more incorrect paths. @RatkoVasic-NOAA would you be willing to do the check @climbfuji was suggesting? Thanks!

**Comment by RatkoVasic-NOAA** [comment]
@srherbener yes, I'm checking it now.

**Comment by srherbener** [comment]
Thank you @RatkoVasic-NOAA!

**Comment by RatkoVasic-NOAA** [comment]
@srherbener I checked all external executables in configs/sites/tier1/orion/packages.yaml and the only one that had incomplete path was the one you already found: git-lfs.
Others, in /usr/bin match versions.

**Comment by srherbener** [comment]
Thank you @RatkoVasic-NOAA for checking the external executable entries. I'll remove the draft status on the PR I created.
