### ISSUE TITLE
jedi-bundle is not building with recently upgraded versions of json and json-schema-validator packages

### ISSUE THREAD

**Issue by srherbener** [JCSDA/spack-stack#1237]
**Describe the bug**

Recent testing on Orion has revealed that jedi-bundle (oops code) will not compile with the latest version of the json and json-schema-validator packages. I verified that jedi-bundle does build correctly when using the spack-stack-1.7.0 versions of these packages.

spack-stack-1.7.0 versions:
- json@3.10.5
- json-schema-validator@2.1.0

develop versions
- json@3.11.2
- json-schema-validator@2.3.0

**To Reproduce**
1. build spack-stack environment from develop branches
2. build jedi-bundle

**Expected behavior**
The steps listed above complete successfully

**System:**
What system(s) are you running the code on?
Orion and Discover

**Additional context**

Here is the error message I am seeing on Discover  using Intel
```
/discover/nobackup/sherbene/jedi/jedi-bundle/oops/src/oops/util/parameters/Parameters.cc(46): error: member function declared with "override" does not override a base class member
    void error(const nlohmann::json_pointer<nlohmann::basic_json<>> &pointer,
         ^

/discover/nobackup/sherbene/jedi/jedi-bundle/oops/src/oops/util/parameters/Parameters.cc(50): error: no suitable user-defined conversion from "const nlohmann::json_abi_v3_11_2::json_pointer<nlohmann::json_abi_v3_11_2::basic_json<std::map, std::vector, std::string, bool, int64_t={long}, uint64_t={unsigned long}, double, std::allocator, nlohmann::json_abi_v3_11_2::adl_serializer, std::vector<uint8_t={unsigned char}, std::allocator<uint8_t={unsigned char}>>>>" to "const
          nlohmann::json_abi_v3_11_2::json_pointer<std::string>" exists
      basic_error_handler::error(pointer, instance, message);
                                 ^

compilation aborted for /discover/nobackup/sherbene/jedi/jedi-bundle/oops/src/oops/util/parameters/Parameters.cc (code 2)
```
and I see a similar error message on Orion using GNU.

**Comment by srherbener** [comment]
Does anyone have any objection to resolving this issue by reverting json and json-schema-validator to the spack-stack-1.7.0 versions? Ie, defer these upgrades until spack-stack-1.9.0. Not sure, but this seems like a library incompatibility issue (between json and json-schema-vaildator) with the new library versions.

**Comment by climbfuji** [comment]
I believe the problem with the old versions was that we were getting duplicate packages. I fear we can't roll back to the old versions and JEDI needs to be updated. Do you have any idea how much work will be involved?

**Comment by srherbener** [comment]
@climbfuji thanks for the feedback. It's not clear at this point. The error involves an object called a `json_pointer` and after a quick look it seems that the code related to a `json_pointer` hasn't been touched for years. So, no related code changes seem to exist and the error pops up. Perhaps there is some environment or build configuration that changed. I'll take a further look.

**Comment by climbfuji** [comment]
Did you check the json github announcements? The author is pretty good at describing the releases, e.g. deprecated features, new features, ...

For example https://github.com/nlohmann/json/discussions/3639

**Comment by climbfuji** [comment]
Maybe also check if there is a conflict between the json and the json-schema-validator version?

**Comment by srherbener** [comment]
I've run into another issue with this: where the make step breaks during the build of oops due to the nlohmann-json-schema-validator library not being found. This turns out to be that the name of the target for the nlohmann-json-schema-validator got renamed. I tried the new name which fixes the spack-stack-1.8.0 build issue with the new json library version, but that won't work with the current spack-stack-1.7.0 versions.

Does anyone know how to test for the existence of a target in cmake? Or is there another mechanism to handle cases like this. I essentially want to query the existence or either target name, and then use the one that exists in the target_link_libraries command.

**Comment by srherbener** [comment]
I think I found it: `if(TARGET <target-name>)`. I'll give it a try.

**Comment by climbfuji** [comment]
I am very confused now, not sure I understand what the problem is. But maybe something like this:
```
 find_package(ESMF 8.3.0 MODULE REQUIRED)
+if (NOT TARGET ESMF::ESMF)
+       add_library(ESMF::ESMF ALIAS esmf)
+endif ()
```

**Comment by srherbener** [comment]
In version 2.1.0 of nlohmann-json-scheme-validator the link target is named `nlohmann-json-schema-validator`

In version 2.3.0 the target is named `nlohmann-json-schema-validator::validator`

**Comment by srherbener** [comment]
The oops PR jcsda-internal/oops/pull/2725 has a fix for the jedi-bundle compile error noted in the initial description, as well as the recently reported issue with the nlohmann_json_schema_validation target name change.

The oops changes will allow jedi-bundle to build with spack-stack-1.7.0 as well as with spack-stack built using the latest develop branches in spack-stack and spack. Therefore there is no need to change anything in spack-stack or spack.

**Comment by climbfuji** [comment]
That's amazing, thanks for fixing this so quickly! Please close the issue whenever you think is appropriate.

**Comment by srherbener** [comment]
https://github.com/JCSDA-internal/oops/pull/2725 has been merged and it fully addresses this issue. I'll close it now.
