### ISSUE TITLE
jedi-bundle fails to build with latest version of spack-stack, spack repos

### ISSUE THREAD

**Issue by srherbener** [JCSDA/spack-stack#1241]
**Describe the bug**

After building spack-stack using the latest develop branches on an AWS Ubuntu 22.24.01 EC2 instance, ebuild of jedi-bundle successfully completes but the make step breaks during the build of oops due to the nlohmann-json-schema-validator library not being found. 

**To Reproduce**
1. build spack-stack
2. ecbuild jedi-bundle
3. make

**Expected behavior**

The build of jedi-bundle successfully completes

**System:**
What system(s) are you running the code on?
AWS Ubuntu 22.24.01 EC2 instance

**Additional context**

**Comment by srherbener** [comment]
After some digging I found that the nlohmann-json-schema-validator changed the manner in which its cmake targets are exported to clients of the nlohmann-json-schema-validator package. This change occurred between nlohmann-json-schema-validator version 2.1.0 and 2.3.0 (which are the two versions in spack-stack-1.7.0 and spack-stack-1.8.0 respectively).

I am testing a fix right now on the AWS instance and it appears to have worked (at least to get past the oops build issue).

**Comment by climbfuji** [comment]
You created #1237 last week - which one do you want to keep?

**Comment by srherbener** [comment]
I initially thought to keep these separate since the fix for #1237 works for both spack-stack-1.7.0 and spack-stack-1.8.0. The fix that I just came up for this issue will only work with spack-stack-1.8.0, but I can see that leaving it like that is problematic. 

I'll close this issue and continue in #1237 and work on a solution that covers both spack-stack-1.7.0 and spack-stack-1.8.0.

**Comment by climbfuji** [comment]
Is spack-stack-1.7.0 also broken? I thought only spack-stack develop.

**Comment by srherbener** [comment]
spack-stack-1.7.0 is not broken - jedi-bundle builds successfully.

The issue is that when trying to build jedi-bundle using a spack-stack built from the latest develop branches in the spack-stack and spack repos, jedi-bundle stopped building. It turns out that changes made in the new nlohmann-json-schema-validator package impacted the oops code.

I initially suggested the quick fix of reverting the json package version, but you pointed out that the version upgrades fixed other issues. So I am now attempting to make the adjustments in oops to accommodate the changes that were made in the nlohmann-json-schema-validator. I think I've got that working, but I want to make sure that the fixes I put into oops work for both versions of the nlohmann-json-schema-validator package.

Having these fixes in oops means that spack-stack develop branches are also not broken.

**Comment by climbfuji** [comment]
Thanks for the explanation. You could also keep a branch/PR open in oops for testing with spack-stack develop and merge it after/when moving to spack-stack 1.8.0.
