### ISSUE TITLE
Shared or static MAPL?

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#1248]
**Is your feature request related to a problem? Please describe.**
Question: in spack-stack-1.6.0, we had static ESMF and static MAPL. This somehow changed, and in 1.7.0 and develop (i.e. soon to be 1.8.0), ESMF is still static but MAPL is shared. What is correct? MAPL can be configured either or, but not both within one installation I think.

**Describe the solution you'd like**
Input from @AlexanderRichert-NOAA, @mathomp4 and @srherbener what works and what doesn't.

**Comment by mathomp4** [comment]
I believe you still should be able to _build_ MAPL2 as static. We don't run that way so it's possible we broke something, but I think the build still supports it.

We also have used ESMF as shared for a very long time, but I can't see any reason why MAPL2 can't use it as static...but again, we've not tested that.

Now, MAPL3 is `SHARED` only. By its design it can no longer be used as a static library.

**Comment by climbfuji** [comment]
Decided to go with static mapl since esmf is static. This is how 1.6.0 was configured, which works for the UFS. And in the past, we had issues with double-free corruption at the end of ufs runs when esmf was static and mapl was shared.

**Comment by climbfuji** [comment]
See https://github.com/JCSDA/spack-stack/pull/1256 for the PR that makes mapl static
