### ISSUE TITLE
[INSTALL]: Need spack-stack/1.6.0 moved to /lfs5 on Jet.

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [JCSDA/spack-stack#1250]
### Package name

spack-stack

### Package version/tag

1.6.0

### Build options

current

### Installation timeframe

ASAP

### Other information

Essentially need `spack-stack-1.6.0` moved from /lfs4 to /lfs5.

**Comment by climbfuji** [comment]
As far as I know all future spack-stack versions are on /contrib, and some older ones (including 1.6?) were rebuilt there, too. @RatkoVasic-NOAA knows. We won't install on any of the /lfs anymore due to the problemsthat made you create this issue. See #1156

**Comment by KateFriedman-NOAA** [comment]
@climbfuji Gotcha, makes sense. Can someone provide me the path to spack-stack/1.6.0 in it's new /contrib location? Thanks!

**Comment by RatkoVasic-NOAA** [comment]
We haven't installed anything on /contrib. Plan was to install from 1.8.0 and newer on /contrib. Alex was testing /contrib spaces on all machines.
I can install spack-stack@1.6.0 on Jet /contrib space.

**Comment by KateFriedman-NOAA** [comment]
> I can install spack-stack@1.6.0 on Jet /contrib space.

Awesome, thanks @RatkoVasic-NOAA !

**Comment by guoqing-noaa** [comment]
I was told the following installations on Hera/Jet:  
`/contrib/spack-stack/spack-stack-d7e7465/envs/ue-intel/install/modulefiles/Core/`  
There is no version information in the path name. Is this a temporary one?

**Comment by RatkoVasic-NOAA** [comment]
@guoqing-noaa I think @AlexanderRichert-NOAA installed that as a test. That was just development branch from June 25th.

**Comment by guoqing-noaa** [comment]
@RatkoVasic-NOAA Thank you! 
rrfs-workflow will also need an installation of spack-stack/1.6.0.  Thanks!

**Comment by ulmononian** [comment]
@RatkoVasic-NOAA thank you for doing this!!!

**Comment by RatkoVasic-NOAA** [comment]
@KateFriedman-NOAA, @guoqing-noaa 
I have installed spack-stack@1.6.0 on Jet at /contrib space.
Also, I installed addons: _gsi-addon-intel_ and _upp-addon-env_
You can change your modulefiles for Jet to point to new place (depending on environment you use):
```
/contrib/spack-stack/spack-stack-1.6.0/envs/unified-env-rocky8/install/modulefiles/Core
/contrib/spack-stack/spack-stack-1.6.0/envs/gsi-addon-intel/install/modulefiles/Core
/contrib/spack-stack/spack-stack-1.6.0/envs/upp-addon-env/install/modulefiles/Core
```

**Comment by guoqing-noaa** [comment]
Great! Thank you, @RatkoVasic-NOAA

**Comment by ulmononian** [comment]
@RatkoVasic-NOAA @jkbk2004 should ufs-wm be tested and prepared to move to this stack?

**Comment by RatkoVasic-NOAA** [comment]
> @RatkoVasic-NOAA @jkbk2004 should ufs-wm be tested and prepared to move to this stack?

@ulmononian , here is my suggestion:
https://github.com/ufs-community/ufs-weather-model/pull/2326#issuecomment-2295124315

**Comment by KateFriedman-NOAA** [comment]
Thanks @RatkoVasic-NOAA !

**Comment by KateFriedman-NOAA** [comment]
@RatkoVasic-NOAA Question, is the `gsi-addon-intel` env equivalent to the `gsi-addon-dev` that existed on `lfs4` before? We were using the `gsi-addon-dev` install. Thanks!

**Comment by RatkoVasic-NOAA** [comment]
@KateFriedman-NOAA , yes it is. Sorry for not using same name.

**Comment by KateFriedman-NOAA** [comment]
> @KateFriedman-NOAA , yes it is. Sorry for not using same name.

No worries, thanks for confirming @RatkoVasic-NOAA !

**Comment by climbfuji** [comment]
Can this issue be closed?

**Comment by KateFriedman-NOAA** [comment]
Yes, thanks! Closing as complete.
