### ISSUE TITLE
[INSTALL]: upgrade eckit to 1.27.0

### ISSUE THREAD

**Issue by srherbener** [JCSDA/spack-stack#1264]
### Package name

eckit

### Package version/tag

1.27.0

### Build options

Use same build options in the current config

### Installation timeframe

Hopefully in time for the 1.8.0 release

### Other information

This upgrade is needed to pull in a fix for building eckit on MacOS Sonoma. It is a necessary fix, but not sufficient for building on Sonoma, and it would be nice to get it into the 1.8.0 release.

I have an open PR in the authoritative spack repo that adds the version directive for eckit@1.27.0. https://github.com/spack/spack/pull/45834

I have built spack-stack successfully on Orion using eckit@1.27.0, and I am testing jedi-bundle now. I'll test skylab too.

If all goes well, I can create PRs for this today. If the testing does not pan out we can wait until after 1.8.0 for this upgrade.

**Comment by climbfuji** [comment]
Closed via #1240
