### ISSUE TITLE
spack-stack-1.8.0 release tasks

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#1278]
Tasks for the spack-stack-1.8.0 release:
- [x] Create release branches
- [x] Install release candidate on a few selected systems for testing. Finalize testing/report back/fix issues by September 6. Suggestion:
    - [x] Hera (@ratkovasic-noaa)
    - [x] Nautilus (@climbfuji): `/p/work2/heinzell/spack-stack-1.8.0-rc1/envs/*` with `*` being one of:
        - ue-intel-2021.5.0
        - ue-gcc-12.2.1
        - ue-aocc-4.0.0 (incomplete, because many packages don't build with `flang`)
        - ue-oneapi-2024.1.2
        - ne-intel-2021.5.0
        - ne-gcc-12.2.1
        - ne-oneapi-2024.1.2
        - ne-aocc-4.0.0 (incomplete, because many packages don't build with `flang`)
    - [x] Discover SCU16 (@srherbener, @ashley314)
    - [x] Acorn (@AlexanderRichert-NOAA)
    - [x] Blackpearl (tier-2; @climbfuji)
        - ue-oneapi@2024.2.0 using `ifx` (incomplete, see #1279; complete with `ifort`)
- [x] Update documentation / prepare changes of documentation to move documentation specific for a specific release to the Wiki: https://github.com/JCSDA/spack-stack/pull/1280
- [x] Roll out release starting September 9, to be completed by September 27. Update site configs and site-specific documentation until September 27.
    - [x] Acorn (EMC)
    - [x] ~~Atlantis (NRL)~~ defer to after system maintenance
    - [x] AWS-Pcluster (JCSDA, @eap)
    - [x] ~~Casper~~ (dropped to tier2)
    - [x] Derecho ~~(EPIC, @ratkovasic-noaa)~~ (NRL, @climbfuji)
        - [x] ue-intel-2021.10.0
        - [x] ue-gcc-12.2.0 (failing)
    - [x] Discover SCU16 (JCSDA, @ashley314)
        - [x] ue-intel-2021.6.0
        - [x] ue-gcc-12.1.0
    - [x] Discover SCU17 (JCSDA, @ashley314)
        - [x] ue-intel-2021.10.0
        - [x] ue-gcc-12.3.0
    - [x] Gaea C5 (EPIC) (@ratkovasic-noaa): /ncrc/proj/epic/spack-stack/spack-stack-1.8.0/envs/
         - [x] ue-intel-2021.9.0 (failing)
    - [x] Gaea C6 (EPIC) (@ratkovasic-noaa): /ncrc/proj/epic/spack-stack/c6/spack-stack-1.8.0/envs/
         - [x] ue-intel-2021.10.0 (failing)
    - [x] Hera (@ratkovasic-noaa): /contrib/spack-stack/spack-stack-1.8.0/envs/
        - [x] ue-intel-2021.5.0
        - [x] ue-gcc-9.2.0
    - [x] Hercules (EPIC) (@ratkovasic-noaa): /work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-1.8.0/envs/
        - [x] ue-intel-2021.9.0
        - [x] ue-gcc-12.2.0
    - [x] Jet (EPIC) (@ratkovasic-noaa): /contrib/spack-stack/spack-stack-1.8.0/envs/
        - [x] ue-intel-2021.5.0
        - [x] ue-gcc-9.2.0
    - [x] Narwhal (NRL)
        - [x] ne-intel-2021.10.0
        - [x] ue-intel-2021.10.0 (chained from ne-intel-2021.10.0)
        - [x] ne-gcc-10.3.0
        - [x] ue-gcc-10.3.0 (chained from ne-gcc-10.3.0)
        - [x] readthedocs updated
        - [x] wiki updated
        - [x] chmod
    - [x] Nautilus (NRL)
        - [x] ne-intel-2021.5.0
        - [x] ue-intel-2021.5.0 (chained from ne-intel-2021.5.0)
        - [x] ne-oneapi-2024.2.1
        - [x] ue-oneapi-2024.2.1 (chained from ne-oneapi-2024.2.1)
        - [x] ne-gcc-12.2.1
        - [x] ue-gcc-12.2.1 (chained from ne-gcc-12.2.1)
        - [x] readthedocs updated
        - [x] wiki updated
        - [x] chmod
    - [x] Parallelworks EPIC AWS (@ratkovasic-noaa): /contrib/spack-stack-rocky8/spack-stack-1.8.0/envs/
        - [x] ue-intel-2021.10.0
    - [x] Parallelworks EPIC Azure (@ratkovasic-noaa) /contrib/spack-stack-rocky8/spack-stack-1.8.0/envs/
        - [x] ue-intel-2021.10.0
    - [x] Parallelworks EPIC GCP (@ratkovasic-noaa) /contrib/spack-stack-rocky8/spack-stack-1.8.0/envs/
        - [x] ue-intel-2021.10.0
    - [x] ~~Parallelworks JCSDA GCP (@fmahebert)~~ no longer supported
    - [x] Orion (EPIC) (@ratkovasic-noaa): /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.8.0/envs/
        - [x] ue-intel-2021.9.0
        - [x] ue-gcc-12.2.0
    - [x] S4 ~~(JCSDA, @srherbener)~~ (NRL, @climbfuji)
    - [x] ~~Sandy (NRL)~~ defer to after system maintenance
- [x] Create soft links to latest modules on each NOAA RDHPCS platform
    - See https://github.com/JCSDA/spack-stack/issues/1204 for a list of platforms and locations
- [x] Draft release notes
- [x] Tag spack submodule, update `.gitmodules` and spack submodule pointer in spack-stack, tag spack-stack
- [x] Publish release on ~~Friday, September 27~~ Wednesday, October 2, 2024
- [x] Merge release branches back into develop / spack-stack-dev
    - [x] https://github.com/JCSDA/spack/pull/478
    - [x] https://github.com/JCSDA/spack-stack/pull/1321
    - [x] https://github.com/JCSDA/spack-stack/pull/1323
    - [x] https://github.com/JCSDA/spack-stack/pull/1332

**Comment by RatkoVasic-NOAA** [comment]
Started working on Hera. It concretized OK.
Installation in under way. There is one problem with crtm_fix:
```
==> Installing crtm-fix-2.4.0.1_emc-al2juhzkilqssvyg75jsni664uhcknls [21/291]
==> No binary for crtm-fix-2.4.0.1_emc-al2juhzkilqssvyg75jsni664uhcknls found: installing from source
==> Error: FetchError: All fetchers failed for spack-stage-crtm-fix-2.4.0.1_emc-al2juhzkilqssvyg75jsni664uhcknls
==> Warning: Skipping build of crtm-2.4.0.1-fvusealmjzqzvr2tjoe7b4gfxkhfil4x since crtm-fix-2.4.0.1_emc-al2juhzkilqssvyg75jsni664uhcknls failed
```
I saw this on Jet as well. It looks like we cannot  access crtm-fix-2.4.0.1_emc. 

and another:
```
==> Installing libpthread-stubs-0.5-75nwhcat2k4nkuzlmnzow5iisqi5x4ct [35/291]
==> No binary for libpthread-stubs-0.5-75nwhcat2k4nkuzlmnzow5iisqi5x4ct found: installing from source
==> Error: FetchError: All fetchers failed for spack-stage-libpthread-stubs-0.5-75nwhcat2k4nkuzlmnzow5iisqi5x4ct
==> Warning: Skipping build of libxcb-1.16-bdkenjctf4jxkkzk73cnoiztl6cqjztm since libpthread-stubs-0.5-75nwhcat2k4nkuzlmnzow5iisqi5x4ct failed
```

**Comment by climbfuji** [comment]
Can you try to rerun the install for crtm-fix with `spack -d install ...` - that might give you more information. If you can't access those files from hera (which shouldn't be the case), then you can try to create a mirror on another machine and update the spack source-cache on hera.

**Comment by RatkoVasic-NOAA** [comment]
> Can you try to rerun the install for crtm-fix with `spack -d install ...` - that might give you more information. If you can't access those files from hera (which shouldn't be the case), then you can try to create a mirror on another machine and update the spack source-cache on hera.

Didn't try for crtm-fix, but there are others that failed with "All fetchers failed", but when I tried to download them manually on Hera, download was OK.

**Comment by srherbener** [comment]
@climbfuji I'm going to start the build on Discover SCU16. Where do I place the release candidate, and what do I name it? Perhaps: /gpfsm/dswdev/jcsda/spack-stack/scu16/spack-stack-rc-1.8.0

**Comment by climbfuji** [comment]
I use spack-stack-1.8.0-rc1 but it's up to you of course. If the path is longer than the final spack-stack-1.8.0 install, then you can use the release candidate to create a binary cache and install from it when you do the final 1.8.0 install.

**Comment by srherbener** [comment]
Thanks @climbfuji. I just wanted to make sure I'm following a best practice. Not sure I understand your comment about the binary cache. I created /gpfsm/dswdev/jcsda/spack-stack/scu16/spack-stack-rc-1.8.0 and will that satisfy the requirement to be able to use the binary cache for the final install?

**Comment by climbfuji** [comment]
If you use the same names for the environments, then yes. `spack-stack-1.8.0` has three characters less than `spack-stack-rc-1.8.0`.

**Comment by RatkoVasic-NOAA** [comment]
Hera:
installed ue-intel (had to use mirror from Hercules): `/contrib/spack-stack/spack-stack-1.8.0/envs/ue-intel`
ue-gcc installation in progress: `/contrib/spack-stack/spack-stack-1.8.0/envs/ue-gcc`
For now, only change goes to `site/mirrors.yaml`

**Comment by climbfuji** [comment]
@RatkoVasic-NOAA I am confused a bit - because of the recent changes to how we build ecflow, I was expecting site config and documentation updates for Hera - removal of external ecflow, addition of external qt5 if not already there, etc. See #1257

**Comment by srherbener** [comment]
I am building the release candidates on Discover SCU16, and @ashley314 will test these.
- [x] GCC: /gpfsm/dswdev/jcsda/spack-stack/scu16/spack-stack-rc-1.8.0/envs/ue-gcc-12.1.0
- [x] Intel: /gpfsm/dswdev/jcsda/spack-stack/scu16/spack-stack-rc-1.8.0/envs/ue-intel-2021.6.0

Checked box means the environment is ready to test.

**Comment by climbfuji** [comment]
> I am building the release candidates on Discover SCU16, and @ashley314 will test these.
> 
> * [ ]  GCC: /gpfsm/dswdev/jcsda/spack-stack/scu16/spack-stack-rc-1.8.0/envs/ue-gcc-12.1.0
> * [ ]  Intel: /gpfsm/dswdev/jcsda/spack-stack/scu16/spack-stack-rc-1.8.0/envs/ue-intel-2021.6.0
> 
> Checked box means the environment is ready to test.

Just want to double-check that you made the ecflow/qt5 changes (see #1257)?

**Comment by srherbener** [comment]
Sorry I didn't add ecflow to the config - too many things going on at once. I'll go do that now.

**Comment by climbfuji** [comment]
We don't want ecflow in the site configs. We want only qt@5 so that spack-stack builds ecflow. (Basically what we did on S4)

**Comment by climbfuji** [comment]
Therefore, we can likely remove the external miniconda and ecflow dependencies for spack-stack, too.

**Comment by climbfuji** [comment]
> Therefore, we can likely remove the external miniconda and ecflow dependencies for spack-stack, too.

Whether you then need a `module use /some/path/to/jedis/modules` at all or not depends on where the qt and mysql are coming from.

**Comment by srherbener** [comment]
@ashley314 Discover SCU16 gcc environment is now ready for testing. It includes ecflow in the stack (and qt@5 is an external package).

**Comment by srherbener** [comment]
> @ashley314 Discover SCU16 gcc environment is now ready for testing. It includes ecflow in the stack (and qt@5 is an external package).

Discover SCU16 Intel environment is now ready for testing.

**Comment by DavidHuber-NOAA** [comment]
Could the gsi-addon environment also be installed on these platforms: Hera, Jet, Orion, Hercules, Gaea C5 (C6 optional), all three PW CSPs, and S4.  EDIT: This environment is only required for the Intel compiler suite.

**Comment by RatkoVasic-NOAA** [comment]
@DavidHuber-NOAA Yes, as soon as we install 1.8.0 on those machines. Some of them are ready for addons (Hera and Jet).

**Comment by RatkoVasic-NOAA** [comment]
@DavidHuber-NOAA I added GSI addon to Hera spack-stack-1.8.0:
`/contrib/spack-stack/spack-stack-1.8.0/envs/gsi-intel-2021.5.0/install/modulefiles/Core`
Notice some name changes.
Also, here are changes for GSI modulefiles:
```
gsi_hera.intel.lua:
prepend_path("MODULEPATH", "/contrib/spack-stack/spack-stack-1.8.0/envs/gsi-intel-2021.5.0/install/modulefiles/Core")
local python_ver=os.getenv("python_ver") or "3.11.7"
local stack_impi_ver=os.getenv("stack-intel-oneapi-mpi") or "2021.5.1"
local cmake_ver=os.getenv("cmake_ver") or "3.28.1"

gsi_common.lua:
local bufr_ver=os.getenv("bufr_ver") or "12.1.0"
local ip_ver=os.getenv("ip_ver") or "5.0.0"
```

**Comment by climbfuji** [comment]
Please make sure all site config and documentation updates are in the spack-stack release branch (incl the readthedocs documentation if applicable) and in https://github.com/JCSDA/spack-stack/wiki/spack%E2%80%90stack%E2%80%901.8.0-release-documentation - THANK YOU!

**Comment by RatkoVasic-NOAA** [comment]
@DavidHuber-NOAA Just finished GSI addon on Jet:
`/contrib/spack-stack/spack-stack-1.8.0/envs/gsi-intel-2021.5.0/install/modulefiles/Core`
Exactly same changes to Jet modulefiles like for [Hera](https://github.com/JCSDA/spack-stack/issues/1278#issuecomment-2354190088).

**Comment by DavidHuber-NOAA** [comment]
Great, thank you @RatkoVasic-NOAA!

**Comment by ashley314** [comment]
FYI, I found a typo for discover-scu17 in `configs/sites/tier1/discover-scu17/packages_intel.yaml`. 
```
-    - spec: intel-oneapi-mkl@2032.2.0%intel@2021.10.0
+    - spec: intel-oneapi-mkl@2023.2.0%intel@2021.10.0
```

**Comment by climbfuji** [comment]
> FYI, I found a typo for discover-scu17 in `configs/sites/tier1/discover-scu17/packages_intel.yaml`.
> 
> ```
> -    - spec: intel-oneapi-mkl@2032.2.0%intel@2021.10.0
> +    - spec: intel-oneapi-mkl@2023.2.0%intel@2021.10.0
> ```

Please create a PR for release/1.8.0 with all changes needed for the discover platforms. Thanks!

**Comment by RatkoVasic-NOAA** [comment]
@DavidHuber-NOAA Current list of gsi addons to 1.8.0:

Hera: /contrib/spack-stack/spack-stack-1.8.0/envs/gsi-intel-2021.5.0/install/modulefiles/Core
Jet: /contrib/spack-stack/spack-stack-1.8.0/envs/gsi-intel-2021.5.0/install/modulefiles/Core
Gaea-C5: /ncrc/proj/epic/spack-stack/c6/spack-stack-1.8.0/envs/gsi-intel-2021.10.0/install/modulefiles/Core
Gaea-C6: /ncrc/proj/epic/spack-stack/spack-stack-1.8.0/envs/gsi-intel-2021.9.0/install/modulefiles/Core
NOAA-AWS: /contrib/spack-stack-rocky8/spack-stack-1.8.0/envs/gsi-intel-2021.10.0/install/modulefiles/Core
