### ISSUE TITLE
Replace configs/sites/tier1/hera/mirrors.yaml with correct mirror path

### ISSUE THREAD

**Issue by RatkoVasic-NOAA** [JCSDA/spack-stack#1289]
**Is your feature request related to a problem? Please describe.**
When installed 1.8.0, some packages were not downloaded.

**Describe the solution you'd like**
I used mirroring (from Hercules).

**Additional context**
Replacing with correct path to new mirror directory on Hera

**Comment by climbfuji** [comment]
Is this still an issue, or has the update been done?

**Comment by RatkoVasic-NOAA** [comment]
It is updated. Done!
