### ISSUE TITLE
Standard naming convention for each environment

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [JCSDA/spack-stack#1291]
**Is your feature request related to a problem? Please describe.**
Each environment (e.g. unified-dev, gsi-addon, etc) should have a standard naming convention.

**Describe the solution you'd like**
Just a suggestion, I'm open to any other solutions.  I suggest replacing the template `dev` with `env`, i.e.:
unified-dev -> unified-env
gsi-addon-dev -> gsi-addon-env

If new installations are required in between official releases, append the same descriptor across all installations.  For instance, if a new version of ESMF is required:
unified-dev -> unified-env-esmfxxx
gsi-addon-dev -> gsi-addon-env-esmfxxx

**Additional context**
This would be helpful when upgrading spack-stack versions within codes used on multiple systems such that we would only need to specify a root location for spack-stack and a version number.

**Comment by climbfuji** [comment]
Before spack-stack-1.7.0, we did agree on the names of the environments except for one little detail:

unified environment: `ue-compiler` or `ue-compiler-version`

The reason I am advocating for adding the version is that I maintain environments for the same compiler but different versions on some machines, for example: `ue-intel-2021.5.0` and `ue-intel-2021.10.0`

Along those lines, the neptune standalone environment would be called `ne-intel-2021.5.0`

Examples for other compilers: `ue-gcc-13.3.0` and `ue-oneapi-2024.2.1`

**Comment by AlexanderRichert-NOAA** [comment]
How about addon environments? `upp-intel-2023.2.1`? `upp-addon-intel-2023.2.1`? I've always assumed that addon environments should be labeled as such but maybe it doesn't matter as long as the purpose is reasonably clear?

**Comment by climbfuji** [comment]
> How about addon environments? `upp-intel-2023.2.1`? `upp-addon-intel-2023.2.1`? I've always assumed that addon environments should be labeled as such but maybe it doesn't matter as long as the purpose is reasonably clear?

I am happy either way, as long as we have a rule. Up to NOAA to decide, since nobody else uses those at the moment.

**Comment by AlexanderRichert-NOAA** [comment]
Okay, then let's do `upp-intel-2023.2.1` `esmfXYZ-gcc-13.2.0` etc. That way the formula is `<abbreviated purpose>-<compiler name>-<compiler version>`.

**Comment by climbfuji** [comment]
Please do me a favor when you use Intel (classic). The compiler versions for icc/icpc/ifort do not match the oneAPI version. We need to use the correct versions reported by `icc --version` instead of the oneAPI version. I know this is confusing, but they way the versions are used in spack (e.g. for applying patches, flags, ...) we need to use this for Intel classic in the site config compiler definition:
```
intel@2021.10.0 # example for very latest classic compilers in oneAPI 2023.2.4, uses icc, icpc, ifort
oneapi@2023.2.4 # example for LLVM compilers in oneAPI 2023.2.4, uses icx, icpx and ifort for now (should be ifx as soon as we can)
```

**Comment by AlexanderRichert-NOAA** [comment]
Fair enough. Do we need to update site configs or is it just a matter of naming the environments correctly?

**Comment by climbfuji** [comment]
This must be fixed in the site configs. spack packages can use this information (if self.spec.satisfies(%intel@2021.10) etc) to apply certain flags or not. It's fine imho to fix it post-release in spack-stack develop in the site config if it works as-is for now, but at least use the correct names for the environments for 1.8.0.

**Comment by climbfuji** [comment]
We need to make sure we add the information agreed upon here to the release documentation (and then merge back to develop)

**Comment by climbfuji** [comment]
Closed via https://github.com/JCSDA/spack-stack/pull/1300
