### ISSUE TITLE
gsi-addon-dev environment needed on gaea-c6 for GSI

### ISSUE THREAD

**Issue by jswhit** [JCSDA/spack-stack#1292]
**Is your feature request related to a problem? Please describe.**
ufs now compiles on gaea-c6, thanks to https://github.com/JCSDA/spack-stack/issues/1130

**Describe the solution you'd like**
we also need GSI for cycling, which requires the gsi-addon-dev environment

**Comment by jswhit** [comment]
I spoke too soon about ufs compiling - it apparently needs the upp-addon-dev environment which has not been built yet for c6

**Comment by jswhit** [comment]
see also https://github.com/ufs-community/ufs-weather-model/issues/2407

**Comment by RatkoVasic-NOAA** [comment]
@jswhit I just installed upp-addon on Gaea-C6:
/ncrc/proj/epic/spack-stack/c6/spack-stack-1.6.0/envs/upp-addon-env/install/modulefiles/Core

Next installations on Gaea (starting with 1.8.0) will be on:
/usw/spack-stack/c5/
/usw/spack-stack/c6/
There is possibility that we will install older version (1.6.0) to that disk, but that will be later.

**Comment by jswhit** [comment]
thanks @RatkoVasic-NOAA. I saw that but didn't realize it was for c6 since it doesn't have "-c6" appended to the name. I'll try modifying the ufs_gaea modulefile for ufs and see if it compiles.

**Comment by jswhit** [comment]
edit ufs_gaea.intel to use /ncrc/proj/epic/spack-stack/c6/spack-stack-1.6.0/envs/upp-addon-env/install/modulefiles/Core and stack-intel/2023.2.0 doesn't quite work (some modules, hdf5 and netcdf-c in particular, are not found)

**Comment by RatkoVasic-NOAA** [comment]
@jswhit can you point me to your modulefile which is using /ncrc/proj/epic/spack-stack/c6/spack-stack-1.6.0/envs/upp-addon-env/install/modulefiles/Core on Gaea C6.

**Comment by jswhit** [comment]
@RatkoVasic-NOAA it is at /gpfs/f6/drsa-precip4/proj-shared/Jeffrey.S.Whitaker/ufs-weather-model-develop-atm/modulefiles/ufs_gaea.intel.lua.  I only changed the module path (here's a git diff)

```
diff --git a/modulefiles/ufs_gaea.intel.lua b/modulefiles/ufs_gaea.intel.lua
index fb2eb49a..0f84248f 100644
--- a/modulefiles/ufs_gaea.intel.lua
+++ b/modulefiles/ufs_gaea.intel.lua
@@ -1,13 +1,13 @@
 help([[
   This module loads libraries required for building and running UFS Weather Model
-  on the NOAA RDHPC machine Gaea C5 using Intel-2023.1.0.
+  on the NOAA RDHPC machine Gaea C5 using Intel-2023.2.0.
 ]])

 whatis([===[Loads libraries needed for building the UFS Weather Model on Gaea ]===])

-prepend_path("MODULEPATH", "/ncrc/proj/epic/spack-stack/spack-stack-1.6.0/envs/upp-addon-env/install/modulefiles/Core")
+prepend_path("MODULEPATH", "/ncrc/proj/epic/spack-stack/c6/spack-stack-1.6.0/envs/upp-addon-env/install/modulefiles/Core")

-stack_intel_ver=os.getenv("stack_intel_ver") or "2023.1.0"
+stack_intel_ver=os.getenv("stack_intel_ver") or "2023.2.0"
 load(pathJoin("stack-intel", stack_intel_ver))

 stack_cray_mpich_ver=os.getenv("stack_cray_mpich_ver") or "8.1.25"
lines 1-21/21 (END)
```

**Comment by RatkoVasic-NOAA** [comment]
@jswhit I cannot access to the main directory, I'm not member of drsa-precip4 group:
```
Gaea:/ncrc/home2/Ratko.Vasic>ll -d /gpfs/f6/drsa-precip4/proj-shared/
drwxrws--- 3 root drsa-precip4 4096 Sep 05 2024 20:21:32 /gpfs/f6/drsa-precip4/proj-shared/
```
Can you please copy just your
 /gpfs/f6/drsa-precip4/proj-shared/Jeffrey.S.Whitaker/ufs-weather-model-develop-atm/modulefiles
directory to your i.e. home directory: /ncrc/home2/Jeffrey.S.Whitaker

**Comment by jswhit** [comment]
Done

**Comment by RatkoVasic-NOAA** [comment]
@jswhit 
you only need one small change in your ufs_gaea.intel.lua file:
replace
`stack_cray_mpich_ver=os.getenv("stack_cray_mpich_ver") or "8.1.25"`
with
`stack_cray_mpich_ver=os.getenv("stack_cray_mpich_ver") or "8.1.29"`

**Comment by jswhit** [comment]
thank you @RatkoVasic-NOAA that did the trick.  If the gsi-addon-dev env can now be built for C6, I think I can make a similar change in the GSI modulefiles and get it to build.

**Comment by climbfuji** [comment]
Thanks @RatkoVasic-NOAA and @jswhit . Can we close this as completed?

**Comment by jswhit2** [comment]
still need the gsi-addon-dev environment for C6

**Comment by RatkoVasic-NOAA** [comment]
@jswhit it is already innstalled on Gaea C6:
/ncrc/proj/epic/spack-stack/c6/spack-stack-1.6.0/envs/gsi-addon/install/modulefiles/Core

**Comment by jswhit2** [comment]
ahh - sorry I didn't see that.  Will you let you know today if I can use it to get GSI compiled

**Comment by jswhit2** [comment]
sort of works -  the cmake configuration runs and the compilation starts, but then hangs.  I'll file a gaea help ticket.

**Comment by jswhit2** [comment]
must have a been a filesystem issue - the compilation completes now.  Thank you @RatkoVasic-NOAA, this issue can be closed.
