### ISSUE TITLE
Document python environment and methodology

### ISSUE THREAD

**Issue by srherbener** [JCSDA/spack-stack#1302]
**Is your feature request related to a problem? Please describe.**
Python package management is difficult to do in a consistent manner across many platforms. There exist many ways to tackle this problem and if a wide variety of approaches are utilized this becomes unmanageable in regard to support and maintenance.

There exist two areas of concern
- The python environment being used by spack (ie, SPACK_PYTHON)
- The python environment being used by an application that was built based on a spack-stack environment

spack-stack development has been moving toward a relatively simple and consistent method for setting up and using the spack python environment and the application python environment. At this point we need to document and help foster adoption of these method.

**Describe the solution you'd like**
Documentation exists that explains the management of python for both spack-stack development, and applications (built upon spack-stack) environments.

**Additional context**
None

**Comment by climbfuji** [comment]
@christinaholtNOAA FYI

**Comment by christinaholtNOAA** [comment]
Documentation in this area would be a huge value add.

**Comment by srherbener** [comment]
Any thoughts about where this documentation should live: spack-stack ReadTheDocs, spack-stack Wiki? I'm leaning toward the Wiki, but I'm okay if ReadTheDocs (or some other place) is preferred. tagging @climbfuji, @AlexanderRichert-NOAA. 

Thanks!

**Comment by climbfuji** [comment]
I'd say readthedocs
