### ISSUE TITLE
cannot find `mpiifort` and `mpiicpc` after loading spack-stack-1.6.0 on Gaea

### ISSUE THREAD

**Issue by guoqing-noaa** [JCSDA/spack-stack#1308]
**Describe the bug**
After loading the spack-stack-1.6.0 on Gaea (either C5 or C6), we can not find `mpiifort` and `mpiicpc`

**To Reproduce**
```
module use /ncrc/proj/epic/spack-stack/spack-stack-1.6.0/envs/unified-env/install/modulefiles/Core
module load stack-intel/2023.1.0
module use stack-cray-mpich/8.1.25
which mpiifort
```

**Expected behavior**
we should be able to find mpiifort and mpiicpc using the which command

**System:**
Gaea C5 or C6

**Additional context**
It looks like spack-stack-1.6.0 on Gaea is using `intel-classic/2023.1.0` not `intel-oneapi`

**Comment by RatkoVasic-NOAA** [comment]
I'll take a look into this.

**Comment by RatkoVasic-NOAA** [comment]
@guoqing-noaa , cray's MPI wrapper is called mpifort not mpiifort. Also you have mpicc and mpicxx.

**Comment by guoqing-noaa** [comment]
Thanks @RatkoVasic-NOAA!  I will make changes and try to build my app and then update here.

**Comment by guoqing-noaa** [comment]
Problem sovled and close the issue. Thanks!
