### ISSUE TITLE
where is 1.8.0 release

### ISSUE THREAD

**Issue by edwardhartnett** [JCSDA/spack-stack#1309]
Is the 1.8.0 coming out soon?

**Comment by climbfuji** [comment]
We are waiting for EPIC and JCSDA to complete their site installs, once we've got the sit config updates in place I will do the final doc updates, create the release notes and publish. We expect to have this all done by Sep 30 at latest, but possibly by the end of this week (Sep 27).

**Comment by climbfuji** [comment]
it's there
