### ISSUE TITLE
Push 1.6.0 site updates

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#1316]
Push 1.6.0 site config updates to release/1.6.0 branch to capture Rocky-related changes on several systems.

**Comment by RatkoVasic-NOAA** [comment]
@AlexanderRichert-NOAA you may want to close this issue.

**Comment by climbfuji** [comment]
Closed via https://github.com/JCSDA/spack-stack/pull/1312
