### ISSUE TITLE
lua module environment on Orion is loading the wrong udunits module

### ISSUE THREAD

**Issue by srherbener** [JCSDA/spack-stack#1333]
**Describe the bug**

After loading the environment for GNU/OpenMPI, I see this for udunits:
```
(venv) orion-login-4[43] herbener$ module av udunits

------------------ /apps/spack-managed/modulefiles/linux-rocky9-x86_64/gcc/12.2.0 ------------------
   udunits/2.2.28 (L,D)

---- /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.8.0/envs/ue-gcc-12.2.0/install/modulefiles/gcc/12.2.0 ----
   udunits/2.2.28

--------------------- /apps/spack-managed/modulefiles/linux-rocky9-x86_64/Core ---------------------
   udunits/2.2.28

  Where:
   L:  Module is loaded
   D:  Default Module

If the avail list is too long consider trying:

"module --default avail" or "ml -d av" to just list the default modules.
"module overview" or "ml ov" to display the number of modules for each name.

Use "module spider" to find all possible modules and extensions.
Use "module keyword key1 key2 ..." to search for all possible modules matching any of the "keys".
```

Unfortunately, the udunits in both places have identical version numbers and the one in `/apps/spack-managed/modulefiles/linux-rocky9-x86_64/gcc/12.2.0` gets marked as the default version and subsequently gets selected to be loaded when `module load udunits/2.2.28` is run. 

Also unfortunate is that the ecbuild step for building jedi-bundle only works with the spack-stack-1.8.0 build of udunits. 

**To Reproduce**
1. Follow steps on the spack-stack wiki for setting up GNU/OpenMPI on Orion
2. clone jedi-bundle
3. cd to your build area and run ecbuild

**Expected behavior**
ecbuild completes successfully

**System:**
What system(s) are you running the code on?
Orion

**Additional context**

I've tried a couple ways to solve this, but lua is very stubborn with marking the "spack-manages" version of udunits as the default module.
- Modifying MODULEPATH did not work
    - if this seems surprising, then perhaps I messed this up and I can try again
- `module unuse /apps/spack-managed/modulefiles/linux-rocky9-x86_64/gcc/12.2.0` before loading udunits didn't work either - there are modules that are needed during the load of the environment that contains udunits (jedi-base-env?).

What is a good way to fix this?

For example, one way to solve this might be to add a "default" symbolic link in the `/work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.8.0/envs/ue-gcc-12.2.0/install/modulefiles/gcc/12.2.0/udunits` directory which is supposed to tell udunits to make the spack-stack-1.8.0 udunits the default module. Is this an acceptable solution? For example, if we force the udunits in spack-stack-1.8.0 to be the default, will that be okay with other applications besides jedi-bundle?

**Comment by climbfuji** [comment]
Orion is maintained by EPIC, adding @RatkoVasic-NOAA as assignee. My recommendation is to try what we do on Derecho:
```
export LMOD_TMOD_FIND_FIRST=yes
```
See https://github.com/JCSDA/spack-stack/blob/3ebd423d83713b8256bd9d781c685a9d36acf8ff/doc/source/PreConfiguredSites.rst?plain=1#L220C2-L220C35

**Comment by srherbener** [comment]
@climfuji thanks for the tip with LMOD_TMOD_FIND_FIRST! I got it to work by using LMOD_TMOD_FIND_FIRST along with modifying MODULEPATH to place the spack-stack-1.8.0 path ahead of the spack-managed path.

**Comment by climbfuji** [comment]
If you do `module use` and not `module use --append` the spack-stack path should always come first and that udunits should be found with `export LMOD_TMOD_FIND_FIRST=yes`?

**Comment by srherbener** [comment]
> If you do `module use` and not `module use --append` the spack-stack path should always come first and that udunits should be found with `export LMOD_TMOD_FIND_FIRST=yes`?

Yes, I just tried `module use $SPACK_STACK_GNU_ENV/install/modulefiles/gcc/12.2.0` instead of the direct setting of MODULEPATH, and that does work. See comment in the PR: https://github.com/JCSDA-internal/jedi-tools/pull/385#discussion_r1800200488

**Comment by climbfuji** [comment]
@srherbener Anything that needs to be changed in spack-stack for this?

**Comment by srherbener** [comment]
> @srherbener Anything that needs to be changed in spack-stack for this?

Not that I'm aware of.  The spack-stack installs themselves appear to be intact. Once I got the environment issue worked out for GNU, the build of jedi-bundle worked and I got 7 ctest failures that appear to be related to CRTM producing different output that is outside tolerance checks. I'm seeing messages like this:
```

     Comparing calculated results with saved ones...
 test_Aerosol_Bypass(FAILURE) : RTSolution results are different!
STOP 1
```

**Comment by srherbener** [comment]
On the other hand, it's not entirely clear why the spack-managed path gets placed on MODULEPATH which could be something in the module files in the spack-stack-1.8.0 installation. If this is the case, I'm still thinking it would be good to use this workaround for now and fix this later with a longer term solution.

**Comment by climbfuji** [comment]
I think that's because one of the module dependencies in the spack-stack config (I assume the compiler) contains a module use statement for compiler dependencies. This is nothing we can fix, something from the system spack modules. If this is the case, then the instructions in the spack-stack wiki need to be updated (similar to what you did for JEDI-tools). Can you do this, please?

**Comment by srherbener** [comment]
Absolutely. I was just waiting on us to settle on the workaround. I'll update the wiki.

**Comment by climbfuji** [comment]
Perfect, thanks! Please close this issue when you are done.

**Comment by srherbener** [comment]
The spack-stack wiki has been updated so I will close this issue now.
