### ISSUE TITLE
Add _ver variables to module files?

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#1336]
Would it make sense to add `{name}_ver` variables to our modulefiles? I don't remember if we've discussed this previously. These will be useful for our NCO work as far as testing different spack-stack versions without having to do a bunch of rewriting of the model module files. I think it would also be useful to developers wanting to test the latest spack-stack, because again they won't need to modify anything (the UWM module files, for example, already look for these environment variables before using the specified defaults). I'm happy to just make these changes for the Acorn config, but if no one objects it might make sense to update the common lmod/tcl configs.

Example:
netcdf-c/4.9.2.lua would contain `setenv("netcdf_c_ver", "4.9.2")`, so that UWM/Global Workflow/GSI/etc. can use the functionality they already have of setting the netcdf-c module version to $netcdf_c_ver.

**Comment by climbfuji** [comment]
What would these variables contain? The version of the package?

**Comment by AlexanderRichert-NOAA** [comment]
Correct. I'll update the description to clarify.

**Comment by climbfuji** [comment]
But that version is already available as part of the module? `module load g2/3.5.1` ?

**Comment by AlexanderRichert-NOAA** [comment]
Right, d'oh. I guess it wouldn't help unless it was in the metamodule. I'll ponder it more and update the issue.

**Comment by climbfuji** [comment]
I remember that a while ago I came across a modulefile (tcl or lmod, can't remember) that determined the version internally from the name of the module.

**Comment by AlexanderRichert-NOAA** [comment]
Circling back to this later
