### ISSUE TITLE
CI tests on ubuntu w/ Intel are hitting build time limit

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#134]
After adding `hdf` and `py-hdf` to the packages, the build time for the `jedi-ewok` app increased from 5h 45min to 6h+. The maximum build time for a single build on GitHub Actions is 6h, thus the build is canceled close to the end.

An idea to speed up the build is to increase the number of OpenMP threads and spack `build_jobs`. Or to install certain packages like `qt@5`, which we require to be an external package on macOS and all HPCs, using `apt-get`.

**Comment by kgerheiser** [comment]
An idea I've had is to cache the build/environment and just force reconcretize it during each build and it'll end up re-using everything it can unless the build has changed. Or do that but just with the base env and let other envs use it as an upstream. 

Pre-installing qt would be good.

I like the package level parallelism setting. I didn't know about that.

I just went through the libraries that take the longest to build and it's really just a few offenders that are the worst. It's ESMF, FFTW, OpenBLAS, gdal, and qt that take more than ~10-15 minutes to build.
