### ISSUE TITLE
skylab-dev environment does not concretize in a Windows WSL Ubuntu 22.04 VM

### ISSUE THREAD

**Issue by srherbener** [JCSDA/spack-stack#1357]
**Describe the bug**
@xian22 initially reported this issue. He was having trouble getting concretize to run when building in his Window/WSL/Ubuntu environment.

After some debugging it was discovered the unified-dev would successfully concretize, and it appeared that was due to turning off the cylc variant in the unified-dev. Note that difficulty with building cylc in spack stack is a known issue: https://github.com/JCSDA/spack-stack/issues/1162. Also note that the cylc variant was intentionally enabled in skylab-dev so that we continue to test building cylc: https://github.com/JCSDA/spack-stack/pull/1193.

@xian22's Windows WSL VM is emulating Ubuntu 22.04 so perhaps that is the difference between the CI testing (which must be working when it attempts to build cylc in the skylab-dev environment).

**To Reproduce**

In Windows WSL VM:
Follow the instructions for building a new site Linux environment in the 1.8.0 documentation: https://spack-stack.readthedocs.io/en/1.8.0/NewSiteConfigs.html#linux

**Expected behavior**
The concretize and subsequent commands complete successfully.

**System:**
What system(s) are you running the code on?
Windows WSL, Ubuntu 22.04, gcc ???

**Additional context**

**Comment by travissluka** [comment]
additional datapoint: I'm using ubuntu 24 and was having the same issue, it wouldn't concretize due to py-cython until `+cylc` was removed from `ewok-env`

**Comment by srherbener** [comment]
@xian22, @travissluka what is the status of this issue? Can it be closed, or is there more work to be done? Thanks!

**Comment by climbfuji** [comment]
WOrkaround is to turn off cylc (`~cylc`)
