### ISSUE TITLE
Latest homebrew install of qt5 for MacOS is 5.15.15, and is not supported in spack-stack

### ISSUE THREAD

**Issue by stiggy87** [JCSDA/spack-stack#1364]
**Describe the bug**
When installing spack-stack on MacOS Sonoma 14.4.1 using Homebrew, the latest release of qt5 for Homebrew is 5.15.15 as of October 2024. Any new user that does auto-updating of Homebrew packages might inadvertently upgrade qt5 to an unsupported/qualified version.

**To Reproduce**
Follow https://spack-stack.readthedocs.io/en/develop/NewSiteConfigs.html#macos making sure to run latest homebrew updates on packages.

**Expected behavior**
Either need to support 5.15.15 in the future, or update docs to provide steps to downgrade qt5 to 5.15.13.

**System:**
What system(s) are you running the code on?
MacOS only

**Additional context**
This is really only a documentation problem until qt 5.15.15 is qualified for spack-stack.

**Comment by climbfuji** [comment]
What is the problem with 5.15.15 ? I think any qt@5 will do.

**Comment by stiggy87** [comment]
You're right, I had a problem using the newest version of Apple clang which had problems with qt@5.
