### ISSUE TITLE
Update old tags for new and upgraded machines: Gaea-C5 and Gaea-C6

### ISSUE THREAD

**Issue by RatkoVasic-NOAA** [JCSDA/spack-stack#1368]
**Is your feature request related to a problem? Please describe.**
New tier1 machine is available (Gaea-C6) and one machine went through major software upgrade (Gaea-C5) - needed to reinstall existing spack-stack installations.
Documentation and some yaml files were updated.

**Describe the solution you'd like**
Creating PRs for 4 tags: 1.5.1, 1.6.0, 1.7.0, and 1.8.0

**Comment by rickgrubin-noaa** [comment]
All PRs reviewed and approved.

**Comment by climbfuji** [comment]
All done!
