### ISSUE TITLE
Intel install with eckit set to gcc does not create a module for eckit

### ISSUE THREAD

**Issue by stiggy87** [JCSDA/spack-stack#1411]
**Describe the bug**

Creating an spack-stack image on Ubuntu 24.04 with intel classic, I run into the problem where after I setup the meta-modules, the eckit (which is forced to be compiled by gcc) does not get loaded even though the required modules of stack-intel and stack-intel-oneapi-mpi are met.

**To Reproduce**

Follow sites/tier2/aws/ubuntu2404/README.md for Intel setup (before concretize and install) from PR #1393 

Add this to spack.yaml in the env:

```bash
packages:
...
  eckit:
    require:
    - '%gcc'
```

Concretize and install

```bash
spack module lmod -y refresh
spack stack setup-meta-modules

module purge
module use install/modulefiles/Core
module load stack-intel/2021.10.0
module load stack-intel-oneapi-mpi/2021.10.0
module load base-env
module load jedi-mpas-env # <--- Get error here
```

**Expected behavior**
eckit should be loaded properly even if gcc built the module.

**System:**
What system(s) are you running the code on?

Ubuntu 24.04 (AWS AMI)

**Additional context**

```bash
$ spack module lmod find eckit
eckit/1.27.0
```

`module debug=1 load eckit/1.27.0` result = [eckit_module_load.txt](https://github.com/user-attachments/files/18103564/eckit_module_load.txt)

`spack spec eckit` result = [eckit_spec.txt](https://github.com/user-attachments/files/18103571/eckit_spec.txt)

[spider.log](https://github.com/user-attachments/files/18103573/spider.log)

@climbfuji This looks like a weird meta-module issue, but I think there could be something else wrong here.

**Comment by climbfuji** [comment]
This is not expected to work, in fact not even supposed to work. eckit requires MPI if I am not mistaken. The MPI library is compiled with the principal=preferred compiler. Therefore, everything that depends on the MPI library must be compiled with the preferred compiler. There are notes in the setup-meta-modules extension in the `spack-ext/lib` directory, but probably not in the documentation (we should add that).

**Comment by climbfuji** [comment]
Found it: See https://github.com/JCSDA/spack-stack/blob/71aa767a78554a8c658851f6e6236fd448ae5584/spack-ext/lib/jcsda-emc/spack-stack/stack/meta_modules.py#L361-L367

**Comment by climbfuji** [comment]
The real question is why you would want to compile eckit with GCC when your main compiler is Intel?

**Comment by stiggy87** [comment]
Thanks for showing me the info in the lib! I do agree that we should add to documentation to it to discourage users from doing it (even though it might be a rarity).

The issue I was running into is that, at least, on Ubuntu 24.04 the intel build of eckit failed to find the standard c++ library, even if the paths are present in the compiiler.yaml. This was fine on Rocky8 that had similar paths added.
