### ISSUE TITLE
Add cgal dependency to JEDI bundles

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#142]
Requested by @fmahebert:

> This is the library I've used in my development:
https://www.cgal.org/index.html
> It's a C++ header-only library, so comparatively easy to install.
> I've been testing with the latest version, 5.4. From the changelogs, I think last summer's 5.3 release introduced the features I need, so we might be able to go back to 5.3 but probably not older. Let me know if it'd be helpful for me to test exactly what the minimum needed version is.

When we do that, we should also explore enabling the `cgal` dependency/variant in ecmwf-atlas.

**Comment by climbfuji** [comment]
We'll need to revisit the need for cgal due to potential licensing issues using it in JCSDA software.

**Comment by fmahebert** [comment]
🙁

**Comment by climbfuji** [comment]
Unfortunately, `cgal` will not be an option for JCSDA due to licensing issues. Closing.
