### ISSUE TITLE
Update NCEPLIBS-bufr to version 11.7.0

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#145]
NCEPLIBS-bufr version 11.7.0 is now available: https://github.com/NOAA-EMC/NCEPLIBS-bufr/tree/bufr_v11.7.0

**Comment by kgerheiser** [comment]
Bufr 11.7.0 was added to the versions in Spack.

**Comment by climbfuji** [comment]
I am working on that.
