### ISSUE TITLE
Add ncview and for macOS xquartz as a prerequisite

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#153]
I noticed we don't have ncview. I think it would be good to add it to the base-env. Thoughts?

**Comment by climbfuji** [comment]
Or maybe jedi-ewok or jedi-tools if the UFS doesn't want/need it.

**Comment by climbfuji** [comment]
Also, need to add instructions for installing xquartz on macOS as a prerequisite or none of these graphical tools will work.

**Comment by climbfuji** [comment]
The documentation now mentions `xquartz`, but `ncview` is not yet part of any of the bundles.

**Comment by climbfuji** [comment]
@srherbener What's your opinion on `ncview`? Should this be in the first release, or can we add it later?

**Comment by srherbener** [comment]
I think ncview can wait and definitely we should not spend the effort to get it into the first release.

Most of us are using hdfView for the same purpose as ncview. I think that people have already downloaded/installed hdfView so I don't think hdfView needs to go into the first release as well (unless of course it's already part of spack-stack).
