### ISSUE TITLE
Boostrap Clingo on Hera

### ISSUE THREAD

**Issue by kgerheiser** [JCSDA/spack-stack#16]
Hera (and other RDHPCS platforms) block outgoing connections by default. This means Spack can't download the Clingo binary and it has to be built from source.

It also turns out there was another bug which prevented bootstrapping from source  because Spack was detecting Hera as a Cray system. 

Applying the fix here allowed me to build Clingo: https://github.com/spack/spack/pull/28726

This requires a GCC compile in your compilers.yaml that supports C++14 (> GCC 4.0).

Then, I ran `spack bootstrap untrust github-actions` 

Then, the firewall prevented me from doing more, but I think a Spack mirror would resolve that issue.

**Comment by kgerheiser** [comment]
Can download Clingo now. The Spack mirror is still necessary for many external packages, but it's better than building Clingo.

**Comment by climbfuji** [comment]
> Can download Clingo now. The Spack mirror is still necessary for many external packages, but it's better than building Clingo.

Mirror not necessary on hera for now - I could build fv3-bundle-env, ufs-bundle-env, um-bundle-env without using a mirror.

**Comment by kgerheiser** [comment]
Wow, I'm surprised nothing in our package list was behind the firewall.

**Comment by climbfuji** [comment]
Hera update PR coming in a bit.
