### ISSUE TITLE
Spack v0.18.0 was released - update spack fork/branch and use this version for first spack-stack release

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#161]
spack v0.18.0 was released, and it contains many new features, improvements and bugfixes:

https://github.com/spack/spack/releases/tag/v0.18.0

We should update our fork/branch of spack and use that version in our first spack-stack release in June 2022.

**Comment by kgerheiser** [comment]
Yeah, this would be perfect. There are a lot of great improvements such as a fix for linking to Intel Python, concretized reuse by default, and a couple others I can't think of.

**Comment by edwardhartnett** [comment]
Awesome! When can we expect the first release of spack-stack?

**Comment by climbfuji** [comment]
@edwardhartnett I'd like to chat with @kgerheiser again, but from the JCSDA side we need a release by the end of this month (June 2022) to support our next JEDI release. Kyle and I made a number of improvements in the last few weeks, and I am working on a documentation PR and a few issues with using spack-stack on gaea and stampede2.

My thinking was that we update our spack branch with the changes from spack v0.18.0, finalize the documentation and the few outstanding issues (gaea, stampede2, how to set versions for libraries and virtual packages), and then have a beta release by June 10 for testing. Final release by the end of the month.

That release will also have the capability to create docker containers for at least one compiler+mpi combination (gcc/gfortran+openmpi on Ubuntu 20.04), more if time permits.

We'll also need better/more comprehensive CI testing, currently the builds take too long and we don't run

How does that sound?
