### ISSUE TITLE
ufs-weather-model-debug-env should contain all its dependencies

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#166]
Right now, `ufs-weather-model-debug-env` contains only the additional dependencies that are not in `ufs-weather-model-env`. This has the advantage that someone who wants to build the ufs-weather-model in DEBUG mode needs to load the `ufs-weather-model-env` module first, and then the `ufs-weather-model-debug-env` module.

It would be better to explicitly list all the dependencies in `ufs-weather-model-debug-env` so that loading `ufs-weather-model-env` first is not required.

**Comment by kgerheiser** [comment]
How about debug as a variant to ufs-weather-model-env?

**Comment by climbfuji** [comment]
> How about debug as a variant to ufs-weather-model-env?

Yes, even better. I'll make this change together with the fms/fms-jcsda unification in one PR today.
