### ISSUE TITLE
Building findutils fails on macOS

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#17]
It looks like a recent update to spack (https://github.com/spack/spack/pull/28316) breaks building findutils on my macOS, see the comment here: https://github.com/spack/spack/pull/28316#issuecomment-1033949493

**Comment by kgerheiser** [comment]
I get the same error.

But it attempted a longstanding problem I had with findutils. MPICH required findutils and it failed with GCC. I just removed the findutils dependency from MPICH and let it use the system one.

For whatever reason the `find` on macOS is not detected as external (BSD vs. GNU, I think).

**Comment by climbfuji** [comment]
I already have a PR for the authoritative spack repo, and there will be one for our fork later today (same commit, cherry-picked).

**Comment by kgerheiser** [comment]
Any objections to changing to version 4.8.0 in the main `packages.yaml`? Else I would add 4.8.0 to the generic macOS site config so that it can build with GCC.

**Comment by climbfuji** [comment]
> Any objections to changing to version 4.8.0 in the main `packages.yaml`? Else I would add 4.8.0 to the generic macOS site config so that it can build with GCC.

I think there was a problem with 4.8.0 on one of the HPCs ... because 4.7.0 worked "everywhere" (I tested) I went for that one. I think it was on Cheyenne if I remember correctly. We can make 4.8.0 the default and change it for Cheyenne or whichever the problematic machine was.

**Comment by climbfuji** [comment]
This issue was resolved by adding a bugfix for 4.7.0 to spack (it's also in the official repo by now). We also made 4.8.0 the default.
