### ISSUE TITLE
Enable branch protection and checks

### ISSUE THREAD

**Issue by kgerheiser** [JCSDA/spack-stack#172]
With the merge of #165 and preparation for release let's enable branch protection rules and checks.

I say we require the unit tests and concretize tests, and use judgement when full builds are necessary (i.e. no need to spend hours waiting for a doc change to go through).

**Comment by climbfuji** [comment]
Yes please. And include administrators in all the rules.

**Comment by kgerheiser** [comment]
Done, going to do same with Spack fork. Any objections to me making `jcsda_emc_spack_stack` the default branch too?

**Comment by climbfuji** [comment]
> Done, going to do same with Spack fork. Any objections to me making `jcsda_emc_spack_stack` the default branch too?

No objections, makes sense - thanks for doing that.

**Comment by kgerheiser** [comment]
Complete
