### ISSUE TITLE
Sort configs/common/packages.yaml alphabetically

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#181]
This should be a separate PR when nobody is working on that file, since it will create a lot of confusion and merge conflicts will be error-prone.

Sorting the file alphabetically will make life a lot easier.

**Comment by kgerheiser** [comment]
Yes, was going to do this once I got the various package updates done.

**Comment by climbfuji** [comment]
> Yes, was going to do this once I got the various package updates done.

Let's coordinate this PR, because it will be easiest if neither of us is doing other work on that file (i.e. no open PRs, ...).

**Comment by climbfuji** [comment]
Closed via #226 in release/v1
