### ISSUE TITLE
create-spack-mirror CI tests failing 06/06/2022

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#183]
The create-spack-mirror CI tests are now (06/06/2022) failing with
```
==> Warning: included configuration files should be updated manually [files=${SPACK_STACK_DIR}/configs/common/modules.yaml, ${SPACK_STACK_DIR}/configs/common/config.yaml, site, packages.yaml]
==> Error: Invalid url format from url: ${SPACK_STACK_DIR}/cache/source_cache
Error: Process completed with exit code 3.
```

**Comment by climbfuji** [comment]
@kgerheiser The problem is that in the upstream spack, they changed
```
def require_url_format(url):
    ut = re.search(r'^(file://|http://|https://|ftp://|s3://|gs://|ssh://|git://|/)', url)
    assert ut is not None
```
to
```
def require_url_format(url):
    ut = re.search(r'^(file://|http://|https://|ftp://|s3://|gs://|ssh://|git://|/)', url)
    if not ut:
        raise ValueError('Invalid url format from url: %s' % url)
```
And because of the env variables in our spack config, we have:
```
==> Error: Invalid url format from url: ${SPACK_STACK_DIR}/cache/source_cache
```
instead of something starting with `file://`

We'll need to replace that environment variable with the true prefix starting with `file://` or revert that change in `url.py`.

**Comment by climbfuji** [comment]
@kgerheiser What's your opinion? Revert the change in spack from the authoritative repo, or use `sed` to replace the environment variable in `spack.yaml`  for this particular CI test? Other ideas?

**Comment by kgerheiser** [comment]
My opinion is that we can run `spack config set config:source_cache:fullpath/mirror`. I think that would work.

**Comment by climbfuji** [comment]
Closed via https://github.com/NOAA-EMC/spack-stack/pull/214
