### ISSUE TITLE
Feature request: bump ecbuild to 3.6.5

### ISSUE THREAD

**Issue by rhoneyager** [JCSDA/spack-stack#188]
### Description

Relevant to JCSDA-internal/ioda#715 and JCSDA-internal/ioda#717.

When reworking ioda's build system, there is a [useful ecbuild commit](https://github.com/ecmwf/ecbuild/commit/b206f343fcf3cd5077477e6beef854021cf80171) that lets us have a `ioda-post-import.cmake.in` file. This is in the latest ecbuild release, which was released last December.

This file lets us set up aliases in CMake, so we can define links like `ioda::Python` for downstream linking, such as in ioda-converters. I am trying to improve how our Python converter tests find ioda's Python APIs, and the current scheme involving statements like `ENVIRONMENT "PYTHONPATH="$<TARGET_FILE_DIR:_ioda_python>/../:$ENV{PYTHONPATH}""` is somewhat sloppy.

### Impact

No impact expected in downstream projects, besides enabling new features.

**Comment by climbfuji** [comment]
Thanks, @rhoneyager, will do before the first release of spack-stack.
