### ISSUE TITLE
Simplify `spack stack` extension for first release

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#195]
The full set of options for the `spack stack` extension is:
```
spack stack [create|setup-meta-modules]

spack stack create [env|container]

# This is way too complicated and confusing!
spack stack create env [--template TEMPLATE] [--specs [SPECS [SPECS ...]]] [--name NAME] [--dir DIR] [--overwrite] [--packages PACKAGES] [--site SITE] [--prefix PREFIX] [--envs-file ENVS_FILE]

# This is not as bad, but still too complicated and confusing!
spack stack create container [--template TEMPLATE] [--specs [SPECS [SPECS ...]]] [--name NAME] [--dir DIR] [--overwrite] [--packages PACKAGES] container
```

Suggestions/questions for `env` and `container`:
1. Get rid of `--specs` - tell user to use template `TEMPLATE` (default `empty`), and when using empty, add specs (can refer to section _Environments_ in the documentation - this section is still missing, but will be completed before the release).2. 

Suggestions/questions for `env`:
2. Get rid of `--envs-file`? if users want to create an environment from a complete envs file, they don't need the overhead of running `spack stack create env`, they can just create a directory and copy the envs file there. It's also something that likely only advanced users want to do, therefore don't need to document? Can add some documentation if we think it is worth it.
3. Why do we need `--prefix` and `--dir`? Should we just always place the enviroment in `envs/name` and let the user overwrite only `prefix`?

Suggestions/questions for `container`:
4. In the help for the command, replace the container option with `container-option` or something like that, because we have `spack stack create container ... container` and that is confusing.
5. Same as for `env`, should we get rid of `--dir`?

**Comment by kgerheiser** [comment]
1. Fine with removing `--specs`
2. You're right that `--envs-file` doesn't really have much use right now. Could be removed. I was testing this with my HPC deployments. Not really user related.
3. `--prefix` is to set the install prefix at configure time, dir is the directory to use instead of `/envs`. `--dirs` isn't really necessary, but useful if you want to place the environment somewhere else.
4. Sure, the naming could be better.
5. Could be removed,

**Comment by climbfuji** [comment]
Ok, let's remove ``--specs``, ``--envs-file`` but leave ``--dir`` for now. And change the help output for ``container``. I'll do that now.
