### ISSUE TITLE
Add grib2 support to Grads

### ISSUE THREAD

**Issue by kgerheiser** [JCSDA/spack-stack#200]
I'm working on a WCOSS2 installation of Grads and the grib2 capability doesn't work out of the box.

I had to add some patches to Grads and compile g2c with `-fPIC`.

**Comment by kgerheiser** [comment]
Fixed by https://github.com/NOAA-EMC/spack/pull/99

**Comment by climbfuji** [comment]
Fixed by https://github.com/NOAA-EMC/spack/pull/99
