### ISSUE TITLE
Turn off internal pio build in latest esmf@8.3.0 for first spack-stack release? No: Update ESMF 8.3.0 to use external PIO in develop, revert to 8.3.0b09 in first release

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#201]
Recent changes in the esmf@8.3.0 release regarding the internal pio version and a new option to use an external pio require some changes to the esmf spack package. See https://github.com/NOAA-EMC/spack/issues/98 and https://github.com/spack/spack/issues/31122 for more information.

For now, turn off pio in esmf in the first spack-stack release, since it isn't used by any of the UFS or JEDI applications.

**Comment by kgerheiser** [comment]
Are you working on this? I was going to go through and update ESMF to work with external PIO.

**Comment by climbfuji** [comment]
I think we need to close this issue and fit it the right way - you got ahead of me on that :-)
