### ISSUE TITLE
ecflow not declared as a Python package

### ISSUE THREAD

**Issue by mer-a-o** [JCSDA/spack-stack#211]
I'm testing the newly created stack on an AMI. I loaded all the modules needed for building fv3-bundle and running ewok. Running `import ecflow` gives me the error: 
```
ModuleNotFoundError: No module named 'ecflow'
```
It looks like ecflow is not declared as a Python package in spack and so is not set in `PYTHONPATH` correctly.

**Comment by climbfuji** [comment]
Closed via https://github.com/NOAA-EMC/spack-stack/pull/214
