### ISSUE TITLE
mapl@2.12.3 does not build on Discover

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#213]
`mapl@2.12.3` currently does not build on Discover. 

Workaround in place: after creating an environment that uses `mapl@2.12.3`, run `spack remove mapl@2.12.3` followed by `spack add mapl@2.11.0`.

If ``spack concretize`` was run before remove `/path/to/env/spack.lock` and rerun `spack concretize`.

**Comment by kgerheiser** [comment]
Why doesn't MAPL build on Discover? Is it the compiler, or MPI? Strange that it doesn't build there of all places.

**Comment by climbfuji** [comment]
Missing libraries/includes (netcdf stuff). No idea/time to look into why.

mapl 2.11.0 builds fine (but it doesn’t build on macOS therefore the move to 2.12.3).

I would suggest that post release 1, we get the mapl spack update from NASA, hopefully this will solve the problems.

**Comment by climbfuji** [comment]
The duct-tape solution to build mapl@2.11.0 instead on Discover was applied in https://github.com/NOAA-EMC/spack-stack/pull/214. Will keep this issue open for the future (not as part of the first release of spack-stack).

**Comment by climbfuji** [comment]
Funny (well ...) - with spack-stack-1.0.0-rc2, I can build mapl@2.12.3 on Discover without problems?!? Error not always reproducible? Sigh.

**Comment by climbfuji** [comment]
Closed via https://github.com/NOAA-EMC/spack/pull/111
