### ISSUE TITLE
release version 1.0

### ISSUE THREAD

**Issue by edwardhartnett** [JCSDA/spack-stack#220]
What remains before the V1.0 release?

We need to deprecate the existing NCEPLIBS-external and NCEPLIBS projects, and have something in their place.

Basically NCEPLIBS-external is broken and NCEPLIBS is out of date. So we need to get those fixed. Can we release 1.0 and that is the fix?

**Comment by climbfuji** [comment]
I think that with the first MRW release from EPIC (MRW 2.0), spack-stack will become the replacement for the NCEPLIBS/NCEPLIBS-external repos.

**Comment by edwardhartnett** [comment]
And when will that release happen?

Also can we release v1.0 of spack-stack without waiting? Is there some reason to wait?

**Comment by edwardhartnett** [comment]
Guys I think we are forgetting some important agile principles.  

We should always be ready for release.

Are we?

**Comment by climbfuji** [comment]
I think we are forgetting that this is the first release ever. If you create a new software project, will you be able to release it immediately after you started working on it?

**Comment by edwardhartnett** [comment]
This release is about six months behind EMC schedule.

Currently the NCEPLIBS and NCEPLIBS-external are broken and there is no approved way to build the software for external users.

Delay is not free. Seems like we can release now.

What specifically are we waiting for? What issues must be resolved before a 1.0 release?

**Comment by climbfuji** [comment]
Please look at the release-v1 labels in the spack-stack and spack issues. There is one item to be sorted out on discover with gnu compilers, and a bit of documentation, apart from that it is finished.

I expect it to be ready and tagged by Wednesday or Thursday this week. But also note that I have done testing for the fv3-jedi applications. It should work fine for ufs-weather-model, but EMC needs to help with the testing.

**Comment by edwardhartnett** [comment]
How are we coming with respect to the v1 release?

Also we need to do a full github release, not just a tag...

**Comment by edwardhartnett** [comment]
Also I see we already have a tag spack-stack-1.0.0. What's the deal with that? Should that tag be moved, or should the 1.0 release be what is at that tag?

I have drafted a set of release notes. Please add to the "New This Release" whatever you would like to add. For future releases we can use issue numbers in this section, but for this release we can just summarize.

(Note when editing the draft release notes, be sure to hit the "save draft" button at the bottom instead of accidentally doing the release.)

**Comment by climbfuji** [comment]
@edwardhartnett spack-stack-1.0.0 is the first release. I tagged it yesterday. We had the corresponding github project, the labels for the issues/PRs and some conversation on slack to define the release and monitor the progress of it. The last github issues that has the release-v1 label (besides this issue) has set of acceptance tests defined for the JEDI release, and I hope I will be ticking those boxes today.

For the JEDI release, we are planning to make it public next week, at which time it would be good to turn the tag into a proper release. I can populate the release notes until then.

The reason for not just using 1.0.0 was to be consistent with the versioning of the spack fork. The spack fork has all the release tags from the official spack repo, and it would be confusing of we were using x.y.z in there. If we don't want this versioning, then we can use x.y.z for the spack-stack release (but keep the tag spack-stack-1.0.0 as an identical tag so that I don't have to rewrite all documentation inside spack-stack and in the JEDI release docs).

Has anybody looked at the documentation, the github issues, the release project page, the slack messages over the past four to six weeks?

**Comment by edwardhartnett** [comment]
I don't mind the name of the release tag, that can be whatever is convenient, as long as we are consistent.

Let's do the proper github release with the spack-slack-1.0.0 release. I can do that today, and outside users can start using this and giving us feedback.

Moving forward, I think a release every quarter, or even more frequently, would be appropriate.

Now that this is released, we can deprecate the hpc-stack project, also the NCEPLIBS and NCEPLIBS-external projects, and stop working on them.

**Comment by climbfuji** [comment]
> I don't mind the name of the release tag, that can be whatever is convenient, as long as we are consistent.
> 
> Let's do the proper github release with the spack-slack-1.0.0 release. I will do that today, and outside users can start using this and giving us feedback.
> 
> Moving forward, I think a release every quarter, or even more frequently, would be appropriate.
> 
> Now that this is released, we can deprecate the hpc-stack project, also the NCEPLIBS and NCEPLIBS-external projects, and stop working on them.
> 
> (Also I don't see a release project page anywhere - where is that?)

It's linked in this issue: https://github.com/NOAA-EMC/spack-stack/issues/167

The link is https://github.com/orgs/NOAA-EMC/projects/5 . Quite mysteriously, this project first showed up as it should in the projects tab of the spack-stack github repo, but I can't see it there anymore. Not sure what happened. Maybe something with Github's move to the "new projects" (beta)?

**Comment by edwardhartnett** [comment]
Yes, I found the project page. It's somewhat inconsistent how it is shown on GitHub. I think for next release, we should use the new projects interface on GitHub and see if that works out.

**Comment by climbfuji** [comment]
Yes, agreed. That's what happens if you are trying to be careful and not use beta features ...

**Comment by edwardhartnett** [comment]
I have published the release notes. On to version 1.1.0!

I will close this issue.

**Comment by climbfuji** [comment]
You are moving fast!

**Comment by edwardhartnett** [comment]
Thank you, I try to.

**Comment by edwardhartnett** [comment]
I put up a project for the 1.1.0 release: https://github.com/orgs/NOAA-EMC/projects/7

I also added draft release notes for the 1.1.0 release. Remember to update them as you work, adding new items to the "New This Release" section, with links to related issues. (And when editing the draft release notes, take care to hit the "save draft" button instead of the "publish release" button.)
