### ISSUE TITLE
Instructions need to mention that the mpi you select needs to be added to the spack.yaml file

### ISSUE THREAD

**Issue by srherbener** [JCSDA/spack-stack#222]
When testing spack-stack build on MacOS, I selected openmpi for my MPI package and I needed to add that to the `specs:` section in the spack.yaml configuration file to get the build to work.

This should be noted in the documentation. Should this go in the MacOS instructions, or does it apply to any platform?

**Comment by kgerheiser** [comment]
Why did the build not work? I generally don't explicitly specify OpenMPI and it gets built automatically.

**Comment by climbfuji** [comment]
Same here, as long as the `packages:all:providers:mpi` section specifies the default you want to build, then it should go with that.

**Comment by srherbener** [comment]
Without that change, I am getting this error:
```
==> Installing openmpi-4.1.3-mba7247cq6hudmg3qpro3u7plie3txaw
==> No binary for openmpi-4.1.3-mba7247cq6hudmg3qpro3u7plie3txaw found: installing from source
==> Cannot find version 4.1.3 in url_list
==> Error: FetchError: All fetchers failed for spack-stage-openmpi-4.1.3-mba7247cq6hudmg3qpro3u7plie3txaw

/Users/stephenh/projects/MY_SPACK_STACK_FORK/spack-stack/spack/lib/spack/spack/package.py:1537, in do_fetch:
       1534
       1535        self.stage.create()
       1536        err_msg = None if not self.manual_download else self.download_instr
  >>   1537        start_time = time.time()
       1538        self.stage.fetch(mirror_only, err_msg=err_msg)
       1539        self._fetch_time = time.time() - start_time
       1540
```

I remember getting the instructions to add `- openmpi` to the specs in spack.yaml a few weeks ago so I tried that and this error went away. Perhaps this was just coincidence and there is a different (and more proper) way to fix this?

**Comment by kgerheiser** [comment]
Looks like a fetch error. Maybe the URL wasn't working or it changed.

**Comment by climbfuji** [comment]
Yes, this definitely looks like a fetch error. I'll close this issue, but if this keeps happening, please reopen it.
