### ISSUE TITLE
Build of MAPL 2.12.3 on MacOS fails due to missing link dependency

### ISSUE THREAD

**Issue by srherbener** [JCSDA/spack-stack#224]
I was able to reproduce the MAPL build failure on my iMac. I have discovered that the issue is that there is a C source file (`pfio_get_att_string.c`) that requires the netcdf-c library `libnetcdf.dylib`, but that library is not specified on the link command line. I verified that adding this library to the link command does indeed fix the problem.

It appears in the concretize log file that the netcdf-c package is listed as a dependency of mapl. Checking in the spack.lock file, netcdf-c appears to be listed as a build and link dependency for mapl. 

So I am not sure what is going wrong, nor what is the proper way to fix this. I would have thought that the dependency listed in the spack.lock file would be sufficient to get this to work.  Is there some other place that needs to specify this dependency for libnetcdf.dylib to be added to the link command?

**Comment by srherbener** [comment]
I noticed that the package.py script for mapl is missing a `depends_on('netcdf-fortran')` spec, so I tried adding that and re-ran concretize and install (for just mapl). Unfortunately, that resulted in the same error.

Perhaps the problem is that there is a mix of both netcdf-c and netcdf-fortran calls (both C and Fortran code) in the MAPL pfio source directory and that is somehow confusing spack?

**Comment by climbfuji** [comment]
Closed via https://github.com/NOAA-EMC/spack/pull/111
