### ISSUE TITLE
When to run `export -n SPACK_SYSTEM_CONFIG_PATH` when creating custom site config?

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#228]
@srherbener noted in the review of https://github.com/NOAA-EMC/spack-stack/pull/227:

> Also don't the new instructions for macOS and Linux, where you unset the SPACK_SYSTEM_CONFIG_PATH before running the spack config add commands, place the compiler spec in the envs/my-env/spack.yaml file instead of the envs/my-env/site/package.yaml file. Would it be worth adding a note on the Platform page about this difference? Sorry if that note is already there and I missed it.

I think that's actually a good point. I think it doesn't matter where those settings from `spack config add` go, but I agree it would be cleaner if they were in the site `package.yaml`. This way, one could probably use double colons and force spack to definitely use those settings.

We should consider making (and testing!) this small change on the customizable platforms.

**Comment by climbfuji** [comment]
@srherbener I tested this. Unless I add `--scope=system` to the `spack add` commands, the compiler spack ends up in `envs/my-env/spack.yaml` and note in the site `package.yaml`.

I am hesitant to require adding `--scope=system` to the `spack add` commands, because users may run this command more often later on, when extending the spack-stack installation, unlike the `spack external find` and `spack compiler find` commands that are usually only run when setting up the environment initially. Therefore I am inclined to leave the instructions as they are now. Ok?

**Comment by srherbener** [comment]
@climbfuji thanks for testing. I think it's okay to leave the instructions as they are now.

I like the idea of running spack commands as much as possible (as opposed to editing yaml files). I think that's a better habit to reinforce. And I think you are right in noting the difference between the commands you run once during setup versus the commands you might run several times after the initial setup.

I'm okay with closing this issue if you want.
