### ISSUE TITLE
Licensing restrictions require two versions of skylab template

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#230]
We can't release GPL code to the public, and some of the software packages in the skylab-1.0.0 template are unfortunately GPL:
- fftw
- gsl
- libiconv - _ignore for now_ this may not be an issue
- parallelio - update: no longer needed, the authors agreed to change their license to Apache 2 (thanks!!!)

We'll need to create a second skylab template that gets used to install the software environment on AMIs and containers and which doesn't include any of these dependencies. This will require adding a few more variants to our convenience environment modules.

- jedi-base-env: need variant to not build fftw
    -  need to propagate up to not build ectrans, and create variant in atlas to turn off ectrans
- need to make sure that when we build openmpi, we turn off ibconv in libxml2 - _ignore for now_
- figure out what/who needs gsl
    - soca-env has it, it's used as standalone executable in soca-science
    - doesn't need to be in the public skylab template

**Comment by climbfuji** [comment]
Closed via https://github.com/NOAA-EMC/spack-stack/pull/233

**Comment by kgerheiser** [comment]
Was doing some reading about linking GPL code from Apache, and it's pretty annoying that you can't even link to GPL. MET (Apache) links to GSL which is technically not allowed from my understanding.

Good to know that parallelio changed their license. I just took a look at it today and saw it as Apache and was wondering why it was listed here.

**Comment by climbfuji** [comment]
> Was doing some reading about linking GPL code from Apache, and it's pretty annoying that you can't even link to GPL. MET (Apache) links to GSL which is technically not allowed from my understanding.
> 
> Good to know that parallelio changed their license. I just took a look at it today and saw it as Apache and was wondering why it was listed here.

I asked them to change the pio license, and they were really quick and helpful doing that.
