### ISSUE TITLE
Merge release/v1 into develop

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#236]
Now that we have a tag spack-stack-1.0.0 and a release, we should merge release/v1 into develop and delete the release branch.

Hopefully we can release directly from develop in the future.

**Comment by kgerheiser** [comment]
I don't think there's any divergent history. Should be an easy merge.

**Comment by climbfuji** [comment]
> I don't think there's any divergent history. Should be an easy merge.

I'll have the spack merge done in a bit, and this one (spack-stack) should be relatively easy. The only file to be careful about is the common packages.yaml, which we sorted alphabetically in the release branch.

**Comment by climbfuji** [comment]
We should merge https://github.com/NOAA-EMC/spack/pull/117 first, and then update the submodule pointer for spack here as part of the PR, so that we can run the full CI tests. I also want to try running on my mac using the self-hosted runner that I added to develop

**Comment by edwardhartnett** [comment]
In future, let's just work from develop, and make the release right from develop, and then there is no need to merge changes from the release back to develop.

In other words, don't create the release branch until the release is ready.

**Comment by climbfuji** [comment]
Curious, why do you need a release branch at all then? If a bugfix is needed, create a hotfix branch from the tag, make the changes, create the new tag, ditch the hotfix branch?

**Comment by edwardhartnett** [comment]
You don't need a release branch. Unless as you say you want to patch it.

Even then it's usually better to apply the fix to develop and then do a new release.

So when doing a release, develop is tagged and everyone keeps working on the develop branch.

**Comment by climbfuji** [comment]
Ok, good, that's my understanding as well.

**Comment by climbfuji** [comment]
Release branches were merged into the development branches for both spack and spack-stack, and then deleted.
