### ISSUE TITLE
Split site.yaml into individual config files

### ISSUE THREAD

**Issue by kgerheiser** [JCSDA/spack-stack#24]
Instead of using a singular `site.yaml`, I think we should keep the individual configs (`packages.yaml`, `compilers.yaml`, etc) in the repository.

This makes it easier to generate configs for each system because Spack already outputs these files instead of having to concatenate them together manually.

`create-env.py` can create the `site.yaml` from the config files automatically.

**Comment by climbfuji** [comment]
Great - that's what I had originally ;-)
