### ISSUE TITLE
ESMF fails to link to external PIO

### ISSUE THREAD

**Issue by kgerheiser** [JCSDA/spack-stack#240]
Ran into an issue where ESMF failed to build because of missing symbols from PIO. Starting with ESMF 8.3.0 an external PIO and PIO was building static libraries only.

 PIO uses the `BUILD_SHARED_LIBS` option https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html but doesn't set it anywhere and defaults to off (maybe it's my CMake?). I added a variant `shared` to the PIO Spack build and it solved my issue.

I don't know why this hasn't show up in the CI. I am using GCC 11.3.0 on macOS 12.4 with CMake 3.23.2.

**Comment by edwardhartnett** [comment]
Is this a problem that I need to fix in the PIO build?

**Comment by kgerheiser** [comment]
@edwardhartnett yes I think so.

I made an issue in PIO: https://github.com/NCAR/ParallelIO/issues/1927
