### ISSUE TITLE
Additional packages requested for building NASA GEOS model

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#242]
From our colleagues, for building GEOS GCM (not GEOS-CHEM):

> Need additional Python packages in spack-stack for GEOS
> Cylc-flow 8 rc3 (https://anaconda.org/conda-forge/cylc-flow)
> Cylc-ui (https://anaconda.org/conda-forge/cylc-ui)
> Requires jupyterhub (currently not allowed on Discover)
> Additional cylc dependency for UKMO? (https://github.com/cylc/cylc-rose)
> Isodate
> Pycodestyle
> Xarray
> Scikit-learn

Don't have any of the above yet

> Cartopy (matplotlib)

We have that; spack-stack currently pins shapely (a cartopy dependency) to 1.8.0 with ‘Agg’ plotting backend. Compatible?

> NetCDF4

We have that; check that version and build variants are compatible.

**Comment by kgerheiser** [comment]
I got a start on filling out the packages here https://github.com/NOAA-EMC/spack/pull/122

**Comment by mer-a-o** [comment]
@climbfuji When adding Xarray can you please add [Dask](https://docs.xarray.dev/en/stable/user-guide/dask.html) too?

**Comment by climbfuji** [comment]
> @climbfuji When adding Xarray can you please add [Dask](https://docs.xarray.dev/en/stable/user-guide/dask.html) too?

As discussed, I am adding `xarray` and `f90nml` for now in PR #320.

**Comment by mathomp4** [comment]
FYI to @climbfuji, if you want to see what I currently install in GEOSpyD and so what might eventually come spack-stack's way: 

https://github.com/GMAO-SI-Team/GEOSpyD/blob/main/src/install_miniconda.bash#L276-L358

Quoth Shelley: "Look on my Works, ye Mighty, and despair!"

Hopefully, spack-stack can be an opportunity to clean some of that up...

**Comment by climbfuji** [comment]
> FYI to @climbfuji, if you want to see what I currently install in GEOSpyD and so what might eventually come spack-stack's way:
> 
> https://github.com/GMAO-SI-Team/GEOSpyD/blob/main/src/install_miniconda.bash#L276-L358
> 
> Quoth Shelley: "Look on my Works, ye Mighty, and despair!"
> 
> Hopefully, spack-stack can be an opportunity to clean some of that up...

Wow. Not impossible but ... a good chunk of work!
