### ISSUE TITLE
Create logo for spack-stack

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#255]
Now that we have a first spack-stack release, we should create a logo for it. I really like the font that I used for the presentation next week at the UFS Summer Workshop, and I think that the logo could be something like this (with the graphics being updated, of course!).

![Screen Shot 2022-07-12 at 1 20 24 PM](https://user-images.githubusercontent.com/8006981/178576905-e9a74a56-6a14-44c2-8844-a5acbbaf6704.png)

One could also rearrange this and add something like "powered by spack" with the spack logo somewhere.

**Comment by climbfuji** [comment]
I have been using this so far, and I think it's good enough for now

[spack-stack-logo.pdf](https://github.com/NOAA-EMC/spack-stack/files/11329681/spack-stack-logo.pdf)
![spack-stack-logo](https://user-images.githubusercontent.com/8006981/234488521-828c6221-fee4-4333-90fd-6b59bbc025d8.png)

**Comment by edwardhartnett** [comment]
You can add this logo to the github page for the project...

**Comment by climbfuji** [comment]
Ok, so far I've only added it to the wiki page. Let me do that ...
