### ISSUE TITLE
Add PIC option to NCEPLIBS packages

### ISSUE THREAD

**Issue by danholdaway** [JCSDA/spack-stack#260]
Soon the saber repo will depend on https://github.com/GEOS-ESM/gsibclim, which will in turn depend on https://github.com/NOAA-EMC/NCEPLIBS-sp. So this NCEPLIBS-sp package should be added to the JEDI stack. We are currently testing this repo on Discover so it would be useful to have available there before too long.

**Comment by climbfuji** [comment]
I'll take care of this.

**Comment by edwardhartnett** [comment]
Isn't NCEPLIBS-sp already handled?

**Comment by climbfuji** [comment]
Not as part of the original skylab-1.0.0 template (this is jedi-fv3 and jedi-ewok, not jedi-ufs). This will be an excellent case to show how we can easily extend the existing installations. I was going to add the entire ufs-weather-model-env to the existing stacks following the process we laid out previously: first, test in an encapsulated environment (chaining the authoritative installation), then, if successful, update authoritative installation.

I’ll do that tonight after the workshop and report how it went.

**Comment by climbfuji** [comment]
Update from @danholdaway. Apparently sp is part of skylab-1.0.0 but I didn't remember... 

> Indeed I can do module load sp/2.3.3 and then get passed the ecbuild step. So the module is there OK in fact. However sp was not installed using -fPIC so the linking fails.

**Comment by danholdaway** [comment]
I wonder if all the NCEPLIBS could be installed with fPIC? We may also have a dependency on w3emc, which in turn depends on bacio.

**Comment by climbfuji** [comment]
> I wonder if all the NCEPLIBS could be installed with fPIC? We may also have a dependency on w3emc, which in turn depends on bacio.

If that's needed (the ufs-weather-model doesn't need it), then we'll have to modify all of the spack packages to add the `-fPIC` option. Not a problem, just takes a bit. And will require a bugfix spack release. @kgerheiser FYI

**Comment by kgerheiser** [comment]
Just had to add a `pic` variant to g2c recently as well, and eventually just defaulted to building shared libraries. We (NCEPLIBS group) should try building shared libraries instead. If your application (an executable) links to these libraries then they should be fine for now, but if it's a shared library linking to them then it needs PIC.

**Comment by climbfuji** [comment]
@edwardhartnett Circling back to your original question, all libraries for building the ufs-weather-model in Release mode are installed as part of skylab-1.0.0:

https://github.com/NOAA-EMC/spack-stack/blob/develop/configs/templates/skylab-1.0.0/spack.yaml

What's missing currently are the debug versions of esmf and mapl (to compile in debug mode).

But as Dan noted, there is a an issue with the nceplibs - they are all built as static libraries, which works for the ufs, but not for jedi (wants shared libraries).
