### ISSUE TITLE
Spack builds with Intel even when GCC is set as preferred

### ISSUE THREAD

**Issue by kgerheiser** [JCSDA/spack-stack#266]
**Describe the bug**
@ulmononian reported not being able to build with GCC on Orion even if GCC/OpenMP is set as preferred in `packages.yaml`. I have also noticed this in the past. And then looking @climbfuji's Skylab 1.0.0 environment, I noticed he also commented out Intel MPI to force Spack to build with OpenMPI.

I created a bug report in the Spack repo here: https://github.com/spack/spack/issues/31669

**Comment by climbfuji** [comment]
Yes, I've done this basically on every platform. When trying to build with GNU, I remove the Intel compiler so that spack doesn't take it. Not sure if it's needed everywhere, but that's the dumb fail safe approach.

Clearly a bug, setting `compilers::` in the site config should work.

**Comment by climbfuji** [comment]
Issue https://github.com/spack/spack/issues/31669 is still unresolved

**Comment by climbfuji** [comment]
This is basically fixed. We are moving forward with the unified environment, which uses compiler matrices, and we also have access to the new `requires` syntax that specifies hard requirements.
