### ISSUE TITLE
Need spack-stack-1.0.2 bug fix release (`-fPIC` for NCEPlibs)

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#270]
Suggestion:

The missing `-fPIC` flags for the most commonly used NCEPlibs should be back-ported to tag spack-stack-1.0.1 to create tag 1.0.2. This then needs to be rolled out at least on Discover, where it is needed before the next planned release of spack-stack-1.1.0.

@kgerheiser @edwardhartnett Thoughts?

**Comment by kgerheiser** [comment]
Sounds good to me. Can we confirm that the relevant package changes work properly?

Do we do a full rebuild with these changes?

**Comment by climbfuji** [comment]
Of course I’ll need to try that first .

**Comment by climbfuji** [comment]
spack-stack-1.0.2 is now available, it includes the `-fPIC` flag for the most commonly used NCEPLIBS and was tested successfully by NASA GMAO on Discover with Intel. I will create a GNU install on Discover for this version as well.
