### ISSUE TITLE
Symbol not found: __cg_png_create_info_struct

### ISSUE THREAD

**Issue by cmgas** [JCSDA/spack-stack#275]
**Describe the bug**
When trying to run one of the scripts  from fv3-jedi-tools, I get the following error message:

```
File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
 File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
 File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
 File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
 File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
 File "<frozen importlib._bootstrap_external>", line 850, in exec_module
 File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
 File "/Users/cgas/Projects/JEDI/spack-stack-v1/envs/skylab-1.0.1/install/apple-clang/12.0.5/py-matplotlib-3.5.2-5pysrbw/lib/python3.9/site-packages/matplotlib/backends/backend_macosx.py", line 4, in <module>
  from matplotlib.backends import _macosx
ImportError: dlopen(/Users/cgas/Projects/JEDI/spack-stack-v1/envs/skylab-1.0.1/install/apple-clang/12.0.5/py-matplotlib-3.5.2-5pysrbw/lib/python3.9/site-packages/matplotlib/backends/_macosx.cpython-39-darwin.so, 2): Symbol not found: __cg_png_create_info_struct
 Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
 Expected in: /Users/cgas/Projects/JEDI/spack-stack-v1/envs/skylab-1.0.1/install/apple-clang/12.0.5/libpng-1.6.37-hsil4rs/lib/libpng16.16.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
```

**To Reproduce**
Spack-stack on Mac OS Big Sur, clang 12.0.5, python 3.9.13.
Clone directory fv3-jedi-tools and then from `fv3-jedi-tools/src/raster` try to run `python3 raster.py --gfs -f $JEDI_BUILD/fv3-jedi/test/Data/20201215.000000.c24.fv_core.res.nc -v T -l 60 -o test` or any other file you want to plot.

**Expected behavior**
This command should create a plot with the temperature at the 60th level. 

**System:**
Mac OS Big Sur, spack-stack, python virtual environment, clang 12.0.5, python 3.9.13.

**Comment by cmgas** [comment]
About the different paths mentioned in the error:
- `/Users/cgas/Projects/JEDI/spack-stack-v1/envs/skylab-1.0.1/install/apple-clang/12.0.5/py-matplotlib-3.5.2-5pysrbw/lib/python3.9/site-packages/matplotlib/backends/backend_macosx.py` exists
- `/Users/cgas/Projects/JEDI/spack-stack-v1/envs/skylab-1.0.1/install/apple-clang/12.0.5/py-matplotlib-3.5.2-5pysrbw/lib/python3.9/site-packages/matplotlib/backends/_macosx.cpython-39-darwin.so` exists
- `/System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO` doesn't exist
- `/Users/cgas/Projects/JEDI/spack-stack-v1/envs/skylab-1.0.1/install/apple-clang/12.0.5/libpng-1.6.37-hsil4rs/lib/libpng16.16.dylib` exists

**Comment by climbfuji** [comment]
On my mac, I have only:

ls /System/Library/Frameworks/ImageIO.framework/Versions/A/
Resources	XPCServices	_CodeSignature

no ImageIO

**Comment by kgerheiser** [comment]
I was looking into this a bit too, and I'm wondering if it's related to the OS version? This seems like a common issue from doing a bit of googling.

What I can't figure out though, is where this symbol is supposed to be coming from? Is `__cg_png_create_info_struct` supposed to be from libpng?

**Comment by kgerheiser** [comment]
What's happening is that `__cg__` (Core Graphics) is a prefix that Apple adds to `libpng` symbols with something like http://stackoverflow.com/questions/26066445/trouble-with-the-libpng-dylib-from-freetype-2-5-3/26068840#26068840

Then, in Spack it's finding the regular `libpng` with the function `_png_create_info_struct`, so symbol not found. It might be hardcoded into the Matplotlib code `matplotlib/backends/_macosx.cpython-39-darwin.so` such that it searches for built-in `libpng`.

**Comment by kgerheiser** [comment]
This is what I get on my Mac macOS 12.4, using a Macports Python and installing everything with Spack:
```
KIG@iMac hpc-stack-env % python3 raster.py --gfs -f /Users/KIG/Desktop/fv3-jedi-data/testinput_tier_1/inputs/gfs_c12/bkg/20201214.230000.fv_core.res.nc -v T -l 60 -o test.png
/opt/local/bin/python3: can't open file 'raster.py': [Errno 2] No such file or directory
KIG@iMac hpc-stack-env % cd fv3-jedi-tools/src/raster
KIG@iMac raster % python3 raster.py --gfs -f /Users/KIG/Desktop/fv3-jedi-data/testinput_tier_1/inputs/gfs_c12/bkg/20201214.230000.fv_core.res.nc -v T -l 60 -o test.png
Parameters:
 - gridfiledir: /Users/KIG/Desktop/spack-stack/envs/hpc-stack-env/fv3-jedi-tools/src/raster/fv3grid
 - geos: False
 - gfs: True
 - filepath: /Users/KIG/Desktop/fv3-jedi-data/testinput_tier_1/inputs/gfs_c12/bkg/20201214.230000.fv_core.res.nc
 - variable: T
 - basefilepath: None
 - basevariable: None
 - levels: 60
 - colormap: viridis
 - centered: False
 - ferret: False
 - output: test.png
raster.py:174: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  fld_tmp = fdata[args.variable][0,levels-1,:,:]
raster.py:176: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  units = fdata[args.variable].units
raster.py:177: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  long_name = fdata[args.variable].long_name
raster.py:228: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  vlons = np.degrees(fgrid["vlons"][:,:,:])
raster.py:229: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  vlats = np.degrees(fgrid["vlats"][:,:,:])
/Users/KIG/Desktop/spack-stack/envs/hpc-stack-env/install/apple-clang/13.1.6/py-cartopy-0.20.2-42e5qqp/lib/python3.8/site-packages/cartopy/io/__init__.py:241: DownloadWarning: Downloading: https://naturalearth.s3.amazonaws.com/110m_physical/ne_110m_coastline.zip
  warnings.warn(f'Downloading: {url}', DownloadWarning)
raster.py executed in 4.1311 seconds
```

![test png_60](https://user-images.githubusercontent.com/3209794/181345361-3c1f11c4-4620-4253-9a9a-b9f1cc4341be.png)

**Comment by kgerheiser** [comment]
Can you run `otool -L /Users/cgas/Projects/JEDI/spack-stack-v1/envs/skylab-1.0.1/install/apple-clang/12.0.5/py-matplotlib-3.5.2-5pysrbw/lib/python3.9/site-packages/matplotlib/backends/_macosx.cpython-39-darwin.so` with your environment setup as if you were running the command?

I get this:


```
KIG@iMac raster % otool -L /Users/KIG/Desktop/spack-stack/envs/hpc-stack-env/install/apple-clang/13.1.6/py-matplotlib-3.5.2-leclvkx/lib/python3.8/site-packages/matplotlib/backends/_macosx.cpython-38-darwin.so
/Users/KIG/Desktop/spack-stack/envs/hpc-stack-env/install/apple-clang/13.1.6/py-matplotlib-3.5.2-leclvkx/lib/python3.8/site-packages/matplotlib/backends/_macosx.cpython-38-darwin.so:
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 23.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 2113.40.126)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1858.112.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 1557.5.4)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1858.112.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

There's some `/System/Library/Framework/` being used, but no `ImageIO`.

**Comment by climbfuji** [comment]
@kgerheiser Thanks for looking into this. I get the same as you get, i.e. the same beautiful plot. My basic Python is coming from homebrew (but nothing else), all other packages are installed via spack-stack.
```
heinzell@JCSDA-L-18146:~/work/CMakeModules/move-jedi-cmake-modules-to-cmakemodules/fv3-jedi-tools/src/raster [brew-x86_64]> otool -L ../../../spack-stack//envs/skylab-1.0.1-cmaketest/install/apple-clang/13.1.6/py-matplotlib-3.5.2-hr33flw/lib/python3.9/site-packages/matplotlib/backends/_macosx.cpython-39-darwin.so
../../../spack-stack//envs/skylab-1.0.1-cmaketest/install/apple-clang/13.1.6/py-matplotlib-3.5.2-hr33flw/lib/python3.9/site-packages/matplotlib/backends/_macosx.cpython-39-darwin.so:
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 23.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 2091.12.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1844.0.0)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 1540.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1844.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```
@cmgas I am wondering if there were any OS updates, xcode updates etc. between when you installed spack-stack and the time you tried to plot?

**Comment by cmgas** [comment]
@kgerheiser I get this:

```
/Users/cgas/Projects/JEDI/spack-stack-v1/envs/skylab-1.0.1/install/apple-clang/12.0.5/py-matplotlib-3.5.2-5pysrbw/lib/python3.9/site-packages/matplotlib/backends/_macosx.cpython-39-darwin.so:
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 23.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 2022.44.149)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1775.118.101)
	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 1463.4.2)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1775.118.101)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

**Comment by climbfuji** [comment]
> rameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 23.0.0)
> 	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
> 	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 2022.44.149)
> 	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1775.118.101)
> 	/System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics (compatibility version 64.0.0, current version 1463.4.2)
> 	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1775.118.101)
> 	/usr/lib/libobjc.A.dylib (compatibility version

no imageio either

**Comment by cmgas** [comment]
by the way I have the same thing as you @climbfuji 
```
ls /System/Library/Frameworks/ImageIO.framework/Versions/A/
Resources	XPCServices	_CodeSignature

```

**Comment by kgerheiser** [comment]
All I can think of is to re-install Python and/or update your OS and developer tools.

**Comment by climbfuji** [comment]
Yeah, I am wondering if that ImageIO limbo is something from the past, maybe it got uninstalled at some point but something didn't get updated correctly. I agree, unfortunately, that updating OS / xcode / homebrew / spack-stack is probably the best chance, but that's a bigger lift.

**Comment by cmgas** [comment]
I found a solution that fixed it for me, I need to `export DYLD_LIBRARY_PATH=/usr/lib/:DYLD_LIBRARY_PATH` and it works as expected.

**Comment by cmgas** [comment]
![test_60](https://user-images.githubusercontent.com/43183478/183116398-073cd2ae-756e-4143-a692-0b66cf97e668.png)

**Comment by climbfuji** [comment]
> I found a solution that fixed it for me, I need to `export DYLD_LIBRARY_PATH=/usr/lib/:DYLD_LIBRARY_PATH` and it works as expected.

I assume `export DYLD_LIBRARY_PATH=/usr/lib/:$DYLD_LIBRARY_PATH` ? Great detective work. If you are ok, let's close this issue as solved, because it's not a spack or spack-stack problem as far as I understand, and we've got a workaround.

How about adding a note to the known issues section in the spack-stack sphinx doc (under macOS)? Would you be willing to do that?
