### ISSUE TITLE
Fix Intel build in Github Action

### ISSUE THREAD

**Issue by kgerheiser** [JCSDA/spack-stack#28]
Error loading `libimf.so` on Ubuntu. Need to set `LD_LIBRARY_PATH` or `EXTRA_RPATHS` in compilers.yaml if trying to avoid using `---dirty`.

**Comment by kgerheiser** [comment]
Using an Ubuntu VM I was able to get the compiler to work by setting LD_LIBRARY_PATH in compiler.yaml. 

```
set:
  LD_LIBRARY_PATH: /opt/intel/oneapi/compiler/latest/linux/compiler/lib/intel64
```

**Comment by climbfuji** [comment]
Yes, same as in the cheyenne and orion configs for example.

**Comment by kgerheiser** [comment]
I don't think setting those variables on HPC systems with modules is necessary. I was able to build on Orion without manually setting any environment variables. The module should handle that.

**Comment by climbfuji** [comment]
That's possible ... but for some reason I had to add the LD_LIBRARY_PATH when I started working on this a month or two back.

However, we will need at least the CXXFLAGS to define the toolchain. I'll also try on Cheyenne w/o LD_LIBRARY_PATH

**Comment by kgerheiser** [comment]
~~Make sure to set the `prefix` not to the compilers themselves, but to the top-level Intel directory.~~ For MPI that is.

**Comment by climbfuji** [comment]
Not sure if I understand your last comment, but I tried on Cheyenne w/o LD_LIBRARY_PATH in the compiler and it failed in parallel-netcdf:
```
ld: /glade/u/apps/opt/intel/2021.2/compiler/2021.2.0/linux/bin/intel64/../../bin/intel64/../../lib/icx-lto.so: error loading plugin: libimf.so: cannot open shared object file: No such file or directory
configure:33760: $? = 1
```
I'll put it back in because it doesn't hurt.

**Comment by climbfuji** [comment]
@kgerheiser Do you have plans to fix this, or keep the `--dirty` in the Intel CI config?

**Comment by kgerheiser** [comment]
Replacing `environment: {}` with `environment: {prepend_path: {LD_LIBRARY_PATH: /opt/intel/oneapi/compiler/latest/linux/compiler/lib}}` should work. Just have to test it out.

**Comment by climbfuji** [comment]
I will try. I have some other CI fixes in my current PR anyway.
