### ISSUE TITLE
[INSTALL] Update tag for NCEPLIBS-bufr JEDI build after NCEPLIBS-bufr PR 222 gets merged

### ISSUE THREAD

**Issue by srherbener** [JCSDA/spack-stack#289]
**Which software in the stack would you like installed?**
This is a request to update the version tag on the NCEPLIBS-bufr library build for JEDI. Ron McLaren needs the changes in NOAA-EMC/NCEPLIBS-bufr/pull/222 before we can merge his feature/query_cxx PR in the ioda-converters repo (jcsda-internal/ioda-converters/pull/1006).

NOAA-EMC/NCEPLIBS-bufr/pull/222 is still under review so I am submitting this issue in part to let everyone become aware of this need beforehand.

**What is the version/tag of the software?**
The version tag is yet to be determined. After NOAA-EMC/NCEPLIBS-bufr/pull/222 is approved and merged, a tag will be generated and then we can do the update being requested in this issue.

**What compilation options would you like set?**
Please keep the compilation options the same as they are now

**Which machines would you like to have the software installed?**
See currently managed HPC machines.

**Any other relevant information that we should know to correctly install the software??**

**Additional context**
Please see jcsda-internal/ioda-converters/issues/965 for additional information.

**Comment by climbfuji** [comment]
@srherbener NCEPLIBS-bufr PR 222 was merged yesterday. There is no new tag yet.

**Comment by climbfuji** [comment]
@srherbener I believe this is the release you were waiting for: https://github.com/NOAA-EMC/NCEPLIBS-bufr/releases/tag/bufr_v11.7.1

**Comment by jbathegit** [comment]
Yep, that's it.  I'd been waiting on one final commit for this release, which was just approved and merged this morning.  With that done, I just officially released 11.7.1 within the past hour.

I came here now to let you know, but looks like Dom beat me to it ;-)

**Comment by srherbener** [comment]
I concur, v11.7.1 is the one Ron needs for his BUFR converter. Thanks @jbathegit for providing this patch!
