### ISSUE TITLE
Error loading scipy with Intel compilers.

### ISSUE THREAD

**Issue by danholdaway** [JCSDA/spack-stack#291]
**Describe the bug**

There seems to be an issue with the installation of `py-scipy` with Intel compilers on Discover. After loading the modules, entering python and doing e.g. `from scipy.stats import skew` the following traceback occurs:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfsm/dswdev/jcsda/spack-stack/spack-stack-v1/envs/skylab-1.0.0-intel-2022.0.1/install/intel/2022.0.1/py-scipy-1.8.0-eiuk7wc/lib/python3.9/site-packages/scipy/stats/__init__.py", line 453, in <module>
    from ._stats_py import *
  File "/gpfsm/dswdev/jcsda/spack-stack/spack-stack-v1/envs/skylab-1.0.0-intel-2022.0.1/install/intel/2022.0.1/py-scipy-1.8.0-eiuk7wc/lib/python3.9/site-packages/scipy/stats/_stats_py.py", line 38, in <module>
    from scipy.spatial.distance import cdist
  File "/gpfsm/dswdev/jcsda/spack-stack/spack-stack-v1/envs/skylab-1.0.0-intel-2022.0.1/install/intel/2022.0.1/py-scipy-1.8.0-eiuk7wc/lib/python3.9/site-packages/scipy/spatial/__init__.py", line 108, in <module>
    from ._geometric_slerp import geometric_slerp
  File "/gpfsm/dswdev/jcsda/spack-stack/spack-stack-v1/envs/skylab-1.0.0-intel-2022.0.1/install/intel/2022.0.1/py-scipy-1.8.0-eiuk7wc/lib/python3.9/site-packages/scipy/spatial/_geometric_slerp.py", line 9, in <module>
    from scipy.spatial.distance import euclidean
  File "/gpfsm/dswdev/jcsda/spack-stack/spack-stack-v1/envs/skylab-1.0.0-intel-2022.0.1/install/intel/2022.0.1/py-scipy-1.8.0-eiuk7wc/lib/python3.9/site-packages/scipy/spatial/distance.py", line 123, in <module>
    from ..special import rel_entr
  File "/gpfsm/dswdev/jcsda/spack-stack/spack-stack-v1/envs/skylab-1.0.0-intel-2022.0.1/install/intel/2022.0.1/py-scipy-1.8.0-eiuk7wc/lib/python3.9/site-packages/scipy/special/__init__.py", line 652, in <module>
    from . import _basic
  File "/gpfsm/dswdev/jcsda/spack-stack/spack-stack-v1/envs/skylab-1.0.0-intel-2022.0.1/install/intel/2022.0.1/py-scipy-1.8.0-eiuk7wc/lib/python3.9/site-packages/scipy/special/_basic.py", line 15, in <module>
    from . import _specfun
ImportError: /gpfsm/dswdev/jcsda/spack-stack/spack-stack-v1/envs/skylab-1.0.0-intel-2022.0.1/install/intel/2022.0.1/py-scipy-1.8.0-eiuk7wc/lib/python3.9/site-packages/scipy/special/_specfun.cpython-39-x86_64-linux-gnu.so: undefined symbol: __svml_pow4_l9
```

No such error occurs with the GNU collection.

**To Reproduce**

On discover:

```
module purge
module use /discover/swdev/jcsda/spack-stack/modulefiles
module load miniconda/3.9.7
module load ecflow/5.8.4
module use /discover/swdev/jcsda/spack-stack/spack-stack-v1/envs/skylab-1.0.0-intel-2022.0.1/install/modulefiles/Core
module load stack-intel/2022.0.1
module load stack-intel-oneapi-mpi/2021.5.0
module load stack-python/3.9.7
module load jedi-ewok-env/1.0.0
module load jedi-fv3-env/1.0.0
module load nco/5.0.6
python
from scipy.stats import skew
```

**Expected behavior**

No error on load

**System:**

NCCS Discover, Intel compiler collection.

**Comment by climbfuji** [comment]
Hmm, that's a missing symbol from the Intel math vector library. Will need to investigate.

**Comment by climbfuji** [comment]
@danholdaway I started looking at this. I think it's got to do with `libsvml` not being linked in properly by the `py-scipy` build system.

**Comment by climbfuji** [comment]
No solution yet, but I got a bit further. spack bug report: https://github.com/spack/spack/issues/32732

**Comment by climbfuji** [comment]
@danholdaway I have a pretty nasty workaround, do you think you can try that in your workflow?
```
# after logging into Discover
module purge
module use /discover/swdev/jcsda/spack-stack/modulefiles
module load miniconda/3.9.7
module use /gpfsm/dnb32/dheinzel/spack-stack/spack-stack-scipy-intel/envs/py-scipy-intel-test/install/modulefiles/Core
module load stack-intel/2022.0.1
module load stack-python/3.9.7
module load py-scipy/1.8.0
```
That test stack has limited packages available, but hopefully it's all that you need for testing. Thanks a lot in advance!

**Comment by climbfuji** [comment]
> spack/spack#32732

EDIT: I removed that directory and started over with an alternative and much better approach coming from discussions with the spack developers.

**Comment by climbfuji** [comment]
> @danholdaway I have a pretty nasty workaround, do you think you can try that in your workflow?
> 
> ```
> # after logging into Discover
> module purge
> module use /discover/swdev/jcsda/spack-stack/modulefiles
> module load miniconda/3.9.7
> module use /gpfsm/dnb32/dheinzel/spack-stack/spack-stack-scipy-intel/envs/py-scipy-intel-test/install/modulefiles/Core
> module load stack-intel/2022.0.1
> module load stack-python/3.9.7
> module load py-scipy/1.8.0
> ```
> 
> That test stack has limited packages available, but hopefully it's all that you need for testing. Thanks a lot in advance!

**EDIT:** I removed that directory and started over with an alternative and much better approach coming from discussions with the spack developers.

**Comment by climbfuji** [comment]
@danholdaway Update. You can try this now:
```
module purge
module use /discover/swdev/jcsda/spack-stack/modulefiles
module load miniconda/3.9.7
module use /gpfsm/dnb32/dheinzel/spack-stack/spack-stack-scipy-intel/envs/py-scipy-intel-test-2/install/modulefiles/Core
module load stack-intel/2022.0.1
module load stack-python/3.9.7
module load py-scipy/1.8.0
```

**Comment by danholdaway** [comment]
Thanks Dom. Would it be possible to add geos, cartopy and matplotlib ? The package I would test this with requires those packages and for whatever reason beyond my understanding pip doesn't install geos when it goes to install those packages.

```
  lib/cartopy/trace.cpp(767): catastrophic error: cannot open source file "geos_c.h"
    #include "geos_c.h"
                       ^
  
  compilation aborted for lib/cartopy/trace.cpp (code 4)
```

**Comment by climbfuji** [comment]
> Thanks Dom. Would it be possible to add geos, cartopy and matplotlib ? The package I would test this with requires those packages and for whatever reason beyond my understanding pip doesn't install geos when it goes to install those packages.
> 
> ```
>   lib/cartopy/trace.cpp(767): catastrophic error: cannot open source file "geos_c.h"
>     #include "geos_c.h"
>                        ^
>   
>   compilation aborted for lib/cartopy/trace.cpp (code 4)
> ```

Doing this now. Hopefully we can get this tested and merged Friday morning before we create the release branches for spack-stack and spack. Thanks for helping with the testing!

**Comment by climbfuji** [comment]
> from scipy.stats import skew

@danholdaway Can you try again, please?
```
module purge
module use /discover/swdev/jcsda/spack-stack/modulefiles
module load miniconda/3.9.7
module use /gpfsm/dnb32/dheinzel/spack-stack/spack-stack-scipy-intel/envs/py-scipy-intel-test-2/install/modulefiles/Core
module load stack-intel/2022.0.1
module load stack-intel-oneapi-mpi/2021.5.0
module load stack-python/3.9.7
module load jedi-ewok-env/1.0.0
```

**Comment by danholdaway** [comment]
@climbfuji it works! Thanks so much. I was able to run the eva tests on Discover using these modules.
