### ISSUE TITLE
Supporting adding package versions dynamically

### ISSUE THREAD

**Issue by uturuncoglu** [JCSDA/spack-stack#303]
**Is your feature request related to a problem? Please describe.**
Currently, spack only supports adding branches and tags to the package manually and it would be nice to have a feature to add those in a more automatized way with the information ingested from the repository itself. This will provide additional flexibility to the package developers that they might want to test different branches and tags easily.

**Describe the solution you'd like**
The current solution that I am using is based on `git ls-remote --refs` command to collect information from the repo without actually checking out it and use this information to populate the versions. Here is the example implementation that I tested in one of my repository

```
    # list refs/heads and refs/tags and add them as version
    git_exe = which('git', required=True)
    cmd = '{} ls-remote --refs {}'.format(git_exe, git)
    git_lst = subprocess.run(cmd, shell=True, text=True, stdout=subprocess.PIPE).stdout.splitlines()

    # loop over list and define them as version
    for item in git_lst:
        # split item as hash, branch/tag name
        item_lst = list(item.split('\t'))

        # replace / with _ in version name since spack does not good with / in the version string
        _name = item_lst[1]
        refs_name = _name.replace('refs/heads/', '')
        refs_name = refs_name.replace('refs/tags/', '')
        version_name = refs_name.replace('/', '_')

        # skip some common branches
        if 'gh-pages' in _name:
            continue

        # add tags and branches to the version
        if 'refs/tags' in _name:
            version(version_name, tag=refs_name)
        elif 'refs/heads' in _name:
            version(version_name, branch=refs_name)
```

This code needs to be placed into top level class in the `package.py. To have more generic solution, this could be an extension in spack side and can be used by all the packages that are provided by the spack. BTW, with this way there is no need to add versions manually but it could be also used with the existing manual implementation. So, the user could add specific hashes as version manually but branches and tags will be added by this code.

Also, note that the the branch name is not same with the version name since `/` is not supported by the spack interface and I had to replace `/` in the branch name as `_`. So, if you would like to install `feature/nuopc_cap` branch then you need to call spack like `spack install noahmp@feature_nuopc_cap`. 

**Additional context**
Here is the example output of `spack info noahmp` from newly added noahmp package (still in my fork),

```
CMakePackage:   noahmp

Description:
    Noah-MP is a community land model contributed by the whole Noah-MP
    scientific community.

Homepage: https://github.com/uturuncoglu/noahmp

Preferred version:  
    v3.8                 [git] https://github.com/uturuncoglu/noahmp.git at tag v3.8

Safe versions:  
    develop_no_gecros    [git] https://github.com/uturuncoglu/noahmp.git on branch develop_no_gecros
    develop              [git] https://github.com/uturuncoglu/noahmp.git on branch develop
    master               [git] https://github.com/uturuncoglu/noahmp.git on branch master
    v3.8                 [git] https://github.com/uturuncoglu/noahmp.git at tag v3.8
    v3.7.1               [git] https://github.com/uturuncoglu/noahmp.git at tag v3.7.1
    v3.7                 [git] https://github.com/uturuncoglu/noahmp.git at tag v3.7
    release-v4.4-WRF     [git] https://github.com/uturuncoglu/noahmp.git on branch release-v4.4-WRF
    feature_nuopc_cap    [git] https://github.com/uturuncoglu/noahmp.git on branch feature/nuopc_cap

Deprecated versions:  
    None

Variants:
    Name [Default]                 When    Allowed values          Description
    ===========================    ====    ====================    ==================================

    build_type [RelWithDebInfo]    --      Debug, Release,         CMake build type
                                           RelWithDebInfo,         
                                           MinSizeRel              
    ipo [off]                      --      on, off                 CMake interprocedural optimization

Build Dependencies:
    cmake  mpi

Link Dependencies:
    esmf  fms  mpi  netcdf-c  netcdf-fortran

Run Dependencies:
    None
```

**Comment by climbfuji** [comment]
I think this is a great idea. I would be in favor of adding a script to the spack-stack repo (maybe a new folder `utilities` or `tools` or so) and supporting documentation the sphinx/readthedocs doc. Wouldn't want to make it part of spack yet, we can think about that after we started using it?

**Comment by uturuncoglu** [comment]
@climbfuji That sounds fine. I was using spack EMC fork but I could move to spack-stack without any issue. Let me explore the best place to put this and create PR for it.

**Comment by uturuncoglu** [comment]
@climbfuji On minor question about the implementation. I think this new feature need to be used in package.py since we will not activate it for all the package. Right? If so, what happens if someone uses the spack (that includes a package with this new feature) outside of the spack-stack? I think that the package.py could not find the provided module to add dynamic version support and will fail. Any suggestion to overcome this issue?

**Comment by climbfuji** [comment]
My thought was to write this as an EXTERNAL tool that you would point to a package.py file (as a command line argument) and that would do its magic and rewrite the package.py file, probably with additional arguments such as the git repo in which to look for the branches etc?

**Comment by uturuncoglu** [comment]
@climbfuji I am not sure. I think rewriting the package is not good idea and it will only change the local copy (I am assuming you are not pushing the result package.py to the repo). I thought that having an additional Python layer that could be imported in the package.py like `from spack-stack import *` and then new features can be used but now I see the issue with it. Maybe this could be an util in spack layer (I see that you have already folder like lib/jcsda-emc/spack-stack/) or additional argument to `spack create` command.

**Comment by climbfuji** [comment]
Yes, it could be a spack extension.

**Comment by uturuncoglu** [comment]
@climbfuji I found an issue about spack and there is no way to specify version for the branches. So, this creates the issue when you are trying to install any branch other than develop since patches are version dependent and if you try to install package with some arbitrary branch, it is trying to install patches without any version restriction even if it is define with `when` argument. So, I think this approach needs to be extended to support those cases as well as ability to expect the regex expression etc. to filter the branch and tags that are defined dynamically. I'll look at those and update you when I have time.

**Comment by climbfuji** [comment]
@uturuncoglu There hasn't been any progress on this, do you want to close the issue as "won't fix" or keep working on it?

**Comment by uturuncoglu** [comment]
@climbfuji yes, I am closing it for now. I could not find time to work on spack side to fix the issue.
