### ISSUE TITLE
Update spack-stack doc to reflect version 1.0.2 more accurately

### ISSUE THREAD

**Issue by srherbener** [JCSDA/spack-stack#305]
**Describe the bug**
A couple users noted some differences/mistakes in the documentation which are due to changes in spack-stack between version 1.0.0 and 1.0.2.

**To Reproduce**
The module load sequence for MSU Orion using GNU will fail with the error "stack-openmpi module not found".

**Expected behavior**
All the modules load properly

**System:**
Orion

**Additional context**

**Comment by climbfuji** [comment]
Closed via https://github.com/NOAA-EMC/spack-stack/pull/306
