### ISSUE TITLE
ensure that spack installs wgrib2 with native wgrib2 build

### ISSUE THREAD

**Issue by edwardhartnett** [JCSDA/spack-stack#307]
ensure that spack installs wgrib2 with native wgrib2 build

**Comment by climbfuji** [comment]
Unfortunate I don't understand what that means, sorry.

**Comment by Hang-Lei-NOAA** [comment]
We (EMC) additionally created the build script for wgrib2 library. However,
it is recommended to use the developer's original build approach.
I believe that present one in spack should use the native build, since Kyle
discussed with me in adding this. But I will double check this part.

**Comment by climbfuji** [comment]
@Hang-Lei-NOAA @edwardhartnett For your information, I am collecting todo items for the next release 1.1.0. I'll create an issue with a freeze date momentarily, but unless someone from EMC is stepping up to take on this particular issue, it will not be included in spack-stack-1.1.0.

**Comment by edwardhartnett** [comment]
wgrib2 has a horrific home-rolled build system which makes working on it very difficult and expensive. We at the EMC have already invested many hours in attempting to work with the wgrib2 developer, including providing a cmake build system, but this was not adopted and the home-rolled system continues.

Also on behalf of the netCDF development team (which I am part of) I asked the wgrib2 developer to stop including a snapshot copy of netcdf-c code within the wgrib2 build. This is terrible practice with numerous pitfalls.

Users should move from wgrib2 to a tool which is properly built and maintained.

**Comment by climbfuji** [comment]
Closing this issue as "not planned". We have done our due diligence to update the wgrib2 package in the authoritative repository, it builds the way the wgrib2 developers wants it to build.
