### ISSUE TITLE
Paralleio 2.5.3 " PermissionError: [Errno 13] Permission denied" when installing on Hera

### ISSUE THREAD

**Issue by ulmononian** [JCSDA/spack-stack#311]
**Describe the bug**
When trying to install ufs-wm-dev common modules as a spack environment (https://github.com/ulmononian/spack-stack/blob/feature/ufs-wm-dev/configs/templates/ufs-wm-dev/spack.yaml), the following error is produced when installing Parallelio 2.5.3:

==> Installing parallelio-2.5.3-td3olnm7irgubt4ljfq2aric5hq6hcsn
==> No binary for parallelio-2.5.3-td3olnm7irgubt4ljfq2aric5hq6hcsn found: installing from source
==> Fetching https://github.com/NCAR/ParallelIO/archive/refs/tags/pio2_5_3.tar.gz
==> Moving resource stage
        source: /scratch1/NCEPDEV/stmp2/Cameron.Book/spack_work/ufs-wm-dev/cache/build_stage/resource-CMake_Fortran_utils-td3olnm7irgubt4ljfq2aric5hq6hcsn/spack-src/
        destination: /scratch1/NCEPDEV/stmp2/Cameron.Book/spack_work/ufs-wm-dev/cache/build_stage/spack-stage-parallelio-2.5.3-td3olnm7irgubt4ljfq2aric5hq6hcsn/spack-src/CMake_Fortran_utils
==> Error: PermissionError: [Errno 13] Permission denied: '/scratch1/NCEPDEV/stmp2/Cameron.Book/spack_work/ufs-wm-dev/cache/build_stage/spack-stage-parallelio-2.5.3-td3olnm7irgubt4ljfq2aric5hq6hcsn/spack-src/CMake_Fortran_utils/.git/objects/44/55cdc3bb428eb5bdad30c07908ca8fda084e0d'

/scratch1/NCEPDEV/stmp2/Cameron.Book/spack_work/ufs-wm-dev/spack/lib/spack/spack/package.py:1559, in do_stage:
       1556
       1557        # Fetch/expand any associated code.
       1558        if self.has_code:
  >>   1559            self.do_fetch(mirror_only)
       1560            self.stage.expand_archive()
       1561
       1562            if not os.listdir(self.stage.path):

**To Reproduce**
module purge
module use /scratch1/NCEPDEV/jcsda/jedipara/spack-stack/modulefiles
module load miniconda/3.9.12

spack stack create environment --site hera --template ufs-wm-dev --name ufs-wm-dev.hera
spack env activate ./envs/ufs-wm-dev.hera
spack concretize
spack install

**Expected behavior**
All specs in configs/templates/ufs-wm-dev/spack.yaml install successfully.

**System:**
Hera

**Additional context**
I am not sure if this could be related to https://github.com/NOAA-EMC/spack-stack/commit/ccde5cc048feda7dbf5e5c6d84761489a4c15cd6 or https://github.com/NOAA-EMC/spack/commit/936d2f2b1f5c609e838ff6a13c3220087d4fd18c.

**Comment by climbfuji** [comment]
I am not sure. My first guess would have been running out of disk quota, or intermittent filesystem errors, or an excessively long path name.

**Comment by Hang-Lei-NOAA** [comment]
I think so. The hera disk quota is always an issue for us. The problem is always the same to this one.

**Comment by ulmononian** [comment]
@Hang-Lei-NOAA @climbfuji interesting. i received the same error when installing PIO 2.5.3 w/ the ufs-srw-dev template. odd that it wants to fail only on this spec. in any case, i cleaned up some disk space and will give it another go. thank you both for the input.

**Comment by ulmononian** [comment]
@Hang-Lei-NOAA @climbfuji i cleared up about 430GB of space here /scratch1/NCEPDEV/stmp2/Cameron.Book, shortened the path as best i could (/scratch1/NCEPDEV/stmp2/Cameron.Book/spack-stack) and re-tried the ufs-wm-dev install, but received the same error with pio 2.5.3. 

this was also tested with my fork in sync with the most recent changes to noaa-emc spack-stack dev. branch.

**Comment by ulmononian** [comment]
i tried installing in another working directory, /scratch2/NCEPDEV/marine/Cameron.Book/sw/kt, but same issue. i don't think there is anything amiss with my ufs-wm-dev spack.yaml and hera config files (compilers, packages) https://github.com/ulmononian/spack-stack/tree/feature/ufs-wm-dev/configs, but maybe i am missing something...

**Comment by ulmononian** [comment]
this issue was resolved by clearing temporary directories generated during spack installations in /tmp on hera.

**Comment by climbfuji** [comment]
Great debugging, thanks for sharing your solution.

**Comment by natalie-perlin** [comment]
@ulmononian - what directories did you clean, did you run "spack clean -a" , or clean it from the command line?..

**Comment by natalie-perlin** [comment]
@ulmononian , @climbfuji  - I wonder if this issue could be reopened! This is a recurrent problem for my installation, too, on Gaea in particular. Usually, two packages routinely fail to install from the first attempt, parallelio and mapl. It did happen once that the installation went successfully from the beginning to the end, but next dozen attempts had it failing on the first try. So actually, there two problems here:
1) in one case, when running a build from a terminal, the installation of parallelio and mapl fails from the first time. When installation is run for the second time, with no any additional cleaning, the same two packages are being built with no issues. 
2) When the job is submitted via Jenkins, it hangs somewhere in the middle, during installation of some of the larger packages requiring few minutes  to be build (wgrib2, or cmake, or others). It did happened once when the installation went all the way through for the first time, and started the second attempt to make up for the two failed ones, parallelio and mapl, and then got hung at the last stage.

I did try to run "spack clean -a" before building the stack, but it never had any effect. At what point cleaning the temporary space could be made and how it is safely done during installation?

**Comment by climbfuji** [comment]
@natalie-perlin Please take a look at a workaround I use on Gaea from time to time (readthedocs --> known issues). I think the latency of the shared filesystem plays a role in the errors you are seeing.
