### ISSUE TITLE
Add scotch library as a replacement for parmetis

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#336]
**Please describe the package or library you would like to add to spack-stack.**
`parmetis` is the parallelized version of the graph partitioning library `metis` and used by several codes that work with unstructured meshes (e.g. MPAS). Unfortunately, `parmetis` was rejected from the WCOSS2 software list and a replacement for it, called `scotch` (sounds much better to me anyway), was found. This needs to be added to spack-stack.

I believe it's this website: https://www.labri.fr/perso/pelegrin/scotch

Which version? @ulmononian @junwang-noaa 

**What applications will be using this package or library?**
Codes using unstructured meshes in operations.

**Is there already a package or library in spack-stack that provides this, or related, functionality?**
`parmetis`, which isn't allowed on WCOSS2

**Additional context**
n/a

**Will This Package be Needed in a NOAA Operational Application?**
Yes. I will skip the WCOSS System Software Request Checklist, because `scotch` has already been approved for installation on WCOSS2 by some effort in the UFS community.

**Comment by ulmononian** [comment]
@climbfuji i can handle this if it is needed.

**Comment by climbfuji** [comment]
THe scotch library is already in spack https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/scotch/package.py - we need to (a) check if the code for this package in our fork is up to date (we pulled in spack develop about two weeks ago), and (b) add it to our spack configuration files. I suggest to add it to the ufs environments/templates for now, not base-env or jedi-base-env.

**Comment by ulmononian** [comment]
@climbfuji not sure if it meets the check you are describing, but i installed scotch@7.0.1 (the latest version) via EMC spack-stack just a few days ago here: /scratch1/NCEPDEV/stmp2/Cameron.Book/spack_work/spack-stack/envs/scotch.intel, so i assume it is up to date in the fork.

as for the templates, i suppose it should go in [hpc-stack-dev](https://github.com/NOAA-EMC/spack-stack/tree/develop/configs/templates/hpc-stack-dev) and [ufs-weather-model](https://github.com/NOAA-EMC/spack-stack/tree/develop/configs/templates/ufs-weather-model). i am not sure what the base-env or jedi-base-envs are...

**Comment by ulmononian** [comment]
@climbfuji circling back to this. if there are specifics for a PR to this repo that are needed, please let me know. it would be nice to jointly address this issue and be able to get https://github.com/NOAA-EMC/hpc-stack/pull/504 merged.

**Comment by climbfuji** [comment]
> @climbfuji circling back to this. if there are specifics for a PR to this repo that are needed, please let me know. it would be nice to jointly address this issue and be able to get [NOAA-EMC/hpc-stack#504](https://github.com/NOAA-EMC/hpc-stack/pull/504) merged.

sorry I missed your previous comment. it's fine to add it to hpc-stack-dev and ufs-weather-model, you may want to add it to spack/var/spack/repos/jcsda_emc_bundles/packages/ufs-weather-model-env/package.py as well?

**Comment by climbfuji** [comment]
Note. Issue https://github.com/NOAA-EMC/spack-stack/issues/465 is more or less a duplicate of this issue, but provides additional information.

**Comment by climbfuji** [comment]
Closed via https://github.com/JCSDA/spack-stack/pull/550
