### ISSUE TITLE
spack-stack 1.1.0 release

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#339]
## Description

Time to note down the release procedure.
- [x] Clear the project board: https://github.com/orgs/NOAA-EMC/projects/7 - @climbfuji, @AlexanderRichert-NOAA
- [x] Create release branches release/1.1.0 in `spack-stack` and `spack - @climbfuji
- [x] Create `skylab-2.0.0` template from `skylab-dev` template - @climbfuji
- [x] Finalize `hpc-stack` template (to be used for transitioning from hpc-stack to spack-stack) - @AlexanderRichert-NOAA 
- [x] Install spack-stack-1.1.0 in existing spack-stack-v1 locations using template `skylab-1.1.0` on the following systems (using final tag, if possible, otherwise use branch release/1.1.0):
    - [x] Orion with Intel - @climbfuji
    - [x] Orion with GNU - @climbfuji
    - [x] Cheyenne with Intel - @climbfuji
    - [x] Cheyenne with GNU - @climbfuji
    - [x] S4 with Intel - @climbfuji
    - [x] Discover with Intel - @climbfuji
    - [x] Discover with GNU - @climbfuji
    - [x] Gaea with Intel - @climbfuji
    - [x] AWS parallelcluster AMI Ubuntu 20.04 with Intel, then add missing pieces for skylab release and create custom AMI - @climbfuji
    - [x] AWS single node AMI Red Hat 8 with GNU, then add missing pieces for skylab release and create custom AMI - @climbfuji
    - [x] AWS single node AMI Ubuntu 20 with GNU, then add missing pieces for skylab release and create custom AMI - @climbfuji
    - [x] Docker container Ubuntu 20.04 gnu+openmpi - @climbfuji, @mer-a-o 
    - [x] Docker container Ubuntu 20.04 clang+mpich - @climbfuji,@mer-a-o 
    - [x] Docker container Ubuntu 20.04 intel+impi - @climbfuji,@mer-a-o 
    - [x] Hera with Intel - @Hang-Lei-NOAA 
    - [x] Hera with GNU - @Hang-Lei-NOAA 
- [x] Install spack-stack-1.1.0 in existing spack-stack-v1 locations using template `hpc-stack-dev` on the following systems:
    - [x] Hera with Intel - @climbfuji 
    - [x] Hera with GNU - @climbfuji 
- [x] Create tag `spack-stack-1.1.0` in spack (to avoid collisions with the official spack releases), and simply `1.1.0` in spack-stack (a departure from the previous naming schemes) - @climbfuji 
    - [x] After creating tag `spack-stack-1.1.0` in spack, update container recipes and `.gitmodules` in spack-stack before creating final `1.1.0` tag there

**Comment by RussTreadon-NOAA** [comment]
@Hang-Lei-NOAA , any updates on the installation of `spack-stack/1.1.0`?     It seems `spack-stack` is the path through which `bufr/11.7.1` (see [hpc-stack #489](https://github.com/NOAA-EMC/hpc-stack/issues/489)) will be installed on Hera.   Will `spack-stack/1.1.0` also be installed on WCOSS2?

**Comment by Hang-Lei-NOAA** [comment]
I have installed a testing version to replace hpc-stack on Hera, before
this release.
Please check it here.
I added an installation for library testing on Hera:  module use
/scratch1/NCEPDEV/global/Hang.Lei/spack-stack/envs/hpc-stack-dev/install/modulefiles

In addition, I have a wcoss2 development, and will be pull to repo now.

**Comment by climbfuji** [comment]
@hanglei-noaa, I would like to install spack-stack with the skylab-2.0.0 template and, once finalized, with the hpc-stack-dev template in the usual shared location on Hera. Or work with you on the installation, just need to coordinate because the EMC folks working on JEDI need that installation. Thanks

**Comment by climbfuji** [comment]
@Hang-Lei-NOAA I found that @kgerheiser installed spack-stack-1.0.0 on hera in `/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1`. I am going to do the same on Hera as I did on the other platforms, namely taking a backup of this directory, then updating the spack-stack and spack branches in `/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1` to `release/1.1.0`, then install template `skylab-2.0.0` with both Intel-2022.0.2 and GNU-9.2.0. I'll share every step of the process here. Afterwards, when the `hpc-stack-dev` template was updated by @AlexanderRichert-NOAA, you should be able to follow exactly those steps but install a separate environment in the same directory tree. The only difference in the commands will be the `--template=...` argument.

**Comment by climbfuji** [comment]
> @Hang-Lei-NOAA I found that @kgerheiser installed spack-stack-1.0.0 on hera in `/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1`. I am going to do the same on Hera as I did on the other platforms, namely taking a backup of this directory, then updating the spack-stack and spack branches in `/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1` to `release/1.1.0`, then install template `skylab-2.0.0` with both Intel-2022.0.2 and GNU-9.2.0. I'll share every step of the process here. Afterwards, when the `hpc-stack-dev` template was updated by @AlexanderRichert-NOAA, you should be able to follow exactly those steps but install a separate environment in the same directory tree. The only difference in the commands will be the `--template=...` argument.

@Hang-Lei-NOAA The sysadmins fixed the filesystem permissions on hera, I am going to install `skylab-2.0.0` in `/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1` now (as `emc.nemspara`)

**Comment by climbfuji** [comment]
@Hang-Lei-NOAA Can you please try to install the updated `hpc-stack-dev` template on Hera using the GNU compilers? These step-by-step instructions should take you right through:
```
# log in as emc.nemspara

cd /scratch1/NCEPDEV/global/spack-stack/spack-stack-v1
module purge
module use /scratch1/NCEPDEV/jcsda/jedipara/spack-stack/modulefiles
module load miniconda/3.9.12
module load ecflow/5.5.3
. setup.sh
spack stack create env --name=hpc-stack-dev-gnu-9.2.0 --site=hera --template=hpc-stack-dev
spack env activate -p envs/hpc-stack-dev-gnu-9.2.0

# Remove the Intel compiler entry from envs/hpc-stack-dev-gnu-9.2.0/site/compilers.yaml
vi envs/hpc-stack-dev-gnu-9.2.0/site/compilers.yaml

# Edit envs/hpc-stack-dev-gnu-9.2.0/site/packages.yaml
# and replace the "active" lines
#    compiler:: [intel@2021.5.0]
#    #compiler:: [gcc@9.2.0]
#    providers:
#      mpi:: [intel-oneapi-mpi@2021.5.1]
#      #mpi:: [openmpi@3.1.4]
# with the commented-out versions (i.e. use gcc@9.2.0, openmpi@3.1.4)
vi envs/hpc-stack-dev-gnu-9.2.0/site/packages.yaml

spack concretize 2>&1 | tee log.concretize.hpc-stack-dev-gnu-9.2.0
spack install --no-checksum --verbose 2>&1 | tee log.install.hpc-stack-dev-gnu-9.2.0
spack module lmod refresh
spack stack setup-meta-modules
```
Please let me know how it goes. Thanks!

**Comment by Hang-Lei-NOAA** [comment]
Hi, Dom,
No problem.
I will install the hpc-stack-dev from the repo. There are several versions
(7 versions) that have not been included in spack, but tested in my running
copy.  I will add them too.

**Comment by climbfuji** [comment]
Can you please just try to install the template as-is first? Once we know that works we can tick the release as done and add more stuff later.

**Comment by Hang-Lei-NOAA** [comment]
Okay

**Comment by Hang-Lei-NOAA** [comment]
@Dominikus Heinzeller - NOAA Affiliate ***@***.***> I
have access limitation on access /scratch1/NCEPDEV/global/spack-stack. It
is only open for emc.nemspara account.

**Comment by climbfuji** [comment]
Then let me try to install it instead for now

**Comment by climbfuji** [comment]
@Hang-Lei-NOAA I finished the hpc-stack-dev gnu install on hera. The only thing that was missing in my notes for you was to replace `%intel` in the hpc-stack-dev template with `%gnu`.

**Comment by Hang-Lei-NOAA** [comment]
@Dominikus Heinzeller - NOAA Affiliate ***@***.***> Thanks, I
will be given access tomorrow.

**Comment by climbfuji** [comment]
spack-stack-1.1.0 released on October 6, 2022!

**Comment by Hang-Lei-NOAA** [comment]
@Dominikus Heinzeller - NOAA Affiliate ***@***.***> Okay,
let's coordinate it.

**Comment by Hang-Lei-NOAA** [comment]
Yes, install needs to happen as emc.nemspara
