### ISSUE TITLE
HDF5 1.10.6 Fortran modules are installed in subdirectories of "include"

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#34]
For `hdf5@1.10.6 +fortran +shared`, identical sets of Fortran modules are installed in subdirectories `shared` and `static` of the `include` directory. These are not found by cmake and they are also not part of the default `CPATH` in the lua module files.

Upgrading to hdf5@1.12.1 fixes the problem.

Since there are other good reasons for using version 1.12.1 (better performance as noted recently by @edwardhartnett), and since the default version in the existing jedi-stack is 1.12.0, this upgrade is not a problem from the JEDI side.

The ufs-weather-model currently uses 1.10.6 (https://github.com/ufs-community/ufs-weather-model/blob/develop/modulefiles/ufs_common). @kgerheiser @edwardhartnett do you think we can update to 1.12.1 for the UFS?

**Comment by kgerheiser** [comment]
I don't see why this would be a problem. We've tested with 1.12.x. From a user perspective there is no difference.

**Comment by edwardhartnett** [comment]
Yes, I think that HDF5-1.12.1 should be used, but netcdf-c should also be upgraded to the next version.

Note that a new version of netcdf-c and netcdf-fortran will be released in the next few weeks. We will want to upgrade to that immediately after it comes out.
