### ISSUE TITLE
Upcoming library updates for ufs-weather-model changes

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#344]
**Please describe the package or library you would like to add to spack-stack.**
See https://github.com/ufs-community/ufs-weather-model/pull/1425:
1. Update `g2tmpl` from `1.10.0` to `1.10.2`
2. The `ufs-weather-model` removes `yafyaml` as a dependency, but we need to keep it for GEOS
3. Update `esmf` to `8.3.1`
3. Update `mapl` to `2.23.1`
4. Update `hdf5` to `1.12.2`
6. Update `netcdf-c` tp `4.9.0` (and use latest `netcdf-fortran`)
7. **To check**: update `fms` to `2022.03`

**What applications will be using this package or library?**
ufs-weather-model, geos?

**Is there already a package or library in spack-stack that provides this, or related, functionality?**
n/a

**Additional context**
n/a

**Will This Package be Needed in a NOAA Operational Application?**
Yes

**WCOSS System Software Request Checklist**
All packages already approved

**Comment by mathomp4** [comment]
@climbfuji yaFyaml will definitely not be dropped from GEOS. MAPL3 will be primarily YAML-based, so it will be a requirement. 

At the moment, MAPL-in-UFS can get away with not needing it as our YAML needs for, say, GOCART are not required and [a PR was made for that](https://github.com/GEOS-ESM/GOCART/pull/187) recently. 

(Side note: I should get all of Tom's GFE packages into spack-stack; I'll work on a PR soon. I'll want to figure out first how to test with spack-stack on discover. → ETA: Well, I made a [WIP PR here](https://github.com/NOAA-EMC/spack/pull/174) just so I don't forget!)

**Comment by climbfuji** [comment]
> @climbfuji yaFyaml will definitely not be dropped from GEOS. MAPL3 will be primarily YAML-based, so it will be a requirement.
> 
> At the moment, MAPL-in-UFS can get away with not needing it as our YAML needs for, say, GOCART are not required and [a PR was made for that](https://github.com/GEOS-ESM/GOCART/pull/187) recently.
> 
> (Side note: I should get all of Tom's GFE packages into spack-stack; I'll work on a PR soon. I'll want to figure out first how to test with spack-stack on discover. → ETA: Well, I made a [WIP PR here](https://github.com/NOAA-EMC/spack/pull/174) just so I don't forget!)

Thanks for letting me know, @mathomp4 - I'll update the issue description accordingly.

**Comment by climbfuji** [comment]
The versions in this issue are out of date already ... need latest versions.

**Comment by climbfuji** [comment]
We have addressed all of these, except esmf and mapl for which we have a separate issue #333 (with the newest versions requested).
