### ISSUE TITLE
JEDI needs ecmwf-atlas 0.30.0

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#349]
**Please describe the package or library you would like to add to spack-stack.**
- Add ecmwf-atlas 0.30.0 to spack fork/branch
- Update config in spack-stack

**What applications will be using this package or library?**
JEDI core and in-kinds

**Is there already a package or library in spack-stack that provides this, or related, functionality?**
ecmwf-atlas up to 0.29.0 is already in spack/spack-stack

**Additional context**
@benjaminmenetrier @svahl991 Are there any new `cmake` options that need to be added for 0.30.0? See https://github.com/NOAA-EMC/spack/blob/jcsda_emc_spack_stack/var/spack/repos/jcsda-emc/packages/ecmwf-atlas/package.py for what is currently there.

**Will This Package be Needed in a NOAA Operational Application?**
Yes

**WCOSS System Software Request Checklist**
ecmwf-atlas already on the approval list

**Comment by benjaminmenetrier** [comment]
It is not clear to me: is the `trans` option enabled? `fiat` and `ectrans` libraries are required for that.

**Comment by climbfuji** [comment]
> It is not clear to me: is the `trans` option enabled? `fiat` and `ectrans` libraries are required for that.

Yes, they are. Example: https://github.com/NOAA-EMC/spack-stack/blob/f98887a052d96b20a3696b6ed2ee399d80d00af9/configs/common/packages.yaml#L51
