### ISSUE TITLE
Update hpc-stack-dev template to match current UFS libraries

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#358]
**Is your feature request related to a problem? Please describe.**
The hpc-stack-dev template is supposed to mirror the current library versions used in the various UFS application / in `hpc-stack`.

**Describe the solution you'd like**
We need this file to be updated, ideally before creating the spack-stack@1.1.0 release tag end of this week (Sep 30).

**Additional context**
n/a

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA @Hang-Lei-NOAA Any progress/update on this issue? Thanks ...

**Comment by Hang-Lei-NOAA** [comment]
I have a full set changes running fine on wcoss2, but has problems to commit it to spack-repo on all steps. Just try to find what the problems would be.

**Comment by climbfuji** [comment]
Closed via https://github.com/NOAA-EMC/spack-stack/pull/368
