### ISSUE TITLE
Make spack-stack working on wcoss2

### ISSUE THREAD

**Issue by Hang-Lei-NOAA** [JCSDA/spack-stack#359]
**Is your feature request related to a problem? Please describe.**
Current spack-stack settings on wcoss2 does not work.

**Describe the solution you'd like**
The problem was diagnosed in last week, and missing gnu features have been added into the compiler setting.

**Additional context**
The solution is found

**Comment by climbfuji** [comment]
@Hang-Lei-NOAA Can this also be closed?

**Comment by climbfuji** [comment]
Closing. If this is still a problem, please open a new issue and provide more information on what is not working.
