### ISSUE TITLE
UFS-WM develop template/spack.yaml question

### ISSUE THREAD

**Issue by ulmononian** [JCSDA/spack-stack#361]
**Is your feature request related to a problem? Please describe.**
Should there be a spack.yaml/template for the ufs-wm develop branch, or is that purpose supposed to be served by this https://github.com/NOAA-EMC/spack-stack/tree/develop/configs/templates/ufs-weather-model?

**Describe the solution you'd like**
A spack.yaml with specs like this https://github.com/ulmononian/spack-stack/blob/develop/configs/templates/ufs-wm-dev/spack.yaml would be consistent with how the srw-dev and srw-public-v2 templates are set-up.

**Comment by climbfuji** [comment]
I think that the hpc-stack-dev template is supposed to do that.

**Comment by ulmononian** [comment]
@climbfuji ok -- that makes sense. it was my understanding that @kgerheiser developed that to mimic the hpc-stack for ufs-wm regression test result validation. the hpc-stack-dev template is just a bit cumbersome, so it might be nice to have a simpler version where users can just get up and running with the most basic modules called for by https://github.com/ufs-community/ufs-weather-model/blob/develop/modulefiles/ufs_common.lua. 

my proposed spack.yaml is very simple (linked in my original post), and i think could be used across various platforms (on-prem, cloud, containers) in the near-term to ensure the wm compiles and can run (basic RTs) as the transition to spack happens. however, this is just a thought and i completely understand if it does not seem pertinent or useful.

**Comment by climbfuji** [comment]
That's fine and a reasonable approach, except for the systems where we want to have a shared environment that supports building *all* UFS and *all* JEDI applications, or if that is not possible two environments, one for *all* UFS and *all* JEDI applications.

**Comment by climbfuji** [comment]
I am closing this issue as completed, because a lot of work has gone into the ufs-weather-model template recently to be able to replicate the current hpc-stack environment as closely as possible.
