### ISSUE TITLE
HDF5 1.10.6 version issues

### ISSUE THREAD

**Issue by rhoneyager** [JCSDA/spack-stack#37]
For the jedi-fv3 environment, the stack installs HDF5 version 1.10.6, but ioda requires HDF5 1.12.0 or greater to run successfully (v1.12.1 preferred).

HDF5 1.12.0 refactored several functions related to chunking and dataspace selections that greatly improved performance when reading and writing large files. IODA also uses several of the new APIs in a few parts of the code (and should error out in ctest when these functions are not available).

https://www.hdfgroup.org/2020/03/release-of-hdf5-1-12-0-newsletter-172/

**Comment by climbfuji** [comment]
This issue is similar to #34 in which we decided to upgrade to 1.12.1.
