### ISSUE TITLE
Port spack-stack to Casper

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#381]
**Is your feature request related to a problem? Please describe.**
Support for Casper is needed for the JCSDA data ingest tasks.

**Describe the solution you'd like**
The stack is working on Cheyenne, it should be relatively easy to get it over to Casper.

**Additional context**
n/a

**Comment by BenjaminRuston** [comment]
happy to close this if you wish @climbfuji

**Comment by climbfuji** [comment]
> happy to close this if you wish @climbfuji

I made up my mind, going to install spack-stack there. It would be helpful if I only had to maintain one installation on casper, either intel or gnu. Any preference @BenjaminRuston ?
