### ISSUE TITLE
jedi-bundle on Mac Intel (x86_64) architecture has persistent ctest failures

### ISSUE THREAD

**Issue by srherbener** [JCSDA/spack-stack#384]
**Describe the bug**

When building spack-stack version 1.1.0 on a Mac using the Intel (x86_64) architecture, then following with building jedi-bundle, the result of `ctest` is that the following 7 test fail:
```
The following tests FAILED:
	 14 - test_util_signal_trap (Failed)
	237 - test_qg_4densvar (Failed)
	238 - test_qg_4densvar_hybrid (Failed)
	912 - ufo_test_tier1_test_ufo_opr_gnssrorefmetoffice (Failed)
	916 - ufo_test_tier1_test_ufo_opr_gnssrobendmetoffice_nopseudo (Failed)
	924 - ufo_test_tier1_test_ufo_opr_groundgnssmetoffice (Failed)
	970 - ufo_test_tier1_test_ufo_opr_scatwind_neutral_metoffice (Failed)
Errors while running CTest
```

These failures are primarily due to issues with signal trapping and exception handling.

These tests have also been failing consistently on the Mac Intel platform for several months. These tests consistently pass on all other platforms. We are getting a bit complacent with ignoring these so I thought it would be good to start tracking them and get them resolved.

**To Reproduce**

Use the following pieces
- MacOS Monterey
- spack-stack 1.1.0
- jedi-bundle, develop branches

Build jedi-bundle and run ctest.

**Expected behavior**

All ctests pass. No issues with signal trapping and exception handling.

**System:**

MacOS Monterey

**Additional context**

**Comment by climbfuji** [comment]
Should this issue be moved to the jedi-bundle repository?

**Comment by srherbener** [comment]
Maybe so. I wasn't sure where to place it. I saw INFRA-2 as maybe the best fit for the Epic and then I put it here in spack-stack.

I'm perfectly fine moving it to jedi-bundle. Is there a different Epic it should be connected to as well?

Thanks!

**Comment by climbfuji** [comment]
I think INFRA-2 is good. Unfortunately, I can't transfer the issue from one organization to another.

**Comment by srherbener** [comment]
It won't let me transfer it either. I'll make a duplicate in jedi-bundle and then close this one.

**Comment by srherbener** [comment]
Closing this issue since I've duplicated in jedi-bundle (jcsda-internal/jedi-bundle/issues/19)
