### ISSUE TITLE
Enable read-only S3 access in HDF5

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#388]
**Is your feature request related to a problem? Please describe.**
From @rhoneyager:
> HDF5 supports a "Read-Only S3 virtual file driver" (ros3). This driver allows access of data in S3 objects without having to download entire files. It would be interesting to see how this performs. Apparently the HDF5 developers argue that this feature is competitive performance-wise with Zarr. I made a [draft PR in ioda](https://github.com/JCSDA-internal/ioda/pull/524) that could make use of this, but have no testing environment.
> Could we add ```--enable-ros3-vfd``` to the options for the containers? No need for the HPCs.

**Describe the solution you'd like**
1. Add ```--enable-ros3-vfd``` to HDF5 build options, create variant if not already existent.
2. Build spack-stack with the new ros3 variant everywhere (if possible).

**Additional context**
n/a

**Comment by symoore90** [comment]
What is the status of this issue?

**Comment by climbfuji** [comment]
This is not a priority, maybe not needed at all. Closing for now.
