### ISSUE TITLE
Add license/copyright information

### ISSUE THREAD

**Issue by kgerheiser** [JCSDA/spack-stack#39]
As @aerorahul pointed out, this repo should have a license and copyright information.

* Add LGPL license
* Add copyright information in files

**Comment by climbfuji** [comment]
At UCAR or NCAR we often use Apache 2, but I am pretty sure NOAA must use LGPL.

We also need a disclaimer at the end of `README.md`.

**Comment by kgerheiser** [comment]
Fixed with #42 and #41
