### ISSUE TITLE
do we support pthread library?

### ISSUE THREAD

**Issue by edwardhartnett** [JCSDA/spack-stack#393]
I am making NCEPLIBS-g2c threadsafe, using the POSIX standard pthread library.

Is this library supported on our systems via spack-stack? Or is this a system-level library that we can expect to already find on the machine? I don't know...

This will not matter until we release NCEPLIBS-g2c-2.0.0, which is some time away. But pthread is coming...

**Comment by Hang-Lei-NOAA** [comment]
Any third party library need to pass the security review, which is a tough process.

**Comment by climbfuji** [comment]
`pthreads` is a system library that spack doesn't build, in that sense you won't have to worry about getting it onto WCOSS2 or it being supported on a particular system or not. I think this issue can be closed.
