### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by kgerheiser** [JCSDA/spack-stack#4]
Create documentation

Some ideas:

### Quickstart
* source setup.sh
* create_env.py
* supported platforms
### Setting up on a new system
* Finding compiler/modules
* Finding common external packages
	* spack external find
		
* Spack Mirrors/Caches
* Manually Configuring Compilers/versions

### Workflow
* Installing a new package/version
* Uninstalling packages
* Modules

**Comment by climbfuji** [comment]
Nearly done! Next week I'll have the PR ready.

**Comment by climbfuji** [comment]
Progress towards this was made in https://github.com/NOAA-EMC/spack-stack/pull/148 - once it's finalized for the first release, we can close this issue.

**Comment by climbfuji** [comment]
Closed via https://github.com/NOAA-EMC/spack-stack/pull/233
