### ISSUE TITLE
Acorn config needs cray-mpich

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#411]
**Is your feature request related to a problem? Please describe.**
For Acorn/WCOSS2, cray-mpich is not currently included in the site config. For moving to operations, it will be necessary to use it.

**Describe the solution you'd like**
Add cray-mpich to Acorn site config as an external package (using ~wrappers flag, as spack's guess as to craype's directory structure is incorrect).

**Comment by Hang-Lei-NOAA** [comment]
@AlexanderRichert-NOAA I have a build on acorn for wcoss2, please refer to:
/lfs/h1/emc/nceplibs/noscrub/Hang.Lei/spack-stack/configs/sites/acorn/

**Comment by AlexanderRichert-NOAA** [comment]
@Hang-Lei-NOAA Is this configuration able to successfully build, let's say, HDF5 with intel & cray wrappers & cray-mpich?

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA Was this fixed in https://github.com/NOAA-EMC/spack-stack/pull/428?

**Comment by AlexanderRichert-NOAA** [comment]
> @AlexanderRichert-NOAA Was this fixed in #428?

Yep
