### ISSUE TITLE
CMake's FindMPI.cmake cannot find cray-mpich with intel compiler on Acorn

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#412]
**Describe the bug**
Because of the Cray PE's quirky and ever-evolving nature, CMake's FindMPI.cmake is unable to find MPI on Acorn when using PrgEnv-intel, meaning that any package with "find_library(MPI)" will fail. There seems to be a nesting doll of issues, including that $PE_ENV env variable is not the expected value (FindMPI.cmake expects "CRAY" while actual value when using PrgEnv-intel is "INTEL"), but changing the value of $PE_ENV only leads to a different error. As far as I can tell, using cray compiler+cray wrappers works correctly, at least as tested with hdf5.

**To Reproduce**
Steps to reproduce the behavior on Acorn:
 - add cray-mpich to external packages in acorn site config (see issue #411)
 - create & activate empty environment with acorn site config
 - install, e.g., hdf5 with **intel compiler** and mpi support

Error output:
```
CMake Error at /lfs/h1/emc/nceplibs/noscrub/alexander.richert/spack-stack/envs/ajwr/install/intel/19.1.3.304/cmake-3.23.1-le6x3ry/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find MPI (missing: MPI_C_FOUND)
Call Stack (most recent call first):
  /lfs/h1/emc/nceplibs/noscrub/alexander.richert/spack-stack/envs/ajwr/install/intel/19.1.3.304/cmake-3.23.1-le6x3ry/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /lfs/h1/emc/nceplibs/noscrub/alexander.richert/spack-stack/envs/ajwr/install/intel/19.1.3.304/cmake-3.23.1-le6x3ry/share/cmake-3.23/Modules/FindMPI.cmake:1830 (find_package_handle_standard_args)
  CMakeLists.txt:712 (find_package)
```

**Expected behavior**: Packages using "find_library(MPI)" should build successfully.

**System:** Acorn

**Comment by AlexanderRichert-NOAA** [comment]
Turns out to be related to spack's cray-mpich package. Modifying cray-mpich/package.py to use cc/CC/ftn (which it for some reason doesn't accommodate right now) does the trick. FindMPI.cmake appears to behave correctly. I'll check with the spack devs, but most likely the change needed will be a new variant for cray-mpich to allow it to use the craype "generic" wrapper names.

**Comment by climbfuji** [comment]
I came across something similar for another package (don’t remember). We can’t simply revert to cc/CC/ftn, because newer cray systems use mpicc et al. There is a variant wrappers for cray-mpich that needs to be turned on or off, see configs/sites/narwhal/packages.yaml

**Comment by AlexanderRichert-NOAA** [comment]
Turns out ~wrappers wasn't helping me because I had broken my configuration in a different way (:

**Comment by AlexanderRichert-NOAA** [comment]
For future reference, the following compiler configuration appears to do the trick, on top of cray-mpich~wrappers:
```compilers:
- compiler:
    spec: intel@19.1.3.304
    paths:
      cc: /opt/cray/pe/craype/2.7.13/bin/cc
      cxx: /opt/cray/pe/craype/2.7.13/bin/CC
      f77: /opt/cray/pe/craype/2.7.13/bin/ftn
      fc: /opt/cray/pe/craype/2.7.13/bin/ftn
    flags: {}
    operating_system: sles15
    target: any
    modules:
    - craype-x86-rome
    - libfabric
    - craype-network-ofi
    - envvar
    - PrgEnv-intel
    - intel/19.1.3.304
    - craype/2.7.13
    - cray-mpich/8.1.9
    environment:
      set:
        # OpenSUSE on WCOSS2 machines sets CONFIG_SITE so 
        # Automake-based builds are installed in lib64 
        # which confuses some packages.
        CONFIG_SITE: ''
    extra_rpaths: []
```
