### ISSUE TITLE
Always use `spack install --verbose`

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#417]
**Is your feature request related to a problem? Please describe.**
Turns out that I (try to, unless I forget) install every spack environment with the options `--source` (install source code with package, needed for debugging) and `--verbose` (convenient to look at logs).

But I do forget this every so often, mostly when an installation fails halfway, I fix something and then restart in between. This creates inconsistent environments, where some packages have the source code, some don't.

**Describe the solution you'd like**
It would be good to **always** use this options as default. I tried changing the defaults in `spack/lib/...` but this led to so many unit test failures for spack that it wasn't feasible. I am wondering if we should create a spack command extension such as `spack stack install ...` that basically translates into `spack install --verbose --source ...`

Other ideas? If at all possible, I want to get this into the current release `spack-stack@1.2.0`.

**Update 2023/05/04**

We decided to not use `--source`

**Additional context**
n/a

**Comment by AlexanderRichert-NOAA** [comment]
@climbfuji Any interest in adding --fail-fast as well? I could go either way, but I'd lean toward adding it as it's especially useful in a CI context.

**Comment by climbfuji** [comment]
I am undecided about fail-fast (actually voted against it in the slack poll), but no strong preference. We can add it.

**Comment by ulmononian** [comment]
sorry -- i lost track of this! @AlexanderRichert-NOAA are you handling this now? if not, i will try to get something together.

**Comment by climbfuji** [comment]
Note. We discussed with the spack developers that these options should also be controllable in the spack yaml config section (similar to some other options that can be set either as a cmd line argument or in the yaml).

**Comment by AlexanderRichert-NOAA** [comment]
@ulmononian I was thinking of looking at this if I have extra time this week. Have you already looked at how to implement? I'll be more or less starting from scratch.

**Comment by ulmononian** [comment]
@climbfuji good to know -- thank you.

@AlexanderRichert-NOAA i haven't looked into this in any extended detail yet, so i'd also be starting from scratch here. if you want to tackle it, feel free. i forgot it was assigned to me until you commented here, but wanted to express that i would be glad to try and do it now that it is back on my radar lol. no pressure either way here :) your call.

**Comment by AlexanderRichert-NOAA** [comment]
@ulmononian I'll look into it later this week, and if I get horribly lost with it I'll let you know :)

**Comment by climbfuji** [comment]
I think we can try to follow how other options are implemented that can be set through the command line or the spack yaml .

**Comment by ulmononian** [comment]
> @ulmononian I'll look into it later this week, and if I get horribly lost with it I'll let you know :)

sounds good!

@climbfuji "I think we can try to follow how other options are implemented that can be set through the command line or the spack yaml ." --> makes sense to me.

**Comment by climbfuji** [comment]
@ulmononian Any update on this?

**Comment by symoore90** [comment]
What is the status of this issue? @ulmononian

**Comment by climbfuji** [comment]
I don't think this is needed. We've gotten used to running `spack install --verbose` on the HPCs, no need to over-engineer a solution unless @ulmononian already has something ready to go.

**Comment by ulmononian** [comment]
sorry for the dearth of updates, but i never found an elegant way to do this. i'd second what @climbfuji said.

**Comment by climbfuji** [comment]
Let's not do this then.
