### ISSUE TITLE
Add valgrind

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#420]
**Please describe the package or library you would like to add to spack-stack.**
Add valgrind to the base-env, or jedi-base-env. Possibly as an optional component, if it doesn't get approval on FISMA high systems. Use external valgrind if available, recent enough, and works with all compilers, otherwise build from spack. it's already contained in the spack repo, and it builds out of the box for Intel and GNU.

**What applications will be using this package or library?**
JCSDA for sure, I would assume others as well.

**Is there already a package or library in spack-stack that provides this, or related, functionality?**
There are other, thirdparty memory debuggers such as Intel Inspector and Arm Forge DDT, but valgrind is widely known and great for debugging serial applications.

**Additional context**
valgrind can be built with boost support. We can use the existing boost install if we flip one variant (`~atomic` to `+atomic`).

**Will This Package be Needed in a NOAA Operational Application?**
If yes, the WCOSS System Software Checklist must also be completed.

**WCOSS System Software Request Checklist**

@edwardhartnett @aerorahul Is it reasonable to assume that valgrind is approved (already exists?) on WCOSS2?

General questions:

Supervisor or sponsor of the requester

Software name and version, specific URL to the software

Software type - New or Upgrade existing?

Justification ( List NPS models using the software)

Completion Time requested

Software License including all Dependency Software Licenses 

Support contact(s) who must have a WCOSS account

Dependency Software list

Installation instructions

Test and verification instructions

Technical Review Checklist for open source software - Review the source code to answer the following questions

Licenses for the requested software and its dependencies

Licenses -  confirm the software Licenses are acceptable

Maturity

Acceptable - Stable, production, or equivalent

Self-contained

No external http, https,  ftp, or other URI exists except that in comments

No binary files in the package unless they are in the approved list

No publicly disclosed cybersecurity vulnerabilities and exposures 

Searching https://cve.mitre.org/cve/

Security High Level Checklists 

Is it prohibited by DHS/DOC/NOAA/NWS

Is it provided by a trusted source? Trusted sources include other NWS, NOAA, or DOC, agencies, or other Federal agencies that operate at a FISMA high or equivalent level. Additionally, trusted sources could be third-party agencies through which there is an existing SLA on file (such as RedHat). 

Is software support offered (is it being updated and patched). 

If maintained by a private entity, does the entity operate in a foreign country, especially a prohibited foreign country (China, Russia, Iran, North Korea, etc.). 

Is there sufficient documentation to support maintenance 

Are there known vulnerabilities or weaknesses

Is there a need for privileged processes 

Are there software dependencies, are those dependencies approved or do they have any security concerns 

Are there any other concerns related to SA, SI, and SC control families

**Comment by aerorahul** [comment]
@climbfuji 
valgrid is already available on WCOSS2.  However, I don't know if it can be used w/ all compilers or if it was built w/ a specific Intel compiler in mind to support.

**Comment by climbfuji** [comment]
> @climbfuji
> valgrid is already available on WCOSS2. However, I don't know if it can be used w/ all compilers or if it was built w/ a specific Intel compiler in mind to support.

Thanks @aerorahul. If it's already on there, then it should be easier to get approval for another version built with spack-stack should the need arise, I hope. For now, let's just use the existing valgrind as an external package.

**Comment by climbfuji** [comment]
Closing this as not planned due to a lack of activity
