### ISSUE TITLE
Confusion with python version for mac build

### ISSUE THREAD

**Issue by srherbener** [JCSDA/spack-stack#432]
**Describe the bug**

I tried building using the latest (as of yesterday) spack-stack, spack repos on my MacBook. The stack got built successfully and a subsequent build of jedi-bundle worked, but the ioda python API was broken because of finding a python in `/usr/local/bin` instead of in the stack.

I discovered that python 3.10.8 was built as part of the stack,  but there was not a lua module built for python/3.10.8 due to python being listed in the tcl/lua module blacklists in the common/module.yaml file.

**To Reproduce**

Build spack-stack using the environment created by: `spack stack create env --site macos.default --template skylab-dev --name skylab.mymacos`

Then clone and build jedi-bundle, and run `ctest`.

**Expected behavior**

All ioda tests pass.

**System:**

MacOS, Ventura 13.1, command line tools version 14.2.

**Additional context**

Is the intention now for python to always be part of the stack. If so, then should we remove python from the module blacklists?

**Comment by climbfuji** [comment]
> **Describe the bug**
> 
> I tried building using the latest (as of yesterday) spack-stack, spack repos on my MacBook. The stack got built successfully and a subsequent build of jedi-bundle worked, but the ioda python API was broken because of finding a python in `/usr/local/bin` instead of in the stack.
> 
> I discovered that python 3.10.8 was built as part of the stack, but there was not a lua module built for python/3.10.8 due to python being listed in the tcl/lua module blacklists in the common/module.yaml file.
> 
> **To Reproduce**
> 
> Build spack-stack using the environment created by: `spack stack create env --site macos.default --template skylab-dev --name skylab.mymacos`
> 
> Then clone and build jedi-bundle, and run `ctest`.
> 
> **Expected behavior**
> 
> All ioda tests pass.
> 
> **System:**
> 
> MacOS, Ventura 13.1, command line tools version 14.2.
> 
> **Additional context**
> 
> Is the intention now for python to always be part of the stack. If so, then should we remove python from the module blacklists?

Yes and no. Since the preconfigured hpc environments still use external python (we can consider changing that), we need to make sure that it stays blacklisted there. Two options: explicitly whitelist in linux.default and macos.default (fewer changes) and leave it form the blacklist in the common config, or remove it from the blacklist in the common config and explicitly whitelist in all site configs.

**Comment by srherbener** [comment]
I think if the HPC situation using external python will persist then it seems to make sense to have the default (common/module.yaml) be to blacklist python (1st option). If we think that eventually we will build python as part of the stack on HPCs, then perhaps the default should be to whitelist python (2nd option).

I'm guessing the situation is that using an external python will persist on HPCs. Do you agree?

**Comment by climbfuji** [comment]
> I think if the HPC situation using external python will persist then it seems to make sense to have the default (common/module.yaml) be to blacklist python (1st option). If we think that eventually we will build python as part of the stack on HPCs, then perhaps the default should be to whitelist python (2nd option).
> 
> I'm guessing the situation is that using an external python will persist on HPCs. Do you agree?

Not necessarily, maybe on specific HPCs. But I think option (1) should be used now. If we get to the point where the majority of HPCs uses spack-built Python, then we can easily make the switch to (2).
