### ISSUE TITLE
spack container build removes `py-pip` as part of the spack cleanup process (`spack gc`) - we need it

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#435]
**Is your feature request related to a problem? Please describe.**

See https://github.com/JCSDA-internal/ewok/issues/545 for a full description. Summary: spack container build removes `py-pip` as part of the spack cleanup process (`spack gc`) - we need to keep it so that `python3 -m pip` works in the containers.

**Describe the solution you'd like**
Keeping `py-pip` should be as easy as adding it to the list of specs that are explicitly requested (https://github.com/NOAA-EMC/spack-stack/blob/develop/configs/containers/README.md)

**Additional context**

**Comment by climbfuji** [comment]
An alternative solution, which I actually prefer, is not to run `spack gc` at all. We somewhat rely on everything that gets build as part of the dependency tree being available as part of the spack environment, since we don't list everything explicitly and we don't run `spack gc` at all.

@AlexanderRichert-NOAA Do you agree?

**Comment by AlexanderRichert-NOAA** [comment]
> An alternative solution, which I actually prefer, is not to run `spack gc` at all. We somewhat rely on everything that gets build as part of the dependency tree being available as part of the spack environment, since we don't list everything explicitly and we don't run `spack gc` at all.
> 
> @AlexanderRichert-NOAA Do you agree?

I can't access the discussion you linked there. Can you elaborate on where/how we're using this? I haven't interacted much with spack container functionality yet...

**Comment by climbfuji** [comment]
Long story short. spack by default runs `spack gc` at the end of the container build to uninstall dependencies that are only used at build time, but not at run time. This also removes `py-pip`. This doesn't make much sense and causes problems, because one convenient and consistent (!) way to use spack with its Python dependencies and at the same time give users the options to install additional Python packages that may not be in spack, is to create a venv as follows:
```
python3 -m venv --system-site-packages --without-pip venv
source venv/bin/activate
```
This then finds and reuses everything that spack has built already, whether it's hdf5/netcdf4 or a Python package. If `spack gc` uninstalls a bunch of Python packages, then you need to create the venv without `--without-pip`, which then installs a different version of pip (and possibly other packages that get removed by `spack gc`).

The reduction of the container size from `spack gc` is so small, compared to the size of the containers, that it really doesn't make sense.

**Comment by mathomp4** [comment]
@climbfuji It's a "hack" solution, but what if you did:

```python
    depends_on('py-pip',           type=('build', 'run'))
```
in some package you control? 

I mean, it's not "right" in sense that it's not needed at run time, but, well, it might cause `spack gc` to not nuke it?

**Comment by climbfuji** [comment]
Correct, this is not "right" and we shouldn't do it.

It's also a lot simpler to add `py-pip` to the list of specs requested explicitly, or - and I prefer that - to simply not run `spack gc` in the container recipes, because the same thing may happen with other packages. We don't use `spack gc` on any of our other systems, and therefore somewhat rely on the build-only dependencies being there.
