### ISSUE TITLE
eckit really doesn't build with cmake 3.20.x

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#44]
Earlier on we removed a guard in the eckit `package.py` that required cmake-3.19 for building because of problems with 3.20.x. It turns out that there is indeed a problem with 3.20.x that manifests itself in dubious build errors (in the compile phase, not the cmake phase). But - it works with 3.22.x.

So we should put that guard back in but exclude 3.20.x and possibly 3.21.x (to be tested). And then aboid using any existing cmake 3.20.x as external package and choose a newer one, if possible. Otherwise the eckit build will trigger the build of a newer cmake.

**Comment by kgerheiser** [comment]
That sounds like a good plan. Would be nice if CMake 3.21 worked.

**Comment by edwardhartnett** [comment]
Who owns eckit? Can we get them to fix their build?

**Comment by climbfuji** [comment]
It only fails to build with 3.20.x - it's fine with 3.19x and 3.22.x, and I will check if it builds with 3.21.x as well. If it's only one version then the authors will have very little interest in spending any time on it. eckit originally came from ECMWF as far as I know.

**Comment by edwardhartnett** [comment]
Certainly a bug report should be filed.

I cannot speak to the interest of the ECMWF programmers, but this is not something that would be tolerated for any of the NCEPLIBS libraries...

**Comment by climbfuji** [comment]
"Fixed" via https://github.com/NOAA-EMC/spack/pull/21
