### ISSUE TITLE
Python 3.10.8 fails to build with Intel compilers

### ISSUE THREAD

**Issue by rjdave** [JCSDA/spack-stack#440]
**Describe the bug**
spack install fails to build with the error (full spack-build-out.txt attached):
```
./Modules/posixmodule.c(5180): error: identifier "HAVE_UTIMENSAT_RUNTIME" is undefined
      if (HAVE_UTIMENSAT_RUNTIME) {
          ^

./Modules/posixmodule.c(5216): error: identifier "HAVE_FUTIMENS_RUNTIME" is undefined
      if (HAVE_FUTIMENS_RUNTIME) {
          ^

./Modules/posixmodule.c(5257): error: identifier "HAVE_UTIMENSAT_RUNTIME" is undefined
      if (HAVE_UTIMENSAT_RUNTIME) {
          ^

./Modules/posixmodule.c(5289): error: identifier "HAVE_UTIMENSAT_RUNTIME" is undefined
      if (HAVE_UTIMENSAT_RUNTIME) {
          ^
```

**To Reproduce**
Run spack install on MacOS Big Sur using the Intel 2022.2.1 (also known as 2021.7.1 by spack) compilers.

**Expected behavior**
Python builds successfully

**System:**
Mid 2014 MacBook Pro running Big Sur using the Intel 2022.2.1 compilers

[spack-build-out.txt](https://github.com/NOAA-EMC/spack-stack/files/10413795/spack-build-out.txt)

**Comment by climbfuji** [comment]
This https://github.com/microsoft/vcpkg/issues/23517 might be helpful to come up with a patch. I haven't looked at your full spack-build-out.txt yet, though.

**Comment by climbfuji** [comment]
I am going to close this issue, because:
- Python builds with Intel on Ubuntu (part of our CI tests, see https://github.com/NOAA-EMC/spack-stack/actions/runs/4602177101/jobs/8130868168 for example)
- We do not support Intel on macOS, because Intel has stopped supporting macOS with the move to the LLVM-based compilers.
