### ISSUE TITLE
CI failures/curl

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#441]
CI runs are failing with undefined reference errors for curl. See, for example, https://github.com/NOAA-EMC/spack-stack/actions/runs/3896652658/jobs/6654131886. I'm working on this, but please let me know if you see possible approaches, as I'm still getting acquainted with the spack-stack CI.

**Comment by climbfuji** [comment]
You can go back in the version history and see how we bounced back and forth between building curl or not. Currently we are looking for external curl on Ubuntu, see https://github.com/NOAA-EMC/spack-stack/blob/8ed32bdb17f667ab8e81d690ab4fb4237b659991/.github/actions/setup-spack-stack/action.yaml#L151. You can also check the documentation for setting up generic Linux systems, there are differences for Red Hat and Ubuntu w.r.t. curl for the same reasons.

**Comment by climbfuji** [comment]
Fixed in #442
