### ISSUE TITLE
Need MET, METPLUS and a Python environment to support Global workflow

### ISSUE THREAD

**Issue by arunchawla-NOAA** [JCSDA/spack-stack#448]
**Please describe the package or library you would like to add to spack-stack.**

Global workflow needs MET v9.1.3 and METplus v3.1.1 installed so they can complete verification tasks. They also need a gfs python virtual environment with the following python packages

- cftime
  - Cython
  - numpy
  - pandas
  - python-dateutil
  - h5py
  - netcdf4
  - PyYAML
  - Jinja2
  - f90nml
  - cartopy
  - matplotlib
 

**What applications will be using this package or library?**

This will be used by GFS developers 

**Is there already a package or library in spack-stack that provides this, or related, functionality?**

I do not know if any of these packages have already been added to spack

**Additional context**
Add any other context or screenshots about the package or library here.

**Will This Package be Needed in a NOAA Operational Application?**

These packages are already approved on WCOSS

**WCOSS System Software Request Checklist**

General questions:

Supervisor or sponsor of the requester

Software name and version, specific URL to the software

Software type - New or Upgrade existing?

Justification ( List NPS models using the software)

Completion Time requested

Software License including all Dependency Software Licenses 

Support contact(s) who must have a WCOSS account

Dependency Software list

Installation instructions

Test and verification instructions

Technical Review Checklist for open source software - Review the source code to answer the following questions

Licenses for the requested software and its dependencies

Licenses -  confirm the software Licenses are acceptable

Maturity

Acceptable - Stable, production, or equivalent

Self-contained

No external http, https,  ftp, or other URI exists except that in comments

No binary files in the package unless they are in the approved list

No publicly disclosed cybersecurity vulnerabilities and exposures 

Searching https://cve.mitre.org/cve/

Security High Level Checklists 

Is it prohibited by DHS/DOC/NOAA/NWS

Is it provided by a trusted source? Trusted sources include other NWS, NOAA, or DOC, agencies, or other Federal agencies that operate at a FISMA high or equivalent level. Additionally, trusted sources could be third-party agencies through which there is an existing SLA on file (such as RedHat). 

Is software support offered (is it being updated and patched). 

If maintained by a private entity, does the entity operate in a foreign country, especially a prohibited foreign country (China, Russia, Iran, North Korea, etc.). 

Is there sufficient documentation to support maintenance 

Are there known vulnerabilities or weaknesses

Is there a need for privileged processes 

Are there software dependencies, are those dependencies approved or do they have any security concerns 

Are there any other concerns related to SA, SI, and SC control families

**Comment by climbfuji** [comment]
@arunchawla-NOAA All of these packages exist in spack-stack, and we also have a global workflow environment/template. We'll need to check if that environment contains everything in your list, and if the versions match.

**Comment by arunchawla-NOAA** [comment]
@WalterKolczynski-NOAA @KateFriedman-NOAA and @aerorahul 

Can we move to using spack stack for global workflow ? Do you see any roadblocks there?

**Comment by WalterKolczynski-NOAA** [comment]
That's the goal. We need to know where the installations are on each machine though. Other issue is making sure everything is installed under both Intel 18 and Intel 22.
