### ISSUE TITLE
Add compiler/package matrix for Acorn config

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#450]
I want to try adding gcc as a compiler for Acorn, then add a compiler/package matrix as in https://github.com/NOAA-EMC/spack-stack/blob/develop/configs/templates/hpc-stack-dev/spack.yaml. Consider doing this with multiple versions, at least for the sake of testing.

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA I believe this work is complete?

**Comment by AlexanderRichert-NOAA** [comment]
This may be moot given the unified env now. @Hang-Lei-NOAA do you see any use for having the ufs-weather-model-static template install gcc in addition to intel? Depending on that, I'll probably mark this as closed once I've got the unified stack fully built on Acorn (which will fully test the gcc compiler).

**Comment by Hang-Lei-NOAA** [comment]
This can be closed. We have built all libs on acorn.

**Comment by climbfuji** [comment]
Thanks!
