### ISSUE TITLE
srw-app templates are missing gsi-ncdiag

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#451]
**Describe the bug**
I built the srw-app env on Cheyenne and noticed that in order to build the entire srw-app, the `gsi-ncdiag` package is missing in both templates:
https://github.com/NOAA-EMC/spack-stack/blob/develop/configs/templates/ufs-srw-public-v2/spack.yaml
https://github.com/NOAA-EMC/spack-stack/blob/develop/configs/templates/ufs-srw-dev/spack.yaml

**To Reproduce**
See above

**Expected behavior**
The templates contain everything needed to build the entire ufs-srw-app code

**System:**
Cheyenne/Intel

**Additional context**
n/a

**Comment by ulmononian** [comment]
thanks for pointing this out. i'll update both of these templates w/ ncdiag@1.0.0. for consistency when i test the updated env. install: i assume you ran something like `./devbuild.sh --platform=cheyenne gsi` to do the srw install with gsi turned on and it failed somewhere along the line in the gsi build?

**Comment by ulmononian** [comment]
actually wondering if we should update the ufs-srw-public-v2 template to v2.1.0 given the latest release branch of the srw is 2.1.0 (https://github.com/ufs-community/ufs-srweather-app/releases/tag/ufs-srw-v2.1.0)? not sure the best way to handle env. template naming/updating for minor releases. it seems like it would prove too cumbersome/clunky to have a template for every minor release...

**Comment by ulmononian** [comment]
@climbfuji i added gsi-ncdiag@1.0.0 (w/ a projection to "ncdiag") to our srw-dev intel env. on cheyenne here:  /glade/work/epicufsrt/spack-stack/envs/srw-develop-intel. i'll run a test of the srw build w/ gsi in the morning.

**Comment by climbfuji** [comment]
> thanks for pointing this out. i'll update both of these templates w/ ncdiag@1.0.0. for consistency when i test the updated env. install: i assume you ran something like `./devbuild.sh --platform=cheyenne gsi` to do the srw install with gsi turned on and it failed somewhere along the line in the gsi build?

I ran `./devbuild.sh --platform=cheyenne` without any arguments, i.e. I assume it was building everything that comes with the srw app.

**Comment by ulmononian** [comment]
> > thanks for pointing this out. i'll update both of these templates w/ ncdiag@1.0.0. for consistency when i test the updated env. install: i assume you ran something like `./devbuild.sh --platform=cheyenne gsi` to do the srw install with gsi turned on and it failed somewhere along the line in the gsi build?
> 
> I ran `./devbuild.sh --platform=cheyenne` without any arguments, i.e. I assume it was building everything that comes with the srw app.

interesting. i never had any failures doing that build method, but then never really checked what was going on with gsi. the only gsi error i usually hit (and i think has been fixed) is the auto-checkout of gsi external for the gerrit fix files (which have been migrated to an ncep ftp server i believe). maybe that was just in the global workflow, though. 

did you have an explicit gsi build failure?

**Comment by climbfuji** [comment]
Closed via #452
