### ISSUE TITLE
Build unified environment on Parallelworks AWS, GCP, Azure

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#457]
**Is your feature request related to a problem? Please describe.**
The new unified environment needs to be built and tested on NOAA Parallellworks.

**Describe the solution you'd like**
Build new unified environment on Parallelworks and update instructions in spack-stack accordingly. Share instructions with NOAA (EMC, EPIC) collaborators.

**Additional context**
Need to do for each of the providers:
- [x] AWS
- [x] GCP
- [x] Azure

Uses/requires #454, but testing and documentation update can happen in parallel.

**Comment by climbfuji** [comment]
@mark-a-potts @ulmononian I think this work is done, correct?

**Comment by mark-a-potts** [comment]
The UE (circa two weeks ago) is installed on all three providers. I can update with any changes since then today or tomorrow.

**Comment by climbfuji** [comment]
Awesome, thanks @mark-a-potts !
