### ISSUE TITLE
remove wgrib2 from spack-stack

### ISSUE THREAD

**Issue by edwardhartnett** [JCSDA/spack-stack#458]
wgrib2 has caused a lot of build problems. At the EMC we are deprecating its use in our systems and software.

We would like to remove it from spack-stack so that our users don't have it available to build into new systems.

@climbfuji any impact on you with this idea?

**Comment by climbfuji** [comment]
Removing wgrib2? I'd be celebrating, that would be the impact :-)

**Comment by edwardhartnett** [comment]
This issue was suggested by @arunchawla-NOAA .

Let's remove wgrib2 before the next release.

**Comment by climbfuji** [comment]
@aerorahul Should we close this if removing wgrib2 is not realistic to happen anytime soon?

**Comment by edwardhartnett** [comment]
Let us bump it to a future release, or just leave it on the backlog, as an aspiration.

**Comment by climbfuji** [comment]
Ok!

**Comment by symoore90** [comment]
When you get the time can you move this into the Icebox for the AOP23 release workspace. @climbfuji

**Comment by climbfuji** [comment]
@aerorahul What do you think is a realistic timeline for being able to remove wgrib2 from spack-stack? If not in the next year or two, I suggest closing this issue as a non-starter. Thanks!

**Comment by climbfuji** [comment]
Just confirmed with EMC that there are plans to modernize wgrib2, therefore we can expect it to stay around: https://github.com/NOAA-EMC/wgrib2 - closing this as not planned.
