### ISSUE TITLE
ESMF: Use setup_build_environment instead of edit

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#460]
@climbfuji @jedwards4b Do you see any issue with using "setup_build_environment" instead of "edit" in esmf/package.py? As far as I can think, the only difference is that "setup_build_environment" will put the various "ESMF_" variables in the environment when running "spack build-env esmf", which should make it easier to debug etc. Since it's all "os.environ" this and that, I don't expect any other impact.

**Comment by climbfuji** [comment]
Makes sense to me!

**Comment by jedwards4b** [comment]
Sure, works for me.

**Comment by Hang-Lei-NOAA** [comment]
This is not only convenient, but also can help in a series of installation issue. For e.g. installation of esmf/8.4.0 need different settings from installations of esmf/8.3.0bs09. With this, you can easily make changes for each version.

**Comment by climbfuji** [comment]
This change was made in the authoritative repo first (thanks @AlexanderRichert-NOAA), and then brought back to our fork with yesterday's PR #492 (and the associated spack PR).
