### ISSUE TITLE
First round installation failure issue

### ISSUE THREAD

**Issue by Hang-Lei-NOAA** [JCSDA/spack-stack#461]
**Describe the bug**
When we fresh checkout the spack-stack to install some templates, the first round installation usually contains some failures, which may gone in your second round try. This would be problematic for operation use. 

**To Reproduce**
E.g. install the spack-stack on Acorn, using the templates ufs-weather-model-static. crtm; PIO; mapl failed in the first round installations, and recovered in the second round.

**Expected behavior**
Make the spack-stack completely succeed at the first try.

**System:**
What system(s) are you running the code on?
Have found similar issues on several system, Acorn, Hera etc. in the past for different templates.

**Additional context**

**Comment by Hang-Lei-NOAA** [comment]
@arunchawla-NOAA Leading by @edwardhartnett, we are trying to use spack-stack for operations as soon as possible.

**Comment by climbfuji** [comment]
I am not seeing this problem on the systems that I have access to (Orion, Cheyenne, Hera, Gaea, Narwhal, Discover, S4, ...) - is this something specific, e.g. related to acorns internet access (or the lack thereof)? Or the size of the temporary caches?

**Comment by AlexanderRichert-NOAA** [comment]
@Hang-Lei-NOAA can you provide some output from these failures? I've run into random failures on Acorn related to the lustre filesystem when spack checks out git repos during install, but that's it (nothing on hera that I can recall).

**Comment by Hang-Lei-NOAA** [comment]
It could be specific to the setting of packages: crtm, mapl and PIO . At
least, I still found this issue on the template prepared for operational
use:
e.g. ufs-weather-model-static

**Comment by Hang-Lei-NOAA** [comment]
@Alexander Richert - NOAA Affiliate ***@***.***>  Since the
formal installation has been covered by the second round installation. I
reproduced the first round issue on Acorn. Please have a look into these
files. I hope we can solve these issues.

***@***.***:~> ls
noscrub/spack-stack/envs/ufs-weather-model-static/install/.spack-db/failures/
esmf-6mqmpnph4grm4fze6kogxa2ph5etjw7a
 mapl-6htewldnqc2ycgm6bbloclxlqxxtluru
 parallelio-slqm7uva3rih6lrcf5rqo4tzcjtxsjft

**Comment by climbfuji** [comment]
I currently don't have access to acorn or wcoss2 (I had it and lost it when the switch to VPN + tectia was made). Working on regaining access.

**Comment by AlexanderRichert-NOAA** [comment]
@Hang-Lei-NOAA Can you give me the absolute path for that directory?

**Comment by Hang-Lei-NOAA** [comment]
Sorry, I did not noticed the path is not complete.
It
is /lfs/h1/emc/nceplibs/noscrub/Hang.Lei/spack-stack/envs/ufs-weather-model-static/install/.spack-db/failures/

**Comment by AlexanderRichert-NOAA** [comment]
I'm still not clear on where/how these packages are failing. Again the only thing I've encountered is "PermissionDenied" errors when packages get pulled from git repos, which is a lustre problem, not a spack problem. I can look into setting up a source cache on acorn.

**Comment by Hang-Lei-NOAA** [comment]
Yes, it is gone when you install it the second time. We have to solve it
before communicating with NCO. ESMF and netcdf used to have the similar
issue, but not in this version. Therefore, I think it could be solved.

**Comment by climbfuji** [comment]
@Hang-Lei-NOAA Is this still an issue or can this be closed?

**Comment by Hang-Lei-NOAA** [comment]
It can be closed. I think that I have found out what the problem is.

**Comment by climbfuji** [comment]
Thanks!
