### ISSUE TITLE
Build spack-stack on standard NCEP/EMC Linux workstations

### ISSUE THREAD

**Issue by aerorahul** [JCSDA/spack-stack#464]
**Is your feature request related to a problem? Please describe.**
spack-stack builds on RHEL8.
The NCEP/EMC linux workstations are RHEL8.

**Describe the solution you'd like**
Support to build and deploy on NCEP/EMC RHEL8 linux workstations to allow local development 
A recipe for these workstations similar to other supported machines.

**Additional context**
Attempts to build on NCEP/EMC RHEL8 linux workstations were unsuccessful.
It is likely a user error.
However, since these machines are standard across EMC, spack-stack should be able to build and deploy the library stack on these class of machines.

**Comment by AlexanderRichert-NOAA** [comment]
@aerorahul I'm working on this right now using my EMC RHEL workstation. Testing is going well based on /opt/rh/gcc-toolset-11.

What are your thoughts on a hardcoded location for build/cache directories in the spack configuration (which I plan to call "emc-rhel")? I'm currently using /dev/shm for the various spack tmp directories because I don't have much disk space. How much RAM and how much disk space does a typical user have? Is there a single location that should theoretically work for every user, either local or network?

**Comment by AlexanderRichert-NOAA** [comment]
Here's my branch with the new config: https://github.com/AlexanderRichert-NOAA/spack-stack/tree/add_emc_rhel_config

I successfully tested building the ufs-weather-model template.

**Comment by aerorahul** [comment]
@AlexanderRichert-NOAA 
A typical EMC RHEL8 workstation has 16 cores and 32GB of RAM with 1Tb of disk space.
I think a network location that is mounted might ease management, but I am not sure how that will work when too many users try to use that.
Hence, I think the ability to build locally in the user `$HOME/opt` would be great.

My RHEL8 workstation is `emc-lw-rmahajan` and if you want me to try and build, let me know.  I can follow instructions.

**Comment by AlexanderRichert-NOAA** [comment]
@aerorahul For now I'm reverting back to the default behavior, which is to have all the cache dirs under the spack-stack directory. Please try the following in a location that has probably at least 8 or 10GB of space:
```
git clone https://github.com/AlexanderRichert-NOAA/spack-stack --recurse-submodules -b add_emc_rhel_config
cd spack-stack/
. setup.sh
spack stack create env --name test --template ufs-weather-model --site emc-rhel
cd envs/test
spack env activate .
spack concretize |& tee concrete.log
spack install [-j 8]
```

After the install,  with your spack env activated:
```
spack module lmod refresh
spack stack setup-meta-modules
```

To use the modules:
```
module use /path/to/spack-stack/envs/test/install/modulefiles/Core
module load stack-gcc
module load stack-openmpi
```
