### ISSUE TITLE
Add netcdf-cxx4 to the stack

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#47]
JEDI uses netcdf-cxx4, which is not yet in the spack-stack environments.

**Comment by edwardhartnett** [comment]
netcdf-cxx is not a great idea. It is not fully maintained and does not contain the latest changes to netcdf-c.

Instead, C++ programmers should always use the netcdf-c library directly.

If JEDI wants to use netcdf-cxx, I suggest that some JEDI programmer spend a few weeks working on netcdf-cxx to bring it up to date, and understand that will be an on-going effort as the C library changes.

For example, netcdf-cxx does not support the new quantize functions, which allow lossy compression of data...

**Comment by climbfuji** [comment]
Good points, and certainly that is something we should look into. For now, in order to build the stack so that it works for JEDI needs, we'll add netcdf-cxx4 as a dependency for the jedi-environments only (i.e. if you build the ufs-weather-model environment, you won't get it).

**Comment by climbfuji** [comment]
@edwardhartnett I just realized that I mistakenly wrote `netcdf-cxx` in the issue, it's `netcdf-cxx4`. Your point still holds, we should migrate to `netcdf-c`, though. I created a corresponding issue in the soca-science repository, which is the only repository that I could find so far that uses `netcdf-cxx4`.
