### ISSUE TITLE
gsl-lite to authoritative spack repo

### ISSUE THREAD

**Issue by aerorahul** [JCSDA/spack-stack#472]
`gsl-lite` is required in the JEDI application using IODA.
`gsl-lite` is in the NOAA-EMC fork of spack, but not in the authoritative spack repo.
https://github.com/NOAA-EMC/spack/blob/83743d32adb1ea1166248a4f64b93f5d4694c502/var/spack/repos/builtin/packages/gsl-lite/package.py

Can a PR be opened into the authoritative spack repo for `gsl-lite` so NOAA/NCEP/NCO can fetch and install `gsl-lite` instead of the fork.  This significantly speeds up processing the installation request.

**Is your feature request related to a problem? Please describe.**
No problem.  Just improving process for getting software installed on operational platforms.

**Describe the solution you'd like**
`gsl-lite` is in the NOAA-EMC fork of spack, but not in the authoritative spack repo.

**Additional context**
This request of installation of `gsl-lite` is being held up on WCOSS2

**Comment by climbfuji** [comment]
Closed via https://github.com/spack/spack/pull/35468
