### ISSUE TITLE
Update gsibec to 1.0.7 for the next release

### ISSUE THREAD

**Issue by shlyaeva** [JCSDA/spack-stack#473]
For the next spack-stack release, we'll need a higher version of gsibec in the stack (for the use in JEDI components: saber and fv3-jedi)
Tag: probably 1.0.7, @benjaminmenetrier -- could you please confirm?

**Comment by benjaminmenetrier** [comment]
Yes, the modifications of `gsibec` are already merged in `develop`, we just need to create a tagged version.

**Comment by climbfuji** [comment]
@benjaminmenetrier Please let me know when the new tag is available and we add it to the next spack-stack release. We'll need this tag until the end of the month, if possible. Thanks!

**Comment by shlyaeva** [comment]
Tag is available: https://github.com/GEOS-ESM/GSIbec/releases/tag/1.0.7
