### ISSUE TITLE
OpenJPEG (and others) file to build on Mac OS Monterey with Intel compilers

### ISSUE THREAD

**Issue by rjdave** [JCSDA/spack-stack#475]
**Describe the bug**
When building spack-stack on Mac OS Monterey with the Intel compilers, compilation (linking specifically) fails for OpenJPEG and other packages that configure/build with cmake. Below is the error. I have added the `-w` flag to my compilation to suppress hundreds of warnings about pointer alignment before the actual error:
```
[ 50%] Linking C shared library ../../../bin/libopenjp2.dylib
cd /Users/robertson/roms/svn/git/spack-stack/cache/build_stage/spack-stage-openjpeg-2.3.1-iurwmfwumuetxdkny3ujulzkq4pvt5bb/spack-build-iurwmfw/src/lib/openjp2 && /opt/local/bin/cmake -E cmake_link_script CMakeFiles/openjp2.dir/link.txt --verbose=1
/Users/robertson/roms/svn/git/spack-stack/spack/lib/spack/env/intel/icc -O2 -g -DNDEBUG -dynamiclib -Wl,-headerpad_max_install_names -Wl,-w -compatibility_version 7.0.0 -current_version 2.3.1 -o ../../../bin/libopenjp2.2.3.1.dylib -install_name @rpath/libopenjp2.7.dylib CMakeFiles/openjp2.dir/thread.c.o CMakeFiles/openjp2.dir/bio.c.o CMakeFiles/openjp2.dir/cio.c.o CMakeFiles/openjp2.dir/dwt.c.o CMakeFiles/openjp2.dir/event.c.o CMakeFiles/openjp2.dir/image.c.o CMakeFiles/openjp2.dir/invert.c.o CMakeFiles/openjp2.dir/j2k.c.o CMakeFiles/openjp2.dir/jp2.c.o CMakeFiles/openjp2.dir/mct.c.o CMakeFiles/openjp2.dir/mqc.c.o CMakeFiles/openjp2.dir/openjpeg.c.o CMakeFiles/openjp2.dir/opj_clock.c.o CMakeFiles/openjp2.dir/pi.c.o CMakeFiles/openjp2.dir/t1.c.o CMakeFiles/openjp2.dir/t2.c.o CMakeFiles/openjp2.dir/tcd.c.o CMakeFiles/openjp2.dir/tgt.c.o CMakeFiles/openjp2.dir/function_list.c.o CMakeFiles/openjp2.dir/opj_malloc.c.o CMakeFiles/openjp2.dir/sparse_array.c.o  -lm
icc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.
ld: unaligned pointer(s) for architecture x86_64
make[2]: *** [bin/libopenjp2.2.3.1.dylib] Error 1
make[1]: *** [src/lib/openjp2/CMakeFiles/openjp2.dir/all] Error 2
make: *** [all] Error 2
==> Error: ProcessError: Command exited with status 2:
    'make' '-j1'
```

I am using the latest Intel C/C++ and Fortran compilers for Mac OS Monterey, as well as the latest Xcode that still contains the Monterey SDK (14.0.1 in this case). 

I believe there is something very strange going on here. After the failed build I can go to the directory where it's failing and replace the spack icc script with just icc it will successfully create `../../../bin/libopenjp2.2.3.1.dylib`:

```
icc -O2 -g -DNDEBUG -dynamiclib -Wl,-headerpad_max_install_names -Wl,-w -compatibility_version 7.0.0 -current_version 2.3.1 -o ../../../bin/libopenjp2.2.3.1.dylib -install_name @rpath/libopenjp2.7.dylib CMakeFiles/openjp2.dir/thread.c.o CMakeFiles/openjp2.dir/bio.c.o CMakeFiles/openjp2.dir/cio.c.o CMakeFiles/openjp2.dir/dwt.c.o CMakeFiles/openjp2.dir/event.c.o CMakeFiles/openjp2.dir/image.c.o CMakeFiles/openjp2.dir/invert.c.o CMakeFiles/openjp2.dir/j2k.c.o CMakeFiles/openjp2.dir/jp2.c.o CMakeFiles/openjp2.dir/mct.c.o CMakeFiles/openjp2.dir/mqc.c.o CMakeFiles/openjp2.dir/openjpeg.c.o CMakeFiles/openjp2.dir/opj_clock.c.o CMakeFiles/openjp2.dir/pi.c.o CMakeFiles/openjp2.dir/t1.c.o CMakeFiles/openjp2.dir/t2.c.o CMakeFiles/openjp2.dir/tcd.c.o CMakeFiles/openjp2.dir/tgt.c.o CMakeFiles/openjp2.dir/function_list.c.o CMakeFiles/openjp2.dir/opj_malloc.c.o CMakeFiles/openjp2.dir/sparse_array.c.o  -lm
```

I have also retrieved the `PATH` environment variable and `$full_command_list` from `spack/lib/spack/env/intel/icc`, added spaces in the correct places, set `PATH`, and successfully built `../../../bin/libopenjp2.2.3.1.dylib`:

```
/opt/intel/oneapi/compiler/2023.0.0/mac/bin/intel64/icc -march=skylake -mtune=skylake -w -Wl,-headerpad_max_install_names -Wl,-rpath,/opt/spack-stack/sw/intel/2021.8.0/openjpeg-2.3.1-iurwmfw/lib -Wl,-rpath,/opt/spack-stack/sw/intel/2021.8.0/openjpeg-2.3.1-iurwmfw/lib64 -Wl,-rpath,/opt/intel/oneapi/compiler/2023.0.0/mac/compiler/lib -Wl,-rpath,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/lib -O2 -g -DNDEBUG -dynamiclib -Wl,-headerpad_max_install_names -Wl,-w -compatibility_version 7.0.0 -current_version 2.3.1 -o ../../../bin/libopenjp2.2.3.1.dylib -install_name@rpath/libopenjp2.7.dylib CMakeFiles/openjp2.dir/thread.c.o CMakeFiles/openjp2.dir/bio.c.o CMakeFiles/openjp2.dir/cio.c.o CMakeFiles/openjp2.dir/dwt.c.o CMakeFiles/openjp2.dir/event.c.o CMakeFiles/openjp2.dir/image.c.o CMakeFiles/openjp2.dir/invert.c.o CMakeFiles/openjp2.dir/j2k.c.o CMakeFiles/openjp2.dir/jp2.c.o CMakeFiles/openjp2.dir/mct.c.o CMakeFiles/openjp2.dir/mqc.c.o CMakeFiles/openjp2.dir/openjpeg.c.o CMakeFiles/openjp2.dir/opj_clock.c.o CMakeFiles/openjp2.dir/pi.c.o CMakeFiles/openjp2.dir/t1.c.o CMakeFiles/openjp2.dir/t2.c.o CMakeFiles/openjp2.dir/tcd.c.o CMakeFiles/openjp2.dir/tgt.c.o CMakeFiles/openjp2.dir/function_list.c.o CMakeFiles/openjp2.dir/opj_malloc.c.o CMakeFiles/openjp2.dir/sparse_array.c.o -lm
```

I would note that in the set of packages I'm actually aiming to build, this is the first package that uses cmake instead of autotools to build. Several packages using autotools build successfully before this failure.

I would also note that the first time I run concretize it creates `~/.spack/bootstrap/store/darwin-bigsur-x86_64/apple-clang-13.0.0` instead of `~/.spack/bootstrap/store/darwin-monterey-x86_64/apple-clang-14.0.0` for clingo, gnupg, etc..

**To Reproduce**
Build a spack-stack configuration that requests the jedi-base-env (and therefore eccodes which relies on openjpeg) on Mac OS Monterey using the Intel compilers.

**Expected behavior**
OpenJPEG (and others) build and link successfully

**System:**
Mac OS Monterey using the Intel compilers.

**Additional context**
This same basic configuration builds successfully on Mac OS Big Sur. The main differences are OS version and Xcode version.

If I modify eccodes' package.py to allow it use the system supplied version of OpenJPEG then eccodes fails to build with the same `unaligned pointer(s)` error.

**Comment by climbfuji** [comment]
Have you tried using
```
spack stage openjpeg@2.3.1
spack cd openjpeg@2.3.1
spack build-env openjpeg@2.3.1
```
Then set these environment variables in a shell and try to run the command that spack doesn't like.

Let me note, though, and it's already indicated as a warning in your output, that we do not support Intel on macOS. We only support Apple's native clang + gfortran and LLVM clang + gfortran. Intel has clearly said that they will not produce the new LLVM-based Intel compilers for macOS, and the Intel classic C/C++ compilers will be deprecated in the second half of this year. The classic Fortran compiler is supposed to follow later (next year?).

**Comment by climbfuji** [comment]
@rjdave Since Intel has decided to stop supporting macOS with its new LLVM-based compilers (`icx`, `icpx`, `ifx`) and since `icc` and `icpc` will be deprecated in the second half of 2023 (`ifort` will follow later), we decided to not support Intel on macOS in spack-stack / spack.

You may want to try seeking help from the spack user community by submitting an issue on their github page (https://github.com/spack/spack) or by joining their slack channel.
