### ISSUE TITLE
Install Issue with Apple M2 Max chip

### ISSUE THREAD

**Issue by ashley314** [JCSDA/spack-stack#479]
**Describe the bug**
I am a new employee at JCSDA and while running `spack install` on my laptop I received a ESMA_cmake error. My MacBook pro has the Apple M2 Max chip and running Ventura 13.0. I was using the skylab-dev template. Here is the error: 

```
1 error found in build log:
     83      ESMA_cmake/compiler/flags/GNU_Fortran.cmake:78 (ecbuild_warn)
     84      ESMA_cmake/compiler/esma_compiler.cmake:9 (include)
     85      ESMA_cmake/esma.cmake:52 (include)
     86      CMakeLists.txt:29 (include)
     87    
     88    
     >> 89    CMake Error at ESMA_cmake/compiler/flags/GNU_Fortran.cmake:140 (message):
     90      Unknown processor.  Please file an issue at
     91      https://github.com/GEOS-ESM/ESMA_cmake
     92    Call Stack (most recent call first):
     93      ESMA_cmake/compiler/esma_compiler.cmake:9 (include)
     94      ESMA_cmake/esma.cmake:52 (include)
     95      CMakeLists.txt:29 (include)
```

**To Reproduce**
I followed instructions at [spack-stack readthedocs](https://spack-stack.readthedocs.io/en/latest/Platforms.html#creating-a-new-environment)

**Expected behavior**
Clean install. 

**System:**
Run on Macbook Pro with Apple M2 Max chip and Ventura 13.0. I had my terminal in a i386 architecture.

**Comment by climbfuji** [comment]
@mathomp4 I assume we need to add a patch for existing versions of `esma_cmake` and `mapl` in spack, and also update the `esma_cmake` code for future versions?

**Comment by mathomp4** [comment]
@climbfuji I thought I fixed this in ESMA_cmake v3.18.0. Before then I had "Apple M1" but I changed it to "Apple M" in hopes I'd not hit this...but this was before M2 macs existed. 

@ashley314  what version are you using?

**Comment by climbfuji** [comment]
@mathomp4 This should be `mapl@2.22.0` which uses `v3.17.0`:
```
    # Versions later than 3.14 remove FindESMF.cmake
    # from ESMA_CMake. This works with mapl@2.22.0:
    resource(
        name="esma_cmake",
        git="https://github.com/GEOS-ESM/ESMA_cmake.git",
        tag="v3.17.0",
        when="@2.22.0:",
    )
    resource(
        name="esma_cmake",
        git="https://github.com/GEOS-ESM/ESMA_cmake.git",
        tag="v3.13.0",
        when="@:2.12.3",
    )
```

**Comment by climbfuji** [comment]
@ashley314 Can you try to apply this patch to your spack submodule and then re-concretize and rerun the install as follows?
```
> cd spack
> git diff
diff --git a/var/spack/repos/builtin/packages/mapl/package.py b/var/spack/repos/builtin/packages/mapl/package.py
index 97620d29bc..98751d1f18 100644
--- a/var/spack/repos/builtin/packages/mapl/package.py
+++ b/var/spack/repos/builtin/packages/mapl/package.py
@@ -38,7 +38,7 @@ class Mapl(CMakePackage):
     resource(
         name="esma_cmake",
         git="https://github.com/GEOS-ESM/ESMA_cmake.git",
-        tag="v3.17.0",
+        tag="v3.18.0",
         when="@2.22.0:",
     )
     resource(
> cd ..
> spack clean -a
> spack concretize --force 2>&1 | tee log.concretize.doitagain
> spack install --source --verbose 2>&1 | tee log.install.doitagain
```

**Comment by mathomp4** [comment]
@climbfuji Do you happen to have access to an M2? I am *assuming* that:
```cmake
cmake_host_system_information(RESULT proc_description QUERY PROCESSOR_DESCRIPTION)
```
will return `"Apple M2"`...

I suppose if it works for @ashley314 we know it does.

**Comment by mathomp4** [comment]
Also, if v3.18.0 doesn't work, we might need to go to v3.21.0. @natalie-perlin found that the detection was a bit off if you were running on a VM on M1 as an x86-64:

https://github.com/GEOS-ESM/ESMA_cmake/releases/tag/v3.21.0

**Comment by climbfuji** [comment]
I am fine going all the way to 3.21.0 if that works for @ashley314

**Comment by mathomp4** [comment]
If we want to be purists, ESMA_cmake v3.21.0 [came to MAPL in v2.32.0](https://github.com/GEOS-ESM/MAPL/blob/main/CHANGELOG.md#2320---2022-12-02) but that's more due to time (there was a new version at the same time, so let's update) rather than need.

But recent updates to ESMA_cmake are usually "Get Baselibs to do something spack can do" or "Add new compiler flags for debugging", per https://github.com/GEOS-ESM/ESMA_cmake/blob/main/CHANGELOG.md so there is probably no big disadvantage to going to 3.21.0 as it's a pretty safe update it seems.

**Comment by ashley314** [comment]
I'm good to try out either version @climbfuji! I will give that a go today and let you know how it goes.

**Comment by ashley314** [comment]
@mathomp4 I used v3.21.0 and it has installed successfully now. Thanks!

**Comment by mathomp4** [comment]
@ashley314 Good to hear! I guess CMake must return `Apple M2`. 

Also, props to JCSDA. An M2 Max laptop! Nice! 😄

**Comment by climbfuji** [comment]
> @ashley314 Good to hear! I guess CMake must return `Apple M2`.
> 
> Also, props to JCSDA. An M2 Max laptop! Nice! 😄

@ashley314 Can you create the PR to fix this, please?

**Comment by ashley314** [comment]
@climbfuji Sure I will give it a shot and let you know if I have any questions. This will be my first PR.

**Comment by climbfuji** [comment]
> @climbfuji Sure I will give it a shot and let you know if I have any questions. This will be my first PR.

Happy to walk you through.
