### ISSUE TITLE
[INSTALL] ESMF 8.4.1b07 on Hera

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#481]
Note: Please search to see if an issue already exists for the software you are requesting to be installed.

**Which software in the stack would you like installed?**
ESMF

**What is the version/tag of the software?**
8.4.1b07

**What compilation options would you like set?**
internal PIO (+pio)

**Which machines would you like to have the software installed?**
Hera

**Comment by AlexanderRichert-NOAA** [comment]
@climbfuji @Hang-Lei-NOAA Would it be reasonable to change the ESMF version in the unified env?

**Comment by climbfuji** [comment]
At some point, we need to decide what we are willing and able to reasonably support in spack-stack (remember we talked with @edwardhartnett in the recent past). Maybe we should require that versions installed with spack-stack are proper releases, not beta snapshots. This takes up too much of our time.

**Comment by AlexanderRichert-NOAA** [comment]
At some points though, as in the current case, EMC is going to say "we want to test UFS with --- on hera" and I need to be able to provide that even it is a beta snapshot.

**Comment by climbfuji** [comment]
One way to do this is to "add" new ESMF+MAPL combinations (which is possible, because those modules don't create any dependencies for other modules) and then instruct people to load them after loading the default set of modules.

Another one is to use chained spack environments if it is for testing. We don't want to install in the official install locations before it has been tested and agreed upon to be merged in.

**Comment by AlexanderRichert-NOAA** [comment]
I'm not real familiar with chaining environments. As long as we can do it cleanly and it does what we want, then I'm fine with that.

I think for the moment the former would work, though it might be challenging for libraries that are deeper in the dependency tree. Where/how would we store the config for the additional versions?

**Comment by Hang-Lei-NOAA** [comment]
No Hurry, @AlexanderRichert-NOAA  there will be a bug fixed version v8.4.1 to release. I will first add it to your template for test and then you can commit it to the repo.

**Comment by Hang-Lei-NOAA** [comment]
For configuring the new ESMF versions, Ed had talked with the ESMF people. They will handle it in spack-stack.

**Comment by AlexanderRichert-NOAA** [comment]
To be clear, I've been asked to install 8.4.1b07 on hera prior to the 8.4.1 release so that the beta version can be tested with UFS.

**Comment by climbfuji** [comment]
https://spack-stack.readthedocs.io/en/latest/MaintainersSection.html#testing-new-packages has information on how to create chained environments. Loading the modules is a little more hands-on, as one manually has to add the full path to the newly created modulefiles and then load them after the fact (which with lmod swaps out the default versions)

**Comment by AlexanderRichert-NOAA** [comment]
Okay thanks, that's good to know. I think for what we're doing right now as far as quickly testing this ESMF snapshot, that makes the most sense.
