### ISSUE TITLE
question about passing customization flags to spack

### ISSUE THREAD

**Issue by edwardhartnett** [JCSDA/spack-stack#487]
Question received over email from @stefan-maxar:

> Hope you are doing well! I am a long-time lurker on all the great work you have been doing with the NOAA EMC repos (NCEPLIB-*, spack-stack, etc.) – really awesome stuff there. We’ve been starting to build out our own Spack environments for running applications like UFS. So far, Spack (and the work you’ve contributed to it) has been great – but we are running into what I am sensing is a common issue…compilation customization. Passing compiler flags seems to be very hit-or-miss and has a strong dependency on a package’s package.py actually reading in that information. For example, EMSF’s package.py reads in the spec.compiler_flags so you can actually change optimization (e.g., pass a -O3 flag), but something like netcdf-c has its own optimization variant but doesn’t read in spec.compiler_flags…so you get what you get. Heck, even ZLib’s package.py overwrites any passed flags.
> 
>  
> 
> So – I am curious what your strategy has been when wanting to pass specific customizations (flags) within Spack. It seems like you can go the “brute force” route and modify each package’s package.py…but just doesn’t seem like a clean way to go about it….and then you start diverging from the main Spack repo. Thoughts welcomed!
> 
>

**Comment by climbfuji** [comment]
I would ask that question the spack developers directly (either through the spack slack channel, or in form of an issue/discussion on their github page). It's something they for sure must have thought about. We have so far adopted the pragmatic solution to use the "default" compiler options from spack + whatever is in the spack package recipe, basically following the idea that "the spack developers and package maintainers know best what options work or don't".

**Comment by mathomp4** [comment]
Well, you can do things like `spack install libelf cflags="-g"` say, and that will pass in flags to the build. Weird thing is you'd think you could do something "semi-permanent" in `packages.yaml` but I don't think you can (only in `compilers.yaml`). Would be a good spack feature I say!

**Comment by stefan-vaisala** [comment]
Thanks for the discussion! The quirk I am coming across is that using something like `cflags="-g"` either within the compilers.yaml or spack.yaml (if in an environment and using a specs section) is that if the underlying package "accepts" that information via its package.py. 

Take, ESMF for example (https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/esmf/package.py#L156) - it reads in the flags as defined at the complier level - so you can pass things as expected and have your `-g` propagate. On the other hand, netcdf-c (https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/netcdf-c/package.py) starts with an empty flag set and doesn't read in anything in from the spec. So no matter what, your `-g`  won't be propagated into the build...at least from my experience. So, really, I think (?) this comes down to the package.py level...which means possibly brute forcing any customizations you might want. Given how many packages we all use...brings me back to my initial question on if there was any different/better approach that ya'll might be using!

**Comment by edwardhartnett** [comment]
In my experience brute force works, if one is prepared to be brutish enough.

There are < 200 packages, if even half of them required intervention, that's still only a few weeks work for one good spack programmer.

What I notice is that many teams are starting to take responsibility or at least involvement with their spack package file. For example, ESMF has now committed to maintaining their spack package file, so presumably any problem should be submitted to their support email. 

Each intervention is also an opportunity to educate that team in spack and invite them to take more ownership of their spack package file. As spack knowledge spreads through the community, the need for such interventions should decrease.

**Comment by AlexanderRichert-NOAA** [comment]
Following on @climbfuji's suggestion, I would recommend getting on the Spack Slack channel and asking the developers for input. That said, given that not every package.py or package build system honors every argument (come to think of it, there's no guarantee that even Spack's built-in settings for architecture etc. will be used by any given package), you're probably looking at some amount of at least package.py development to ensure those common variants are actually getting picked up by the build systems.

Relatedly, the Spack team is doing their annual user survey (https://github.com/spack/spack/discussions/35706). Raising the idea of "standardizing the way packages accept compiler arguments" would probably be a welcome suggestion.
