### ISSUE TITLE
Improve documentation by rearranging what is in the quickstart section

### ISSUE THREAD

**Issue by eap** [JCSDA/spack-stack#488]
As a new JEDI developer I've spent some time recently in the spack-stack docs and I had some ideas to reorganize it. I'm using this bug to capture these ideas as a proposal. I'll start by summarizing the specific issues I'm looking to address.

1) The section on platforms includes quite a bit of information on developer environment configuration since developer environments are categorized as a platform. In many ways this is true, but it also buries a core early-user journey within a conceptual hierarchy that isn't obvious to early users.

2) The typical use and environment setup are separated and some very practical notes (ie; on bash_profile/bashrc) are in the quickstart even though they should be in developer setup.

Reorganization proposal:

* Section 1 - no changes.
* Section 2 Quickstart:
   * Swap contents of 2.1 and 2.2 since most new users are here because they want to build and run code (@climbfuji - is this accurate?).
   * Preface "2.1. Using a Spack Environment" with a link to environment setup and encourage new users to start there.
* New Section - "New Developer Setup".
   * Take all the content from Section 3.2 and present it as the basic setup steps to install spack-stacks prerequisites and use spack-stack for JEDI development. Organize this into the following
   * 3.1 introduction
   * 3.1.1 MacOS setup (including subheadings on m1, etc).
   * 3.1.1 Add instructions on configuring iTerm2 to use the brew-installed bash binary.
   * 3.1.2 Linux Setup (including subheadings on yum / apt ecosystems)
   * 3.2 Basic environment setup from environment templates; including sub-heading on environment operation, such as source shell scripts, etc.
   * 3.3 Add some documentation on typical development use of spack stack; source shell script, change deps, etc.
 * Section 3 Platforms:
   * This is now section 4 (since all existing sections are incremented due to new section 3).
   * Existing section 3.2 is collapsed back into primary section, MacOS and linux templates are now included here as the basis of new user onboarding - link to section 3.

**Comment by climbfuji** [comment]
Regarding section 2, quickstart: It depends on the users. The majority of users, especially at our partner agencies/outside the JEDI core team, is more interested in using an existing build on an HPC than building on their own. How about the following:
- Remove the quickstart section:
- Move any specific instructions to either the top of the platforms section (which should become section 2) or to the appropriate place in the developers section (I think mostly after when thinking about extending environments). The new section 3 is then the "new developer setup" section.
- Add links from overview to section 2 (pre-configured environments, including the quick-start code for it at the top) and section 3 (configurable environments/developer section, including the "extend environment" section at the bottom). I admit that "extending environments" may in principle also be used by users on HPCs, but it's going to be rare
- Consider moving the containers section into its own section 4, since it doesn't fit in the new sections 2 and 3

What do you think?

**Comment by eap** [comment]
> * Remove the quickstart section:

Agreed. As it stands today it is unclear to me who is being served by the quickstart. Even with your notes on users, that seems like they should start with platform specific instructions.

> * Move any specific instructions to either the top of the platforms section (which should become section 2) or to the appropriate place in the developers section (I think mostly after when thinking about extending environments).

> The new section 3 is then the "new developer setup" section.

yep to both, works well with removal of quickstart.

> * Add links from overview to section 2 (pre-configured environments, including the quick-start code for it at the top) and section 3 (configurable environments/developer section, including the "extend environment" section at the bottom). I admit that "extending environments" may in principle also be used by users on HPCs, but it's going to be rare

> * Consider moving the containers section into its own section 4, since it doesn't fit in the new sections 2 and 3

I like this also

So new organization is
- Section 1 - Overview, mostly unchanged, but includes disambiguation linking users to either (1) the platforms quickstart or (2) new developer setup.
- Section 2 - Platforms; focused on existing supported platforms and includes HPC quickstart
- Section 3 - New Developer Setup (update as described in the bug)
- Section 4 - Building Containers (relocating content from todays section 2 and section 4)
- Sections 5-12 unchanged.

**Comment by climbfuji** [comment]
That sounds great!

**Comment by eap** [comment]
During the cleanup here I need to resolve what's going on with step 7 of "Creating a new environment" (currently in section 3). Neither myself nor Ashley could track down a config file containing a "definitions" list or struct. Step 7 reads as follows:

_If applicable (depends on the environment), edit the main config file for the environment and adjust the compiler matrix to match the compilers for macOS, as above:_
```
definitions:
- compilers: ['%apple-clang']
```

**Comment by climbfuji** [comment]
As it says, "if applicable (depends on the environment)". Only one template so far uses this `definitions` construct (`unified-dev`), the others don't.

**Comment by climbfuji** [comment]
@eap We would like to include this update in the upcoming spack-stack 1.3.0 release. For this, we'll need to have the PR to update the documentation ready by March 17. It will need to go into the (yet to be created) release branch `release/1.3.0`. This branch will be forked from `develop` next week, it should therefore be safe to work on this based on `develop`. Does that timeline work for you?

**Comment by eap** [comment]
@climbfuji - Yes, that timeline works.

**Comment by climbfuji** [comment]
Awesome, thanks!

**Comment by climbfuji** [comment]
Closed via https://github.com/NOAA-EMC/spack-stack/pull/499
