### ISSUE TITLE
gsi-ncdiag to authoritative spack repository

### ISSUE THREAD

**Issue by aerorahul** [JCSDA/spack-stack#494]
gsi-ncdiag is required in the various GSI uses
gsi-ncdiag is in the NOAA-EMC fork of spack, but not in the authoritative spack repo.
https://github.com/NOAA-EMC/spack/blob/jcsda_emc_spack_stack/var/spack/repos/jcsda-emc/packages/gsi-ncdiag/package.py

Can a PR be opened into the authoritative spack repo for gsi-ncdiag so NOAA/NCEP/NCO can fetch and install from the authoritative repo  instead of the fork. This significantly speeds up processing the installation request.

**Is your feature request related to a problem? Please describe.**
No problem. Just improving process for getting software installed on operational platforms.

**Describe the solution you'd like**
gsi-ncdiag is in the NOAA-EMC fork of spack, but not in the authoritative spack repo.

**Additional context**
This request of installation of gsi-ncdiag is being held up on WCOSS2
I also opened a parallel issue in the NOAA-EMC fork of spack at https://github.com/NOAA-EMC/spack/issues/239

**Comment by ulmononian** [comment]
@aerorahul i'll get a PR in for this

**Comment by ulmononian** [comment]
@aerorahul PR in here: https://github.com/spack/spack/pull/35999

**Comment by ulmononian** [comment]
> @aerorahul PR in here: https://github.com/spack/spack/pull/35999

@aerorahul aforementioned spack PR was merged.

**Comment by ulmononian** [comment]
can this be closed @aerorahul @climbfuji?

**Comment by climbfuji** [comment]
Yes for me.

**Comment by aerorahul** [comment]
Thank you @ulmononian for opening this PR and following up.
