### ISSUE TITLE
CDO / HDF5+threadsafe / UFS conflict

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#496]
The latest version of UFS WM cannot run with hdf5 built with +threadsafe, but CDO requires it. I think the solution will be to disable OpenMP and add `+openmp` to the `when` statement for CDO's hdf5+threadsafe requirement, but I need to make sure global workflow is only running CDO serially.

**Comment by mathomp4** [comment]
This sounds familiar. In an old set of notes on spack I have:

    # Note that cdo requires threadsafe, but hdf5 doesn't
    # seem to want that with parallel. Hmm.

I suppose my "workaround" at the time was probably just to ignore CDO's parallel capabilities.

**Comment by AlexanderRichert-NOAA** [comment]
That's good to know, thanks. Thankfully it looks like global workflow runs it in serial anyway.

**Comment by mathomp4** [comment]
> That's good to know, thanks. Thankfully it looks like global workflow runs it in serial anyway.

Yeah. Even for my own info, I took a look at the list of parallelized operators:

https://code.mpimet.mpg.de/projects/cdo/embedded/index.html#x1-958000B

and I don't think I've used any of them in a long time, so GEOS is probably serial-happy as well.
