### ISSUE TITLE
Mark Python as buildable: False on Orion (and maybe others)

### ISSUE THREAD

**Issue by kgerheiser** [JCSDA/spack-stack#51]
I was building the stack on Orion, but I got some strange concretization preferences.

In `common/packages.yaml` it marks the preferred Python version as 3.8.10. While I was building on Orion it was using the built-in `python@3.7.5` for most packages, but fckit was building Python 3.8.10 from scratch. It should prefer the system version.

**Comment by climbfuji** [comment]
> I was building the stack on Orion, but I got some strange concretization preferences.
> 
> In `common/packages.yaml` it marks the preferred Python version as 3.8.10. While I was building on Orion it was using the built-in `python@3.7.5` for most packages, but fckit was building Python 3.8.10 from scratch. It should prefer the system version.

I am wondering why ... we don't want to build Python. We supply it to spack and that's the only version it is supposed to use.

**Comment by kgerheiser** [comment]
I really don't know. The `py-` packages are using the built-in Python, but for some reason fckit is using the version in packages.yaml.

**Comment by climbfuji** [comment]
> I really don't know. The `py-` packages are using the built-in Python, but for some reason fckit is using the version in packages.yaml.

Maybe the Python entry in the site config needs double colons.

**Comment by climbfuji** [comment]
It shouldn't, because the `buildable = False` should take care of this, but ...

**Comment by kgerheiser** [comment]
`buildable: False` is not present, but when I added it, it uses system Python.

**Comment by climbfuji** [comment]
My currently open PR #38 is already adding it back in (one of the previous removed it), I was waiting for the gaea build to finish after the last sanitizing round, but gaea's f2 is hanging. I'll merge the PR now.
