### ISSUE TITLE
add eckit 1.22.1 for release v5

### ISSUE THREAD

**Issue by shlyaeva** [JCSDA/spack-stack#516]
eckit 1.22.1 contains features that would be useful in jedi oops (https://github.com/JCSDA-internal/oops/issues/2140).
Would be helpful if it were added to stack and made a default for jedi stacks in the next release (v5).

**Comment by climbfuji** [comment]
Thanks! We should be able to add it in an intermediate release well before the end of Q2 2023. I expect there will be one, because the spack-stack-1.3.0 release is the first one that covers the UFS applications, and there will likely be bug fixes/updates needed.
