### ISSUE TITLE
Upgrade compilers to Intel/2022.1.2 on Orion, Hera, Jet, and Gaea

### ISSUE THREAD

**Issue by kgerheiser** [JCSDA/spack-stack#52]
The RDHPCS admins recommend moving to Intel 2022.1.2. We have Intel 2021 as compilers on these platforms, but should use 2022. The 2021 compilers are vulnerable to the log4j bug (not sure that it's relevant, but this is what we're going to be targeting).

**Comment by climbfuji** [comment]
The lates version available on gaea is intel/2021.3.0, which we are currently using. Similar for Cheyenne (2021.2.0).

**Comment by kgerheiser** [comment]
Ok, that's fine. I thought Gaea was an RDHPCS platform where they installed 2022, but if not using 2021 is fine, but Hera, Jet, and Orion have 2022.1.2.,

**Comment by climbfuji** [comment]
Done on hera in PR #82

**Comment by climbfuji** [comment]
gaea is already using the latest version available (2021.3.0)

**Comment by kgerheiser** [comment]
Thanks, and I'll add Jet later today

**Comment by kgerheiser** [comment]
Most recent compilers have been added with #89
