### ISSUE TITLE
Bug: py-mysql-connector-python is not building the C extension

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#522]
**Describe the bug**
The `py-mysql-connector-python` in spack-stack-1.3.0 doesn't build the C extension. The problem is that `setup.py` makes the C extension optional, depending on whether the additional dependencies are found:
```
# C extensions
EXTENSIONS = [
    Extension(
        "_mysql_connector",
        sources=[
            "src/exceptions.c",
            "src/mysql_capi.c",
            "src/mysql_capi_conversion.c",
            "src/mysql_connector.c",
            "src/force_cpp_linkage.cc",
        ],
        include_dirs=["src/include"],
    ),
    ...
]

...

setup(
    name="mysql-connector-python",
    ...
    install_requires=["protobuf>=3.11.0,<=3.20.3"],
    extras_require={
        "dns-srv": ["dnspython>=1.16.0,<=2.1.0"],
        "compression": ["lz4>=2.1.6,<=3.1.3", "zstandard>=0.12.0,<=0.19.0"],
        "gssapi": ["gssapi>=1.6.9,<=1.8.2"],
    },
)
```
But https://github.com/NOAA-EMC/spack/blob/jcsda_emc_spack_stack/var/spack/repos/builtin/packages/py-mysql-connector-python/package.py only has:
```
    depends_on("py-setuptools", type=("build", "run"))
    depends_on("py-protobuf@3.0.0:", type=("build", "run"))
```

**To Reproduce**
Install and look!

**Expected behavior**
There should be a variant that enables the extensions and then asks for the correct dependencies.

**System:**
Any

**Additional context**
R2D2 needs the C extension

**Comment by climbfuji** [comment]
Corresponding issue in authoritative spack repo: https://github.com/spack/spack/issues/36449

**Comment by climbfuji** [comment]
Update. I was able to build that extension for 8.0.32, but it segfaults when being called by Python3. This could be why the conda wheel doesn't have the C extension for 8.0.32, or because I did something wrong, or because the py-mysql-connector-python build system is doing something wrong (it's horrible at the least).

**Comment by climbfuji** [comment]
Note. When this gets fixed, we also need to make sure to add the correct version of `protobuf` so that r2d2 and ewok don't install their own version later.

**Comment by eap** [comment]
I think I'm getting failures due to this issue in ubuntu 22.04 LTS following the spack-stack 1.3.1 install instructions for skylab 4. During a stage that starts with `Installing mysql-8.0.29-qf4ync6xwhzia6644g26cvpuujqczzrc` I get an error involving a a little over a dozen errors that all look similar to this.

```
 >> 1104    /home/ubuntu/spack-stack-1.3.1/cache/build_stage/spack-stage-mysql-8.0.29-qf4ync6xwhzia6644g26cvpuujqczzrc/spack-src/include/lex_string.h:57:20: error: 'string_view' in namespace 'std' does
             not name a type
     1105       57 | static inline std::string_view to_string_view(LEX_STRING str) {
     1106          |                    ^~~~~~~~~~~
     1107    /home/ubuntu/spack-stack-1.3.1/cache/build_stage/spack-stage-mysql-8.0.29-qf4ync6xwhzia6644g26cvpuujqczzrc/spack-src/include/lex_string.h:57:15: note: 'std::string_view' is only available fr
             om C++17 onwards
     1108       57 | static inline std::string_view to_string_view(LEX_STRING str) {
     1109          |               ^~~
```

Interestingly the mysql version here is 8.0.29 which differs from the system installation of 8.0.33, It looks like spack is trying to build it, I'm not sure why, since spack was able to find the local installation;
 
 ```
$ spack external find --scope system mysql

==> The following specs have been detected on this system and added to /home/ubuntu/spack-stack-1.3.1/envs/skylab-/site/packages.yaml
mysql@8.0.33
```

**Comment by climbfuji** [comment]
I believe this is because of a conflict between what version of mysql we request (in some package). I think 8.0.33 should work well, we'll have to "find" and fix the `depends_on(mysql...)` place in spack and then you should be good.
If you add `buildable: False` to the external `mysql` package entry in your `site/packages.yaml`, the concretization step should fail and spack should tell you which package wants `mysql@8.0.31` or earlier.

**Comment by eap** [comment]
@climbfuji - problem solved. In the script I'm using to do repeatable ec2 setup there was a character transposition in the SPACK_SYSTEM_CONFIG_PATH. This caused all the `spack external find` results to get written elsewhere. This is now resolved and it is no longer trying to compile mysql

**Comment by climbfuji** [comment]
One problem less, thanks!

**Comment by climbfuji** [comment]
Well, too fast. This issue is not about what you reported but about the mysql connector. Still one problem less, just not closing this issue :-)

**Comment by climbfuji** [comment]
Because we'll move the mysql functionality to a dedeicated server in the cloud, and users only make r2d2 web requests, we won't need to fix this.
