### ISSUE TITLE
Narwhal (Cray) spack builds depend on loaded modules

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#523]
**Describe the bug**
When building the `unified-dev` environment on Narwhal (a Cray), I noticed that several builds fail (wgrib2, esmf, ...) when having a different compiler loaded in the environment than the one for which it is built. This shouldn't be the case with spack ...

I still have to check if this is also responsible for the error reported in #517 or not.

But it seems like that on Cray machines, we need to build separate environments and load the respective compiler / PrgEnv / MPI modules when doing so.

**To Reproduce**
Try to load another compiler than you are building for into your environment when building spack-stack/spack environments.

**Expected behavior**
User environment does not interfere with spack build environment.

**System:**
Narwhal

**Additional context**

**Comment by climbfuji** [comment]
We've learned that on Cray systems spack install environments depend on the loaded modules. The only way to deal with that is to install in separate directories/environments, commenting out the unused compiler. That's what we are doing for Narwhal right now, and it's the only Cray where we currently try to support two compilers.

My suggestion is to update the documentation (Known issues, and Preconfigured sites for Narwhal) to include that information. And consider dropping GNU support on Narwhal, just stick with Intel as on all the other Crays (don't know about Acorn).

Comments? @ulmononian @srherbener @AlexanderRichert-NOAA ?

**Comment by climbfuji** [comment]
I am not sure this is still true - we should try building on Narwhal with none of the Intel/GNU modules loaded, if that works we can close the issue and build one unified-env for both compilers instead of having separate ones. And update the documentation. If it doesn't work, push issue back to icebox and leave things as is.

**Comment by AlexanderRichert-NOAA** [comment]
You might try building using the '-i' option for setup.sh (which if we're being honest I forgot about but we should try to use it more :) )

**Comment by climbfuji** [comment]
I actually think it's not even needed. I'll try first without, and if it doesn't work I'll try with `-i` (which I completely forgot about and never used).

**Comment by climbfuji** [comment]
I'm closing this as won't fix. There is simply no clean way to build on a Cray without having the correct modules (PrgEnv, compiler) loaded. We have those instructions in the documentation, let's just keep following this instead of spending more time on 2-3 platforms than on all the others.
