### ISSUE TITLE
mapl 2.35.2 build errors on Narwhal

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#524]
**Describe the bug**
mapl@2.22.0 builds fine on Narwhal (a Cray) with Intel, but 2.35.2 chokes with:
```
     784     Running Python2 import test on ShaveMantissa_
     785     cd /p/app/projects/NEPTUNE/spack-stack/spack-stack-1.3.0/cache/build_stage/heinzell/spack-stage-mapl-2.35.2-24y4r3s7yvhietdiewh2jv2o7c6lvnut/spack-build-24y4r3s/MAPL_cfio_r4 && /p/app/projects/NEPTUNE/spack-stack/spac
             k-stack-1.3.0/envs/unified-env-intel-2021.4.0/install/intel/2021.4.0/cmake-3.23.1-tfol62l/bin/cmake -E env LD_LIBRARY_PATH=/p/app/projects/NEPTUNE/spack-stack/spack-stack-1.3.0/cache/build_stage/heinzell/spack-stage-m
             apl-2.35.2-24y4r3s7yvhietdiewh2jv2o7c6lvnut/spack-build-24y4r3s/lib:/opt/cray/pe/libsci/22.08.1.1/INTEL/19.0/x86_64/lib:/opt/cray/pe/gcc/10.3.0/snos/lib:/opt/cray/pe/gcc/10.3.0/snos/lib64:/opt/intel/oneapi_2021.4.0.34
             22/mkl/2021.4.0/lib/intel64:/opt/intel/oneapi_2021.4.0.3422/compiler/2021.4.0/linux/lib:/opt/intel/oneapi_2021.4.0.3422/compiler/2021.4.0/linux/lib/x64:/opt/intel/oneapi_2021.4.0.3422/compiler/2021.4.0/linux/lib/emu:/
             opt/intel/oneapi_2021.4.0.3422/compiler/2021.4.0/linux/lib/oclfpga/host/linux64/lib:/opt/intel/oneapi_2021.4.0.3422/compiler/2021.4.0/linux/lib/oclfpga/linux64/lib:/opt/intel/oneapi_2021.4.0.3422/compiler/2021.4.0/lin
             ux/compiler/lib/intel64_lin:/opt/cray/pe/papi/6.0.0.16/lib64:/opt/cray/libfabric/1.11.0.4.125/lib64 Python2_EXECUTABLE-NOTFOUND -c import\ ShaveMantissa_
     786     No such file or directory
  >> 787     make[2]: *** [MAPL_cfio_r4/CMakeFiles/ShaveMantissa_.dir/build.make:84: ShaveMantissa_] Error 1
     788     make[2]: Leaving directory '/p/app/projects/NEPTUNE/spack-stack/spack-stack-1.3.0/cache/build_stage/heinzell/spack-stage-mapl-2.35.2-24y4r3s7yvhietdiewh2jv2o7c6lvnut/spack-build-24y4r3s'
  >> 789     make[1]: *** [CMakeFiles/Makefile2:652: MAPL_cfio_r4/CMakeFiles/ShaveMantissa_.dir/all] Error 2
     790     make[1]: *** Waiting for unfinished jobs....
```
I don't know why it thinks that it needs to have Python 2. The spack `package.py` doesn't list Python as a dependency. And if it wants Python, then it needs to asl for Python 3 (and not 2) in the spack package recipe.

**To Reproduce**
Try to build mapl@2.35.2 on Narwhal with the existing Intel (or GNU) site config.

**Expected behavior**
It builds!

**System:**
Narwhal, Intel 2021.4.0

**Additional context**
n/a

**Comment by mathomp4** [comment]
@climbfuji Yeah, this is due to an outdated `package.py`. Per https://github.com/NOAA-EMC/spack/pull/241, you want to add a new variant:
```python
    variant("f2py", default=False, description="Build with f2py support")
```
and it's partner:
```python
            self.define_from_variant("USE_F2PY", "f2py"),
```
We had to add an `f2py` package to MAPL and I...I'm not sure "hate" is a strong enough word...hate `f2py`. It's the bane of my CMake existence. 

But with that variant and it's default of `False`, you will no longer try to build it. 

You will see I've been trying to warn users in the Release Notes:

https://github.com/GEOS-ESM/MAPL/releases/tag/v2.35.2

**Comment by mathomp4** [comment]
You'll also see in https://github.com/NOAA-EMC/spack/pull/241 that I did add `python@3` as a dependency.

**Comment by mathomp4** [comment]
Oh, and all this `f2py` junk is the reason MAPL 2.36.0 triggered a new ESMA_cmake update:

https://github.com/GEOS-ESM/ESMA_cmake/pull/313

because of other craziness. Graaaaah!

**Comment by climbfuji** [comment]
Indeed ... well I'll leave it at this for now, have the spack-stack on Narwhal without mapl@2.35.2 (nobody will want to run the latest ufs-weather-model on Navy's Narwhal). The next release 1.4.0 will hopefully have all your shiny updates and it will all build just fine.

But thanks for letting me know that this is not a problem of my making and that you are on it!

**Comment by climbfuji** [comment]
Reopening this, since the problem persists even with `esmf@8.4.2` as part of spack-stack-1.4.0.

**Comment by mathomp4** [comment]
As I said above, you'll most likely need to add an `f2py` variant like I have in https://github.com/JCSDA/spack/pull/241.

So you'd want to add:

```python
    variant("f2py", default=False, description="Build with f2py support")
```
and then:
```python
            self.define_from_variant("USE_F2PY", "f2py"),
```
There is no need for you to go near this code. *I* don't want to go near this code as f2py one of the banes of my existence. Fragile and *not* made for CMake.

**Comment by climbfuji** [comment]
Let's revisit this when we install spack-stack 1.5.0. The updated MAPL and ESMF versions hopefully build fine on Narhwal.

**Comment by mathomp4** [comment]
Note that in the latest mapl package, f2py variant is default off. It is sort of the one place I violate the @AlexanderRichert-NOAA rule of "spack variants echo cmake option defaults"...because I hate f2py. 😄

**Comment by climbfuji** [comment]
This problem is solved thanks to the latest updates of the mapl package. I was able to build mapl@2.35.2 with esmf@8.4.2 using the Intel compiler on Narwhal without issues. Thanks @mathomp4 !
