### ISSUE TITLE
Create fork merge documentation

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#534]
Let's have a documentation page with steps on how to merge main Spack into our fork. This would also be a good place to inventory known differences between our fork and the upstream (container stuff, binary relocation stuff, provider hashes in module directory hierarchy, etc.).

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA Going through old issues, is this something you still want to do?

**Comment by AlexanderRichert-NOAA** [comment]
Yes, I'll try to do this next time we do an upstream merge.

**Comment by climbfuji** [comment]
Thanks @AlexanderRichert-NOAA!

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA Do you want to do this on the release/1.6.0 branch or postpone to 1.7.0?

**Comment by AlexanderRichert-NOAA** [comment]
Postpone

**Comment by climbfuji** [comment]
> Postpone

Thanks, done!

**Comment by AlexanderRichert-NOAA** [comment]
We seem to be doing fine without documentation here, so I'm going to close for now and we can reopen later if needed.
