### ISSUE TITLE
add CRTM v2.4.1 for JEDI/UFO applications 

### ISSUE THREAD

**Issue by BenjaminTJohnson** [JCSDA/spack-stack#544]
**Please describe the package or library you would like to add to spack-stack.**
This is a request to add CRTM v2.4.1 from https://github.com/JCSDA/crtm  `release/crtm_jedi_v2.4.1` branch, which is tagged at 
[v2.4.1-jedi](https://github.com/JCSDA/crtm/tree/v2.4.1-jedi).   Unless there's a need identified via this PR., the develop branch should not change.   If necessary, I will issue a new tag if the develop branch does change.

An associated binary file tarball is located at: 
https://ftp.ssec.wisc.edu/pub/s4/CRTM/file/crtm_coefficients_2.4.1_skylab_4.0.tar.gz

This will be transitioned to UCAR gdex once I've got enough testing / feedback from users.

**What applications will be using this package or library?**
JCSDA UFO + downstream applications

**Is there already a package or library in spack-stack that provides this, or related, functionality?**
Prior CRTM packages

**Will This Package be Needed in a NOAA Operational Application?**
No, this is not recommended.  In fact, it should not be used operationally, since we'll be transitioning all capabilities in v2.4.1 into v3.0.0, and no further development will occur in the v2.x versions of CRTM.

CRTM is public domain code.

**Comment by climbfuji** [comment]
We'll need this version in JCSDA public so that it can be installed by people w/o access to JCSDA-internal.

**Comment by BenjaminTJohnson** [comment]
@climbfuji I've now switched CRTM v2.4.1 to public, and updated the top comment accordingly.   No need to do anything with internal for this release (the hashes no longer match up anyway) -- I'll just ask everyone to use public.
