### ISSUE TITLE
mapl@2.35.2 build errors on macOS after esmf@8.4.1 build errors are fixed in 8.4.2b02

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#553]
**Describe the bug**
```
  >> 1769    Undefined symbols for architecture x86_64:
     1770      "__ZNKSt13runtime_error4whatEv", referenced from:
     1771          __ZNK8nlohmann16json_abi_v3_11_26detail9exception4whatEv in libesmf.a(ESMC_InfoCDef.o)
     1772          __ZNK8nlohmann16json_abi_v3_11_26detail9exception4whatEv in libesmf.a(ESMC_InfoCDefGeneric.o)
     1773          __ZNK8nlohmann16json_abi_v3_11_26detail9exception4whatEv in libesmf.a(ESMCI_Array.o)
     1774          __ZNK8nlohmann16json_abi_v3_11_26detail9exception4whatEv in libesmf.a(ESMCI_Base.o)
     1775          __ZNK8nlohmann16json_abi_v3_11_26detail9exception4whatEv in libesmf.a(ESMCI_Field_F.o)

     ...

     3079          _c_esmc_arrayread_ in libesmf.a(ESMCI_Array_F.o)
     3080          _c_esmc_arraysmmstoreind4_ in libesmf.a(ESMCI_Array_F.o)
     3081          _c_esmc_arraysmmstoreind8_ in libesmf.a(ESMCI_Array_F.o)
     3082          _c_esmc_arraysmmstorenf_ in libesmf.a(ESMCI_Array_F.o)
     3083          ...
     3084    ld: symbol(s) not found for architecture x86_64
  >> 3085    collect2: error: ld returned 1 exit status
  >> 3086    make[2]: *** [bin/cub2latlon.x] Error 1
  >> 3087    make[1]: *** [base/CMakeFiles/cub2latlon.x.dir/all] Error 2
     3088    make[1]: *** Waiting for unfinished jobs....
     3089    /usr/local/Cellar/cmake/3.23.1/bin/cmake -E cmake_copy_f90_mod include/MAPL.generic/mapl_statespecification.mod generic/CMakeFiles/MAPL.generic.dir/mapl_statespecification.mod.stamp GNU
     3090    /usr/local/Cellar/cmake/3.23.1/bin/cmake -E touch generic/CMakeFiles/MAPL.generic.dir/StateSpecification.F90.o.provides.build
     3091    [ 91%] Building Fortran object generic/CMakeFiles/MAPL.generic.dir/ComponentSpecification.F90.o
```
The missing symbols error in esmf 8.4.1, fixed in 8.4.2b02, seems to be handed down to mapl.

**To Reproduce**
Build mapl@2.35.2 with esmf@8.4.2b02

**Expected behavior**
It builds

**System:**
macOS with clang + gfortran

**Additional context**
n/a

**Comment by theurich** [comment]
@climbfuji - just to clarify something for me, the previous version of ESMF that used to work in this context under Spack on macOS was v8.3.0b09? Then a few things in Spack changed, and we also pushed out the v8.4.1. With the _new_ Spack, you tried _v8.4.1_, and first it failed the ESMF installation on macOS... which is what I addressed in v8.4.2b02. Now we are where MAPL shows the link issues on macOS. Is that a correct description, or am I missing something relevant wrt the Spack/ESMF/macOS progression?

**Comment by climbfuji** [comment]
That is correct.

**Comment by theurich** [comment]
Do you by any chance have the same kind of log file, that you posted for the failing case, for the ESMF build on macOS under the old configuration with v8.3.0b09, that still worked fine?

**Comment by climbfuji** [comment]
[log.install.unified-env.001.esmf830b09-mapl2220.gz](https://github.com/NOAA-EMC/spack-stack/files/11297078/log.install.unified-env.001.esmf830b09-mapl2220.gz)

@theurich See here please

**Comment by theurich** [comment]
@climbfuji - please give [v8.4.2b03](https://github.com/esmf-org/esmf/releases/tag/v8.4.2b03) a shot. Thanks!

**Comment by climbfuji** [comment]
You are producing beta snapshots faster than I can test them ... will do as soon as I have time, probably over the weekend.

**Comment by climbfuji** [comment]
I started this before I left for Vienna and of course forgot to check if it worked ... redoing it on my other laptop now.

**Comment by theurich** [comment]
@climbfuji - I just noticed that I had not actually pushed the revision that v8.4.2b03 was referencing to the GitHub remote. When you get a chance, let me know what ESMF hash your test was ending up... It might still be a valid test, because what was missing was just some additional output in the ESMF info, but I want to make sure. Sorry about that! And thanks for doing this while on travel!

**Comment by climbfuji** [comment]
This is the checksum I got today:
```
+    version(
+        "8.4.2b03",
+        sha256="e9b3e25b5a90fb77649e2f57da233318ccccf6ed47592e859c3fc909202f6298",
+    )
```
and with that I could build on my other mac cleanly, both esmf and also mapl@2.35.2 - thanks very much!

**Comment by theurich** [comment]
This is great news! When you get a chance, please post the ESMF build portion of the log.  Thanks!

**Comment by climbfuji** [comment]
@theurich Apologies for the delay, here are the build logs for esmf and mapl. 
[logs_esmf842b03_mapl_2352.tar.gz](https://github.com/NOAA-EMC/spack-stack/files/11365614/logs_esmf842b03_mapl_2352.tar.gz)

**Comment by theurich** [comment]
@climbfuji - thank you, and no worries!
