### ISSUE TITLE
MAPL/ESMA_cmake resources

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#557]
The MAPL package doubule-uses ESMA_cmake resources for 2.22.x and 2.23.x. For the second esma_cmake resource block, `when="@2.22.0:"` should be `when="@2.22.0:2.23"` or something to that effect.

**Comment by mathomp4** [comment]
Oops. Yeah. Probably true. Probably be tomorrow before I can get to this and test, but you can probably do it quickly!

**Comment by mathomp4** [comment]
@AlexanderRichert-NOAA I think I changed this in my NOAA-EMC [tracking spack PR](https://github.com/NOAA-EMC/spack/pull/241) with this commit:

https://github.com/NOAA-EMC/spack/pull/241/commits/0966f016bdc090ee608f0a152efbd90625bd3728

Note: Fun times, the `FindESMF.cmake` file might actually ***go back in*** to MAPL! Why? Well, if I want to build MAPL outside of spack but using spack as libraries, the file is nigh-impossible to find. Inside spack's build system, spack knows where it is from the ESMF recipe, but I just cannot figure out how to get that information outside of spack in a simple way...and just putting it in MAPL solves the issue.

And I guess that means these lines can stop being needed...

**Comment by AlexanderRichert-NOAA** [comment]
Do you mean that the esma_cmake isn't needed in that case..? (I know nothing about this aspect of MAPL and its build system)

**Comment by mathomp4** [comment]
For now, keep it in as things work with it. It's my hope that "soon" it isn't needed for MAPL-as-Spack-Library. But spack is an odd beast sometimes...
