### ISSUE TITLE
Do we need to install source directories?

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#560]
Right now, the use of the `--source` option for `spack install` yields a unified env that's about a million files. Do we really need all those files? If nothing else, could we set up a script that cleans out things like the source dirs for git and cmake, which surely we're never going to need? Also, do we need these for weather libraries if those libraries aren't compiled with `-g` or similar?

The motivation for reducing the installation footprint is that we've been running into file number quotas on a couple of systems.

===
Inside `install/`, run `find -mindepth 6 -maxdepth 6 -path '*/share/*/src' -type d | xargs rm -rf` on the following systems:
- [x] Orion (@ulmononian, @climbfuji)
- [x] Discover (@climbfuji)
- [x] Narwhal (@climbfuji)
- [x] Casper (@climbfuji)
- [x] Cheyenne (@ulmononian)
- [x] Gaea (@climbfuji)
- [x] Hera (@ulmononian)
- [x] Jet (@ulmononian)
- [x] UW S4 (@climbfuji)
- [n/a] AWS Parallelcluster (not needed, new versions will or may be installed without `--source`)
- [n/a] AWS AMI (not needed, new versions will or may be installed without `--source`)
- [x] Acorn (@AlexanderRichert-NOAA)

**Comment by ulmononian** [comment]
thanks for opening this, @AlexanderRichert-NOAA. just had to deal with file quota this morning on hera/nems (again), so it would be good to address this. i know that @climbfuji prefers to include `--source` and `--verbose`, so it may be useful to have his input here. to me, it seems like it will become untenable to continually add new envs w/ spack-stack version updates if we maintain the use of `--source`. `spack gc` and `spack clean -a` don't seem to reduce the size of the ue installs by enough to be the sole amelioration technique we resort to for this issue.

**Comment by climbfuji** [comment]
I agree. It would be nice to have the source files but if it's impossible then let's skip it. `--verbose` doesn't change anything in terms of the installed files, but it leaves log files that can be inspected and that have proven to be useful already, so I would vote for keeping this part and get rid of `--source` only?

**Comment by AlexanderRichert-NOAA** [comment]
I have no preference re: `--verbose`, and would be perfectly happy to do away with `--source` (maybe if Spack some day supports selective source directory preservation by package then we could revisit this, esp. if we end up wanting to support debugging for some libraries). Should we eliminate the source directories for existing installations? I think inside `install/`, running `find -mindepth 6 -maxdepth 6 -path '*/share/*/src' -type d | xargs rm -rf` should do the trick.

**Comment by climbfuji** [comment]
> I have no preference re: `--verbose`, and would be perfectly happy to do away with `--source` (maybe if Spack some day supports selective source directory preservation by package then we could revisit this, esp. if we end up wanting to support debugging for some libraries). Should we eliminate the source directories for existing installations? I think inside `install/`, running `find -mindepth 6 -maxdepth 6 -path '*/share/*/src' -type d | xargs rm -rf` should do the trick.

We can do that, sure. Will need a checkbox list of HPCs somewhere in this issue to keep track.

**Comment by AlexanderRichert-NOAA** [comment]
Done (please edit as needed).

**Comment by ulmononian** [comment]
just want to confirm that we are going with the command `find -mindepth 6 -maxdepth 6 -path '*/share/*/src' -type d | xargs rm -rf` for each ue installation. will proceed on orion, cheyenne, hera, and jet if so.

**Comment by AlexanderRichert-NOAA** [comment]
Let's do it. Just to be safe, before you start, can you edit the issue description to include your name by those systems?

**Comment by ulmononian** [comment]
> Let's do it. Just to be safe, before you start, can you edit the issue description to include your name by those systems?

added my name to those four machines. will commence now.

**Comment by ulmononian** [comment]
running this cut the` install/` directory by 50% on hera. is this expected?

**Comment by ulmononian** [comment]
jet, cheyenne, hera, & orion are finished.

**Comment by AlexanderRichert-NOAA** [comment]
> running this cut the` install/` directory by 50% on hera. is this expected?

I haven't checked the size differences, but that sounds reasonable to me.

**Comment by climbfuji** [comment]
@ulmononian stats for one environment on Orion:
```
Orion-login-3[15] dheinzel$ pwd
/work2/noaa/da/dheinzel-new/spack-stack-unified-env-io-updates/envs/unified-dev-test4/install
Orion-login-3[15] dheinzel$ find ./ -type f | wc -l
505958
Orion-login-3[15] dheinzel$ du -hs .
37G     .
Orion-login-3[17] dheinzel$ find -mindepth 6 -maxdepth 6 -path '*/share/*/src' -type d | xargs rm -rf
Orion-login-3[18] dheinzel$ find ./ -type f | wc -l
137452
Orion-login-3[19] dheinzel$ du -hs .
13G     .

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA Only acorn is missing to close this issue - have you done the cleanup of the source files there/can you do that please?

**Comment by AlexanderRichert-NOAA** [comment]
Yep, done, thanks.
