### ISSUE TITLE
Finish spack-stack installations on Hercules, Gaea C5, Nautilus

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#562]
## Description

Preliminary configurations exist for Hercules, Gaea C5, Nautilus. We need to finish installing spack-stack-1.3.1 on these platforms and provide the missing documentation.

Checklist:
1. Installation users/locations?
    - [x] Gaea C5: `/lustre/f2/dev/wpo/role.epic/contrib/spack-stack/spack-stack-1.3.1-c5`
    - [x] Hercules: `/work/noaa/epic-ps/role-epic-ps/spack-stack` next to Orion installation
    - [x] Nautilus: `/p/app/projects/NEPTUNE/spack-stack`
2. Necessary external packages for spack-stack installed
    - [x]  Gaea C5
    - [x]  Hercules
    - [x]  Nautilus
3. spack-stack-1.3.1 installed
    - [x]  Gaea C5
    - [x]  Hercules
    - [x]  Nautilus (develop close to spack-stack-1.4.0, official 1.4.0 installation will be installed)
4. Successful tests with jedi-bundle / ecflow server+gui
    - [x]  Gaea C5 - so far only jedi-bundle tested, ecflow GUI not yet. Will be done in a separate issue, if necessary.
    - [x]  Hercules (quite a few ctest failures, but these will be addressed separately and are not related to the spack-stack config)
    - [x] Nautilus: no - ecflow GUI doesn't run there yet. jedi-bundle builds successfully - won't fix as part of this issue

**Comment by AlexanderRichert-NOAA** [comment]
Where are we at in terms of installation users/locations?

**Comment by climbfuji** [comment]
> Where are we at in terms of installation users/locations?

- Hercules: still need to check if we (@ulmononian and I) have access to the epic role account. If yes, then we are set. install location is next to the orion stack
- Gaea C5: I believe we can install next to the "ordinary" Gaea C3/4 stack, but I don't think there is a role account yet (to check
- Nautilus: not yet determined

(good point, I added this to the checklist in the issue description)

**Comment by ulmononian** [comment]
> > Where are we at in terms of installation users/locations?
> 
>     * Hercules: still need to check if we (@ulmononian and I) have access to the epic role account. If yes, then we are set. install location is next to the orion stack
> 
>     * Gaea C5: I believe we can install next to the "ordinary" Gaea C3/4 stack, but I don't think there is a role account yet (to check
> 
>     * Nautilus: not yet determined
> 
> 
> (good point, I added this to the checklist in the issue description)

@climbfuji just checked and i do have access to the epic role account on hercules. to confirm, we want hercules done parallel to the orion UE installs (as you did spack-stack-1.3.0-casper parallel to the cheyenne installs)?

also, should i install _only_ 1.3.1?

**Comment by climbfuji** [comment]
> > > Where are we at in terms of installation users/locations?
> > 
> > 
> > ```
> > * Hercules: still need to check if we (@ulmononian and I) have access to the epic role account. If yes, then we are set. install location is next to the orion stack
> > 
> > * Gaea C5: I believe we can install next to the "ordinary" Gaea C3/4 stack, but I don't think there is a role account yet (to check
> > 
> > * Nautilus: not yet determined
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > (good point, I added this to the checklist in the issue description)
> 
> @climbfuji just checked and i do have access to the epic role account on hercules. to confirm, we want hercules done parallel to the orion UE installs (as you did spack-stack-1.3.0-casper parallel to the cheyenne installs)?
> 
> also, should i install _only_ 1.3.1?

Yes, I think 1.3.1 is good on Hercules. Be prepared for wgrib2 to fail (everything else should build). But you first need my PR that updates the hercules site config - next week (I am traveling this week).

**Comment by climbfuji** [comment]
@ulmononian FYI this is the PR that I was referring to, contains also the new hera openmpi: https://github.com/NOAA-EMC/spack-stack/pull/555 - to be finalized on May 1.

**Comment by ulmononian** [comment]
> @ulmononian FYI this is the PR that I was referring to, contains also the new hera openmpi: #555 - to be finalized on May 1.

ah, thanks for the heads up @climbfuji! i'll manually add in your update to the site config for now and install what i can. based on https://github.com/NOAA-EMC/spack-stack/issues/552, it looks like a fix for the wgrib2 failure has not yet been identified?

hope the travel times have been enjoyable!!!

**Comment by climbfuji** [comment]
Correct, wgrib2 failure is still an issue on Hercules. Thanks for doing this!

**Comment by climbfuji** [comment]
@ulmononian Note that I need to provide the instructions for installing the 3rd party dependencies for spack-stack on Hercules in the documentation, then build those in the role account space (right now they are in my personal directory and need to be removed), and then we can install the "official" spack-stack-1.3.1 .

**Comment by climbfuji** [comment]
> @ulmononian Note that I need to provide the instructions for installing the 3rd party dependencies for spack-stack on Hercules in the documentation, then build those in the role account space (right now they are in my personal directory and need to be removed), and then we can install the "official" spack-stack-1.3.1 .

@ulmononian I am doing this now

**Comment by ulmononian** [comment]
> > @ulmononian Note that I need to provide the instructions for installing the 3rd party dependencies for spack-stack on Hercules in the documentation, then build those in the role account space (right now they are in my personal directory and need to be removed), and then we can install the "official" spack-stack-1.3.1 .
> 
> @ulmononian I am doing this now

ok cool. keep me posted and then we can run the install. i wrote to mssu IT about wgrib2 on hercules since they built `wgrib2/3.1.1` there using spack.

**Comment by climbfuji** [comment]
That’s good to know. I believe we are still trying to build wgrib2 2.0.8 (and I don’t know why we are still no that old version)

**Comment by climbfuji** [comment]
@areineke For Nautilus, can you please let me know which compiler and MPI library you want me to use?
