### ISSUE TITLE
running error due to inconsistent module names for py-netcdf4-1.5.3  

### ISSUE THREAD

**Issue by hyunsookkim-NOAA** [JCSDA/spack-stack#568]
Running SOCA on Orion:
see below for running error from SOCA_SCIENCE_BIN_DIR/soca_domom6_action.py checkpoint in run.var.sh 

hskim@-Orion-login-3:run.var> python /work/noaa/aoml-hafs1/hskang/MOM6-SIS2-HAT10/jedi_builds_20230501_intel/soca-science/build.a_domom6_action.py checkpoint
Traceback (most recent call last):
  File "/work/noaa/aoml-hafs1/hskang/MOM6-SIS2-HAT10/jedi_builds_20230501_intel/soca-sience/build.intel/bin/soca_domom6_action.in <module>
    import netCDF4
  File "/work/noaa/epic-ps/role-epic-ps/spack-stack/spack-stack-1.3.0/envs/unified-env/install/intel/2022.0.2/py-netcdf4-1.5.3-cthon3.9/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
ModuleNotFoundError: No module named 'netCDF4._netCDF4'

It appears an inconsistency in loaded module file, example 
/work/noaa/epic-ps/role-epic-ps/spack-stack/spack-stack-1.3.0/envs/unified-env/install/intel/2022.0.2/py-netcdf4-1.5.3-cthon3.9/
vs.
62) py-netcdf4/1.5.3 (below).

Currently Loaded Modules:
  1) ecflow/5.8.4                     25) eccodes/2.27.0     49) json/3.10.5                  73) py-pyhdf/0.10.4
  2) stack-intel/2022.0.2             26) eigen/3.4.0        50) json-schema-validator/2.1.0  74) py-pyyaml/6.0
  3) stack-intel-oneapi-mpi/2021.5.1  27) openblas/0.3.19    51) odc/1.4.5                    75) py-gast/0.5.3
  4) miniconda/3.9.7                  28) eckit/1.20.2       52) py-attrs/22.1.0              76) py-beniget/0.4.1
  5) stack-python/3.9.7               29) fftw/3.3.10        53) py-pycparser/2.21            77) py-ply/3.11
  6) cmake/3.22.1                     30) fckit/0.10.0       54) py-cffi/1.15.1               78) py-pythran/0.11.0
  7) zlib/1.2.13                      31) fiat/1.1.0         55) py-findlibs/0.0.2            79) py-scipy/1.9.3
  8) curl/7.85.0                      32) ectrans/1.2.0      56) py-setuptools/59.4.0         80) py-xarray/2022.3.0
  9) git/1.8.3.1                      33) atlas/0.32.1       57) py-numpy/1.22.3              81) sp/2.3.3
 10) zstd/1.5.2                       34) gsibec/1.0.7       58) py-eccodes/1.4.2             82) jedi-base-env/1.0.0
 11) netcdf-c/4.9.2                   35) gsl-lite/0.37.0    59) py-f90nml/1.4.3              83) gsl/2.7.1
 12) nccmp/1.9.0.1                    36) libjpeg/2.1.0      60) py-h5py/3.7.0                84) nco/5.0.6
 13) netcdf-fortran/4.6.0             37) krb5/1.15.1        61) py-cftime/1.0.3.4            85) soca-env/unified-dev
 14) parallel-netcdf/1.12.2           38) libtirpc/1.2.6     62) py-netcdf4/1.5.3             86) fms/release-jcsda
 15) parallelio/2.5.9                 39) hdf/4.2.15         63) py-bottleneck/1.3.5          87) emc-utils/1.1.0
 16) py-pip/21.2.4                    40) jedi-cmake/1.4.0   64) py-pyparsing/3.0.9           88) contrib/0.1
 17) wget/1.14                        41) libpng/1.6.37      65) py-packaging/21.3            89) noaatools/1.0
 18) base-env/1.0.0                   42) libxt/1.1.5        66) py-numexpr/2.8.3             90) rocoto/1.3.3
 19) boost/1.72.0                     43) libxmu/1.1.2       67) py-six/1.16.0                91) wgrib/2.0.8
 20) bufr/11.7.1                      44) libxpm/4.11.0      68) py-python-dateutil/2.8.2     92) impi/2022.1.2
 21) git-lfs/2.12.0                   45) libxaw/1.0.13      69) py-pytz/2022.2.1             93) intel/2020.2
 22) crtm/v2.4-jedi.2                 46) udunits/2.2.28     70) py-pandas/1.4.0              94) antlr/2.7.7
 23) ecbuild/3.6.5                    47) ncview/2.1.8       71) py-pybind11/2.8.1            95) hdf5/1.10.6
 24) openjpeg/2.3.1                   48) netcdf-cxx4/4.3.1  72) py-pycodestyle/2.8.0         96) netcdf/4.7.4

This issue should be resolved.

**Comment by srherbener** [comment]
It might be that the underlying .so file in the python netCDF4 installation is missing, or unreadable, etc. In this directory:

`/work/noaa/epic-ps/role-epic-ps/spack-stack/spack-stack-1.3.0/envs/unified-env/install/intel/2022.0.2/py-netcdf4-1.5.3-cthon3.9/site-packages/netCDF4/`

There should be a file named like this: `_netCDF4.cpython-<python_version>-<platform>.so` where `<python_version>` is 39 for python3.9, and `<platform>` is x86-64-linux-gnu for x86-64 GNU/Linux.

If the .so file is there, then a likely culprit is that you are running with a different version of python compared to the version used to build the spack-stack.

**Comment by ulmononian** [comment]
@hyunsookkim-NOAA please try to add load("ufs-pyenv") to your soca machinefiles on orion (intel & gnu) and let me know how that goes.

**Comment by ulmononian** [comment]
please try the orion machine files here: https://github.com/ulmononian/soca-science/blob/spack_ue/configs/machine (now using `spack-stack/1.3.1.`. note that i commented out the loading of `/work/noaa/da/kritib/soca-shared/spack-stack/soca_python-3.9/bin/activate` in these fork machine files so only the spack-stack python is utilized, as i agree with @srherbener about python/miniconda conflicts as a potential cause of this error. 

if you want to share your current soca/soca-science build/run steps, i can test on my side. i'm not sure if the old build/run instructions i used to use are valid anymore.

**Comment by hyunsookkim-NOAA** [comment]
Both the gnu and intel excutable are working on Orion. Thank you.

**Comment by hyunsookkim-NOAA** [comment]
Both the gnu and intel excutable are working on Orion. Thank you.
