### ISSUE TITLE
The `yafyaml` package build fails when building on macOS with gfortran 13 --> remove from all envs

### ISSUE THREAD

**Issue by fabiolrdiniz** [JCSDA/spack-stack#577]
**Describe the bug**
The `yafyaml` package build fails when building on macOS with gfortran 13.

**To Reproduce**
Follow the steps to build spack-stack-v1.3.1, using clang 14.0.0 and gfortran 13.

**Expected behavior**
`yafyaml` should be built fine.

**System:**
What system(s) are you running the code on?
macOS Monterey, 12.6.5 (21G531)

**Additional context**
Underneath, I was following https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/using/jedi_environment/spackbuild.html#building-spack-stack-modules-for-jedi, but the crash should be the same regardless of the environment.

Please, find attached the log for the crash: [spack-build-out.txt](https://github.com/NOAA-EMC/spack-stack/files/11446172/spack-build-out.txt).

**Comment by mathomp4** [comment]
Yes, we know about this. We've had issues all over the place with GCC 13. On the one system I managed to build everything with GCC 13, GEOS fell apart.

@tclune and I are hoping to work on it soon, but for now, GCC 13.1 is probably a no-go for GFE libraries.

**Comment by climbfuji** [comment]
We should probably add a `conflict` statement for gcc13 somewhere central in spack-stack until we've devoted enough time to test and fix building with it.

**Comment by mathomp4** [comment]
I want to say I got further along with GFE stuff on Intel Mac compared to M1 Mac. Not sure why...

**Comment by climbfuji** [comment]
@mathomp4 Any update on this?

**Comment by mathomp4** [comment]
@climbfuji Not yet as it hasn't been high on our issue list in recent times. And, unfortunately, the one person who might know how to fix this, @tclune, is a civil servant and, well, shutdown fun. Maybe he can work on this in the coming days/weeks or maybe not. I'm not too sure.

But I'll try and do some tests soon on this.

Though, again, you don't need yaFyaml for recent MAPL that uses ESMF 8.5.0, so this might be even less of a priority for MAPL/GEOS, though I'm sure @tclune would like to support the compiler in future.

**Comment by climbfuji** [comment]
If that's the case (yafyaml no longer needed), then I suggest to not spend any time on this and close this issue as "won't fix"

**Comment by climbfuji** [comment]
We've removed the need for yafyaml from all spack-stack environments, therefore we can close this as done.

**Comment by mathomp4** [comment]
Note that I think Tom did fix this...as I know I've built it with Clang + Gfortran 13. But as you say, not really needed anymore for GEOS at least.
