### ISSUE TITLE
Issue with install of scipy with Intel on Discover (spack-stack-1.3.0)

### ISSUE THREAD

**Issue by danholdaway** [JCSDA/spack-stack#579]
**Describe the bug**

@climbfuji I think there is an issue with the install of scipy on Discover with Intel. If I load all the modules and try:

``` python
import scipy.stats
```

I get the error `ModuleNotFoundError: No module named 'scipy.stats._hypotests_pythran'`

On further investigation there is no file `/gpfsm/dswdev/jcsda/spack-stack/spack-stack-1.3.0/envs/unified-env/install/intel/2022.0.1/py-scipy-1.9.3-7mhx3mk/lib/python3.9/site-packages/scipy/stats/_hypotests_pythran.py` I think there should be. You can see the file in version 1.9.3 of the package here: https://github.com/scipy/scipy/tree/v1.9.3/scipy/stats

**Comment by climbfuji** [comment]
This is going to be fixed in the next release - see #566 for the PR that fixed it (got merged today).

**Comment by danholdaway** [comment]
Thanks @climbfuji. It seems we can just unload that module without impact. So that will work until the next release.
