### ISSUE TITLE
Update spack-stack to use C++17

### ISSUE THREAD

**Issue by fmahebert** [JCSDA/spack-stack#591]
ECMWF libraries like eckit and atlas are transitioning to C++17.

We had to revert some C++17 changes in atlas to enable it to bring with JCSDA code that (so far) is compiled on the C++14 standard.

At a minimum, after JCSDA build systems are updated, spack-stack should go back to using the develop branch of atlas instead of the JCSDA fork with its reversion commit.

Possibly, we should make any desired updates in how spack builds packages to adopt more C++17 (but I expect this is dictated by each package, not by spack)

**Comment by climbfuji** [comment]
Thanks for creating the issue, @fmahebert. We'll be working on this for spack-stack 1.5.0 to support Skylab v6. Based on what I know, all our systems have recent enough Intel compilers and GCC backends (for libstdc++) to be able to support C++-17. The only system we may have to check is Cheyenne with the older Intel compiler, but in the worst case this system will be replaced over the fall by its successor Derecho.

**Comment by srherbener** [comment]
I looked into packages in our spack-stack builds using the `cxxstd` variant and there appear to be two packages where we can utilize this: boost and mysql. This was done in the context of the default.macos site and the unified-dev template.

I believe that @climbfuji is going to update the boost variant to C++17 (ie, +cxxstd=17) in a soon to be submitted PR, which leave mysql.

I believe that the mysql package is the MySQL server, and the only place I'm aware of using the MySQL server is on the Mac. The HPC systems, I think, are using a MySQL server running on an AWS EC2 instance. For the Mac we are using the homebrew installed mysql server.

The packages requiring C++17 in the spack-stack build (eg, atlas, eckit, etc) should already have their cmake or autoconf configuration set up to use the `std=c++17` option during their builds.

I think for Mac in JCSDA, this means that we are set after the boost update is in.

However, with my check I probably didn't see a fair amount of packages that are being built across all the HPC platforms. Do I need to do something like for every package in common/packages.yaml, run `spack spec` on that package and see which ones have the `cxxstd` (or analogous) variant?

**Comment by climbfuji** [comment]
I think it's pretty safe to assume that we don't need to do more than the boost change (which will be part of my PRs https://github.com/JCSDA/spack-stack/pull/722 / https://github.com/JCSDA/spack/pull/304).

FWIW, we do install mysql server everywhere, not just on machines that use r2d2 as localhost, but on each machine it's installed from precompiled binaries because building it from source is a pain.

Thanks for checking the packages.

I'll close this issue iff (if and only if) my PRs with the boost update and the new ECMWF versions work for jedi-bundle / skylab.
