### ISSUE TITLE
Clean up cmake deps

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#596]
mapl and crtm have cmake as a "full" dependency, i.e., it is a dependency included in the resulting package module. ectrans has ecbuild as a runtime dependency. @climbfuji it looks like the relevant package.py lines were added by you-- any downside to making these build-only dependencies?

**Comment by climbfuji** [comment]
Not at all. `cmake` is a runtime dependency in base-env, and I think that is what we want.
