### ISSUE TITLE
Reset $PATH before installing

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#597]
I didn't realize until recently that Spack doesn't touch the $PATH variable when generating a build environment, so theoretically what's in the user's path can affect installations. We could set the PATH variable in each site's compilers.yaml to ensure consistency of installations. In most cases, it will probably just be '/usr/bin:/bin' or similar (Spack adds its own compiler paths, etc. onto this setting).

**Comment by climbfuji** [comment]
That's very dangerous I think ... therefore I am telling users to follow instructions, run `module purge` and don't add stuff to `.bashrc` etc. But sometimes you want to have certain paths set (e.g. have homebrew activated on macOS, have the scl environment loaded on Red Hat).

**Comment by AlexanderRichert-NOAA** [comment]
Sorry, to clarify, I'm talking about named HPC systems where we're doing official installations, that way for instance we won't have any differences between 1.3.1 and 1.4.0 on Acorn that are the result of me and Hang having different bashrc's.

**Comment by climbfuji** [comment]
I see ... ok that might be useful

**Comment by climbfuji** [comment]
What are we going to do with this?

**Comment by AlexanderRichert-NOAA** [comment]
I've made some progress but haven't had much time to work on it further.
