### ISSUE TITLE
spack-stack-1.4.0 release work

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#599]
## Description

Summary of all tasks for releasing spack-stack-1.4.0.

Starting from the release branches (`git clone -b release/1.4.0 --recursive https://github.com/jcsda/spack-stack`), install on platforms - any bug fixes/documentation updates for specific platforms go into the release branch before the final tag is made.

### Platforms

- [ ] Acorn (Intel): (@AlexanderRichert-NOAA)
    - [ ] redone with `hdf5@1.14.0` in ...
- [x] Casper (Intel): `/glade/work/epicufsrt/contrib/spack-stack/spack-stack-1.4.0-casper/envs/unified-env/` (@climbfuji)
    - [x] redone with `hdf5@1.14.0` in `/glade/work/epicufsrt/contrib/spack-stack/spack-stack-1.4.0-casper/envs/unified-env-v2`
- [x] Cheyenne (Intel): `/glade/work/epicufsrt/contrib/spack-stack/spack-stack-1.4.0/envs/unified-env/` (@climbfuji)
    - [x] redone with `hdf5@1.14.0` in `/glade/work/epicufsrt/contrib/spack-stack/spack-stack-1.4.0/envs/unified-env-v2`
- [x] Discover (GNU & Intel): `/discover/swdev/jcsda/spack-stack/spack-stack-1.4.0/envs/unified-env/` (@climbfuji)
    - [x] redone with `hdf5@1.14.0` in `/discover/swdev/jcsda/spack-stack/spack-stack-1.4.0/envs/unified-env-v2`
- [x] Gaea C4 (Intel): `/lustre/f2/dev/wpo/role.epic/contrib/spack-stack/spack-stack-1.4.0-c4/envs/unified-env` (@climbfuji)
    - [x] redone with `hdf5@1.14.0` in `/lustre/f2/dev/wpo/role.epic/contrib/spack-stack/spack-stack-1.4.0-c4/envs/unified-env-v2`
- [x] Gaea C5 (Intel): `/lustre/f2/dev/wpo/role.epic/contrib/spack-stack/spack-stack-1.4.0-c5/envs/unified-env` (@climbfuji)
    - [x] redone with `hdf5@1.14.0` in `/lustre/f2/dev/wpo/role.epic/contrib/spack-stack/spack-stack-1.4.0-c5/envs/unified-env-v2`
- [x] Hera (GNU & Intel): `/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.4.0/envs/unified-env` (@ulmononian & @mark-a-potts)
    - [x] redone with `hdf5@1.14.0` in `/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.4.0/envs/unified-env-v2`
- [x] Hercules (GNU & Intel): `/work/noaa/epic-ps/role-epic-ps/spack-stack/spack-stack-1.4.0-hercules/envs/unified-env` (@climbfuji)
    - [x] redone with `hdf5@1.14.0` in `/work/noaa/epic-ps/role-epic-ps/spack-stack/spack-stack-1.4.0-hercules/envs/unified-env-v2`
- [x] Jet (GNU & Intel): ` /mnt/lfs4/HFIP/hfv3gfs/role.epic/spack-stack/spack-stack-1.4.0/envs/unified-env` (@ulmononian)
    - [x] redone with `hdf5@1.14.0` in `/mnt/lfs4/HFIP/hfv3gfs/role.epic/spack-stack/spack-stack-1.4.0/envs/unified-env-v2`
- [x] Nautilus (Intel): `/p/app/projects/NEPTUNE/spack-stack/spack-stack-1.4.0/envs/unified-env-intel-2021.5.0` (@climbfuji)
    - [x] redone with `hdf5@1.14.0` in `/p/app/projects/NEPTUNE/spack-stack/spack-stack-1.4.0/envs/unified-env-intel-2021.5.0-hdf5-1.14.0`
- [x] Narwhal (GNU): `/p/app/projects/NEPTUNE/spack-stack/spack-stack-1.4.0/envs/unified-env-gcc-10.3.0` (@climbfuji)
- [x] Narwhal (Intel): `/p/app/projects/NEPTUNE/spack-stack/spack-stack-1.4.0/envs/unified-env-intel-2021.4.0` (@climbfuji)
    - [x] redone with `hdf5@1.14.0` in `/p/app/projects/NEPTUNE/spack-stack/spack-stack-1.4.0/envs/unified-env-intel-2021.4.0-hdf5-1.14.0`
- [x] Orion (GNU & Intel): `/work/noaa/epic-ps/role-epic-ps/spack-stack/spack-stack-1.4.0/envs/unified-env` (@ulmononian)
    - [x] redone with `hdf5@1.14.0` in `/work/noaa/epic-ps/role-epic-ps/spack-stack/spack-stack-1.4.0/envs/unified-env-v2`
- [x] S4 (Intel): `/data/prod/jedi/spack-stack/spack-stack-1.4.0/envs/unified-env` (@climbfuji)
    - [x] redone with `hdf5@1.14.0` in `/data/prod/jedi/spack-stack/spack-stack-1.4.0/envs/unified-env-v2`

### Cloud

- [x] JEDI/Skylab AWS EC2 Red Hat 8 single node (GNU): `/home/ec2-user/spack-stack/spack-stack-1.4.0/envs/unified-env` (@climbfuji)
- [x] JEDI/Skylab AWS EC2 Ubuntu 20 single node (GNU): `/home/ubuntu/spack-stack/spack-stack-1.4.0/envs/unified-env` (@climbfuji)
- [x] JEDI/Skylab AWS Ubuntu 20 Parallelcluster (Intel - GNU openmpi is broken): `/mnt/experiments-efs/skylab-v5/spack-stack-1.4.0/envs/unified-env` (@climbfuji)
    - [x] redone with `hdf5@1.14.0` in `/mnt/experiments-efs/skylab-v5/spack-stack-1.4.0/envs/unified-env-v2`
- [ ]  NOAA Parallelworks AWS (Intel):
    - [ ] redone with `hdf5@1.14.0` in ...
- [ ]  NOAA Parallelworks Azure (Intel):
    - [ ] redone with `hdf5@1.14.0` in ...
- [ ]  NOAA Parallelworks Gcloud (Intel):
    - [ ] redone with `hdf5@1.14.0` in ...
### Containers

- [x] JEDI/Skylab container gcc/openmpi (@climbfuji)
    - [x] Docker (uploaded to ECR and Dockerhub)
    - [x] Singularity (uploaded to Sylabs and S3 bucket)
- [x] JEDI/Skylab container clang/mpich (@climbfuji)
    - [x] Docker (uploaded to ECR and Dockerhub)
    - [x] Singularity (uploaded to Sylabs and S3 bucket)
- [x] JEDI/Skylab container intel/impi (@climbfuji)
    - [x] Docker (uploaded to ECR)
    - [x] Singularity (uploaded to S3 bucket)
    - [x] redone with `hdf5@1.14.0` with tag `skylab-v5-v2`
        - [x] Docker (uploaded to ECR)
        - [x] Singularity (uploaded to S3 bucket)

### User platforms

- [x] @climbfuji's macOS Monterey 12.1, apple-clang@13.1.6, x86_64 rosetta2 emulator mode, unified-dev
- [x] @climbfuji's macOS Monterey 12.1, apple-clang@13.1.6, x86_64 rosetta2 emulator mode, skylab-dev

### Documentation

- [x] Update of preconfigured platforms page
- ...

### Final code changes

- [x] tag spack and spack-stack
- [x] replace `release/1.4.0` with tag `spack-stack-1.4.0` for `spack` and tag `1.4.0` for spack-stack in `.gitmodules and container recipes
- [x]  create and publish release notes
- [x] archive/delete spack-stack-1.4.0 project at NOAA-EMC

### Misc

- [x] open a bottle of champagne

**Comment by climbfuji** [comment]
Opening the bottle of champagne now, that was the last item in the above checklist that needed to be ticked.

Everything else will be done on develop later.

**Comment by ulmononian** [comment]
> Opening the bottle of champagne now, that was the last item in the above checklist that needed to be ticked.
> 
> 
> 
> Everything else will be done on develop later.

well deserved. skål 🫧

**Comment by jieshunzhu** [comment]
@climbfuji I am able to build an old version of soca-science using spack-stack-1.4.0 (/lustre/f2/dev/wpo/role.epic/contrib/spack-stack/spack-stack-1.4.0-c4/envs/unified-env-v2/install/modulefiles/Core) on C4, but failed to build it on C5. The following is my machine.gaea-c5.intel. Can you help me check my problems? Thanks.

+++++++++++++++++++++
source /lustre/f2/dev/role.epic/contrib/Lmod_init_C5.sh
module unload cray-mpich
module unload darshan-runtime
module load PrgEnv-intel/8.3.3
module load intel-classic/2022.2.1
module load cray-mpich/8.1.25
module load python/3.9.12

module use /lustre/f2/dev/wpo/role.epic/contrib/spack-stack/modulefiles-c5
module load ecflow/5.8.4
module load mysql/8.0.31

module use /lustre/f2/dev/wpo/role.epic/contrib/spack-stack/spack-stack-1.4.0-c5/envs/unified-env-v2/install/modulefiles/Core
module load stack-intel/2022.2.1
module load stack-cray-mpich/8.1.25
module load stack-python/3.9.12
#module -t available

module load soca-env/unified-dev
module load fms/release-jcsda

**Comment by climbfuji** [comment]
> @climbfuji I am able to build an old version of soca-science using spack-stack-1.4.0 (/lustre/f2/dev/wpo/role.epic/contrib/spack-stack/spack-stack-1.4.0-c4/envs/unified-env-v2/install/modulefiles/Core) on C4, but failed to build it on C5. The following is my machine.gaea-c5.intel. Can you help me check my problems? Thanks.
> 
> +++++++++++++++++++++ source /lustre/f2/dev/role.epic/contrib/Lmod_init_C5.sh module unload cray-mpich module unload darshan-runtime module load PrgEnv-intel/8.3.3 module load intel-classic/2022.2.1 module load cray-mpich/8.1.25 module load python/3.9.12
> 
> module use /lustre/f2/dev/wpo/role.epic/contrib/spack-stack/modulefiles-c5 module load ecflow/5.8.4 module load mysql/8.0.31
> 
> module use /lustre/f2/dev/wpo/role.epic/contrib/spack-stack/spack-stack-1.4.0-c5/envs/unified-env-v2/install/modulefiles/Core module load stack-intel/2022.2.1 module load stack-cray-mpich/8.1.25 module load stack-python/3.9.12 #module -t available
> 
> module load soca-env/unified-dev module load fms/release-jcsda

Can you please create a new issue with a descriptive title, repeat what you wrote here, and add the relevant log output (or location of the log files on disk). I hope that between EPIC and JCSDA we can help you debug the problem. Thanks.
