### ISSUE TITLE
Duplicate package `nco` in unified-dev environment in spack-stack-1.4.0

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#605]
**Describe the bug**
With spack-stack-1.4.0, we are seeing duplicate nco packages being built on some - but not all - systems.

It looks like this comes from `nco` concretizing different with the GNU compilers for `global-workflow-env` and `soca-env`.

**To Reproduce**
I've seen this problem on Nautilus, and @ulmononian on Jet.

**Expected behavior**
Only one nco version per compiler

**System:**
Nautilus / Jet

**Additional context**
n/a

**Comment by climbfuji** [comment]
I tracked this down to multiple versions of `bison` being used. The best solution is to remove external `bison` versions earlier than 3.8 from the site config (`packages.yaml`). I am doing this for Jet as part of release 1.4.0, and I am adding documentation in the "Known issues" section so that we can fix it for other platforms later, if needed.

**Comment by ulmononian** [comment]
same issue on orion

**Comment by climbfuji** [comment]
comment out the external bison, reconcretize, dry to “uninstall” the external python, finish install and check if there are still duplicates - if it works I make the change in my next release branch PR
