### ISSUE TITLE
tar command failed on Hercules when zlib/1.2.13 is loaded

### ISSUE THREAD

**Issue by BijuThomas-NOAA** [JCSDA/spack-stack#609]
With the following spack-stack environment, the tar extraction failed(on Hercules) with the tar file: (/work2/noaa/hwrf/scrub/bthomas/tar_test_spack_stack/hafs.t12z.dropsonde.tar)

```
module use /work/noaa/epic-ps/role-epic-ps/spack-stack/spack-stack-1.4.0-hercules/envs/unified-env/install/modulefiles/Core
module load stack-intel/2021.7.1                                                                    
module load stack-intel-oneapi-mpi/2021.7.1                                                          
module load zlib/1.2.13
```

I can confirm that zlib/1.2.13 is from /work/noaa/epic-ps/role-epic-ps/spack-stack/spack-stack-1.4.0-hercules/envs/unified-env/install/modulefiles/intel/2021.7.1

 If I create the tar file(tar -cvf) within the above spack-stack environment, I have no problem in untar it (tar -xvf).

 I can untar successfully hafs.t12z.dropsonde.tar, if I do not load spack-stack environment(default system environment).

**Comment by climbfuji** [comment]
We will try to fix this on develop before skylab-1.5.0

**Comment by BijuThomas-NOAA** [comment]
@climbfuji Thank you

**Comment by ulmononian** [comment]
just a note on this: @BijuThomas-NOAA and i realized that if one includes `module load tar/1.34` after loading the stack, either in the modulefile for the workflow environment or from the command line, the tar command succeeds.

**Comment by climbfuji** [comment]
@ulmononian Please confirm (later) that https://github.com/JCSDA/spack-stack/pull/674 fixed this issue. Thanks!

**Comment by ulmononian** [comment]
i copied `/work2/noaa/hwrf/scrub/bthomas/tar_test_spack_stack/hafs.t12z.dropsonde.tar` to my user space and did 

```
module purge
module use /work/noaa/epic/role-epic/spack-stack/hercules/modulefiles
module load ecflow/5.8.4
module load mysql/8.0.31

module use /work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-dev-20230717/envs/unified-env/install/modulefiles/Core
module load stack-intel/2021.9.0
module load stack-intel-oneapi-mpi/2021.9.0
module load stack-python/3.9.14

tar -xvf hafs.t12z.dropsonde.tar
```

it successfully untarred the file for me. 

@BijuThomas-NOAA can please you try the load sequence i listed above and try to untar a file (in the hafs workflow or however you were originally testing)? thank you!!

**Comment by BijuThomas-NOAA** [comment]
@ulmononian Thank you. It worked!

**Comment by climbfuji** [comment]
Closed via https://github.com/JCSDA/spack-stack/pull/674 :-) Thanks everyone!
