### ISSUE TITLE
Concretization issues

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#616]
We continue to have issues with duplicate packages, especially when an environment is reconcretized part way through an installation. This may be solvable by getting to the point where we can set `unify: true`, or by reporting the issue to the Spack developers. I'm working on producing a test case for the latter, though it's proven more difficult that I expected-- it may have to do with the subtleties of our config file layout, our use of certain external packages, etc.

**Comment by AlexanderRichert-NOAA** [comment]
I appear to have gotten around this problem for the moment on Acorn by using external 'flex'. I still want to understand why this is happening and get a fix from main Spack.

**Comment by climbfuji** [comment]
Looks like we are doing ok right now, whether that is due to updates from mainline spack or adding specs explicitly in spack.yaml.
