### ISSUE TITLE
Packages being built more than once 

### ISSUE THREAD

**Issue by kgerheiser** [JCSDA/spack-stack#62]
I had an issue with packages being concretized more than once with different hashes, and then module generation fails.

For example: 

```
[+]  p646jz7          ^bufr@11.5.0%intel@2021.2.0~ipo+python build_type=RelWithDebInfo patches=e1df1ac218da54b57e84712dfc0b6735b84ce14a72aa18ac0c3533d7d94bb740 arch=linux-centos7-skylake_avx512
[+]  5j5zboe              ^py-numpy@1.20.3%intel@2021.2.0+blas+lapack patches=873745d7b547857fcfec9cae90b09c133b42a4f0c23b6c2d84cf37e2dd816604 arch=linux-centos7-skylake_avx512
[+]  lnctc7m                  ^py-cython@0.29.24%intel@2021.2.0 arch=linux-centos7-skylake_avx512
[+]  gb2le4x                      ^py-pip@21.3.1%intel@2021.2.0 arch=linux-centos7-skylake_avx512
[+]  dqwpoqv                      ^py-setuptools@57.4.0%intel@2021.2.0 arch=linux-centos7-skylake_avx512
[+]  wxbkvbm                          ^py-wheel@0.37.0%intel@2021.2.0 arch=linux-centos7-skylake_avx512
```

```
[+]  p646jz7      ^bufr@11.5.0%intel@2021.2.0~ipo+python build_type=RelWithDebInfo patches=e1df1ac218da54b57e84712dfc0b6735b84ce14a72aa18ac0c3533d7d94bb740 arch=linux-centos7-skylake_avx512
[+]  bm3glwv          ^py-numpy@1.20.3%intel@2021.2.0+blas+lapack patches=873745d7b547857fcfec9cae90b09c133b42a4f0c23b6c2d84cf37e2dd816604 arch=linux-centos7-skylake_avx512
[+]  qbxqeen              ^openblas@0.3.19%intel@2021.2.0~bignuma~consistent_fpcsr~ilp64+locking+noavx512+pic+shared symbol_suffix=none threads=none arch=linux-centos7-skylake_avx512
[+]  lmjma7n                  ^perl@5.16.3%intel@2021.2.0+cpanm+shared+threads patches=0eac10ed90aeb0459ad8851f88081d439a4e41978e586ec743069e8b059370ac,3bbd7d6f9933d80b9571533867b444c6f8f5a1ba0575bfba1fba4db9d885a71a arch=linux-centos7-skylake_avx512
[+]  oah2cnu              ^py-cython@0.29.24%intel@2021.2.0 arch=linux-centos7-skylake_avx512
[+]  gb2le4x                  ^py-pip@21.3.1%intel@2021.2.0 arch=linux-centos7-skylake_avx512
```

You can see two instances of `py-numpy` being built with hashes `5j5zboe` and `bm3glwv`.

A solution I found is to run `spack install --reuse` or `spack concretize --reuse`, and then I only see once instance of `py-numpy` being built with hash `5j5zboe`.

The `--reuse` behavior is supposed to be the default in the next version of Spack.

**Comment by climbfuji** [comment]
> I had an issue with packages being concretized more than once with different hashes, and then module generation fails.
> 
> For example:
> 
> ```
> [+]  p646jz7          ^bufr@11.5.0%intel@2021.2.0~ipo+python build_type=RelWithDebInfo patches=e1df1ac218da54b57e84712dfc0b6735b84ce14a72aa18ac0c3533d7d94bb740 arch=linux-centos7-skylake_avx512
> [+]  5j5zboe              ^py-numpy@1.20.3%intel@2021.2.0+blas+lapack patches=873745d7b547857fcfec9cae90b09c133b42a4f0c23b6c2d84cf37e2dd816604 arch=linux-centos7-skylake_avx512
> [+]  lnctc7m                  ^py-cython@0.29.24%intel@2021.2.0 arch=linux-centos7-skylake_avx512
> [+]  gb2le4x                      ^py-pip@21.3.1%intel@2021.2.0 arch=linux-centos7-skylake_avx512
> [+]  dqwpoqv                      ^py-setuptools@57.4.0%intel@2021.2.0 arch=linux-centos7-skylake_avx512
> [+]  wxbkvbm                          ^py-wheel@0.37.0%intel@2021.2.0 arch=linux-centos7-skylake_avx512
> ```
> 
>  ```
> [+]  p646jz7      ^bufr@11.5.0%intel@2021.2.0~ipo+python build_type=RelWithDebInfo patches=e1df1ac218da54b57e84712dfc0b6735b84ce14a72aa18ac0c3533d7d94bb740 arch=linux-centos7-skylake_avx512
> [+]  bm3glwv          ^py-numpy@1.20.3%intel@2021.2.0+blas+lapack patches=873745d7b547857fcfec9cae90b09c133b42a4f0c23b6c2d84cf37e2dd816604 arch=linux-centos7-skylake_avx512
> [+]  qbxqeen              ^openblas@0.3.19%intel@2021.2.0~bignuma~consistent_fpcsr~ilp64+locking+noavx512+pic+shared symbol_suffix=none threads=none arch=linux-centos7-skylake_avx512
> [+]  lmjma7n                  ^perl@5.16.3%intel@2021.2.0+cpanm+shared+threads patches=0eac10ed90aeb0459ad8851f88081d439a4e41978e586ec743069e8b059370ac,3bbd7d6f9933d80b9571533867b444c6f8f5a1ba0575bfba1fba4db9d885a71a arch=linux-centos7-skylake_avx512
> [+]  oah2cnu              ^py-cython@0.29.24%intel@2021.2.0 arch=linux-centos7-skylake_avx512
> [+]  gb2le4x                  ^py-pip@21.3.1%intel@2021.2.0 arch=linux-centos7-skylake_avx512
> ```
> 
> You can see two instances of `py-numpy` being built with hashes `5j5zboe` and `bm3glwv`.
> 
> A solution I found is to run `spack install --reuse` or `spack concretize --reuse`, and then I only see once instance of `py-numpy` being built with hash `5j5zboe`.
> 
> The `--reuse` behavior is supposed to be the default in the next version of Spack.

Yes, I had the same. I always use `spack concretize --reuse`. There is also an open PR in the official spack repo that will make the `--reuse` flag the default: https://github.com/spack/spack/pull/29111 - it's part of the set of upcoming high impact changes https://github.com/spack/spack/issues/24223.

**Comment by kgerheiser** [comment]
I was just looking at that PR and I think we can make re-use the default in our `spack.yaml` if we want to with:

```
 concretizer:
     reuse: true
```

**Comment by kgerheiser** [comment]
I looked into adding a `concretizer.yaml`, but our version of Spack doesn't support this. It was just recently added around a month ago. In the future when we update Spack, we should enable reuse. By that time it might be the default option so there might be nothing to do.
