### ISSUE TITLE
UPP failed with spack-stack-1.3.1 and spack-stack-1.4.0 on Hercules

### ISSUE THREAD

**Issue by BijuThomas-NOAA** [JCSDA/spack-stack#623]
The UPP component in HAFS system failed with both spack-stack-1.3.1 and spack-stack-1.4.0 on Hercules. @WenMeng-NOAA also tested UPP on Hercules and reported the same kind of failure. Based on @WenMeng-NOAA tests,  UPP can be run successfully without generating simulated satellite products.  @WenMeng-NOAA think the issue might be in crtm/2.4.0 installation or fix files for crtm/2.4.0([issue 719](https://github.com/NOAA-EMC/UPP/issues/719))

**Comment by ulmononian** [comment]
@BijuThomas-NOAA @WenMeng-NOAA would either of you be willing to share the build and run steps you used to test the UPP against spack-stack on hercules? it will help to debug the issue if i can ensure that i configure the build/test environment and compile the executables exactly as it was done in @BijuThomas-NOAA's hafs testing or however @WenMeng-NOAA tested. thank you!!! :)

**Comment by WenMeng-NOAA** [comment]
@ulmononian I set up a UPP test case at /home/wmeng/stmp2/UPP_hercules/UPP on Hercules:
1) modules for building UPP executable: UPP/modulefiles/hercules.lua
2) UPP building script: UPP/tests/compile_upp.sh
3) the driver script for running UPP for HAFS: UPP/submit_run_post_fv3hafs_hercules.sh
   modules for runtime in that script are:
    ```
   module purge
   module use /work/noaa/epic-ps/role-epic-ps/spack-stack/spack-stack-1.3.1-hercules/envs/unified- 
   env/install/modulefiles/Core
   module load stack-intel/2021.7.1
   module load stack-intel-oneapi-mpi/2021.7.1
   module load jasper/2.0.32
   module load crtm/2.4.0
   module load crtm-fix/2.4.0_emc
   module load prod-util/1.2.2
    ```
Please let me know if you see issues in my testing configuration. Thanks!

**Comment by ulmononian** [comment]
@WenMeng-NOAA thanks for sharing this test case. based on what you shared, i re-built the upp w/ slightly adjusted modulefile and runtime environment, but it failed in the exact same way reported by @BijuThomas-NOAA and yourself. my test is here `/work2/noaa/epic-ps/cbook/HERCULES/UPP/cb_new/UPP`. a closer look will be needed.

**Comment by WenMeng-NOAA** [comment]
I tested the UPP with the latest spack-stack from /work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-1.4.1/envs/unified-env/install/modulefiles/Core on Hercules. The UPP still crashed at generating simulated satellite data process which call crtm/2.4.0. The error messages are same as the ones noted in the UPP issue #[719](https://github.com/NOAA-EMC/UPP/issues/719). I wonder if any applications else have crtm issue as UPP? 
If someone would like to check job configuration, the job card of my UPP test case is /home/wmeng/stmp2/UPP_hercules/UPP/submit_run_post_fv3hafs_hercules.sh

**Comment by climbfuji** [comment]
We installed a new version of the stack using the latest intel compilers, can you try that please?
```
module purge
module use /work/noaa/epic/role-epic/spack-stack/hercules/modulefiles
module load ecflow/5.8.4
module load mysql/8.0.31

# For spack-stack-dev-20230717 with Intel, load the following modules after loading miniconda and ecflow:

module use /work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-dev-20230717/envs/unified-env/install/modulefiles/Core
module load stack-intel/2021.9.0
module load stack-intel-oneapi-mpi/2021.9.0
module load stack-python/3.9.14
module available
```

**Comment by WenMeng-NOAA** [comment]
@climbfuji The new version of spack-stack is working in UPP for generating simulated satellite products.

**Comment by climbfuji** [comment]
Yay! Thanks for letting us know. I am going to close this issue as completed.

**Comment by WenMeng-NOAA** [comment]
@climbfuji Thanks for your help! I will update UPP modulefiles with this version of spack-stack on Hecules.

**Comment by climbfuji** [comment]
Credits go to @ulmononian for getting this fixed.
