### ISSUE TITLE
Set some package settings explicitly in unified-dev template

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#627]
We should consider explicitly associating certain packages (namely, ones with multiple versions/variants) with metapackages in unified-dev/spack.yaml in order to be able to install our environments in one go without reconcretizing. Spending hours building only to reconcretize only to find that you can't convince Spack to install another ESMF _without_ installing another zlib/hdf5/netcdf-c/netcdf-fortran chain is the path to sadness.

Related to #616

**Comment by climbfuji** [comment]
I agree. This does however not solve the problem when adding new versions during the lifetime of a spack-stack installation. I found in my many tries that when using something like
```
spack install --add --verbose esmf@8.4.2%intel
```
I got away very often w/o duplicate packages.

I also noted that the spack v0.20.0 release (which is a bit newer than what we have in our fork) behaves a bit differently when adding new packages: it only concretizes the new specs but leaves everything that is installed alone.

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA I ended up doing that in https://github.com/JCSDA/spack-stack/pull/722.

**Comment by AlexanderRichert-NOAA** [comment]
Hm that's odd, that's how I've been able to avoid trouble when adding packages after installation, is getting really explicit in spack.yaml about which metapackages get which version of a package that I'm adding an extra version of (I used this for example when we were adding the 2nd versions of ESMF and MAPL for UFS). Anyway, there may not be anything we need to do here for the moment, apart from keep it in mind as an option when we need to update an existing environment.
