### ISSUE TITLE
INFRA-53.1: spack-stack-1.4.1 bug fix release

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#630]
## Description

This epic contains the necessary information for creating the spack-stack-1.4.1 bug fix release. The main purpose of this release is to provide full support for the UFS Weather Model, but other minor updates can be included as well.

**Comment by climbfuji** [comment]
Done and dusted!

**Comment by symoore90** [comment]
Hi @climbfuji can you add INFRA-53.1 to the title of this epic?

**Comment by AlexanderRichert-NOAA** [comment]
@symoore90 please let me know if that looks right

**Comment by symoore90** [comment]
@AlexanderRichert-NOAA , this looks good thank you!
