### ISSUE TITLE
[INSTALL] Variables jedi-neptune-env/unified-dev module on nautilus 

### ISSUE THREAD

**Issue by areinecke** [JCSDA/spack-stack#634]
Please add the following variables to the `jedi-neptune-env/unified-dev` module on nautilus:

setenv SPACK_STACK_INSTALL t
set NEPHOME "/p/app/projects/NEPTUNE"
setenv HOST nautilus
setenv NEPHOME $NEPHOME
setenv DATABASE_GFS $NEPHOME/database/auxiliary-physics-files
setenv DATABASE_PHYSICS $NEPHOME/database/auxiliary-physics-files
setenv DATABASE_TERRAIN $NEPHOME/database
setenv DATABASE_HA $NEPHOME/database/high_altitude_physics
setenv GLOBAL_DATA $NEPHOME/global
setenv GLOBAL_DATA2 $NEPHOME/global

**Which software in the stack would you like installed?**
Please provide the name of the software you would like installed on the HPCs.  Ensure the software exists in the list of supported software.  If new software needs to be added to the stack, use the [add_package_request.md](./add_package_request.md) template.

**What is the version/tag of the software?**
Please provide the version/tag of the software to be installed.

**What compilation options would you like set?**
Give a detailed list of compilation options, compiler and MPI flavors and versions, etc.

**Which machines would you like to have the software installed?**
See currently managed HPC machines.

**Any other relevant information that we should know to correctly install the software??**
Please describe in as much detail as possible.

**Additional context**
Add any other context or screenshots about the install request here.

**Comment by climbfuji** [comment]
@areinecke I am afraid we can't do that. spack-stack is more or less host-agnostic, we shouldn't put host-dependent environment variables into a (somewhat unrelated) software stack. I'll have to ask you to create your own module file for these environment variables and then load that before/after loading the software stack.
