### ISSUE TITLE
Configuration template for UFS_UTILS.

### ISSUE THREAD

**Issue by HenryRWinterbottom** [JCSDA/spack-stack#644]
**Is your feature request related to a problem? Please describe.**
The UFS global workflow requires several software packages for research and development. One of them is [UFS_UTILS](https://github.com/ufs-community/UFS_UTILS). Currently a template does not exist to build the required software stack for using spack-stack.

**Describe the solution you'd like**
A configuration template beneath `config/templates` specific to the `UFS_UTILS` software packages.

**Comment by climbfuji** [comment]
@HenryWinterbottom-NOAA Are the current templates and environment packages sufficient, or is there more that needs to be done?

**Comment by HenryRWinterbottom** [comment]
@climbfuji I haven't worked with this since our last conversation https://github.com/JCSDA/spack-stack/pull/645.

However, my testing at the time resulted in successful compilation. If the templates are sufficient please use them. My recollection is that you had to load the modules manually. The templates I provided were able to load the necessary modules.

**Comment by climbfuji** [comment]
Thanks for the quick reply. In #645 you mentioned:
> I would like to try and configure this myself using your explanations above. It will provide me an opportunity to learn something new. If it's OK, maybe I just try to learn through this PR? Once it is working as it should we could just move the ufs-utils-env into the release as I think you are suggesting above?
Please revive the PR or open a new one once/if you have updates. Thanks!

**Comment by HenryRWinterbottom** [comment]
Thank you for the reminder.

Can I take a look at this next week? I can see if I can (1) successfully implement your suggestions and (2) prepare things accordingly for a JCSDA PR. 

How does that work for you?

**Comment by climbfuji** [comment]
No rush, just checking what should go into spack-stack 1.5.0 around end of August.

**Comment by HenryRWinterbottom** [comment]
@climbfuji OK, great. I will try to carve out some time next week to take a look. I will follow-up with questions.

Thanks again and have a nice weekend.

**Comment by climbfuji** [comment]
Closed by #707
