### ISSUE TITLE
Update met to 11.1.0 once released and adjust date range for patch

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#646]
**Describe the bug**
This is just a reminder that until `met@11.0.3` is released, we can't build `met@11` (and therefore `metplus@5` and `global-workflow-env`) on macOS. I previously thought this was only the case for the M1 (`aarch64`) architecture, but it is the same on Intel (`x86-64`).

**UPDATE** - see https://github.com/JCSDA/spack-stack/issues/646#issuecomment-1636282170

**To Reproduce**
Try it.

**Expected behavior**
The error is expected. This issue will be closed by a PR that adds `met@11.0.3`, once released.

**System:**
macOS (version and architecture don't matter)

**Additional context**
n/a

**Comment by climbfuji** [comment]
This is actually on a problem on release-1.4.x, because develop has a patch:

https://github.com/JCSDA/spack/blob/01d6aa5239a8f46862d0f35a9f3533afdb9151a2/var/spack/repos/builtin/packages/met/package.py#L63

When met@11.1.3 or whatever the tag is comes out, then this patch will no longer be needed and likely fail. We should then update the `when` statement accordingly - keeping this issue open until that is done.

**Comment by srherbener** [comment]
The expected release date for met@11.1.0 which will contain the fixes we need to remove the patches is targeted for July 31, 2023.

**Comment by climbfuji** [comment]
It's been released, I will work on the update next week.
