### ISSUE TITLE
parallelio build failure with apple-clang 12.0.5 (but not with (llvm-)clang)

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#66]
parallelio fails to build with errors about conflicting type definitions when using apple-clang 12.0.5. This was reported by two people independently. It builds fine on my macOS with llvm-clang@13.0.0.

I will try to reproduce the error and paste the exact error message here.

**Comment by climbfuji** [comment]
I tested this on my mac with apple-clang@13.0.0 and parallelio-2.5.2 builds fine. @shlyaeva

**Comment by shlyaeva** [comment]
I'm going to try again tomorrow, and will post the error message.

**Comment by kgerheiser** [comment]
Is it this issue? https://github.com/NOAA-EMC/spack/issues/17

Looks like a legitimate build problem, perhaps related to the MPI version.

**Comment by kgerheiser** [comment]
If so, the fix was merged with https://github.com/NCAR/ParallelIO/pull/1916

We could create a patch from this PR.

**Comment by shlyaeva** [comment]
@kgerheiser yes, the same issue; patching would be great!
**update** and I was building with mpich4.0.1, which agrees with the issue reported in https://github.com/NCAR/ParallelIO/issues/1912

**Comment by kgerheiser** [comment]
Fixed with the submodule update in #88
