### ISSUE TITLE
Upgrade ip to 4.x

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#661]
ip 3.3.3 is aging, so let's move to 4.x for v1.5.0.

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA Just to check again, this won't be going into the release because you'll do the NCEPlibs batch update after everything went to spack develop, correct?

**Comment by AlexanderRichert-NOAA** [comment]
No, this doesn't require the batch of NCEPLIBS updates (which I'm going to push to main spack first anyway because of some other stuff I'm working on for NCEPLIBS), it'll just need an update to the grib_util recipe once the release is out some time today.

**Comment by climbfuji** [comment]
Ok, thanks. I wasn't sure if the release will be available in time. I would like to start installing tonight/over the weekend, if possible.

**Comment by climbfuji** [comment]
This was resolved on the release branch in https://github.com/JCSDA/spack-stack/issues/767 and will come back to develop when the release branch gets merged back.
