### ISSUE TITLE
add json and json-schema-validator packages for all jedi applications

### ISSUE THREAD

**Issue by shlyaeva** [JCSDA/spack-stack#67]
Add nlohmann-json and nlohmann-json-schema-validator to packages used with all jedi applications (they are used for YAML validations across JEDI).

**Comment by kgerheiser** [comment]
Hmm, I thought we had this. We have an entry for it in the modules. @climbfuji where would be the best repo to put this?`jedi-base-env`? `jedi-tools-env`?

**Comment by shlyaeva** [comment]
@kgerheiser Sorry, I should've added that I'll open a PR (@climbfuji helped with putting it together): https://github.com/NOAA-EMC/spack-stack/pull/72

**Comment by climbfuji** [comment]
@kgerheiser We added it to the jedi-base-env it's needed in the bundles.
