### ISSUE TITLE
Resolve ioda-converters test failure when using bufr v12.0 library

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#670]
Initial testing using spack-stack-1.4.1 on S4, Intel/Impi, using jedi-bundle including ioda-converters resulted in one ioda-converters test failure: `test_iodaconv_prepbufr_ncep_api_adpsfc2ioda`

Details of the failure:
```
1383/2091 Testing: test_iodaconv_prepbufr_ncep_api_adpsfc2ioda
1383/2091 Test: test_iodaconv_prepbufr_ncep_api_adpsfc2ioda
Command: "/usr/bin/bash" "/data/users/sherbener/jedi/build-intel/bin/iodaconv_comp.sh" "netcdf" "/data/users/sherbener/jedi/venv/bin/python3.9 testinput/prepbufr_adpsfc_api.py" "prepbufr_adpsfc_api.nc" "0.0"
Directory: /data/users/sherbener/jedi/build-intel/iodaconv/test
"test_iodaconv_prepbufr_ncep_api_adpsfc2ioda" start time: Jul 12 20:41 UTC
Output:
----------------------------------------------------------

 ***********BUFR ARCHIVE LIBRARY ABORT**************
 BUFRLIB: NEMTBB - ITAB (      0) NOT FOUND IN TABLE B                                               
 ***********BUFR ARCHIVE LIBRARY ABORT**************

<end of output>
Test time =   0.68 sec
----------------------------------------------------------
Test Failed.
"test_iodaconv_prepbufr_ncep_api_adpsfc2ioda" end time: Jul 12 20:41 UTC
"test_iodaconv_prepbufr_ncep_api_adpsfc2ioda" time elapsed: 00:00:00
```

Here is the issue in ioda-coverters that we can use to track this: https://github.com/JCSDA-internal/ioda-converters/issues/1292

**Comment by climbfuji** [comment]
This also fails on develop on S4, so not related to the new bufr library.

**Comment by srherbener** [comment]
This turns out to be an issue with bufr@12.0.0 which needs to be debugged and fixed. The develop failure was due to a mixup with which library the test code was linked to (which turned out to be bufr@12.0.0). Recent testing demonstrated that bufr@11.7.1 works (all ioda-converters tests pass) with develop branchs.

**Comment by ashley314** [comment]
This has been fixed. Thanks!
