### ISSUE TITLE
INFRA-53.2: spack-stack-1.5.0 library updates

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#676]
**Is your feature request related to a problem? Please describe.**
This epic collects library updates for spack-stack-1.5.0 with a preliminary release date of September 9.

**Comment by DavidHuber-NOAA** [comment]
A note on the GSI.  There are demonstrable differences when using bufr/12.0.0 in the GSI.  It appears that it is related to the virtual temperature retrieved by certain data types and is being investigated.  See NOAA-EMC/GSI#589 for more details.

**Comment by symoore90** [comment]
Hi @climbfuji I don't have editing rights. Do you mind adding INFRA-53.1 to the beginning of this epic

**Comment by srherbener** [comment]
> Hi @climbfuji I don't have editing rights. Do you mind adding INFRA-53.1 to the beginning of this epic

@symoore90, Dom is on leave now so I updated the title of this epic as you requested.

**Comment by symoore90** [comment]
Hi @srherbener one more thing can you add it to the roadmap under the infrastructure project and add dates as well

**Comment by climbfuji** [comment]
We updated all the libraries for the release, now it's time to roll it out!
