### ISSUE TITLE
readthedocs rendering of tier 1 spack-stack install table not working

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#677]
**Describe the bug**
See https://spack-stack.readthedocs.io/en/latest/PreConfiguredSites.html - something must have gone wrong with the rendering of the table in the latest PR https://github.com/JCSDA/spack-stack/pull/675

**Additional context**
Columns need to be the same width for tables to be rendered correctly

**Comment by ulmononian** [comment]
i see what happened here. my mistake. 

do you want a PR for this or can we just directly commit the fix lol

**Comment by climbfuji** [comment]
PR
