### ISSUE TITLE
Request for a python API suited for reading GRIB files for use in ioda-converters

### ISSUE THREAD

**Issue by gthompsnJCSDA** [JCSDA/spack-stack#678]
**Please describe the package or library you would like to add to spack-stack.**
py-pygrib or grib2io (to be determined)

_EDIT Dom: This package also needs to go into the CI containers._

**What applications will be using this package or library?**
For help in converting some GRIB2 data into IODA, the ioda-converters repo has a couple of outdated python codes to convert snow depth (in `src/land`) and I added a converter for MRMS radar data that uses pygrib to ingest the GRIB2 data in a python script (`feature/new_mrms_reflectivity:/src/mrms/mrms_grib2ioda.py`)

**Is there already a package or library in spack-stack that provides this, or related, functionality?**
Unknown - _EDIT Dom: NO_

**Additional context**
Nothing additional known

**Will This Package be Needed in a NOAA Operational Application?**
Unknown - _EDIT Dom/SteveH: Unlikely, but note pygrib is not approved while grib2io is approved_

**WCOSS System Software Request Checklist**

General questions:

Supervisor or sponsor of the requester
JCSDA

Software name and version, specific URL to the software
The specific version I used when developing the ioda-converter was: `    py-pygrib: version: [2.1.4]`

Software type - New or Upgrade existing?
?

Justification ( List NPS models using the software)
?

Completion Time requested
ASAP

Software License including all Dependency Software Licenses 
?

Support contact(s) who must have a WCOSS account
?

Dependency Software list
?

Installation instructions
?

Test and verification instructions
?

Technical Review Checklist for open source software - Review the source code to answer the following questions

Licenses for the requested software and its dependencies

Licenses -  confirm the software Licenses are acceptable

Maturity

Acceptable - Stable, production, or equivalent

Self-contained

No external http, https,  ftp, or other URI exists except that in comments

No binary files in the package unless they are in the approved list

No publicly disclosed cybersecurity vulnerabilities and exposures 

Searching https://cve.mitre.org/cve/

Security High Level Checklists 

Is it prohibited by DHS/DOC/NOAA/NWS

Is it provided by a trusted source? Trusted sources include other NWS, NOAA, or DOC, agencies, or other Federal agencies that operate at a FISMA high or equivalent level. Additionally, trusted sources could be third-party agencies through which there is an existing SLA on file (such as RedHat). 

Is software support offered (is it being updated and patched). 

If maintained by a private entity, does the entity operate in a foreign country, especially a prohibited foreign country (China, Russia, Iran, North Korea, etc.). 

Is there sufficient documentation to support maintenance 

Are there known vulnerabilities or weaknesses

Is there a need for privileged processes 

Are there software dependencies, are those dependencies approved or do they have any security concerns 

Are there any other concerns related to SA, SI, and SC control families

**Comment by srherbener** [comment]
The decision between pygrib and grib2io is being discussed here: https://github.com/JCSDA-internal/ioda-converters/pull/1301

We are leaning toward grib2io, but the decision hasn't been finalized yet.

**Comment by AlexanderRichert-NOAA** [comment]
@srherbener is it correct to say that the dependencies are there either way? I think it's safe to say g2c isn't going anywhere; do you know if eccodes will always and forever be used by JEDI?

**Comment by gthompsnJCSDA** [comment]
> @srherbener is it correct to say that the dependencies are there either way? I think it's safe to say g2c isn't going anywhere; do you know if eccodes will always and forever be used by JEDI?

My 2 cents only:  a very emphatic yes in my opinion that `eccodes` is useful to JCSDA developers and partner agencies (other than NOAA evidently) as it is a highly supported piece of software with a lot of documentation and FAQ material at ECMWF.

**Comment by srherbener** [comment]
I believe that eccodes is here to stay with JCSDA. As @gthompsnJCSDA points out eccodes is quite useful.

So, I think that the dependencies for both pygrib and grib2io are in place.

One question: pygrib is a python API to eccodes while grib2io is a python API to necplibs-g2c. Do the underlying libraries, eccodes and g2c, handle the same GRIB file format/layout? In other words is there a reason to choose one of eccodes or g2c because of the way the GRIB files are constructed? (I'm thinking of the example of WMO bufr vs prepBUFR)

**Comment by srherbener** [comment]
Note that py-eccodes and eccodes provide a python API for reading GRIB files and they already exist in spack-stack-1.4.0. This might be the best option (certainly from the spack-stack perspective since we want to minimize duplicating features). See discussion in: https://github.com/JCSDA-internal/ioda-converters/pull/1301

**Comment by gthompsnJCSDA** [comment]
When I can replicate the MRMS converter replacing pygrib methods with direct solutions using only eccodes, I will close this issue.  So this might be temporary.  TBD.

**Comment by ashley314** [comment]
@gthompsnJCSDA Have you tested this?

**Comment by gthompsnJCSDA** [comment]
> @gthompsnJCSDA Have you tested this?

This has been on my backburner for the past 2 weeks, but I am resuming effort later this week on it.

**Comment by gthompsnJCSDA** [comment]
I suggest this can now be closed per the new #751 PR that resolves the component trying to use pygrib was re-coded.
