### ISSUE TITLE
Add environment chaining features to our Spack extensions

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#680]
Per our earlier discussion about plans to support updates between releases, we should modify our `create env` and `setup-meta-modules` commands to support chained environments. Specifically, for the former, we can add a `--upstream=/path/to/upstream/spack-stack-1.4.1/envs/unified-env/install` that adds an `upstreams:` section to spack.yaml. We could then either modify `setup-meta-modules` or add a new command which copies over module files from the upstream environment so that they can all be accessed in one place. To handle the situation where, say, we want to try a new version number of ESMF and all of its dependencies, we could make a list of packages consisting of the root spec(s) for the downstream environment (e.g., ESMF) and the output of `spack dependents` (e.g., MAPL, etc.) to clear out those now-obsolete modulefiles and avoid confusion/conflicts.

**Comment by climbfuji** [comment]
Another idea would be to modify the `spack stack setup-meta-modules` command for chained environments to automatically add the upstream module paths with the correct priorities so that anything in the chained environment will have higher priority.

**Comment by AlexanderRichert-NOAA** [comment]
Note to self, apparently there's a `--upstream-modules` option for `spack module {lmod,tcl} refresh` that installs modules for upstream installed packages.
