### ISSUE TITLE
Update of eckit and fckit for spack-stack-1.5.0

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#686]
**Please describe the package or library you would like to add to spack-stack.**

1. Update eckit version to the one that fixes bug affecting saber interpolations (ask @fmahebert)
2. We need a variant for `fckit` to disable the "auto final" option on Hercules (or, better: for `intel@2021.9.0` and only for that version for now).

- [x] eckit version 1.24.4
- [x] fckit version 0.11.0

**What applications will be using this package or library?**
JCSDA/JEDI

**Is there already a package or library in spack-stack that provides this, or related, functionality?**
Both of them are already in spack-stack and, with the fisma-high variant, approved for installation on wcoss2.

**Additional context**
n/a

**Will This Package be Needed in a NOAA Operational Application?**
Yes - see above.

**Comment by fmahebert** [comment]
That would be eckit tag 1.24+

**Comment by srherbener** [comment]
@fmahebert this is the issue I was thinking of in today's JCSDA update meeting. This issue mentions eckit and fckit version updates, but does not mention atlas. Should we modify this issue to include atlas? Or do you think it's better to create a new issue for atlas? Thanks!

**Comment by fmahebert** [comment]
@srherbener Thanks for the ping. AFAIK the eckit tag I pasted above is still our most up-to-date requirement for JEDI.

Let's open a new spack-stack issue for atlas because that will be an independent decision based on PRs and conversations still in the future.

**Comment by srherbener** [comment]
Sounds good. I'll create the atlas update issue now, and we can fill in the version later. We are probably going to set a freeze on spack-stack-1.5.0 changes in 2 or 3 weeks (after Dom gets back). We would need to get the atlas version specified by then. Thanks!
