### ISSUE TITLE
[INSTALL] bufr/11.7.0 and gsi-ncdiag/1.1.1 under spack-stack 1.4.1

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [JCSDA/spack-stack#687]
Note: Please search to see if an issue already exists for the software you are requesting to be installed.

**Which software in the stack would you like installed?**
bufr and gsi-ncdiag.

**What is the version/tag of the software?**
11.7.0 and 1.1.1, respectively

**What compilation options would you like set?**
Required for both Intel and GNU builds (where GNU is already rolled out).  Default settings are fine.

**Which machines would you like to have the software installed?**
Hera, Orion, Hercules, Jet, Gaea, S4, Cheyenne, and the Parallel Works AWS, GCP, and Azure instances.

**Any other relevant information that we should know to correctly install the software??**
This should be incorporated into the spack-stack/1.4.1 builds.

**Additional context**
This is required in order to build the GSI against spack-stack.  The GSI needs some additional work to run correctly with bufr 12.0.0 and there are new features in the gsi-ncdiag/1.1.1 library that fix bugs in the GSI itself.  These will both be needed before the GSI can be rolled out with the SRW app.  Related issues and PRs: noaa-emc/gsi#571, noaa-emc/gsi#563, noaa-emc/gsi#589.  This has been tested successfully on Hera, Jet, Orion, and the Parallel Works platforms using test builds of spack-stack/1.4.1.

**Comment by AlexanderRichert-NOAA** [comment]
Unfortunately I don't have access to the installations on these machines, but I tested these changes on Acorn successfully. I uninstalled the existing bufr and gsi-ncdiag, as well as py-scipy (though that may have been a system-specific issue), and updated common/packages.yaml (which included adding an entry for gsi-ncdiag) and added v1.1.1 to gsi-ncdiag/package.py (`version("1.1.1", sha256="26fc10cf448dd62daa1385e38921d338778416342956c478337e6c6d1b20bf8c")`).

**Comment by ulmononian** [comment]
@AlexanderRichert-NOAA thanks for doing that.

@DavidHuber-NOAA i will do the first-pass check on cheyenne, jet, or gaea first (since they are used less than hera/orion),and once all looks clear, update the rest of the machines. i don't have access to s4, though. also: aws may have to wait until we are granted more allocation.

**Comment by ulmononian** [comment]
`bufr/11.7.0` + `gsi-ncdiag/1.1.1` have been added to the official hera, orion, jet, gaea c3/c4, & cheyenne `spack-stack-1.4.1/unified-env` installations, as well as to the official gaea c5 & hercules `spack-stack-dev-20230717/unified-env` installations. i added them as part of the `gsi-env`, so everything needed for gsi can be loaded via `module load gsi-env` (after the usual prereq. loads, of course). 

other virtual environment packages (i.e., all other than `gsi-env`) will still load w/ the previous bufr version, so users will need to manually load `bufr/11.7.0` and/or `gsi-ncdiag/1.1.1` if they want these in their module environment. this was done to safeguard the integrity of the existing stacks and maintain continuity for those who may be using `bufr/12.0.0`.

s4 & parallel works still need to be done.

**Comment by ulmononian** [comment]
@mark-a-potts can you please do s4 and the parallel works instances?

**Comment by mark-a-potts** [comment]
I finished the installs on the NOAA cloud platforms, but I don't think I have access to update the stack on s4 right now.

**Comment by climbfuji** [comment]
Is S4 still needed?

**Comment by ulmononian** [comment]
i am not sure if it is _needed_ at this point given the gsi situation (@DavidHuber-NOAA?), but you may want to install if there for consistency.

**Comment by DavidHuber-NOAA** [comment]
@ulmononian @climbfuji It would be nice to have for both the UFS and the GSI, but I'm OK with waiting until 1.5.0 is released for S4 if necessary.

**Comment by climbfuji** [comment]
@DavidHuber-NOAA I installed  gsi-ncdiag@1.1.1 and bufr@11.7.0 on S4 in spack-stack-1.4.1.

**Comment by climbfuji** [comment]
@davidhuber-noaa did you have a chance to check the spack-stack-1.4.0 bufr@11.7.0 gsi-ncdiag@1.1.1 install?

**Comment by DavidHuber-NOAA** [comment]
@climbfuji Not spack-stack-1.4.0.  I was able to test the 1.4.1 install which worked perfectly for the UFS regression tests.

For the GSI, these installs have worked perfectly as well with one known bug in the GSI remaining for hdf5/1.14.0 that we are still working on.

I will go ahead and close this as resolved.  Thanks!
