### ISSUE TITLE
py-cython being built twice with different hashes

### ISSUE THREAD

**Issue by kgerheiser** [JCSDA/spack-stack#69]
On Orion I'm getting:

`[+]  oah2cnu ^py-cython@0.29.24%intel@2021.2.0 arch=linux-centos7-skylake_avx512`

And 

`[+]  lnctc7m  ^py-cython@0.29.24%intel@2021.2.0 arch=linux-centos7-skylake_avx512`

because two versions of `py-setuptools` are being used (57.4.0 and 59.4.0):

```
[+]  yi6zl45   ^py-setuptools@59.4.0%intel@2021.2.0 arch=linux-centos7-skylake_avx512
[+]  dqwpoqv ^py-setuptools@57.4.0%intel@2021.2.0 arch=linux-centos7-skylake_avx512
```

With the bufr py-cython from nceplibs-bundle being different than the one from jedi-base-env.

I'm thinking one of the Python packages in JEDI is somehow forcing a different version (a conflict somewhere?) because nceplibs has no other use of Python. It is strange though that the nceplibs-bundle bufr is trying to use an older version of py-setuptools. Adding version 57.4.0 to packages.yaml lets them all be built with the same version, but trying to prefer 59.4.0 doesn't (57.4.0 is still built in one of the concretizations).

I'm going to look into it a little more to see why the concretizations are different, but preferring 57.4.0 should work.

**Comment by climbfuji** [comment]
Was did after my PR got mergesd yesterday? I took jedi-tools-env out of the jedi-all and all applications. Can you check if you have jedi-tools-env in your specs?

I have no problem going back to 57.4.0.

**Comment by kgerheiser** [comment]
Let me check... it's also possible I didn't pass --reuse either.

**Comment by kgerheiser** [comment]
Still an issue with the most recent develop. Off the top of your head do you know if there's something in JEDI that causes it to use `py-setuptool@57.4.0`? We can just pin 57.4.0 as the preferred version as an easy fix.

**Comment by climbfuji** [comment]
> Still an issue with the most recent develop. Off the top of your head do you know if there's something in JEDI that causes it to use `py-setuptool@57.4.0`? We can just pin 57.4.0 as the preferred version as an easy fix.

I am not aware of any, but I am totally fine with using 57.4.0.

**Comment by kgerheiser** [comment]
Think I found what was happening. `py-scipy` `depends_on('py-setuptools@:57', when='@1.7:', type='build')` and we are using 1.7.3.

**Comment by kgerheiser** [comment]
And interestingly, I think each bundle is concretized separately (but a single bundle as whole). Hypothetically, if we turned the `all` environment into a single bundle that used the other bundles, everything would be concretized together and prevent this from happening.

**Comment by climbfuji** [comment]
> And interestingly, I think each bundle is concretized separately (but a single bundle as whole). Hypothetically, if we turned the `all` environment into a single bundle that used the other bundles, everything would be concretized together and prevent this from happening.

Coming back to this ... we can't concretize everything together, because of the ufs-weather-model-debug-env, i.e. the requirement to have esmf+debug and a consistently built mapl+debug. One environment cannot depend on two different versions of the same package. We can revive the jedi-env mother-of-all environment that has everything except jedi-tools (because of these Python dependency conflicts) and ufs-weather-model-debug-env.

**Comment by kgerheiser** [comment]
I know we can't concretize together formally (`concretization: together`), but if we turned 'all' into a bundle instead of listing specs like:

```
specs:
- jed-env
- ufs-weather-env
- nceplibs-bundle
- ...
```

And did this instead:

```
specs:
- all-bundle-env
```

My hypothesis is that this counts as a single package is concretized as one, instead of going through `concretizing jedi-env`, `ufs-weather-bundle`, `nceplibs-bundle` . And in the case of `py-setuptools`, `nceplibs-bundle` would have taken the version required by `py-scipy` because it's listed as a single spec.

**Comment by climbfuji** [comment]
> I know we can't concretize together formally (`concretization: together`), but if we turned 'all' into a bundle instead of listing specs like:
> 
> ```
> specs:
> - jed-env
> - ufs-weather-env
> - nceplibs-bundle
> - ...
> ```
> 
> And did this instead:
> 
> ```
> specs:
> - all-bundle-env
> ```
> 
> My hypothesis is that this counts as a single package is concretized as one, instead of going through `concretizing jedi-env`, `ufs-weather-bundle`, `nceplibs-bundle` . And in the case of `py-setuptools`, `nceplibs-bundle` would have taken the version required by `py-scipy` because it's listed as a single spec.

I still don't think that you will get esmf built both with ~debug and +debug though ... (and then the same for mapl). That was the issue I had with the original ufs-weather-model-env that had
```
depends_on('esmf+debug')
depends_on('esmf~debug')
```
You could do 
```
depends_on('esmf+debug', when='+debug')
depends_on('esmf~debug', when='~debug')
```
in ufs-weather-model-env, but then you'd have to install `ufs-weather-model-env+debug` and `ufs-weather-model-env~debug`, just moving the switch up one step.

**Comment by kgerheiser** [comment]
Ah, you may be right. I haven't tried it.

**Comment by climbfuji** [comment]
> Ah, you may be right. I haven't tried it.

I played this game for a few hours a couple of days ago. We can put everything in a bundle except the debug versions of esmf and mapl, and then have the concretizer process the mother-of-all-env and the additional ufs-weather-model-debug-env.

**Comment by climbfuji** [comment]
I just tried `concretization: together` and it worked as long as I don't use ufs-weather-model-debug-env.
