### ISSUE TITLE
Update ReadTheDocs configuration 

### ISSUE THREAD

**Issue by srherbener** [JCSDA/spack-stack#691]
**Is your feature request related to a problem? Please describe.**

ReadTheDocs is changing the way configuration is being done. The build engine at ReadTheDocs has been automatically providing default configuration (via a .readthedocs.yaml file), and they will stop doing this meaning that we have to specify a .readthedocs.yaml file in our project. The deadline for fixing this is Sep 25, 2023.

**Describe the solution you'd like**

Add a .readthedocs.yaml file to the project to satisfy the upcoming requirement from ReadTheDocs.

**Additional context**

Here are some references:

https://blog.readthedocs.com/migrate-configuration-v2/

https://docs.readthedocs.io/en/stable/examples.html

**Comment by srherbener** [comment]
@AlexanderRichert-NOAA, @ulmononian are either of you getting notifications from ReadTheDocs about this? I think you have to be an admin for the spack-stack ReadTheDocs project to receive the notifications.

I received notifications for JCSDA ReadTheDocs projects. I suspect that these notifications are going out since there is no .readthedocs.yaml (or .readthedocs.yml) file in this repo.

I guess the first thing is to verify that notifications are going out so we know that ReadTheDocs is indicating that we need to do this update.

If we do need this update, we could probably use the .readthedocs.yml file in the spack repo as a guide: https://github.com/JCSDA/spack/blob/jcsda_emc_spack_stack/.readthedocs.yml

**Comment by ulmononian** [comment]
@srherbener i have not received any notice of this, but very glad you did! sounds like we have about two months to fix it.
