### ISSUE TITLE
Conflict in Boost on macOS with GCC causes compiler to change

### ISSUE THREAD

**Issue by kgerheiser** [JCSDA/spack-stack#7]
Boost v1.76 and below has a conflict with GCC on macOS which 

https://github.com/spack/spack/blob/d4ca803fc58e127469fd0e0773b89fdc2087fac0/var/spack/repos/builtin/packages/boost/package.py#L209

Using Boost 1.77.0+ resolves this issue. I know there's an issue with newer versions of Boost on (e.g. Orion), so I think this should be added to `sites/macos/site.yaml`

**Comment by climbfuji** [comment]
@kgerheiser I built the stripped-down version of boost 1.72 on macOS with apple-cland, (llvm-)clang and gcc. Right now, we can use 1.72 everywhere. That might change if we require building actual boost code, not just the headers, but we need to check.

**Comment by climbfuji** [comment]
Also, this note
```
      # Versions 1.73+ don't compile on platforms like orion (bootstrap.sh fails) ... on the todo list
```
is from the early days of spack-stack when the compiler toolchain setup wasn't correct I think. Might be worth trying again.

**Comment by climbfuji** [comment]
@kgerheiser I tested newer boost versions again on Orion, still the same problem. The bootstrapping fails. But Boost 1.78 works everywhere else, thus in PR #120 I will update the default boost version to 1.78 and pin the one on Orion to 1.72.
