### ISSUE TITLE
[INSTALL] Please update eckit to 1.23.0 on Hera, Jet

### ISSUE THREAD

**Issue by lgramer** [JCSDA/spack-stack#700]
Note: Please search to see if an issue already exists for the software you are requesting to be installed.

Which software in the stack would you like installed?
`eckit`

What is the version/tag of the software?
1.23.0

What compilation options would you like set?
N/A

Which machines would you like to have the software installed?
Hera, Jet

Any other relevant information that we should know to correctly install the software??
Additional context

I am attempting a build of the JCSDA JEDI "SOCA-science" package on HERA and JET, and encountered the following version error on HERA:

```
  Could not find a configuration file for package "eckit" that is compatible with requested version "1.23.0".

  The following configuration files were considered but not accepted:

    /scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/eckit-1.19.0-mhcpgdq/lib64/cmake/eckit/eckit-config.cmake, version: 1.19.0
```

**Comment by ulmononian** [comment]
hi @lgramer. `eckit/1.23.1` is actually installed on hera/jet as part of the spack-stack unified environment. i think the issue might be that the stack soca-science is loading to build/run on hera is out of date. could you try changing lines 7-12 of `soca-science/configs/machine/machine.hera.intel` (i.e. https://github.com/JCSDA-internal/soca-science/blob/118755aab2091991e0e976c7c148772e60e48ee2/configs/machine/machine.hera.intel#L7-L12) to the following:

```
module use /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.4.1/envs/unified-env/install/modulefiles/Core
module load stack-intel/2021.5.0
module load stack-intel-oneapi-mpi/2021.5.1
module load stack-python/3.9.12
module load soca-env
module load fms/release-jcsda
```

if you then do `source soca-science/configs/machine/machine.hera.intel`, it should show that `eckit/1.23.1` is loaded, along with other necessary modules. if everything looks correct, you can try building again. please let me know if this works, and if not, we can try something else!

as for jet, i do not know if that is fully supported within the soca-science workflow, but if you have the required obs. and input data to run the model/da on jet, the following is something you could try in an example `machine.jet.intel` config file:

```
module purge
module use /lfs4/HFIP/hfv3gfs/spack-stack/modulefiles
module load miniconda/3.9.12
module load ecflow/5.5.3

module use /mnt/lfs4/HFIP/hfv3gfs/role.epic/spack-stack/spack-stack-1.4.1/envs/unified-env/install/modulefiles/Core
module load stack-intel/2021.5.0
module load stack-intel-oneapi-mpi/2021.5.1
module load stack-python/3.9.12
module load soca-env
module load fms/release-jcsda
```

i am not sure if this will work, as i never ran soca-science on jet.

**Comment by climbfuji** [comment]
Thanks @ulmononian ! 

@lgramer please check if you can use those installations and let us know.

**Comment by climbfuji** [comment]
Since we haven't heard back, I assume it's all working now. Please reopen if this is not the case.
