### ISSUE TITLE
Warning: detected custom TCL modules configuration

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#703]
**Describe the bug**
The latest pull from main Spack gifted us with an annoying "Warning: detected custom TCL modules configuration..." message.

**To Reproduce**
Install any of the spack-stack environments

**Expected behavior**
No more warning!

**System:**
Affects all systems

**Additional context**
Related to #50

Per @climbfuji's suggestion in #672, let's split the common/modules.yaml configs into two files, have `spack stack create env` automatically use lmod unless it belongs to a site where tcl is needed (plus have manual override option), and add a CI check that ensures that modules_lmod.yaml and modules_tcl.yaml match to the extent that they should. Alternatively, we could put the config in one template file and have `spack stack create env` generate modules.yaml dynamically depending on whether lmod or tcl is used.

**Comment by climbfuji** [comment]
We decided to push this to the next spack-stack release, therefore removing it from the sprint and switching the epic/release.
