### ISSUE TITLE
For spack-stack-1.5.0: update ufs-weather-model-static template

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#721]
**Is your feature request related to a problem? Please describe.**
The template ufs-weather-model-static has fallen behind and will continue to do so, since we use unified-dev and skylab-dev on all systems except Acorn.

**Describe the solution you'd like**
Someone needs to go and update the versions in the template before the 1.5.0 release to match what is built in the unified environment.

**Additional context**
n/a

**Comment by ulmononian** [comment]
i can take this one.

**Comment by ulmononian** [comment]
whoops-- i take it back (misinterpreted the issue initially). i forgot alex is the one who maintains ufs-wm-static for acorn.

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA Do you have time to work on this during this week before we tag the release?

**Comment by AlexanderRichert-NOAA** [comment]
Yep will do.

**Comment by climbfuji** [comment]
Closed via #772
