### ISSUE TITLE
[INSTALL] scotch@7.0.4

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#727]
**Which software in the stack would you like installed?**
scotch

**What is the version/tag of the software?**
7.0.4

**What compilation options would you like set?**
no changes

**Installation timeframe: Would you like this package to be installed in an upcoming quarterly spack-stack release, or sooner?**
spack-stack 1.5.0 release

**Any other relevant information that we should know to correctly install the software??**
None (7.0.4 provides bug fixes)

**Comment by climbfuji** [comment]
Yup, that's already included in #722 (will make the PR close the issue)

**Comment by ulmononian** [comment]
do we know if there are any changes to build settings that will need to be in scotch's package.py for 7.0.4? sounded to me that there were already some weird things happening from emc's testing with the new version.

**Comment by AlexanderRichert-NOAA** [comment]
None that I know of. It should just be bug fixes, so apart from no longer needing the MPI_Fint patch, I don't think it changes the build itself.

**Comment by ulmononian** [comment]
so these lines can go https://github.com/JCSDA/spack/blob/a7778813cd955229db7a8c4d48883610e3fe1f74/var/spack/repos/builtin/packages/scotch/package.py#L76-L77 ? what about the `noarch` variant?

**Comment by AlexanderRichert-NOAA** [comment]
No, those lines can stay, the patch just won't be applied to 7.0.4 because it's not needed. The noarch variant should stay; I seem to recall it related to compiler issues that as far as I know are not scotch's fault.
