### ISSUE TITLE
Add awscli to ewok-env

### ISSUE THREAD

**Issue by ashley314** [JCSDA/spack-stack#728]
**Please describe the package or library you would like to add to spack-stack.**

Updates to the EWOK and skylab code that allow capability to ingest backgrounds require `awscli` to download background files. We'd like to add it to the existing `ewok-env` and roll it out with the next spack-stack release. It looks like awscli is already available in spack-stack. 

**What applications will be using this package or library?**
JEDI (ewok/skylab)

**Is there already a package or library in spack-stack that provides this, or related, functionality?**
`awscli`

**Additional context**
<img width="830" alt="image" src="https://github.com/JCSDA/spack-stack/assets/5719084/df13ccf7-dc5d-4c42-b260-1ec44ab06495">

**Will This Package be Needed in a NOAA Operational Application?**
N/A

**Comment by climbfuji** [comment]
We'll have to see. We tried that in the past, added `awscli` and `pcluster`, but those packages were poorly maintained, had very strict version requirements that caused lots of trouble with the other Python packages in `ewok-env`. Therefore, we decided to keep those out of spack-stack. But we've updated spack several times from the authoritative repositories, maybe those packages work better now.

**Comment by ashley314** [comment]
Good to know, thanks! If it is not compatible still, we can add it to the ingest suite instructions as an prerequisite. I am trying to keep those instructions as small as possible but it is not a show stopper. @cmgas mentioned we can add it to `ewok/setup.py` as well. There's a couple of different options.

**Comment by climbfuji** [comment]
I am going to postpone this to 1.6.0, if we do it at all. The `awscli` package and the `parallelcluster` package in spack are seriously outdated, and reading the AWS CLI readme (https://github.com/aws/aws-cli/tree/2.13.15) installing via Python setuptools is no longer possible for v2. We'll need a bit more time to see if we can build using PyInstaller (the required version of PyInstaller isn't available either in spack, way behind).

**Comment by climbfuji** [comment]
Turns out this was easier than expected, moving back to spack-stack-1.5.0!
