### ISSUE TITLE
Upgrade to latest intel compilers on Acorn

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#731]
**Is your feature request related to a problem? Please describe.**
It has been requested that we upgrade spack-stack to the most recent intel compilers ("intel-classic" module) on Acorn. Acorn module: intel-classic/2022.2.0.262

**Describe the solution you'd like**
Update acorn/compilers.yaml

**Testing**
...in progress...

This will most likely not be included in the spack-stack 1.5.0 release, depending partly on whether any issues are encountered.

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA @Hang-Lei-NOAA What's the status of this?

**Comment by Hang-Lei-NOAA** [comment]
@climbfuji This had been done. 
Alex had installed with the testing compiler intel-classic/2022 on acorn.

**Comment by climbfuji** [comment]
Thanks @Hang-Lei-NOAA !
