### ISSUE TITLE
Concretization issues on Derecho and Hercules with gcc

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#740]
**Describe the bug**
Not sure when/how this started, but with develop I am seeing concretization issues on both Derecho and Hercules for gcc (not for intel):
```
dmgjrzj  jedi-base-env@1.0.0%gcc@12.2.0+fftw+hdf4+python  build_system=bundle  arch=linux-sles15-zen3
r3t5vy3  jedi-base-env@1.0.0%gcc@12.2.0+fftw+hdf4+python  build_system=bundle  arch=linux-sles15-zen3
fnr5tgq  py-attrs@21.4.0%gcc@12.2.0  build_system=python_pip  arch=linux-sles15-zen3
hw3yerb  py-attrs@23.1.0%gcc@12.2.0  build_system=python_pip  arch=linux-sles15-zen3
b5kh5ww  py-eccodes@1.4.2%gcc@12.2.0  build_system=python_pip  arch=linux-sles15-zen3
ebz7ud3  py-eccodes@1.4.2%gcc@12.2.0  build_system=python_pip  arch=linux-sles15-zen3
```

**To Reproduce**
Try to concretize develop as of today on either of those platforms with gcc enabled.

**Expected behavior**
No duplicates.

**System:**
Derecho, Hercules with gcc

**Additional context**

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA @ulmononian I can fix this by pinning `py-attrs` to an older version, because `py-myst-parser` requires that version. `py-myst-parser` is part of `jedi-tools-env` which only gets built with `gcc`. I don't see any problems with using that slightly older version of `py-attrs`. Is that an agreeable solution for you?

**Comment by ulmononian** [comment]
> ix this by pinning `py-`

sorry for the late confirmation, but this sounds fine to me. thanks for finding a fix so quickly.
