### ISSUE TITLE
can we include build instructions in the readme?

### ISSUE THREAD

**Issue by edwardhartnett** [JCSDA/spack-stack#746]
In the readme it says to look at the readthedocs for install instructuons.

When I look there I get info on modules and how to work with spack-stack on NOAA R&D machines. But no instructions on how to install on a new machine.

So firstly, how do I install spack-stack on my Linux box.

Secondly, can we include those instructions in the README?

**Comment by climbfuji** [comment]
Firstly: look for section https://spack-stack.readthedocs.io/en/latest/NewSiteConfigs.html

Secondly: I am against that, because I don't want to duplicate information and it's a lot that really belongs into the comprehensive documentation.

If we add more links in the README (for fully supported sites, see ... ; for installing spack-stack on a new system see ...) would that work?

**Comment by edwardhartnett** [comment]
To summarize discussion from email, we agree that outside users (i.e. scientists outside NOAA/UCAR) should use spack-stack to install the UFS.

That being the case, we need to provide better instructions, and they should be in the README. Users will, in general, not read much documentation before they get confused and give up, telling everyone they know that spack-stack is terrible and not worth the effort. Such negative talk can really impact funding and use by other projects, just as it can for commercial projects.

Since we want spack-stack to succeed, we will need to support multiple versions of the documentation, including a simple way to get started, and of course the more complex documentation needed to understand all the details.

Since installation process should not change much from release to release, this does not represent an undue maintenance burden. But whatever burden it does represent, is necessary for project success so must be endured.

**Comment by edwardhartnett** [comment]
Using the current instructions I tried this command but it is not working for me:

```
ed@Pooh-Bah:~/spack-stack$ spack stack create env --site linux.default --template unified-env-all --name unified-env.mylinux

Configuring basic directory information ...
  ... script directory: /home/ed/spack-stack/spack/lib/jcsda-emc/spack-stack/stack
  ... base directory: /home/ed/spack-stack/spack/lib/jcsda-emc/spack-stack
  ... spack directory: /home/ed/spack-stack/spack
==> Error: Template: "unified-env-all" does not exist

```

**Comment by climbfuji** [comment]
Where did you get the template name from?

**Comment by edwardhartnett** [comment]
From the readthedocs document. THat's the command that is given here: https://spack-stack.readthedocs.io/en/latest/NewSiteConfigs.html

**Comment by climbfuji** [comment]
A typo in the documentation! The macOS section has it right, template is `unified-dev`
```
spack stack create env --site macos.default [--template unified-dev] --name unified-env.mymacos
spack env activate [-p] envs/unified-env.mymacos
```

**Comment by edwardhartnett** [comment]
I get this message, is it expected?

WARNING! User umask is neither 0022 nor 0027, check before proceeding

**Comment by climbfuji** [comment]
Yes. We've had so many problems with building spack-stack on HPCs where the default umask is such that users outside the group (or sometimes not even the group members) could see the spack environments, therefore the check. Reminds folks to change their umask before proceeding.

**Comment by edwardhartnett** [comment]
SO what should it be?

**Comment by climbfuji** [comment]
One of the two - 0022 or 0027

**Comment by edwardhartnett** [comment]
Eventually I get this error:

spack concretize 2>&1 | tee log.concretize
==> Error: variant "opcode" not found in package "perl"

**Comment by climbfuji** [comment]
I've never seen this. Are you using any pre-configured site or are you trying to generate a new site config?

**Comment by edwardhartnett** [comment]
I am following the instructions here:
https://spack-stack.readthedocs.io/en/latest/NewSiteConfigs.html

**Comment by climbfuji** [comment]
Wondering where that `opcode` variant comes from. I assume that perl is found as an external package, can you confirm?

**Comment by climbfuji** [comment]
@edwardhartnett Any updates on this issue?

**Comment by edwardhartnett** [comment]
No update.

**Comment by climbfuji** [comment]
May I suggest closing this due to a lack of activity?

Also, the original topic of this issue (can we include build instructions in readme) has been addressed (satisfactorily?) by #755?

**Comment by AlexanderRichert-NOAA** [comment]
My two cents-- I've had fairly good luck with a couple users with pointing them to the updated documentation. We could maybe tweak the README to make the documentation more visible. For example we could put something in bold that says 'To get started using spack-stack, go to https://spack-stack.readthedocs.io/en/latest/Overview.html#getting-started'; that link has a handful of common use cases with links to the documentation (including our reinstated 'quick start' instructions).

**Comment by climbfuji** [comment]
Sounds good to me.

**Comment by climbfuji** [comment]
`README.md` was updated in #804
