### ISSUE TITLE
[INSTALL] Add mapl@2.40.3 or mapl@2.35.2 with esmf@8.5.0 to spack-stack@1.5.0 environments

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#753]
**Which software in the stack would you like installed?**
Per https://github.com/ufs-community/ufs-weather-model/issues/1854, we need to add `mapl@2.40.3` *or* `mapl@2.35.2` (depends on testing that is currently going on) with `esmf@8.5.0` to the `spack-stack@1.5.0` environments.

**What is the version/tag of the software?**
See above

**What compilation options would you like set?**
Same as before

**Installation timeframe: Would you like this package to be installed in an upcoming quarterly spack-stack release, or sooner? If it is needed sooner (such as for testing a new package/version before incorporating it into a full release), please specify a preferred timeline and *one* machine on which you would like it to be installed for testing prior to the next spack-stack release.**
Roll out as part of `spack-stack@1.5.0`

**Any other relevant information that we should know to correctly install the software??**
n/s

**Additional context**
A test environment will be installed on Hera based on the current ufs-weather-model spack-stack environment to enable testing before the `spack-stack@1.5.0` release.

**Comment by climbfuji** [comment]
As I explained in the PRs that added ESMF and MAPL to our spack fork, we can't build mapl@2.40.3 and mapl@2.35.2 in the same environment, because they have vastly different version requirements for their thirdparty dependencies (--> duplicate package errors). There is an issue in the ufs-weather-model which deals with testing ESMF 8.5.0 and MAPL 2.40.3 in the UFS. If that gets sorted out in time for the spack-stack 1.5.0 release, we simply move up to the newer versions and have the UFS switch over when they move to spack-stack 1.5.0.

**Comment by mathomp4** [comment]
> As I explained in the PRs that added ESMF and MAPL to our spack fork, we can't build mapl@2.40.3 and mapl@2.35.2 in the same environment, because they have vastly different version requirements for their thirdparty dependencies (--> duplicate package errors). There is an issue in the ufs-weather-model which deals with testing ESMF 8.5.0 and MAPL 2.40.3 in the UFS. If that gets sorted out in time for the spack-stack 1.5.0 release, we simply move up to the newer versions and have the UFS switch over when they move to spack-stack 1.5.0.

Huh. I guess I'd have thought that you could install both. I mean, they need different versions of GFE libraries and ESMF, but that should all be doable. It might point to a bug in the mapl package `depends_on`. What sort of errors do you get?

**Comment by climbfuji** [comment]
Actually, scrap that. This happens if you try to finish off work after 10 hours in front of your screen. As long as the versions of the dependencies are different, there is no problem. A `module load mapl@2.40.3` will load its own version of `pflogger`, and a `module load mapl@2.35.2` will load another version of `pflogger` as dependency. We would have a problem if `mapl@2.40.3` depended on `pflogger@x.y.z` with a different variant than `mapl@2.35.2`, because the module name for the two `pflogger` versions would be the same.

**Comment by AlexanderRichert-NOAA** [comment]
To be clear, is UFS the only hold up? If so, I'd say let's just move to the recent versions and be done with it, and we can make adjustments through chained envs later as needed.

**Comment by climbfuji** [comment]
We are working on it (see UFS WM issue https://github.com/ufs-community/ufs-weather-model/issues/1854)

**Comment by climbfuji** [comment]
We aren't ready for this yet. Testing with the spack-stack modules isn't going great with the ufs-weather-model, see https://github.com/ufs-community/ufs-weather-model/issues/1854. I also found that because of the different dependencies (package versions!) for mapl and the need to add debug builds here and there, it's easy to end up with duplicate packages when building multiple mapl and esmf versions in the same environment.

Here is my suggestion (@AlexanderRichert-NOAA @ulmononian FYI): 

We'll release spack-stack-1.5.0 with esmf 8.4.2 and mapl 2.35.2. When the time comes to update to newer versions, we'll create chained environments to protect the original installations.

**Comment by climbfuji** [comment]
This is no longer needed, those versions of esmf and mapl are part of spack-stack-1.5.1.
