### ISSUE TITLE
Enabling pflogger variant for mapl breaks our builds (all CI)

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#754]
**Describe the bug**
https://github.com/JCSDA/spack-stack/pull/752 turns off `pflogger` explicitly. It used to be off by default, but the updates in the corresponding spack PR https://github.com/JCSDA/spack/pull/313 enable it by default. All three CI builds failed with `pflogger` enabled.

**To Reproduce**
Create a PR for spack-stack that enables `pflogger` for `mapl`

**Expected behavior**
It builds

**System:**
CI (macOS arm64, macOS Intel, Ubuntu)

**Additional context**
n/a

**Comment by mathomp4** [comment]
@climbfuji I have a thought. When I build pflogger in my testing I always have in my `packages.yaml`:
```
  pflogger:
    variants: +mpi
```
because, well, I know I need it. But in the mapl `package.py` I have:
```
    depends_on("pflogger@:1.6", when="@:2.22+pflogger")
    depends_on("pflogger@1.9.1:", when="@2.23:2.39+pflogger")
    depends_on("pflogger@1.9.5:", when="@2.40:+pflogger")
```
I wonder if it should be with `+mpi`:
```
    depends_on("pflogger@:1.6 +mpi", when="@:2.22+pflogger")
    depends_on("pflogger@1.9.1: +mpi", when="@2.23:2.39+pflogger")
    depends_on("pflogger@1.9.5: +mpi", when="@2.40:+pflogger")
```
I suppose in your testing, you could add the pflogger mpi variant to the common packages.yaml and see if that helps?

**Comment by mathomp4** [comment]
Yeah, I see in the CI that it is not building MPI pflogger:
```
@1.10.0%intel@2022.1.0~ipo~mpi build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-icelake
```
but it somehow found the AWS one:
```
2023-08-29T15:21:56.0583928Z             y/GFTL_SHARED-1.5/include/v2 -I/opt/amazon/openmpi/include -I/opt/a
2023-08-29T15:21:56.0584237Z             mazon/openmpi/lib -cpp -O3 -free -stand f08 -diag-disable 5268 -mod
```

**Comment by mathomp4** [comment]
The macOS failure does make me think building `pflogger +mpi` would fix that. MAPL assumes MPI pFlogger and so gets very confused when it sees a non-MPI pFlogger.

**Comment by mathomp4** [comment]
Yeah. I can duplicate the macOS failure locally by not having the `+mpi` variant of pflogger installed. I made a PR to spack here:

https://github.com/spack/spack/pull/39683

So that should solve at least the macOS issue. Not sure if it helps the Ubuntu issue though.

**Comment by climbfuji** [comment]
This was fixed by https://github.com/JCSDA/spack/pull/314, and `pflogger` can remain on in https://github.com/JCSDA/spack-stack/pull/752.
