### ISSUE TITLE
Adding and removing several environmental variables for METplus and MET modules

### ISSUE THREAD

**Issue by weiwilliam** [JCSDA/spack-stack#757]
I'm using METplus-4.1.1/MET-10.1.1 under spack-stack-1.4.1 to calculate scores.
Adding and removing several environmental variables will be very helpful to use it later.

1. Removing MET_BASE 
With $MET_BASE exported, METplus/MET will encounter the error below
```
OUTPUT:
WARNING:
WARNING: get_filenames() -> can't stat "/data/prod/jedi/spack-stack/spack-stack-1.4.1/envs/unified-env/install/intel/2021.5.0/met-10.1.1-oy2shu6/table_files"
WARNING:
WARNING:
WARNING: get_filenames() -> can't stat "/data/prod/jedi/spack-stack/spack-stack-1.4.1/envs/unified-env/install/intel/2021.5.0/met-10.1.1-oy2shu6/table_files"
WARNING:
ERROR  :
ERROR  : recursive_envs() -> unable to open input file "/data/prod/jedi/spack-stack/spack-stack-1.4.1/envs/unified-env/install/intel/2021.5.0/met-10.1.1-oy2shu6/config/ConfigConstants"
ERROR  :
```
This was discussed on METplus discussion last year.
[METplus Discussion#1810](https://github.com/dtcenter/METplus/discussions/1810#discussion-4398627)
By unsetting MET_BASE after loading modules, it can successfully generate statistics files.

2. Adding MET_INSTALL_PATH (or something similar)
By exporting this path, the 'MET_INSTALL_DIR' in main.conf for run_metplus.py can be pointed to this variable by {ENV[MET_INSTALL_PATH]}.
For example, MET_INSTALL_PATH can be '/data/prod/jedi/spack-stack/spack-stack-1.4.1/envs/unified-env/install/intel/2021.5.0/met-10.1.1-oy2shu6' on S4.

3. Adding METPLUS_PATH
Similar to point 2, the PARM_BASE in main.conf can be pointed to {ENV[METPLUS_PATH]}.
METPLUS_PATH can be '/data/prod/jedi/spack-stack/spack-stack-1.4.1/envs/unified-env/install/intel/2021.5.0/metplus-4.1.1-l75c2q5'

Then the conf files for METplus can be prepared without hard-coded library paths.

**Comment by climbfuji** [comment]
Are you saying that we need to set `MET_INSTALL_PATH` and `METPLUS_PATH` as part of the met/metplus modules generated by spack-stack? Unless this is a universal requirement for ALL met/metplus users (also those outside of JEDI), I think it's better to incorporate this in your workflow:
```
export MET_INSTALL_PATH=${met_ROOT}
export METPLUS_PATH=${metplus_ROOT}
```
The `*_ROOT` entries are generated by spack automatically.

**Comment by weiwilliam** [comment]
Oh! I didn't know there are lower case variables.
Then it should be fine to use met_ROOT and metplus_ROOT.
Thank you!
I was looking for capital METPLUS.... or MET.... because like METPLUS_PATH is the variable they used on Cheyenne.

**Comment by climbfuji** [comment]
Ok, please let me know if that works for you. Thanks!

**Comment by weiwilliam** [comment]
@climbfuji Thank you, it works. Then the only issue here is MET_BASE.

**Comment by climbfuji** [comment]
So you are basically saying that when we build MET with spack, we need to unset/not set the MET_BASE env variable, correct? I see that this change is already in spack develop (the authoritative repo), but not yet in our fork. @AlexanderRichert-NOAA ?

**Comment by weiwilliam** [comment]
My thinking was to unset it after the spack-stack finishes the installation if it is required for installation.
But I see the difference between our fork and spack/spack.
If MET_BASE will not be there then it should work properly.

**Comment by AlexanderRichert-NOAA** [comment]
Based on the discussion in https://github.com/dtcenter/METplus/discussions/1810, it looks like we should add "share/met" to the MET_BASE definition? It looks like that's how it was done in hpc-stack. @weiwilliam, after you load the modules, can you try something to effect of `export MET_BASE=${MET_BASE}/share/met` and see if that helps?

**Comment by weiwilliam** [comment]
@AlexanderRichert-NOAA Yes, it works. Thanks.
Do you know if that is a needed path when installing METplus/MET? If it is not required, we can skip it actually.

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA @weiwilliam Have we come to a conclusion of what we should do? Should we update MET from spack develop (and metplus while we are at it) and re-activate the MET_BASE environment variable with the correct value (which is ???)?

**Comment by weiwilliam** [comment]
I think we can remove it.
https://metplus.readthedocs.io/en/latest/Users_Guide/glossary.html#term-MET_BASE
It said we don't need to set it now.

**Comment by AlexanderRichert-NOAA** [comment]
Is the idea that the share directory will be found be default? I'm also looking at https://met.readthedocs.io/en/latest/Users_Guide/config_options.html#met-base

**Comment by weiwilliam** [comment]
Yeah, I think so. In the [answer ](https://github.com/dtcenter/METplus/discussions/1810#discussioncomment-3684127)of the discussion I posted, the MET_BASE will be defined through --prefix.

**Comment by AlexanderRichert-NOAA** [comment]
I think I missed the connection there as far as how that build-time option gets propagated to run time?

MET_BASE is defined currently in the hpc-stack module (<metroot>/share/met), so I just want to make extra sure we don't break anything by taking it out :)

**Comment by weiwilliam** [comment]
I don't exactly know. Here is my understanding.
In our spack fork, the met/package.py defines the MET_BASE at [line 187](https://github.com/JCSDA/spack/blob/42ede2de1f4b04844d4fb51ae2f88cde518c1ab8/var/spack/repos/builtin/packages/met/package.py#L187-188), which is not the case in [met/package.py in develop branch of spack](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/met/package.py).
I think that is the reason the MET_BASE is defined.
And user doesn't need MET_BASE in runtime unless the final folder of MET is different from the prefix (during compilation).

**Comment by AlexanderRichert-NOAA** [comment]
Okay, that makes sense. In your test, after you've unset MET_BASE, are you able to confirm that it's using the table_files/ that's in the met install path?

**Comment by weiwilliam** [comment]
After unset, I can run it properly without any warning or error messages.
In the log file, I see it grabbed a default config file under share/met.
So, I believe it uses the correct path and files.
The version I tried is METplus 4.1.1/MET 10.1.1 and METplus 5.1.0/MET 11.1.0.

**Comment by AlexanderRichert-NOAA** [comment]
Okay, let's remove it then. I'm happy to put in a PR in a little while here.

**Comment by climbfuji** [comment]
Thanks @AlexanderRichert-NOAA !
