### ISSUE TITLE
Switch to Intel MKL on systems with Intel compiler

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#759]
## Description

The Nautilus site config shows how to switch to Intel MKL as provider for `blas` and `lapack` (and `fftw-api` if I remember correctly).

I think it would be good to switch to Intel MKL when using the Intel compiler, and keep `openblas`/`fftw` for `gcc` and `clang`. This ensures that we remain compatible with the different providers. We can probably make use of the `require: one_of / when` syntax to implement this.

Update 2023/10/11: See https://github.com/JCSDA/spack/pull/342 for work that needs to be done on `ectrans` and `ecmwf-atlas`.

## Requirements

See above

## Acceptance Criteria (Definition of Done)

A clean solution to use Intel MKL with at least the Intel compilers.

## Dependencies

n/a

**Comment by AlexanderRichert-NOAA** [comment]
Can you elaborate on "remain compatible with the different providers," i.e., are you talking about the downstream packages or spack-stack or..? All other things being equal I would be inclined to use openblas+fftw for everything just for consistency, but if some applications need MKL for their own fourier transform/linear algebra purposes then that's another matter.

**Comment by climbfuji** [comment]
> Can you elaborate on "remain compatible with the different providers," i.e., are you talking about the downstream packages or spack-stack or..? All other things being equal I would be inclined to use openblas+fftw for everything just for consistency, but if some applications need MKL for their own fourier transform/linear algebra purposes then that's another matter.

If you take a look at the nautilus site config, you'll be able to see I think. I propose that when we use Intel compilers, we use MKL as the provider for blas, lapack, fftw-api. When we use GNU, we keep the current combination of openblas as provider for blas and lapack, and fftw for fftw-api.

**Comment by AlexanderRichert-NOAA** [comment]
Would it be a reasonable goal for the 1.8.0 release to build a second unified env (or subset thereof) using MKL on a handful of systems? That would give developers a chance to test and give feedback.

**Comment by climbfuji** [comment]
> Would it be a reasonable goal for the 1.8.0 release to build a second unified env (or subset thereof) using MKL on a handful of systems? That would give developers a chance to test and give feedback.

Yes, of course. Good idea
