### ISSUE TITLE
Failure in module dependencies

### ISSUE THREAD

**Issue by areinecke** [JCSDA/spack-stack#761]
**Describe the bug**
This is only a bug in my implementation.  There is not an issue template for general usage questions.  I am at `commit 70b48cfc1`.

I’m trying to test different mpi implementations on Atlantis and want to be able to build different spack-stack environments to evaluate.  I have a simplified spack.yaml that for the purposes of this example only builds one library, p4est@2.8.

**To Reproduce**
After building the library, modules, and meta modules, I am able to successfully setup the module environment with

```
module use --append /software7/depot/atlantis-modulefiles
module use --append /users/reinecke/spack-test/spack-stack/envs/test1/install/modulefiles/Core
module load stack-intel/2021.6.0
module load stack-openmpi/4.1.5
```
however, `module load p4est/2.8` fails with

> Lmod has detected the following error:  The following module(s) are unknown: "intel/2021.6.0/openmpi/4.1.5" "intel/2021.6.0/zlib/1.2.13"

The else branch of the following block of code in `p4est/2.8` module
```
if {![info exists ::env(LMOD_VERSION_MAJOR)]} {
    module load openmpi/4.1.5
    module load zlib/1.2.13
} else {
    depends-on intel/2021.6.0/openmpi/4.1.5
    depends-on intel/2021.6.0/zlib/1.2.13
}
```
is the source of the failure because `intel/2021.6.0` is prepended to the path of the two dependencies.  This is inconsistent with the meta-module `stack-intel/2021.6.0` where the MODULEPATH variable is set to
`prepend-path {MODULEPATH} {/users/reinecke/spack-test/spack-stack/env/test1/install/modulefiles/intel/2021.6.0}`, which already has `intel/2021.6.0` appended to the path.

How do I fix this?

**Expected behavior**
I expect the  module to load without errors.  I believe that I have an incorrect setting in a common or site yaml file.

**System:**
Atlantis (not accessible)

**Additional context**

**Comment by climbfuji** [comment]
Is atlantis using `lmod` or `tcl` modules?

**Comment by areinecke** [comment]
It's using lmod v8.5

[test1] 113 atlantis1:~/spack-test/spack-stack> echo $LMOD_VERSION
8.5

but `LMOD_VERSION_MAJOR` is empty.

**Comment by areinecke** [comment]
The site/modules.yaml file was using tcl and I was using `spack module tcl refresh` to generate my modules.

If I change site/modules.yaml to use lmod and use `spack module lmod refresh` it is working.

**Comment by climbfuji** [comment]
That's what I expected, because I made the same "mistake" last week on another platform ;-)

Can we close the issue? I think it makes sense to always use lmod when you can.

**Comment by areinecke** [comment]
It seems like it would work if it tested for LMOD_VERSION instead of LMOD_VERSION_MAJOR.  But okay to close.

**Comment by climbfuji** [comment]
I can try to make this a logical "OR" condition, because it's probably not ok for mainline spack to change this. I'll let you know, and if tcl/tk syntax is too restrictive then I'll close and add a note in the "Known issues" section.

In any case, we should add a note to check for consistency for the type of modules and always use `lmod` when available.

**Comment by areinecke** [comment]
Sounds good.
