### ISSUE TITLE
Gaea C5 application errors

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#766]
**Describe the bug**
This issue is to capture errors building/running applications on Gaea C5 with spack-stack.

For spack-stack-1.4.0 (copied from meeting minutes):
- UFS weather model failure on Gaea C5 (only occurs in debug mode)
    - @natalie-perlin had issues with compiling ESMF in debug mode - still working on resolution
- @climbfuji reported jedi-bunde ctest test issues in https://github.com/JCSDA-internal/oops/issues/2196
- @deniseworthen reported UFS WM issues with aerosol configuration: https://github.com/ufs-community/ufs-weather-model/issues/1888

The suggestion was to wait for spack-stack-1.5.0 to re-test and fix issues. Detailed problem description should be added below for these.

**To Reproduce**
Wait for spack-stack-1.5.0 for instructions

**Expected behavior**
No errors building and running UFS and JEDI applications

**System:**
Gaea C5

**Additional context**
n/a

**Comment by ulmononian** [comment]
does this still need resolved w/ transition to 1.5.0 and 1.5.1?

**Comment by climbfuji** [comment]
I worked on the JEDI side and my findings are summarized in https://github.com/JCSDA-internal/oops/issues/2196#issuecomment-1794030188:
> I've gotten a lot further with this, but I want to record here that there's a problem on Gaea with MPI jobs that require only one MPI task. These (at least all the ufo and I think also fv3-jedi tests) hang indefinitely at startup. The only way to make those run successfully is to run them without mpi, i.e. remove the MPI 1 from the test definition. For the record, the cmake command on gaea is:
```
cmake -DMPIEXEC_EXECUTABLE="/usr/bin/srun" -DMPIEXEC_NUMPROC_FLAG="--clusters=c5;-n" ../jedi-bundle 2>&1 | tee log.cmake
```

So as far as JEDI is concerned, I think we are ok. Once the ufs-weather-model has been tested successfully (especially the two errors reported above), we can close this. I assume EPIC or EMC will take care of that testing?

**Comment by climbfuji** [comment]
@natalie-perlin @DeniseWorthen Can you confirm that you (EPIC and EMC) will be re-testing the ufs-weather-model on Gaea C5, in particular for the problems reported above?

**Comment by natalie-perlin** [comment]
@climbfuji  @DeniseWorthen - 
 Yes, I'm planning to do testing of spack-stack higher versions. Two recent installations on Gaea C5 seem do be - 
  
 /lustre/f2/dev/role.epic/contrib/spack-stack/c5/spack-stack-1.5.0
 /lustre/f2/dev/role.epic/contrib/spack-stack/c5/spack-stack-1.5.1

**Comment by climbfuji** [comment]
Thanks! I would go straight to 1.5.1 because that's what the ufs-weather-model is moving to rapidly.

**Comment by natalie-perlin** [comment]
> I worked on the JEDI side and my findings are summarized in https://github.com/JCSDA-internal/oops/issues/2196#issuecomment-1794030188:
> 
> > I've gotten a lot further with this, but I want to record here that there's a problem on Gaea with MPI jobs that require only one MPI task. These (at least all the ufo and I think also fv3-jedi tests) hang indefinitely at startup. The only way to make those run successfully is to run them without mpi, i.e. remove the MPI 1 from the test definition. For the record, the cmake command on gaea is:
> 
> ```
> cmake -DMPIEXEC_EXECUTABLE="/usr/bin/srun" -DMPIEXEC_NUMPROC_FLAG="--clusters=c5;-n" ../jedi-bundle 2>&1 | tee log.cmake
> ```
> 
> So as far as JEDI is concerned, I think we are ok. Once the ufs-weather-model has been tested successfully (especially the two errors reported above), we can close this. I assume EPIC or EMC will take care of that testing?

The link gives "404/Not found" error. Is there a way to view the summary?

**Comment by climbfuji** [comment]
> > I worked on the JEDI side and my findings are summarized in [JCSDA-internal/oops#2196 (comment)](https://github.com/JCSDA-internal/oops/issues/2196#issuecomment-1794030188):
> > > I've gotten a lot further with this, but I want to record here that there's a problem on Gaea with MPI jobs that require only one MPI task. These (at least all the ufo and I think also fv3-jedi tests) hang indefinitely at startup. The only way to make those run successfully is to run them without mpi, i.e. remove the MPI 1 from the test definition. For the record, the cmake command on gaea is:
> > 
> > 
> > ```
> > cmake -DMPIEXEC_EXECUTABLE="/usr/bin/srun" -DMPIEXEC_NUMPROC_FLAG="--clusters=c5;-n" ../jedi-bundle 2>&1 | tee log.cmake
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So as far as JEDI is concerned, I think we are ok. Once the ufs-weather-model has been tested successfully (especially the two errors reported above), we can close this. I assume EPIC or EMC will take care of that testing?
> 
> The link gives "404/Not found" error. Is there a way to view the summary?

Not without having access to JCSDA-internal, sorry. That's why I quoted the contents in my comment above.

**Comment by natalie-perlin** [comment]
Modulefiles and scripts for gaea-c5 were updated as continuation of the PR into the UFS weather model repo started by @ulmononian (https://github.com/ufs-community/ufs-weather-model/pull/1784) , which uses spack-stack/1.5.0 at the moment.
 Regression tests on Gaea-c5 ran successfully testing the updates. A PR with the updates was created: https://github.com/ulmononian/ufs-weather-model/pull/13

**Comment by climbfuji** [comment]
@natalie-perlin Any update on this? Is the work done and does it all work as expected on C5? Thanks!

**Comment by DeniseWorthen** [comment]
@climbfuji The last comment on https://github.com/ufs-community/ufs-weather-model/issues/1888 suggested a new MAPL branch. I have not tested it. 

I would also note in that thread that the error is also seen on Hercules. I do not think it is Gaea-C5 related and so I see no reason why it would block that PR.

**Comment by climbfuji** [comment]
Thanks Denise. Ok, yet another mapl version ;-) - should I go ahead and close this issue? Is this what you meant?

**Comment by DeniseWorthen** [comment]
@climbfuji I can't speak to the other issues that were named at the top of this issue (debug mode and jedi-bundle) so I don't know if you could close or not. But the PET log error message is not C5 specific so if that is the only unresolved one, then yes I think we could close this issue. There will still be the open ufs-issue https://github.com/ufs-community/ufs-weather-model/issues/1888 to track.

**Comment by climbfuji** [comment]
@natalie-perlin How about compiling ESMF in debug mode, have you tried that again? On the JEDI side, the issues we've seen on C5 are resolved.

**Comment by climbfuji** [comment]
@natalie-perlin Gentle reminder about https://github.com/JCSDA/spack-stack/issues/766#issuecomment-1836166544. We would like to close this out before we release spack-stack-1.6.0. Many thanks!

**Comment by climbfuji** [comment]
@natalie-perlin Closing this based on all the success we've seen on Gaea C5 with the UFS using the last two spack-stack installations. If another problem comes up, please open a new issue.
