### ISSUE TITLE
[INSTALL] new NCEPLIBS-bufr version 12.0.1

### ISSUE THREAD

**Issue by jbathegit** [JCSDA/spack-stack#778]
**Which software in the stack would you like installed?**
A new version of the NCEPLIBS-bufr library is now available from https://github.com/NOAA-EMC/NCEPLIBS-bufr/releases/tag/v12.0.1

**What is the version/tag of the software?**
v12.0.1

**Which machines would you like to have the software installed?**
This library needs to be installed on WCOSS2 (cactus and dogwood) as well as various HPC machines including Jet, Hera, and possibly others where there's already an installation of an earlier version of the library.  This is a quick-update release at the request of @rmclaren, but if there are still earlier versions of the library available on any platform, please leave them there in order to give users time to transition on their own schedule.

Please also note that this is a follow-on to #626, given that the previous version 12.0.0 of this library is still waiting to be installed on WCOSS2.

**Any other relevant information that we should know to correctly install the software??**
Please see https://github.com/NOAA-EMC/NCEPLIBS-bufr/blob/develop/README.md.  The -DMASTER_TABLE_DIR option does not need to be specified (you can just let it default to `path1`), but the -DENABLE_PYTHON=ON should be included for any machines on which it is currently available for earlier versions of the library.

**Additional context**
Full release notes are available from https://noaa-emc.github.io/NCEPLIBS-bufr/md__home_runner_work_NCEPLIBS_bufr_NCEPLIBS_bufr_bufr_docs_ReleaseNotes.html

**Comment by Hang-Lei-NOAA** [comment]
@Jeff Ator - NOAA Federal ***@***.***> I will send bufr/12.0.0 to
NCO today. I noticed that you changed the bufr tag name by eliminating the
lib name. Is that what you planned to do?

**Comment by climbfuji** [comment]
This will go on the RDHPC & other platforms (not talking about WCOSS2/Acorn here) after the spack-stack-1.5.0 release, at latest in the first week of October.

**Comment by AlexanderRichert-NOAA** [comment]
I'll add 12.0.1 to the recipe shortly.

**Comment by jbathegit** [comment]
> @jeff Ator - NOAA Federal ***@***.***> I will send bufr/12.0.0 to NCO today. I noticed that you changed the bufr tag name by eliminating the lib name. Is that what you planned to do?
> 

Yes this was intentional, per a previous discussion in [library issue 516](https://github.com/NOAA-EMC/NCEPLIBS-bufr/issues/516).  So all good!

**Comment by srherbener** [comment]
Please include bufr@12.0.1 in the spack-stack-1.5.1 configuration. Thanks!

**Comment by climbfuji** [comment]
> Please include bufr@12.0.1 in the spack-stack-1.5.1 configuration. Thanks!

Please create the PRs for develop, I will bring it over to the release-1.5.1 branches. Thanks.

**Comment by srherbener** [comment]
> > Please include bufr@12.0.1 in the spack-stack-1.5.1 configuration. Thanks!
> 
> Please create the PRs for develop, I will bring it over to the release-1.5.1 branches. Thanks.

Done:

https://github.com/JCSDA/spack/pull/330
https://github.com/JCSDA/spack-stack/pull/797

**Comment by climbfuji** [comment]
This is now in the 1.5.1 release branches. We don't have a date for rolling it out yet, we'll discuss at the next spack-stack developer meeting.

**Comment by climbfuji** [comment]
spack-stack@1.5.1 has been installed on all tier-1 platforms as far as spack-stack is concerned (RDHPC, JCSDA, EPIC, ...). We agreed that we can consider install requests as done once these steps are completed and that installation on wcoss2 by GDIT is handled elsewhere, therefore closing this as complete.
