### ISSUE TITLE
[INSTALL] MET/METplus versions 9.1.3/3.1.1

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [JCSDA/spack-stack#784]
Note: Please search to see if an issue already exists for the software you are requesting to be installed.

**Which software in the stack would you like installed?**
MET and METplus under both spack-stack ~1.4.1 and~ 1.5.0.

**What is the version/tag of the software?**
MET version 9.1.3 and METplus version 3.1.1.

**What compilation options would you like set?**
Standard serial options.

**Installation timeframe: Would you like this package to be installed in an upcoming quarterly spack-stack release, or sooner? If it is needed sooner (such as for testing a new package/version before incorporating it into a full release), please specify a preferred timeline and *one* machine on which you would like it to be installed for testing prior to the next spack-stack release.**
Ideally, I would like this installed before the quarterly release.  We could start with Hera for testing.

**Any other relevant information that we should know to correctly install the software??**
Both of these packages have recipes in spack.

**Additional context**
They are the newest available versions that are compatible with the verif-global package (used in the global workflow).  Reference issue NOAA-EMC/global-workflow#1868.

**Comment by climbfuji** [comment]
Can we do this for just the latest spack-stack please? We really shouldn't spend any more time on adding packages to 1.4.x.

**Comment by DavidHuber-NOAA** [comment]
@climbfuji Sure, just 1.5.0 would be fine.  I think I may need to upgrade to that version for the global workflow anyway.

**Comment by climbfuji** [comment]
@DavidHuber-NOAA Can we close this? The `gsi-addon` env contains these versions, and we have a follow-up issue to add a new template for GSI to spack-stack (in `configs/templates/`).

**Comment by DavidHuber-NOAA** [comment]
@climbfuji Yes, we can close this.  Thanks!
