### ISSUE TITLE
INFRA-57.1: Fix ctest failures on MacOS

### ISSUE THREAD

**Issue by srherbener** [JCSDA/spack-stack#792]
**Describe the bug**
We've been ignoring a set of test failures on the MacOS due to these tests passing on all the other platforms. MacOS has a fairly unique situation where this platform is cross-compiling using apple-clang for C, C++ and GNU for Fortran. These two sets of compilers have their own underlying C++ and C standard libraries which makes it challenging to get all the code to link and load with the proper standard libraries. This might be the reason we see tests fail on MacOS while passing on other platforms.

**To Reproduce**
Build jedi-bundle on MacOs (either native Intel, or native ARM architectures) and run ctests.

**Expected behavior**
All the ctests pass

**System:**
What system(s) are you running the code on?
MacOS

**Additional context**

**Comment by climbfuji** [comment]
@srherbener We should consider adjusting the estimates for the issues related to this epic. They are either overlapping or duplicates of each other.

**Comment by srherbener** [comment]
There is definitely overlap - eg, fixing the signal trapping will probably fix some of the test failures. I somewhat arbitrarily reduced the estimates across the issues attached to this epic. There is a total of 5 story points now.

**Comment by symoore90** [comment]
Can this epic be put back into the epic pipeline please @srherbener @climbfuji

**Comment by srherbener** [comment]
Sure! I just moved it back.

**Comment by symoore90** [comment]
Does this epic need to be extended into Q3? @srherbener

**Comment by srherbener** [comment]
@symoore90 thanks for checking, yes this is not completed yet so it needs to be in Q3.

**Comment by symoore90** [comment]
@srherbener It looks like I don't have permissions to edit anything on this epic do you mind extending the date out to Jan 8 please

**Comment by climbfuji** [comment]
@symoore90 Can you try again, please?

**Comment by symoore90** [comment]
It's still not letting me edit anything @climbfuji

**Comment by srherbener** [comment]
I've updated the end date for this epic.

**Comment by climbfuji** [comment]
@srherbener It seems unlikely we'll have addressed all ctest failures by Jan 15, 2024. Can we extend the end date to the end of the AOP (March 31, 2024)?

**Comment by srherbener** [comment]
I agree. I'll update the end date.

**Comment by climbfuji** [comment]
@symoore90 We've updated the end date for INFRA-57.1 to March 31, 2024.

**Comment by climbfuji** [comment]
I am closing this. We'll deal with the remaining issues in AOP24 in the CI epic (I moved them to the CI parking lot)
