### ISSUE TITLE
nccmp crashes on Hera ecflow node (hecflow01)

### ISSUE THREAD

**Issue by DusanJovic-NOAA** [JCSDA/spack-stack#812]
**Describe the bug**
In ufs-weather-model regression test we need to start using `nccmp` program form the spack-stack instillation because the version available from the default location does not support zstd compression.

When nccmp program is executed on hecflow01 node (for example when ufs-wm regression test is using ecflow) it crashes with 'Illegal instruction' error, see https://github.com/ufs-community/ufs-weather-model/pull/1932#issuecomment-1748900072

**To Reproduce**

On Hera:
```
$ ssh hecflow01

$ module purge

$ module use /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.4.1/envs/ufs-pio-2.5.10/install/modulefiles/Core

$ module load stack-intel/2021.5.0 stack-intel-oneapi-mpi/2021.5.1

$ module load nccmp/1.9.0.1

$ module list

Currently Loaded Modules:
  1) intel/2022.1.2                    5) curl/7.29.0         9) zstd/1.5.2
  2) stack-intel/2021.5.0              6) pkg-config/0.27.1  10) netcdf-c/4.9.2
  3) impi/2022.1.2                     7) zlib/1.2.13        11) nccmp/1.9.0.1
  4) stack-intel-oneapi-mpi/2021.5.1   8) hdf5/1.14.0

$ which nccmp
/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.4.1/envs/unified-env/install/intel/2021.5.0/nccmp-1.9.0.1-hmpi4fb/bin/nccmp

$ cd /scratch2/NAGAPE/epic/UFS-WM_RT/NEMSfv3gfs/develop-20231003/control_p8_intel

$ nccmp -m sfcf000.nc sfcf000.nc 
Illegal instruction

```

**Expected behavior**

nccmp should run without crashing.

**System:**
What system(s) are you running the code on? Hera.

**Additional context**

**Comment by climbfuji** [comment]
Do you know if `hecflow01` uses a different CPU than the "regular" nodes?

**Comment by DusanJovic-NOAA** [comment]
hecflow01 node has: Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
login nodes have: Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz

**Comment by DusanJovic-NOAA** [comment]
The other difference I see is that the login nodes (and I assume compute nodes) support avx512 while ecflow node(s) only avx2, which might explain the error if libraries/executables are compiled using native (HOST) flags.

**Comment by climbfuji** [comment]
Yes, that’s it. Two solutions: add the common denominator for the CPU architecture to Hera’s site config (better), or build on hecflow01 (easier). I prefer the first solution.

**Comment by climbfuji** [comment]
@DusanJovic-NOAA How critical/urgent is this problem? From your description above you say "we need to start using" but it sounds that you need this right away, correct? If it's urgent, we can recreate the spack-stack-1.5.0 unified env without avx512. If it can wait for a few (how many?) weeks, then we'll make the switch to no-avx512 in spack-stack-1.5.1.

**Comment by climbfuji** [comment]
I went ahead and started building a parallel environment `unified-env-noavx512`, simply by building on `hecflow01`. This seems to be the easiest and shortest way for spack-stack-1.5.0. I'll let you know when it is available, and I'll also make the change in my ufs-weather-model branch for PR https://github.com/ufs-community/ufs-weather-model/pull/1920.

**Comment by climbfuji** [comment]
I also thought about Jet, but I think we don't have that problem there, because we already build for `target: [core2]` as the lowest common denominator so that the code runs on s/t/u/v/x/k/whatever-jet.

**Comment by DusanJovic-NOAA** [comment]
It is not urgent, whatever is easier for you. I can temporarily disable use of zstd compression on Hera.

**Comment by climbfuji** [comment]
I'll let you know if I hit an error during the build (unlikely), if not then it's going to be available by the end of today.

**Comment by DusanJovic-NOAA** [comment]
> I also thought about Jet, but I think we don't have that problem there, because we already build for `target: [core2]` as the lowest common denominator so that the code runs on s/t/u/v/x/k/whatever-jet.

Not related to this issue, but speaking of jet and ecflow, are you able to run regression test on jet using ecflow? My test fails in:

```
+ /mnt/lfs4/HFIP/hfv3gfs/Dusan.Jovic/ufs/develop/ufs-weather-model/tests/abort_dep_tasks.py
Traceback (most recent call last):
  File "/mnt/lfs4/HFIP/hfv3gfs/Dusan.Jovic/ufs/develop/ufs-weather-model/tests/abort_dep_tasks.py", line 3, in <module>
    import ecflow as ecflow
ModuleNotFoundError: No module named 'ecflow'
```
Looks to me that the problem is in ecflow module file:

```
$ module show ecflow/5.5.3
-----------------------------------------------------------------------------------------
   /apps/modules/modulefiles/ecflow/5.5.3:
-----------------------------------------------------------------------------------------
prepend_path("PATH","/apps/ecflow/5.5.3/bin")
prepend_path("MANPATH","/apps/ecflow/5.5.3/man")
conflict("ecflow")
setenv("ECF_ROOT","/apps/ecflow/5.5.3")
prepend_path("PYTHONPATH","/apps/ecflow/5.5.3/lib/python3.7/site-packages/ecflow")
...
```
Path '/apps/ecflow/5.5.3/lib/python3.7/site-packages/ecflow' does not exist, python3.8 does.

```
$ ls /apps/ecflow/5.5.3/lib/python3.7/site-packages/ecflow
ls: cannot access /apps/ecflow/5.5.3/lib/python3.7/site-packages/ecflow: No such file or directory

$ ls /apps/ecflow/5.5.3/lib/                              
cmake  python3.8

```

**Comment by climbfuji** [comment]
> > I also thought about Jet, but I think we don't have that problem there, because we already build for `target: [core2]` as the lowest common denominator so that the code runs on s/t/u/v/x/k/whatever-jet.
> 
> Not related to this issue, but speaking of jet and ecflow, are you able to run regression test on jet using ecflow? My test fails in:
> 
> ```
> + /mnt/lfs4/HFIP/hfv3gfs/Dusan.Jovic/ufs/develop/ufs-weather-model/tests/abort_dep_tasks.py
> Traceback (most recent call last):
>   File "/mnt/lfs4/HFIP/hfv3gfs/Dusan.Jovic/ufs/develop/ufs-weather-model/tests/abort_dep_tasks.py", line 3, in <module>
>     import ecflow as ecflow
> ModuleNotFoundError: No module named 'ecflow'
> ```
> 
> Looks to me that the problem is in ecflow module file:
> 
> ```
> $ module show ecflow/5.5.3
> -----------------------------------------------------------------------------------------
>    /apps/modules/modulefiles/ecflow/5.5.3:
> -----------------------------------------------------------------------------------------
> prepend_path("PATH","/apps/ecflow/5.5.3/bin")
> prepend_path("MANPATH","/apps/ecflow/5.5.3/man")
> conflict("ecflow")
> setenv("ECF_ROOT","/apps/ecflow/5.5.3")
> prepend_path("PYTHONPATH","/apps/ecflow/5.5.3/lib/python3.7/site-packages/ecflow")
> ...
> ```
> 
> Path '/apps/ecflow/5.5.3/lib/python3.7/site-packages/ecflow' does not exist, python3.8 does.
> 
> ```
> $ ls /apps/ecflow/5.5.3/lib/python3.7/site-packages/ecflow
> ls: cannot access /apps/ecflow/5.5.3/lib/python3.7/site-packages/ecflow: No such file or directory
> 
> $ ls /apps/ecflow/5.5.3/lib/                              
> cmake  python3.8
> ```

Thanks Dusan - I will fix this on Jet

**Comment by climbfuji** [comment]
@DusanJovic-NOAA The jet error is actually something the sysadmins need to fix, because it's there ecflow module. But - assuming you are using my ufs-weather-model PR https://github.com/ufs-community/ufs-weather-model/pull/1920 - it's unconvered by removing the additional paths/modules loads for ecflow in `rt.sh`. I can add a workaround back in my PR for the time being and send a request to the RDHPCS admins to fix their module.

**Comment by climbfuji** [comment]
I sent a request to the Jet helpdesk.

**Comment by climbfuji** [comment]
@DusanJovic-NOAA The spack-stack build on `hecflow01` is done. Can you try this change please before I push it to my ufs-weather-model branch?
```
--- a/modulefiles/ufs_hera.gnu.lua
+++ b/modulefiles/ufs_hera.gnu.lua
@@ -2,7 +2,7 @@ help([[
 loads UFS Model prerequisites for Hera/GNU
 ]])

-prepend_path("MODULEPATH", "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.0/envs/unified-env/install/modulefiles/Core")
+prepend_path("MODULEPATH", "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.0/envs/unified-env-noavx512/install/modulefiles/Core")
 prepend_path("MODULEPATH", "/scratch1/NCEPDEV/jcsda/jedipara/spack-stack/modulefiles")

 stack_gnu_ver=os.getenv("stack_gnu_ver") or "9.2.0"
diff --git a/modulefiles/ufs_hera.intel.lua b/modulefiles/ufs_hera.intel.lua
index 469dacd9..c86cfb1d 100644
--- a/modulefiles/ufs_hera.intel.lua
+++ b/modulefiles/ufs_hera.intel.lua
@@ -2,7 +2,7 @@ help([[
 loads UFS Model prerequisites for Hera/Intel
 ]])

-prepend_path("MODULEPATH", "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.0/envs/unified-env/install/modulefiles/Core")
+prepend_path("MODULEPATH", "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.0/envs/unified-env-noavx512/install/modulefiles/Core")
 prepend_path("MODULEPATH", "/scratch1/NCEPDEV/jcsda/jedipara/spack-stack/modulefiles")

 stack_intel_ver=os.getenv("stack_intel_ver") or "2021.5.0"
```

**Comment by DusanJovic-NOAA** [comment]
nccmp now works fine on ecflow node on Hera. Thanks.

Do we still need:
``` 
prepend_path("MODULEPATH", "/scratch1/NCEPDEV/jcsda/jedipara/spack-stack/modulefiles")
```

**Comment by DusanJovic-NOAA** [comment]
When I look at the top of the model stdout, I see:

```                                                                                          
Currently Loaded Modules:
  1) intel/2022.1.2                   23) crtm-fix/2.4.0_emc
  2) stack-intel/2021.5.0             24) git-lfs/2.10.0
  3) impi/2022.1.2                    25) crtm/2.4.0
  4) stack-intel-oneapi-mpi/2021.5.1  26) g2/3.4.5
  5) curl/7.29.0                      27) g2tmpl/1.10.2
  6) cmake/3.23.1                     28) ip/4.3.0
  7) libjpeg/2.1.0                    29) sp/2.3.3
  8) jasper/2.0.32                    30) w3emc/2.10.0
  9) zlib/1.2.13                      31) gftl/1.9.0
 10) libpng/1.6.37                    32) gftl-shared/1.5.0
 11) pkg-config/0.27.1                33) fargparse/1.4.2
 12) hdf5/1.14.0                      34) gettext/0.19.8.1
 13) snappy/1.1.10                    35) libxcrypt/4.4.35
 14) zstd/1.5.2                       36) sqlite/3.42.0
 15) c-blosc/1.21.4                   37) util-linux-uuid/2.38.1
 16) netcdf-c/4.9.2                   38) python/3.10.8
 17) netcdf-fortran/4.6.0             39) mapl/2.35.2-esmf-8.4.2
 18) parallel-netcdf/1.12.2           40) scotch/7.0.4
 19) parallelio/2.5.10                41) ufs_common
 20) esmf/8.4.2                       42) nccmp/1.9.0.1
 21) fms/2023.01                      43) modules.fv3
 22) bacio/2.4.1

 

Model started:   Fri Oct 6 17:00:11 GMT 2023
  0: 
  0: 
  0: * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . * . 
  0:      PROGRAM ufs       HAS BEGUN. COMPILED       0.00     ORG: np23   
  0:      STARTING DATE-TIME  OCT 06,2023  17:00:18.275  279  FRI   2460224
```

Why does model need libxcrypt, sqlite, snappy, python, gettext etc? None of these are currently needed in develop branch. Where do all these dependencies come form?

**Comment by climbfuji** [comment]
spack-stack typically builds everything from scratch that is a dependency for libraries you want, unless you tell it to go and use an external package (an OS library etc). We haven't implemented the logic to "hide" these modules that are just dependencies of the "primary modules" that we are really interested in - it's on our todo list.

**Comment by climbfuji** [comment]
@DusanJovic-NOAA Jet admins fixed the ecflow module, I removed the workaround in my ufs-weather-model PR.
