### ISSUE TITLE
[INSTALL] gsi-ncdiag 1.1.2

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [JCSDA/spack-stack#822]
**Which software in the stack would you like installed?**
gsi-ncdiag

**What is the version/tag of the software?**
1.1.2

**What compilation options would you like set?**
Standard options

**Installation timeframe: Would you like this package to be installed in an upcoming quarterly spack-stack release, or sooner? If it is needed sooner (such as for testing a new package/version before incorporating it into a full release), please specify a preferred timeline and *one* machine on which you would like it to be installed for testing prior to the next spack-stack release.**
This should replace gsi-ncdiag 1.1.1 in the upcoming spack-stack 1.5.1 installation.  It would be nice to have this installed under 1.5.0 on Hera for testing ahead of that time.  The gsi-ncdiag PR is still open at this time (NOAA-EMC/gsi-ncdiag#8), after which I will create a spack PR.  Once these are merged, I will update this issue.

**Any other relevant information that we should know to correctly install the software??**
Dependent on netCDF-c/netCDF-fortran/HDF5 4.9.2/4.6.0/1.14.0

**Additional context**
This will resolve a memory over-allocation in the GSI.

**Comment by AlexanderRichert-NOAA** [comment]
Relatedly, I'll install this version in a test space on Hera per discussion with @DavidHuber-NOAA & @aerorahul.

@climbfuji can we include this in 1.5.1? If so I can update the recipe/default while I'm looking at it.

**Comment by climbfuji** [comment]
Yes, it's in the plan. I'll merge the spack PR for jcsda_emc_spack_stack now, then we need a PR for spack-stack develop to update the version in config/*, once that's done I created the PRs to backport this to release/1.5.1.

**Comment by Hang-Lei-NOAA** [comment]
First of all, we need the tag to be made correctly as expected.

**Comment by climbfuji** [comment]
It's there: https://github.com/NOAA-EMC/GSI-ncdiag/releases/tag/v1.1.2 and the spack PR is also merged already: https://github.com/JCSDA/spack/pull/343

**Comment by climbfuji** [comment]
This is done, spack-stack@1.5.1 has been rolled out everywhere and comes with gsi-ncdiag@1.1.2
