### ISSUE TITLE
[INSTALL] fms/2023.02.01

### ISSUE THREAD

**Issue by junwang-noaa** [JCSDA/spack-stack#823]
Note: Please search to see if an issue already exists for the software you are requesting to be installed.

**Which software in the stack would you like installed?**
fms 

**What is the version/tag of the software?**
2023.02.01

**What compilation options would you like set?**
The same as 2023.02.

**Installation timeframe: Would you like this package to be installed in an upcoming quarterly spack-stack release, or sooner? If it is needed sooner (such as for testing a new package/version before incorporating it into a full release), please specify a preferred timeline and *one* machine on which you would like it to be installed for testing prior to the next spack-stack release.**
See the list of [supported HPC platforms](https://spack-stack.readthedocs.io/en/latest/PreConfiguredSites.html).
The bug fix in fms/2023.02.01 is required for the GFSv17 IAU coupled configuration. It is one of the few high priorities in GFSv17 implementation. We hope to get it installed (installed of fms/2023.02) in spack stack 1.5.0 as soon as possible.

**Any other relevant information that we should know to correctly install the software??**
Please describe in as much detail as possible (such as whether there is currently a Spack recipe for this package).

**Additional context**
Add any other context or screenshots about the install request here.

**Comment by junwang-noaa** [comment]
Please let me know when a test version is available, I will test it in UFS WM. Thanks

**Comment by AlexanderRichert-NOAA** [comment]
@junwang-noaa since spack-stack 1.5.0 is already deployed, would it be sufficient to add this on to the installations on, say, Hera, Orion, and Acorn?

**Comment by junwang-noaa** [comment]
Sure.

**Comment by climbfuji** [comment]
This should go into release/1.5.1 - we plan on rolling 1.5.1 out in the first week of November. I would encourage everyone not to make too many changes on a subset of machines. I think the idea was that we'd pick one system (e.g. Hera) where candidate versions for the next release get installed in a chained environment for testing. Don't install in the official locations please (same for gsi-ncdiag).

**Comment by AlexanderRichert-NOAA** [comment]
As I recall the idea was to minimize spack-stack team workload by not having developers assume that a new test package would immediately get installed into chained environments on all of the supported platforms, but it should get installed on as many as is necessary for the work being done. @junwang-noaa, would it suffice to just have Acorn and maybe one of the other machines? And/or can it wait until early November?

On Acorn, the updated environment with fms@2023.02.01 is at /lfs/h1/emc/nceplibs/noscrub/spack-stack/spack-stack-1.5.0/envs/fms-2023.02.01/install/modulefiles/Core

**Comment by climbfuji** [comment]
> As I recall the idea was to minimize spack-stack team workload by not having developers assume that a new test package would immediately get installed into chained environments on all of the supported platforms, but it should get installed on as many as is necessary for the work being done. @junwang-noaa, would it suffice to just have Acorn and maybe one of the other machines? And/or can it wait until early November?
> 
> On Acorn, the updated environment with fms@2023.02.01 is at /lfs/h1/emc/nceplibs/noscrub/spack-stack/spack-stack-1.5.0/envs/fms-2023.02.01/install/modulefiles/Core

That's what I was trying to say albeit less concise ;-)

**Comment by junwang-noaa** [comment]
Unfortunately, we can't use the fms/2023.02 in spack-stack 1.5.0 for GFSv17 implementation, the fms/2023.02.01 needs to be available on the major development platforms and wcoss2. I was told this is a priority for GFSv17 implementation. Is there any way I can escalate this?

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA If you could take care of the PRs for fms to develop and then the backport to release/1.5.1, please? I'll do gsi-ncdiag. Thanks!

**Comment by AlexanderRichert-NOAA** [comment]
@climbfuji yes will do.

@junwang-noaa, when you say major development platforms, would that be Hera Orion Acorn?

**Comment by junwang-noaa** [comment]
it's hera/orion/gaea and wcoss2 (cactas and dogwood). We can only run low resolution tests on Acorn.

**Comment by junwang-noaa** [comment]
@AlexanderRichert-NOAA My test failed on acorn when using the spack stack: /lfs/h1/emc/nceplibs/noscrub/spack-stack/spack-stack-1.5.0/envs/fms-2023.02.01/install/modulefiles/Core

With error:
```
double free or corruption (fasttop)
double free or corruption (fasttop)
double free or corruption (fasttop)
double free or corruption (fasttop)
double free or corruption (fasttop)
double free or corruption (fasttop)
double free or corruption (fasttop)
```

I noticed that several libraries are updated in this version ip, w3emc, scotch and GOCART besides fms. May I ask if the library has been tested on acorn yet? Also is it possible that you can install a test version on hera for me to try? Just want to confirm if it could be related to the installation on acorn.

**Comment by AlexanderRichert-NOAA** [comment]
I'm not aware of any other testing of fms@2023.02.01 on Acorn. I'll install on Hera and we can go from there.

**Comment by AlexanderRichert-NOAA** [comment]
I seem to recall that we ran into "double free" errors with certain versions of ESMF, but I don't remember how that got resolved (or if there were other things that could trigger it).

**Comment by junwang-noaa** [comment]
FYI. I ran the same tests on acorn with the UFS weather model develop branch (using spack-stack 1.4.1), the tests passed successfully.

**Comment by AlexanderRichert-NOAA** [comment]
I don't (yet) have access to the main installation on Hera, so for now here's a test environment in my personal space, which is built on the 1.5.0 deployment: /scratch1/NCEPDEV/nems/Alexander.Richert/spack-stack-1.5.0-fms/envs/fms-test/install/modulefiles/Core

**Comment by climbfuji** [comment]
Note that the spack-stack-1.5.0 version updates (ip, w3emc, scotch and GOCART) are all tested as part of my ufs-weather-model PR and they work fine. Must be the FMS version.

**Comment by AlexanderRichert-NOAA** [comment]
Good point. I'll see if I can reproduce it on Acorn.

**Comment by AlexanderRichert-NOAA** [comment]
@junwang-noaa is there a particular RT where you're encountering the double free errors?

**Comment by junwang-noaa** [comment]
I am running the cpld_control_gfsv17 test on acorn.

**Comment by AlexanderRichert-NOAA** [comment]
I just remembered this is the issue we resolved by using static ESMF instead of shared. For some reason in spack-stack-1.5.0 on Acorn, ESMF was concretized/built as a shared library, so that's why 1.4.1 is working (where ESMF was correctly built static) but not 1.5.0. I'll fix this in 1.5.0 on Acorn and I'm betting that'll take care of it.

**Comment by junwang-noaa** [comment]
Great! Thanks for looking into the issue. Please let me know if you have an updated spack stack ready.

**Comment by AlexanderRichert-NOAA** [comment]
Okay please try again. I ran cpld_control_gfsv17 successfully just now on Acorn -- that was using Dom's spack-stack 1.5.0 PR + adding `use mpp_mod` to two of the files under FV3/io/.

**Comment by junwang-noaa** [comment]
@AlexanderRichert-NOAA I tested the case on Acorn, the results are expected. Would you please install the version on other R&D platforms? Besides GOCART changes in Dom's PR, Dusan has the fv3/io changes in his UFS WM [PR#1932](https://github.com/ufs-community/ufs-weather-model/pull/1932) (fv3 [PR#706](https://github.com/NOAA-EMC/fv3atm/pull/706)). I hope we can have this bug fix version fms/2023.02.01 when we update UFS WM with the 2nd spack-stack PR after Dom's PR#1920 to update ESMF,MAPL, FMS. Currently it is a bottleneck for ocn to create correct history files in GFSv17 IAU configuration with fms 2023.02. Please let me know what I can help with using fms/2023.02.01, instead of 2023.02.  Thank you very much!

**Comment by AlexanderRichert-NOAA** [comment]
Great- I can install it on Orion in the same way as Acorn, and soon I should have role account access for installing on Hera & Gaea...

**Comment by AlexanderRichert-NOAA** [comment]
On Orion: /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.5.0/envs/fms-2023.02.01/install/modulefiles/Core

**Comment by AlexanderRichert-NOAA** [comment]
On Hera: /scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.0/envs/fms-2023.02.01/install/modulefiles/Core

On Gaea C4: /lustre/f2/dev/wpo/role.epic/contrib/spack-stack/c4/spack-stack-1.5.0/envs/fms-2023.02.01/install/modulefiles/Core

**Comment by climbfuji** [comment]
@RatkoVasic-NOAA @ulmononian What's the status of spack-stack-1.5.1 on the platforms that you've been working on (Jet, Hera, Gaea C4)?

**Comment by RatkoVasic-NOAA** [comment]
@climbfuji  Done on Jet and Hera

**Comment by junwang-noaa** [comment]
@RatkoVasic-NOAA would you please share the spack-stack location on these two platforms?

**Comment by climbfuji** [comment]
@RatkoVasic-NOAA Ecellent, can you please provide the information on install location and any site config updates you had to make so that I can add them to the release/1.5.1 branch (e.g. as part of https://github.com/JCSDA/spack-stack/pull/855)?

**Comment by RatkoVasic-NOAA** [comment]
```
Jet:/mnt/lfs4/HFIP/hfv3gfs/role.epic/spack-stack/spack-stack-1.5.1
Hera:/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.1
```
No config updates.

**Comment by ulmononian** [comment]
@climbfuji done on c4

**Comment by RatkoVasic-NOAA** [comment]
`Gaea-c4:/lustre/f2/dev/wpo/role.epic/contrib/spack-stack/c4/spack-stack-1.5.1`

**Comment by climbfuji** [comment]
The roll-out of spack-stack@1.5.1 with fms@2023.02.01 is complete, closing.
