### ISSUE TITLE
Remove upp/10.0.10 from spack-stack installation

### ISSUE THREAD

**Issue by WenMeng-NOAA** [JCSDA/spack-stack#825]
**Describe the bug**
The upp is configured as a submodule of FV3 component at ufs-weather-model now.  Pre-installed upp lib is not needed any more. Could you remove upp/10.0.10 from the list of spack-stack?
 
**To Reproduce**

**Expected behavior**

**System:**
What system(s) are you running the code on?

**Additional context**

**Comment by climbfuji** [comment]
Do we know for sure that no other component out there uses upp provided as module? JEDI doesn't but how about UFS SRW app and other applications? @ulmononian Do you know?

**Comment by WenMeng-NOAA** [comment]
Thanks for making this done.
