### ISSUE TITLE
Derecho site config updates ... once more

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#835]
**Is your feature request related to a problem? Please describe.**
Derecho continues to be a pain .. ... ... but I think now the module config is somewhat stable enough that we can update the modules in the site config to use `ncarenv/23.09` in the compiler dependencies and then avoid using our workaround modulefiles.

**Describe the solution you'd like**
We should try this when we roll out spack-stack-1.5.1 and then bring it back to develop when we merge the release branches back one final time.

**Additional context**
n/a

**Comment by ulmononian** [comment]
@climbfuji do you have an updated derecho site config somewhere that uses `ncarenv/23.09` i can test with? was not clear if you had a branch for this yet or not.

i was hoping to use spack-stack/1.5.0 for [ufs-wm PR #1836](https://github.com/ufs-community/ufs-weather-model/pull/1836)...

**Comment by climbfuji** [comment]
derecho and the other two systems cheyenne and casper are down for the entire week. Likely derecho will look different again after the maintenance, and I'll have to update my new site config which uses ncarenv 23.09) again.

**Comment by climbfuji** [comment]
closed via https://github.com/JCSDA/spack-stack/pull/853
