### ISSUE TITLE
Model Coupling Toolkit (MCT)

### ISSUE THREAD

**Issue by michalakes** [JCSDA/spack-stack#845]
**Is your feature request related to a problem? Please describe.**
The Model Coupling Toolkit ([MCT](https://github.com/MCSclimate/MCT/releases/tag/MCT_2.11.0))  supports straightforward coupling between components of a multi-component application such as the DOE's E3SM. NRL would like to use MCT to support part of our implementation of asynchronous model output in a way that allows the model to write asynchronously (for performance) in stand-alone fashion when NUOPC is not available or otherwise needed. Simplifies operation and also possibly interaction between NEPTUNE and JEDI.

**Describe the solution you'd like**
Add MCT to Spack-stack as a library package and set of Fortran module includes and mod files

**Additional context**

**Comment by climbfuji** [comment]
@michalakes I checked the spack repo and it's currently not available, which means that we'll have to add and configure it. We are planning to include it in spack-stack 1.6.0 in December. Is that timeline ok?

**Comment by michalakes** [comment]
Sorry I missed this reply, Dom.  Yes, December is plenty soon enough. Thanks!

**Comment by climbfuji** [comment]
@michalakes I built mct in spack-stack on my macOS, how can I test it?

**Comment by michalakes** [comment]
> @michalakes I built mct in spack-stack on my macOS, how can I test it?

There are some test codes in the MCT distribution.  The simple 2-component concurrent case is the one I have used.

**Comment by climbfuji** [comment]
Done: `spack-stack@1.6.0` is installed on all platforms (release will be announced tomorrow) and comes with `mct@2.11.0`
