### ISSUE TITLE
spack-stack-1.3.1 issue on Orion? (Hercules?)

### ISSUE THREAD

**Issue by mjhossen** [JCSDA/spack-stack#852]
**Describe the bug**
I built soca-science with /work/noaa/epic-ps/role-epic-ps/spack-stack/spack-stack-1.3.1/envs/unified-env/ and was able to run cycles without problem until Oct 25. But today, I found a problem with netCDF4 saying 
```ImportError: libmpi.so.40: cannot open shared object file: No such file or directory```

**System:**

Traceback (most recent call last):
  File "/work/noaa/aoml-osse/jhossen/sandbox/soca-science-stablenightly-Sep252023/build.gnu/bin/soca_preqc.py", line 12, in <module>
    import netCDF4 as nc
  File "/work/noaa/epic-ps/role-epic-ps/spack-stack/spack-stack-1.3.1/envs/unified-env/install/gcc/10.2.0/py-netcdf4-1.5.3-shy6v3v/lib/python3.9/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
ImportError: libmpi.so.40: cannot open shared object file: No such file or directory

**Additional context**

**Comment by climbfuji** [comment]
Can you try this again with spack-stack-1.5.0 or 1.5.1 please?

**Comment by climbfuji** [comment]
@natalie-perlin @ulmononian Can you please help @mjhossen when he comes back with answers to my question?

**Comment by natalie-perlin** [comment]
@mjhossen - please note that the space on Orion /work/noaa/epic-ps/role-epic-ps/ is no longer available, it was a temporary solution until a project-dedicated space has been established.  All the software stacks and data on Orion have migrated to `/work/noaa/epic/role-epic/ ` . The migration was requested in spring, but the read-only space was still available until recently. I'm sorry to hear you and/or your group was not notified.
There seem to be several spack-stacks built on Orion, please take a look if any of them could work for you:
/work/noaa/epic/role-epic/spack-stack/spack-stack-1.4.1
/work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.5.0
/work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.5.1

**Comment by climbfuji** [comment]
@mjhossen Were you able to build your application with any of the newer spack-stack installations? Can we close this issue?

**Comment by climbfuji** [comment]
CLosing this due to a lack of activity
