### ISSUE TITLE
release/1.5.1 CI containers don't have bufr@12.0.1, but bufr@12.0.0

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#867]
**Describe the bug**
When `bufr@12.0.1` was added for release 1.5.1, the container specs didn't get updated and therefore the 1.5.1 JEDI CI containers still have `bufr@12.0.0`.

**To Reproduce**
See https://github.com/JCSDA/spack-stack/blob/883ebcb2509df68702a7207bdd410926f20e3e9c/configs/containers/README.md?plain=1#L8C58-L8C58

**Expected behavior**
We wanted 12.0.1, not 12.0.0.

**System:**
Docker containers used by JEDI CI

**Additional context**
Since the next release 1.6.0 will be made before Christmas, there is no point going back and fixing it in the release. Instead, update https://github.com/JCSDA/spack-stack/blob/651ff12482b6f583c8e90a58ec826ec61947c9d2/configs/containers/specs/jedi-ci.yaml#L3 after https://github.com/JCSDA/spack-stack/pull/866 was merged.

**Comment by srherbener** [comment]
@climbfuji thank you for finding this! Sure enough the ioda converter test that depends on bufr@12.0.1 doesn't find the required version and skips the build and test of the bufr2ioda.x app. See https://github.com/JCSDA-internal/ioda-converters/pull/1325 for details.

Is it just a matter of manually rebuilding the containers, or should we do a 1.5.2 patch? The OBS team may decide to merge PR 1325 and then the bufr2ioda build and testing will be skipped until the containers are fixed.

**Comment by srherbener** [comment]
Sorry, I think I missed something in the initial description the first time I read it. You are suggesting we go ahead and merge 1.5.1 into develop, then submit a PR to develop that updates the container spec, then rebuild the containers from that point. If that's what you are saying, then I agree that is the way to proceed (since it will save a lot of headache by avoiding a patch to 1.5.1).

**Comment by climbfuji** [comment]
I wanted to suggest to make that update with 1.6.0 in 6 weeks or so, unless that's a showstopper. We can rebuild the containers but they won't be release/1.5.1 anymore. At this point, I am pretty much against a 1.5.2 release given how much work it is every time.

**Comment by climbfuji** [comment]
@srherbener I thought about this again. Since release/1.5.1 has bufr@12.0.1 in the site configs (preconfigured and user), but just not in the containers, I think we should simply rebuilt the containers and make a manual change in the container specs to get the new bufr version. No new release etc. The next release 1.6.0 is around the corner, therefore the chances that we would want to go back again and do another container update (and then have to remember to switch bufr) are pretty low. Thoughts?
