### ISSUE TITLE
[INSTALL]: w3emc/2.10.0 and ip/4.3.0 with 8-byte integer support

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [JCSDA/spack-stack#873]
### Package name

w3emc and ip

### Package version/tag

2.10.0 and 4.3.0, respectively

### Build options

BUILD_8=ON in both cases

### Installation timeframe

Please install into the gsi-addon environment on Hera first, then on all platforms.

### Other information

Both the gsi_utils and gfs_utils repositories require passing 8-byte integers to these libraries.

###
Platforms:
- [x] Hera
- [x] Orion
- [x] Jet
- [x] Gaea C5
- [x] Hercules
- [x] S4

**Comment by AlexanderRichert-NOAA** [comment]
:+1:

**Comment by AlexanderRichert-NOAA** [comment]
Done on Hera. @DavidHuber-NOAA let me know if that looks good.

**Comment by DavidHuber-NOAA** [comment]
@AlexanderRichert-NOAA Hmm, unfortunately, I am still having trouble with gfs_utils.  It cannot find the `ip` routines `GDSWZD`, `ipolates`, and `ipolatev` in the ip library.  Would you mind taking a look at the build log: `/scratch1/NCEPDEV/nems/David.Huber/GW/gw_spack-stack_151/sorc/gfs_utils.fd/ush/build.log`

If we cannot get this sorted, I may need to request w3emc/2.9.2 and ip/3.3.3 be installed instead.

**Comment by AlexanderRichert-NOAA** [comment]
The ipolates and ipolatev ones are easy, just add "use ip_mod, only: ipolates, ipolatev" at the top of that subroutine with the other use statements. For gdswzd, I'm running into trouble in fbwndgfs.f and I'm not sure what the issue is.

**Comment by AlexanderRichert-NOAA** [comment]
Okay apparently taking out "use gdswzd" at the top does the trick... I have no idea why that is, but, I guess go ahead and try it and see if that helps. :upside_down_face:

**Comment by AlexanderRichert-NOAA** [comment]
fbwndgfs.fd/fbwndgfs.f, GDSWZD issue: I can fix this by changing `GDSWZD` to `GDSWZD_GRIB1`. I'll make an issue for this in the library since it may mean there's something wrong with the interface.

**Comment by AlexanderRichert-NOAA** [comment]
For mkgfsawps.fd, I can get it to work if I switch it over to ip_4, though I don't know if that's desirable. If needed we can go with 3.3.3 for now, though if we can push through and get things working with ip v4 that would definitely be nice.

**Comment by DavidHuber-NOAA** [comment]
@AlexanderRichert-NOAA Thanks for the detective work!  I will see what I can dig out of `mkgfsawps`'s use of ~ip_8~ `ip_d` and if it's necessary.

**Comment by DavidHuber-NOAA** [comment]
@AlexanderRichert-NOAA I ran into a hang with the AWIPS generation program in gfs_utils (`mkgfawps.x`) using w3emc/2.10.0 on Hera.  I created an issue to track this with more details: noaa-emc/gfs-utils#33.

**Comment by AlexanderRichert-NOAA** [comment]
Okay. This may relate to some changes made to w3emc. I'll try some different build settings, probably in another chained environment, and we can see if that helps.

**Comment by DavidHuber-NOAA** [comment]
Everything checked out on Hera.  There are issues with metplus/3.1.1 -- it appears that that version of metplus is incompatible with python/3.10.8, but this isn't critical as users can run verif-global offline with the system builds of met and metplus.

**Comment by DavidHuber-NOAA** [comment]
Can we go ahead and install w3emc and ip with 8-byte integers into the gsi-addon environments on Orion, Jet, S4, and Hercules?

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA If you don't mind, can you provide a set of instructions for the install please?

**Comment by AlexanderRichert-NOAA** [comment]
Yep sounds good

**Comment by AlexanderRichert-NOAA** [comment]
After setup.sh, inside envs/gsi-addon/ dir:
```
for lib in w3emc ip sp; do
  mkdir envrepo/packages/${lib}
  wget https://raw.githubusercontent.com/NOAA-EMC/NCEPLIBS-${lib}/develop/spack/package.py --output-document=envrepo/packages/${lib}/package.py
  if [[ "w3emc ip" =~ ${lib} ]]; then
    sed -i "s:global-workflow-env.\+:& ^${lib} precision=4,d,8:" spack.yaml
    sed -i "s:ufs-weather-model-env.*:& ^${lib} precision=4,d,8:" spack.yaml
  fi
done

sed -i "s:w3emc:w3emc +extradeps:" spack.yaml
sed -i 's:depends_on("sp precision=.":depends_on("sp@2.3.3":' envrepo/packages/ip/package.py

spack env activate .

spack concretize |& tee log.concretize_w3emc_ip_8

spack install global-workflow-env%intel ufs-weather-model-env%intel |& tee log.install_w3emc_ip_8

spack module lmod refresh --upstream-modules
```

For some reason, just running plain "spack install" produced some weird behavior in envs with multiple compilers, and it was fixed by explicitly listing endpoint packages with compilers... but it may not matter when there's only one compiler. @climbfuji if you can please do S4 again I can take care of the rest.

**Comment by AlexanderRichert-NOAA** [comment]
The affected libraries should be ip, w3emc, nemsio, nemsiogfs, and grib-util, plus the UFSWM and GW metapackages.

**Comment by AlexanderRichert-NOAA** [comment]
Hera Orion Gaea/C5, Jet, Hercules done

**Comment by climbfuji** [comment]
@DavidHuber-NOAA @AlexanderRichert-NOAA I updated the S3 gsi-addon env. I took that opportunity to fix my previous mistake and reinstall the entire gsi-addon env with the correct upstream (spack-stack-1.5.1). David can you please check if it all looks ok?
```
Metamodule generation completed successfully in /data/prod/jedi/spack-stack/spack-stack-1.5.1/envs/gsi-addon/install/modulefiles/Core
```

**Comment by DavidHuber-NOAA** [comment]
Verified installs on Hera, Jet, Orion, S4, Gaea-C5, and Hercules.  Successfully built against on Hera, Jet, Orion, and S4 and successfully tested against on Hera and Orion.  Thanks @AlexanderRichert-NOAA and @climbfuji!!  We can go ahead and close this.
