### ISSUE TITLE
[INSTALL]: Python 3.10.12+

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [JCSDA/spack-stack#887]
### Package name

Python

### Package version/tag

3.10.12 or newer

### Build options

Current

### Installation timeframe

With the next release, though it would be good to have a test environment with metplus/3.1.1 to verify it works before installing everywhere.

### Other information

There is an import bug in Python 3.10.8 that appears to be resolved with 3.10.12 (see https://github.com/python/cpython/issues/88227) that affects METplus version 3.1.1 (see https://github.com/NOAA-EMC/global-workflow/issues/2091).

### WCOSS2

- [ ] Check this box if and only if your package should be installed on WCOSS2 Cactus and Dogwood (all spack-stack packages will be installed on Acorn). If not, you may disregard the rest of the items below and submit this request.

### WCOSS2: Technical & security review list

- [ ] The code is mature, stable, and production ready
- [ ] The code is does not and cannot use the internet, and does not contain URLs (http, https, ftp, etc.) except in comments
- [ ] The package does not contain prebuilt binary files that have not been approved by NCO security review
- [ ] The code has no publicly disclosed cybersecurity vulnerabilities and exposures (search https://cve.mitre.org/cve/)
- [ ] The code is not prohibited by DHS, DOC, NOAA, or NWS
- [ ] The code comes from a trusted source. Trusted sources include other NWS, NOAA, or DOC, agencies, or other Federal agencies that operate at a FISMA high or equivalent level. Additionally, trusted sources could be third-party agencies through which there is an existing SLA on file (such as RedHat).
- [ ] The code is actively maintained and supported (it continues to get updates, patches, etc.)
- [ ] The code is not maintained by a private entity operating in a foreign country (if it is, make a note below)
- [ ] There is sufficient documentation to support maintenance
- [ ] There are no known security vulnerabilities or weaknesses
- [ ] Installing and running the code does not require privileged processes/users
- [ ] There are no software dependencies that are unapproved or have security concerns (if there are, make a note below)
- [ ] There are no concerns related to SA, SI, and SC NIST control families

**Comment by climbfuji** [comment]
Thanks @DavidHuber-NOAA! We should definitely have a test environment early in the process of rolling out.

**Comment by climbfuji** [comment]
@DavidHuber-NOAA FYI I'll be addressing this in one of my next PRs (adding cylc).

**Comment by malloryprow** [comment]
If there is a test installation at any point, I am happy to test.

**Comment by climbfuji** [comment]
> If there is a test installation at any point, I am happy to test.

We'll have a release candidate on Hercules towards the end of next week.
