### ISSUE TITLE
NUOPC/ESMF build

### ISSUE THREAD

**Issue by michalakes** [JCSDA/spack-stack#892]
**Describe the bug**

Compiling our application as a NUOPC component using the Spack-Stack version of ESMF.  I’m running into  `[spack cc] ERROR: Spack compiler must be run from Spack! Input ‘some variable' is missing, `where variable is:
 
```
SPACK_ENV_PATH
SPACK_DEBUG_LOG_DIR
SPACK_DEBUG_LOG_ID
SPACK_COMPILER_SPEC
SPACK_CC_RPATH_ARG
…etc…
 
```

Setting one of these in the environment just leads to the same error on the next unset variable in the list.  Didn't chase it all the way bottom, once I hit one I didn't know how to fudge (last in the list above).  This is on Narwhal (narwhal.navydsrc.hpc.mil)

**To Reproduce**
Not sure how to provide a simple reproducer, here, since its tangled up with the build for our application and cannot be distributed. If one has access to our application, I can send instructions for how to reproduce on Narwhal

**Expected behavior**

Should compile and link correctly.

**System:**
Narwhal (narwhal.navydsrc.hpc.mil)

**Comment by climbfuji** [comment]
This is because the spack compiler end up in `esmf.mk` as `ESMF_F90COMPILER` etc. I think a similar bug fix than what was needed for hdf5 (`h5cc`) and hdf4 can be applied here: https://github.com/spack/spack/blob/7d45e132a669c54cc591fd2c019936c65868358d/var/spack/repos/builtin/packages/esmf/package.py#L393

**Comment by jedwards4b** [comment]
Not sure why you would assign me.

**Comment by climbfuji** [comment]
Apologies, but isn't the ESMF team maintaining the esmf package in spack? Should I assign someone else from your team (who)? Solving this issue requires updates to the esmf package.

**Comment by jedwards4b** [comment]
Ah - I'm not on the ESMF team.   "theurich" and "uturuncoglu" are.

**Comment by climbfuji** [comment]
> Ah - I'm not on the ESMF team. "theurich" and "uturuncoglu" are.

Oh I am sorry. I'll ask them for help then. Thanks!

**Comment by climbfuji** [comment]
Issue in spack: https://github.com/spack/spack/issues/41487

**Comment by climbfuji** [comment]
@sking112 Just mentioned that the DA team has a workaround in NEPTUNE, which supresses the use of the ESMF compiler/linker variables. That may be a good alternative to my suggestion for a workaround (manually modify `esmf.mk`) until it's fixed in the next spack-stack release.
