### ISSUE TITLE
Add util to check executables/shared libs for missing shared libs for macOS -> no, support on Linux only

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#898]
**Is your feature request related to a problem? Please describe.**
PR https://github.com/JCSDA/spack-stack/pull/890 adds a utility to check executables/shared libs for missing shared libraries for Linux. The macOS part still needs to be done post spack-stack 1.6.0

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA I suggest we don't try to implement this for macOS. There's no clean and easy way. You can either have full paths to libraries or "rpath-ed" libraries, but the output of `otool` is not going to tell you if a shared library can be found or not (unlike Linux). You would have to spend quite some time on the `ldd_check.py` utility to
- check for each linked library with an absolute path if it exists
- collect all rpaths stored in the dylib library
- then loop over all rpaths for each library that is linked as `@rpath/mylibrary.dylab` and check if it can be found in any of these locations

Given that I haven't used the utility at all, I feel like this is too much effort. I will update the tool and the documentation to make clear this only works on Linux, and send it your way to review if that's ok.

**Comment by climbfuji** [comment]
See commit 815cd37a1b00e03097bb5a4a5e1ff091419a193c

**Comment by AlexanderRichert-NOAA** [comment]
That sounds good. The precipitating issue was one that involved a missing dependency in a recipe (which will apply regardless of platform), plus arguably it's mostly important to catch these things in our tier-1 platform installations, so I have no objection to making it Linux only.

**Comment by climbfuji** [comment]
Thanks very much!
