### ISSUE TITLE
Need an updated prod_util library to support err_exit() on HPCs with Slurm

### ISSUE THREAD

**Issue by guoqing-noaa** [JCSDA/spack-stack#899]
**Is your feature request related to a problem? Please describe.**
The current prod_util released with spack-stack is too old and err_exit() will not work as expected on HPCs with Slurm (such as Hera, Jet, Orion, etc)

**Describe the solution you'd like**
prod_util needs to be updated to support slurm for err_exit() as in this PR https://github.com/NOAA-EMC/NCEPLIBS-prod_util/pull/69

**Additional context**
An updated prod_util has been used for a while in the[ rrfs-workflow ](https://github.com/NOAA-EMC/rrfs-workflow) through a temporary installation.

**Comment by climbfuji** [comment]
Please provide a minimum version number that fixes the problem, thanks!

**Comment by guoqing-noaa** [comment]
> Please provide a minimum version number that fixes the problem, thanks!

Thanks, @climbfuji! Will provide a version number once the referenced NCEPLIBS-prod_util PR is merged.

**Comment by guoqing-noaa** [comment]
@climbfuji Not sure whether a tag will be ready tomorrow but my PR was merged today and the latest commit hash is [d1db177](https://github.com/NOAA-EMC/NCEPLIBS-prod_util/commit/d1db177d910187e3add5f317e65f60732aab758a). Can spack-stack uses a hash?

**Comment by climbfuji** [comment]
We can but we really don't want to do that. I'd rather wait until Friday, but if the tag isn't ready by then it likely won't be in spack-stack-1.6.0.

**Comment by climbfuji** [comment]
Resolved via https://github.com/JCSDA/spack-stack/pull/906

**Comment by guoqing-noaa** [comment]
Thanks, @climbfuji
