### ISSUE TITLE
Cannot use ESMF_F90COMPILER macro

### ISSUE THREAD

**Issue by drinkblud** [JCSDA/spack-stack#900]
**Describe the bug**

On the machine narwhal (navy), makefile cannot use $(ESMF_F90COMPILER) to compile Fortran code after loading spackstack modules. e.g.
%.o $(OBJDIR)/%.o : %.F90
  $(ESMF_F90COMPILER) -c $(FFLAGS_F90) $(ESMF_F90COMPILEOPTS) $(ESMF_F90COMPILEPATHS) $(ESMF_F90COMPILEFREECPP) $(ESMF_F90COMPILECPPFLAGS) $(CPLFLAG) $(MODFLAG) $(INCFLAG) $< -o $@
Results in an error:

/p/app/projects/NEPTUNE/spack-stack/spack-stack-1.5.1/spack/lib/spack/env/intel/ifort -c  -traceback -O3 -g -fPIC -m64 -align all -w -ftz -convert big_endian -assume byterecl -mcmodel=small -I/p/home/feiliu/ESPC/stackspack/ESPC-SRC/share   -I. -I/p/app/projects/NEPTUNE/spack-stack/spack-stack-1.5.1/envs/unified-env-intel-2021.4.0/install/intel/2021.4.0/netcdf-fortran-4.6.0-v6s2aeg/include -I/p/app/projects/NEPTUNE/spack-stack/spack-stack-1.5.1/envs/unified-env-intel-2021.4.0/install/intel/2021.4.0/netcdf-c-4.9.2-bidxx3c/include -I/p/app/projects/NEPTUNE/spack-stack/spack-stack-1.5.1/envs/unified-env-intel-2021.4.0/install/intel/2021.4.0/hdf5-1.14.0-wgpha3r/include code.F90 -o code.o
**[spack cc] ERROR: Spack compiler must be run from Spack! Input 'SPACK_ENV_PATH' is missing.**

Note that what's odd is that both $(ESMF_F90COMPILER) and $(FC) point to ftn on Narwhal.

**To Reproduce**
module use --append /p/app/projects/NEPTUNE/modulefiles
module load neptune/1.4

In any makefile use $(ESMF_F90COMPILER) instead of $(FC) results in the above error.

**Expected behavior**

I expected no difference using either $(FC) or $(ESMF_F90COMPILER) since both point to 'ftn'

**System:**
What system(s) are you running the code on?

Narwhal

**Additional context**

None

**Comment by drinkblud** [comment]
Used wrong github ID accidentally.

**Comment by climbfuji** [comment]
This would have been a duplicate of https://github.com/JCSDA/spack-stack/issues/892
