### ISSUE TITLE
"more" does not work on Derecho with UWM spack-stack modules loaded

### ISSUE THREAD

**Issue by DeniseWorthen** [JCSDA/spack-stack#910]
**Describe the bug**

The command "more" on Derecho fails if the UWM spack-stack is loaded.

**To Reproduce**

Login to Derecho and load no additional modules

```
[worthen@derecho:] /glade/work/worthen/ufs-weather-model: module list

Currently Loaded Modules:
  1) ncarenv/23.06 (S)

  Where:
   S:  Module is Sticky, requires --force to unload or purge
```

Issue a "more" command:
```
[worthen@derecho:] /glade/work/worthen/ufs-weather-model: more build.sh
#!/bin/bash
set -eu

if [[ $(uname -s) == Darwin ]]; then
...
```

Load UWM modules

```
[worthen@derecho:] /glade/work/worthen/ufs-weather-model: module use modulefiles/
[worthen@derecho:] /glade/work/worthen/ufs-weather-model: module load ufs_derecho.intel

The following have been reloaded with a version change:
  1) ncarenv/23.06 => ncarenv/23.09
```

Issue "more" command:

```
[worthen@derecho:] /glade/work/worthen/ufs-weather-model: more build.sh
more: symbol lookup error: more: undefined symbol: _nc_cur_term, version NCURSES6_TINFO_5.7.20081102
````
**Expected behavior**

more should work as expected

**System:**
What system(s) are you running the code on?

Derecho

**Additional context**

**Comment by climbfuji** [comment]
how about “less” ?

**Comment by DeniseWorthen** [comment]
[worthen@derecho:] /glade/work/worthen/ufs-weather-model: less build.sh
/bin/bash: error while loading shared libraries: libtinfo.so.6: failed to map segment from shared object

less works, but also produces the message above

**Comment by climbfuji** [comment]
Oh what fun ...

**Comment by climbfuji** [comment]
@DeniseWorthen Same problem for `watch`:
```
(venv) heinzell@derecho3:/lustre/desc1/scratch/heinzell/skylab-intel-20231218> watch -n 10 'ls'
watch: /glade/u/apps/derecho/23.09/opt/view/lib/libncursesw.so.6: version `NCURSESTW6_5.7.20081102' not found (required by watch)
```
I think what we need to do is remove packages or replace prefixes `/glade/u/apps/derecho/23.09/opt/view` for packages in https://github.com/JCSDA/spack-stack/blob/develop/configs/sites/derecho/packages.yaml with the actual path. Best is probably to try to stick with OS packages and include as little as possible packages installed under `/glade/u/apps/derecho/23.09`.

**Comment by climbfuji** [comment]
@DeniseWorthen I fixed this in the next spack-stack release 1.6.0 that we are currently rolling out. I'll close this bug when https://github.com/JCSDA/spack-stack/pull/930 gets merged (site config and doc update for Derecho for spack-stack-1.6.0), but of course you won't see the issue being resolved until you switch to 1.6.0.

**Comment by DeniseWorthen** [comment]
Great! It's definitely been an annoyance so it will be nice to have it fixed.

**Comment by climbfuji** [comment]
Closed via https://github.com/JCSDA/spack-stack/pull/930
