### ISSUE TITLE
Update eccodes to latest version 2.33.0

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#918]
**Is your feature request related to a problem? Please describe.**
After release/1.6.0: add eccodes 2.33.0 to spack develop, pull in, make default in our templates

**Describe the solution you'd like**
See above

**Comment by BenjaminRuston** [comment]
can't edit this issue

the only thing needed from ecCodes v2.33.0 are the new WMO BUFR templates.. at present the only data type I"m aware of that uses new metaData or parameters from these templates is the GNSS-RO. There are produced currently in real time by EUMETSAT for their Spire data, and for other commercial data EUMETSAT produces 

would expect all GNSS-RO data to start following soon as well

**Comment by climbfuji** [comment]
I started this by adding the latest version of eccodes to spack develop - PR is here: https://github.com/spack/spack/pull/42257. Once that is merged, I will bring the changes down to our fork.
