### ISSUE TITLE
Stop packages from accessing internet during installation

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#934]
Based on installing spack-stack-1.6.0 on Acorn, I found three packages that access the internet at install time (i.e., can't be completely pre-fetched), which causes the build to hang when building on the Acorn compute nodes. These are **proj**, **cprnc**, and **py-nbconvert**.

 - [x] proj - https://github.com/JCSDA/spack/pull/389
 - [x] cprnc - https://github.com/spack/spack/pull/42015
 - [x] py-nbconvert - https://github.com/spack/spack/pull/42024

**Comment by climbfuji** [comment]
Thanks for this @AlexanderRichert-NOAA !

**Comment by AlexanderRichert-NOAA** [comment]
All done
