### ISSUE TITLE
Remove libtool form Gaea, Hera and Jet in release/1.6.0

### ISSUE THREAD

**Issue by RatkoVasic-NOAA** [JCSDA/spack-stack#936]
**Is your feature request related to a problem? Please describe.**
Follow Hercules installation - removing libtool from Gaea, Hera and Jet.

**Describe the solution you'd like**
Removed libtool from configs/sites/*/packages.yaml

**Comment by climbfuji** [comment]
Closed via https://github.com/JCSDA/spack-stack/pull/937
