### ISSUE TITLE
Build an old version of soca-science using spack-stack-1.4.0 on C5

### ISSUE THREAD

**Issue by jieshunzhu** [JCSDA/spack-stack#946]
I am able to build an old version of soca-science using spack-stack-1.4.0 on C4, but failed to build it on C5. My log file with error is here: /lustre/f2/dev/ncep/JieShun.Zhu/ng-godas/CODEs/stable-nightly.20220729_iodaconvert_20240102c5spack1.4.0/build/log.ecbuild

Can anyone help me check my problems? Thanks.

The following is my machine.gaea-c5.intel. 
+++++++++++++++++++++
source /lustre/f2/dev/role.epic/contrib/Lmod_init_C5.sh
module unload cray-mpich
module unload darshan-runtime
module load PrgEnv-intel/8.3.3
module load intel-classic/2022.2.1
module load cray-mpich/8.1.25
module load python/3.9.12

module use /lustre/f2/dev/wpo/role.epic/contrib/spack-stack/modulefiles-c5
module load ecflow/5.8.4
module load mysql/8.0.31

module use /lustre/f2/dev/wpo/role.epic/contrib/spack-stack/spack-stack-1.4.0-c5/envs/unified-env-v2/install/modulefiles/Core
module load stack-intel/2022.2.1
module load stack-cray-mpich/8.1.25
module load stack-python/3.9.12
#module -t available

module load soca-env/unified-dev
module load fms/release-jcsda

**Comment by climbfuji** [comment]
We may or may not be able to solve this problem with spack-stack-1.4.0.

I see from your log file that it is complaining about the Python interpreter:
```
-- [iodaconv] (0.0.1) [e5c6e8d]
-- Feature TESTS enabled
CMake Error at /autofs/ncrc-svm1_sw/gaea-c5/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/cmake-3.23.1-d2agejkeecr2btxpcjoaaab3tyoe42ax/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Python3 (missing: Development Development.Module
  Development.Embed) (found version "3.10.8")
```

As you can see, it finds "some" version of Python 3.10.8. But, for spack-stack-1.4.0, we still relied on an external Python version (see /lustre/f2/dev/wpo/role.epic/contrib/spack-stack/spack-stack-1.4.0-c5/envs/unified-env-v2/site/packages.yaml), and that should be 3.9.12.

There are a few possibilities here:
1. You have a mix-up of Python versions in your environment
2. Somewhere there is a default 3.10.8 nowadays, and the old iodaconv code is simply looking for the newest version it can find. In this case, you can try to tell `cmake` which Python to use. I believe the command line syntax is
```
-DPython3_EXECUTABLE:FILEPATH=/sw/gaea-c5/spack-envs/base/opt/linux-sles15-x86_64/gcc-7.5.0/python-3.9.12-n7xlvqjslbeeaexdaibryhi7miqjjoa2/bin/python3
```

**Comment by jieshunzhu** [comment]
@climbfuji By specifying Python3_EXECUTABLE in cmake/ecbuild as you suggested, I am able to ecbuild and compile the soca-science I wanted with spack-stack-1.4.0. Thanks for the help.

**Comment by climbfuji** [comment]
Thanks for letting me know, glad it's working!
