### ISSUE TITLE
Derecho requires additional environment variable set (sometimes).

### ISSUE THREAD

**Issue by byoung-joo** [JCSDA/spack-stack#957]
**Describe the bug**
I have built a mpas-bundle with a spack-stack v1.5 (gnu). I could run a simple DA test with 192 (96 x 2 nodes) or 180 (90 x 2 nodes) processors. When I tried to run with 256 processors (128 x 2 nodes), it gave the following message:
```
libfabric:154281:1705433813::cxi:core:cxip_ux_onload_cb():2393<warn> dec1643: RXC (0x39f1:70:0) PtlTE 234:[Fatal] LE resources not recovered during flow control. FI_CXI_RX_MATCH_MODE=[hybrid|software] is required
dec1643.hsn.de.hpc.ucar.edu: rank 55 died from signal 6 and dumped core
dec1664.hsn.de.hpc.ucar.edu: rank 128 died from signal 15
```
If I set` export FI_CXI_RX_MATCH_MODE=‘hybrid’` in runtime , it fixes the issue. I have asked CISL about this and please see the conversation here: https://ncarhpcusergroup.slack.com/archives/C0408SWRUDN/p1705439183692209 .

So I wonder if this environmental setting can be added in the JCSDA's spack-stack.   Or we can still set this in run-time as we are doing now.

 
**To Reproduce**

**Expected behavior**

**System:**
NCAR HPC, Derecho 

**Additional context**

**Comment by climbfuji** [comment]
Thanks @byoung-joo - do you know if we can set the env variable unconditionally, i.e. simply set it all the time?

**Comment by byoung-joo** [comment]
> do you know if we can set the env variable unconditionally, i.e. simply set it all the time?

No, I don't know about that...

**Comment by ulmononian** [comment]
@RatkoVasic-NOAA can you please take a look at this issue on derecho?

**Comment by climbfuji** [comment]
@byoung-joo FYI I checked with the Derecho admins whether we can set this variable all the time:
> We always have this set on our software stack based on discussions with HPE.  Of course it is possible that there is an application that exists that won't like the setting but we haven't seen it yet.

Based on that I'll issue a PR to include that in the Derecho settings. Stay tuned.

**Comment by byoung-joo** [comment]
Thank you, @climbfuji.

**Comment by ulmononian** [comment]
@climbfuji 

> Based on that I'll issue a PR to include that in the Derecho settings. Stay tune

just checking in on this to see if this fix will be addressed in the PR you mentioned?

**Comment by climbfuji** [comment]
Not yet done, but thanks for the reminder. I'll add it to one of my next PRs (not the update from spack/develop, that one is already gigantic).
