### ISSUE TITLE
py-contourpy intel@:19 conflict

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#959]
@climbfuji in the py-contourpy recipe, you added a conflict with intel@:19 related to C++17. I am not sure as to the details of the initial issue, however:
 - This conflict creates a problem on Acorn, because I'm building intel@19 and intel@2022, and this conflict causes it to revert to intel@2022, which is all well and good (and surprisingly doesn't mess up the dependents or dependencies), except it leads to a modulefile path collision. For now my workaround is to compile separate environments, which it would be nice to avoid.
 - I successfully compiled py-contourpy on Acorn with intel 19 just now, both with and without supplemental gcc backend (10.2.0) in the build environment. Is there some way we can refine the restriction here? Or if that proves difficult, maybe make it a system-by-system setting instead of having the conflict in the recipe?

**Comment by climbfuji** [comment]
Hmm - looking at the notes in `package.py`:
```
    # py-contourpy uses c++-17 flags that cause a problem
    # with older Intel compilers (@19) in combination with
    # C++-17 capable backends (gnu@9:). Instead of trying
    # to figure out what gnu version the Intel compiler
    # uses as backend, simply refuse to build. See also:
    # https://bitbucket.org/berkeleylab/upcxx/issues/302/build-failure-for-intel-c-with-std-c-17
```
and the link in there https://bitbucket.org/berkeleylab/upcxx/issues/302/build-failure-for-intel-c-with-std-c-17 it's quite likely that this is only an issue with `gnu@9` as backend. The problem is then how to write the `conflicts` statement, because there is no simple spack-way to infer the `gnu` backend version. Maybe inqure it via a system call to `gcc --version` and then restrict the conflict to versions 9.x ?

**Comment by climbfuji** [comment]
I do remember having seen this problem somewhere else in the past ... maybe poking around in the package recipes might be useful.

**Comment by AlexanderRichert-NOAA** [comment]
That sounds good. If I can get the logic working then we can refine further as needed.

**Comment by AlexanderRichert-NOAA** [comment]
I am unable to reproduce the issue on Acorn with gcc 9.2.0 and 9.3.0... :thinking:

**Comment by climbfuji** [comment]
Wow. Wondering if it's because of the newer version. Looking at git blame, the latest version was added well after my bug fix: https://github.com/JCSDA/spack/blame/c7af00bb3c6d78f18e3db1190e3d50662b49abcf/var/spack/repos/builtin/packages/py-contourpy/package.py

**Comment by climbfuji** [comment]
Any updates on this? Should we constrain the conflict with `intel@19` to earlier versions of `py-contourpy` only?

**Comment by AlexanderRichert-NOAA** [comment]
That would be fine with me, and/or set up conflicts/requirements on a per-system basis as needed.
