### ISSUE TITLE
Cannot build against wgrib2api on Orion and Hercules (spack-stack 1.6.0)

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [JCSDA/spack-stack#962]
**Describe the bug**
When attempting to build gfs-utils on Orion or Hercules with wgrib2api.mod, the compiler is unable to find the module.  The gfs-utils branch used for this work is [DavidHuber-NOAA:feature/ss160](https://github.com/DavidHuber-NOAA/gfs-utils/tree/feature/ss160).  This version _does_ build on Hera.  The gfs-utils module that uses the API is [src/reg2grb2.fd/regdiag.f](https://github.com/DavidHuber-NOAA/gfs-utils/blob/eb8769c92c1bf27ac0aa32ea48bd192ecefbdd63/src/reg2grb2.fd/regdiag.f#L52).

**To Reproduce**
```
git clone git@github.com:DavidHuber-NOAA/gfs-utils -b feature/ss160
cd gfs-utils/ush
./build.sh
```

**Expected behavior**
gfs-utils would be able to build against wgrib2api on all platforms.

**System:**
Hercules (possibly others, but not Hera)

**Additional context**
Found while upgrading the global workflow to spack-stack version 1.6.0 (NOAA-EMC/global-workflow#2195).

**Comment by climbfuji** [comment]
I wonder if that's because the wgrib2 build failed silently. Previously, we had to pin wgrib to a newer version (3.1.1) to avoid build errors on Hercules. With the last release, this wasn't necessary, but perhaps this was a false positive and the 2.0.8 build failed silently without causing spack install to abort.

**Comment by climbfuji** [comment]
@DavidHuber-NOAA I'll start looking into this today

**Comment by climbfuji** [comment]
Well, after Hercules recovered from the power outage ... Orion is offline today, too.

**Comment by DavidHuber-NOAA** [comment]
This problem is also present on Orion.  I'll update the description.

**Comment by DavidHuber-NOAA** [comment]
Actually, it looks like the wrong version of wgrib2 is being loaded.  The gfs-utils modulefile requests version 2.0.8, but the system version 3.1.1 is being loaded instead, which does not include the wgrib2api.mod module.  I fixed this for Orion, but will need to work a little more on Hercules.  Closing this issue and will track further work in https://github.com/NOAA-EMC/gfs-utils/pull/43.
