### ISSUE TITLE
gsi-addon environment on gaea C5, f5 filesystem

### ISSUE THREAD

**Issue by jswhit** [JCSDA/spack-stack#964]
GSI needs bufr 11.7.0 (including the 64 bit libbufr_d), current spack-stack installations on gaea c5 (in the new /gpfs/f5 filesystem) only have  bufr 12.0.0.  https://github.com/JCSDA/spack-stack/issues/841 addressed this on the old f2 filesystem, but the gsi-addon environment doesn't yet exist for f5.

**Comment by jswhit** [comment]
Current spack-stacks just have unified-env (e.g. /ncrc/proj/epic/spack-stack/spack-stack-1.6.0/envs), which only includes bufr v12.

**Comment by climbfuji** [comment]
@RatkoVasic-NOAA @ulmononian Can you add the missing gsi-addon-env installations on Gaea F5 please (since you did the installs there)? Thanks very much in advance!

**Comment by RatkoVasic-NOAA** [comment]
Coming right up.

**Comment by climbfuji** [comment]
Awesome, thank you so much!

**Comment by RatkoVasic-NOAA** [comment]
gsi-addon's are added to spack-stack-1.5.1 and spack-stack-1.6.0
/ncrc/proj/epic/spack-stack/spack-stack-1.5.1/envs/gsi-addon/install/modulefiles/Core
/ncrc/proj/epic/spack-stack/spack-stack-1.6.0/envs/gsi-addon-dev/install/modulefiles/Core

**Comment by climbfuji** [comment]
> gsi-addon's are added to spack-stack-1.5.1 and spack-stack-1.6.0 /ncrc/proj/epic/spack-stack/spack-stack-1.5.1/envs/gsi-addon/install/modulefiles/Core /ncrc/proj/epic/spack-stack/spack-stack-1.6.0/envs/gsi-addon-dev/install/modulefiles/Core

Thanks a lot @RatkoVasic-NOAA! @jswhit Please check and if ok, close the issue.

**Comment by jswhit2** [comment]
How do I load bufr/11.7.0?

I tried 

module use /ncrc/proj/epic/spack-stack/spack-stack-1.5.1/envs/unified-env/install/modulefiles/Core
module use /ncrc/proj/epic/spack-stack/spack-stack-1.5.1/envs/gsi-addon/install/modulefiles/Core
module load stack-intel/2023.1.0
module load stack-cray-mpich/8.1.25
module load bufr/11.7.0

and I get 

Lmod has detected the following error:  These module(s) or extension(s) exist but cannot be loaded as requested:
"bufr/11.7.0"
   Try: "module spider bufr/11.7.0" to see how to load the module(s).

**Comment by RatkoVasic-NOAA** [comment]
@jswhit thanks for checking this. I'll try to reinstall addon for 1.5.1
BTW, have you tried 1.6.0 as well?

**Comment by climbfuji** [comment]
> @jswhit thanks for checking this. I'll try to reinstall addon for 1.5.1 BTW, have you tried 1.6.0 as well?

Please don't forget the `--upstream-modules` when running `spack module tcl refresh` on gaea

**Comment by climbfuji** [comment]
and then run `spack stack setup-meta-modules`

**Comment by RatkoVasic-NOAA** [comment]
@climbfuji I was running this:
```
spack concretize
spack install  --verbose
spack module lmod refresh
spack stack setup-meta-modules

```

**Comment by climbfuji** [comment]
> @climbfuji I was running this:
> 
> ```
> spack concretize
> spack install  --verbose
> spack module lmod refresh
> spack stack setup-meta-modules
> ```

Oops, you are correct, c5 uses lmod - but when installing a chained env you ALWAYS need to use `spack module lmod refresh --upstream-modules` (no matter which platform)

**Comment by RatkoVasic-NOAA** [comment]
I got it. I'll add --upstream-modules

**Comment by RatkoVasic-NOAA** [comment]
@jswhit thanks to @climbfuji I added `--upstream-modules` to installation and it looks it works now:
```
Gaea:/ncrc/home2/Ratko.Vasic>module use /ncrc/proj/epic/spack-stack/spack-stack-1.5.1/envs/unified-env/install/modulefiles/Core
Gaea:/ncrc/home2/Ratko.Vasic>module use /ncrc/proj/epic/spack-stack/spack-stack-1.5.1/envs/gsi-addon/install/modulefiles/Core
Gaea:/ncrc/home2/Ratko.Vasic>module load stack-intel/2023.1.0

The following have been reloaded with a version change:
  1) intel-classic/2022.2.1 => intel-classic/2023.1.0

Gaea:/ncrc/home2/Ratko.Vasic>module load stack-cray-mpich/8.1.25
Gaea:/ncrc/home2/Ratko.Vasic>module load bufr/11.7.0
Gaea:/ncrc/home2/Ratko.Vasic>

```

**Comment by jswhit2** [comment]
@RatkoVasic-NOAA this works now, thank you

**Comment by climbfuji** [comment]
The same is probably needed on Orion to resolve #952

**Comment by climbfuji** [comment]
Thanks for fixing this @RatkoVasic-NOAA

**Comment by RatkoVasic-NOAA** [comment]
> The same is probably needed on Orion to resolve #952

I'll go there and check i out.
I guess they are doing something on Orion, I cannot login, I should look at that later.

**Comment by RatkoVasic-NOAA** [comment]
Done on Orion.
