### ISSUE TITLE
Build unified-env with oneAPI 2024 compilers (aka many packages don't build with oneAPI compilers)

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack-stack#969]
**Describe the bug**
This is in addition to the wgrib2 issue I posted (#967).

There's a list of packages that don't build with the oneAPI compilers 2024.0.2. Updated list after switching to `ifx` instead of `ifort` (because the Python `meson` builder doesn't accept spack compiler flags and trips over the deprecation messages from `ifort`):
```
ai-env-1.0.0-juvu3nik2oqc3tyl3xcsgo7nglecfk2c
ewok-env-1.0.0-cx4jzlczhau3qk45vza3omszgy62a5bd
fms-2023.04-tn6g4hdumwnbwhlykds5acbd7toocgfk
gdal-3.8.3-p6iatrs32e6q7hrkmolzxgvfu6nctxhq
gfsio-1.4.1-mcg3mb3qmgrsaan5tvfjsnkquukg4zd7
global-workflow-env-1.0.0-upb53g4iru5anqukigiw6l3vpc2ey22p
gmao-swell-env-1.0.0-cquu3az5m4hg2b3n2pcijqbhqekf4ccl
grib-util-1.3.0-fbhkry6znyjhgsp34etba7f77utvsohe
gsi-env-1.0.0-dtodfhlos6a5juvha7tug5n7ju4onmz2
jedi-base-env-1.0.0-m5cg44j276uvy6q6vagwgseuv2hqhhv5
jedi-fv3-env-1.0.0-x5s5xtq3bjlngkfyzryaghhxwadae2q3
jedi-geos-env-1.0.0-2wipr3k7iqzb5y5tnho4zczo4c24gvds
jedi-mpas-env-1.0.0-rs5xmdtqjlpj4xtpslqdcm6hg5ovlbi2
jedi-neptune-env-1.0.0-4z7kdwdn6pkxzldlfqppuhpy6fmllmjx
jedi-tools-env-1.0.0-pmzcvsyysygcebfixepaasxlkh3gnfnb
jedi-ufs-env-1.0.0-vt7pgktu5u4jjpy3uhd7jhkdsfeq6fhx
jedi-um-env-1.0.0-4dlsyqaozn5sibyndryflco7vsq243bj
landsfcutil-2.4.1-z7io4g7ccdfhjfewmzdyfrhxjdlxfxri
mapl-2.40.3-f2pmar2sy3sfsivampru23kl5sm6b6ld
met-11.1.0-wfkyd4kqjzkavjqcftvvhvasg3um7efz
metplus-5.1.0-4z353ifekeymyxf2iggimmjcbomai3g5
py-cartopy-0.21.1-2bwaccqbxmjq4o7g4uwwfn34wvolhv2c
py-networkx-3.1-ow75t7mfx6f4ukptwjtv3j3g3dops7na
py-pandas-1.5.3-qpvhapy7fywnusiugkb5tjpj5dynt7na
py-torch-2.1.2-h4bubyoloaxtkwzf7tdn5jui2n662rcw
py-xarray-2023.7.0-tjvaimmrsrc62lpcvallnz4szjo25hie
sfcio-1.4.1-mjvs2ifapl6ulr3aeuibec3o4qwo6quv
sigio-2.3.2-hiv4tdfwdmwt6ubl54b4no6i25i4jysh
soca-env-1.0.0-iklom4kp3topbddcuyzibwalbzdmedwm
ufs-pyenv-1.0.0-pnhke3ht6rtcndfcl7jzkso54exzjxnz
ufs-srw-app-env-1.0.0-arz4cg54i7pprqqedvsn4obfpu364ury
ufs-weather-model-env-1.0.0-lvj3mp2kufgr2wwo26b2q6lj5vrc2ffe
w3nco-2.4.1-cfrrf6gpqqhcquijv4wf5i3a3u3pasph
wgrib2-2.0.8-qlozqyttr5xmme4ox42xoyhosjy3xe3s
```

Note that some of these failures look like weird bison/flex parsing errors - maybe bison/flex need to be fixed instead?

**To Reproduce**
Build unified-environment with oneAPI 2024.0+ compilers

**Expected behavior**
Entire stack builds with oneAPI compilers

**System:**
AWS ParalleCluster (Ubuntu 22.04) using OS gcc@11.4.0 as backend and Intel oneAPI 2024.0.2 (icx, icpx, ifx)

**Additional context**
n/a

**Comment by ulmononian** [comment]
@climbfuji is this only happening on the AWS ParallelCluster (Ubuntu 22.04) or other machines, too? i do recall some bison issues with scotch, at least.

**Comment by climbfuji** [comment]
I don't have access to any other machine with oneapi 2024.0.2 installed at the moment (and no time to install and test this elsewhere unfortunately)

**Comment by climbfuji** [comment]
This is a duplicate of https://github.com/JCSDA/spack-stack/issues/912 - I added the information from this epic (969) to 912 as a comment, closing 969 as "not planned".
