### ISSUE TITLE
Building UFS Weather Model with custom spack-stack

### ISSUE THREAD

**Issue by dustinswales** [JCSDA/spack-stack#992]
To enable GPU functionality within the UFS, the GNU compiler (and openmpi) need to be rebuilt with the [Nvidia PTX option](https://gcc.gnu.org/onlinedocs/gcc/Nvidia-PTX-Options.html). Subsequently, a new spack-stack needs to be created using gnu and openmpi.

On Hera, I was able to build and install this new stack, but ran into problems when building the UFS Weather Model.

To create the stack,[following section 6.1.4:](https://spack-stack.readthedocs.io/en/latest/NewSiteConfigs.html#creating-a-new-environment)
> cd /scratch1/BMC/gmtb/Dustin.Swales/libs
> source ./Hera_setup.csh
> git clone -b release/1.5.1--recurse-submodules https://github.com/JCSDA/spack-stack
> cd spack-stack
> exec bash -l						                 - Switch to bash shell
> . setup.sh
> emacs -nw configs/sites/hera/compilers.yaml	**_- Add personal gcc-nvptx and openmpi_**
> emacs -nw configs/sites/hera/packages.yaml	**_- Switch gcc/gnu-11.3.0 openmpi-4.1.1_**
> spack stack create env --site hera --template ufs-weather-model --name ufs-weather-model-gpu.hera
> cd envs/ufs-weather-model-gpu.hera/
> spack env activate .
> spack concretize
> spack install --source --verbose 2>&1 | tee log.install
> spack module lmod refresh
> spack stack setup-meta-modules

Then to build the UFS using this stack:
> cd  /scratch1/BMC/gmtb/Dustin.Swales/UFS/spack-stack
> git clone --recursive https://github.com/ufs-community/ufs-weather-model.git
> cd ufs-weather-model/
> ml cmake
> module use /scratch1/BMC/gmtb/Dustin.Swales/libs/spack-stack/envs/ufs-weather-model-gpu2.hera/install/modulefiles/Core
> module use /scratch2/BMC/gsd-hpcs/Daniel.Abdi/gnu/modulefiles/base
> ml gcc-nvptx/11.3.0
> ml openmpi/4.1.1
> ml stack-gcc/11.3.0
> setenv CMAKE_FLAGS "-DAPP=ATM -DCCPP_SUITES=FV3_GFS_v16"
> ./build.sh

Here the build fails. Can't find the netCDF libraries.
I can see that the netcdf libraries, and all the other dependencies, are being built with my stack, so I must be doing something wrong, missing a step, or?

**Comment by climbfuji** [comment]
You are not loading any of the libraries, just the compiler and mpi?

**Comment by dustinswales** [comment]
> You are not loading any of the libraries, just the compiler and mpi?

Correct. I tried following [this](https://spack-stack.readthedocs.io/en/latest/UsingSpackEnvironments.html), but this assumes that I'm using a "functioning" spack-stack, which may not be true.

**Comment by climbfuji** [comment]
Basically, all you need to do is to load the stack-COMPILER, stack-MPI, stack-PYTHON, then load ufs-weather-model-env, then do `mkdir build && cd build && cmake ALL_THE_OPTIONS`.

If this doesn't work, can you please check with @RatkoVasic-NOAA and/or @AlexanderRichert-NOAA ?

**Comment by dustinswales** [comment]
After some discussion with Nvidia developers, it seems that this GNU extension was possibly a one-off and is quite behind the current Nvidia HPC SDK.
