### ISSUE TITLE
[INSTALL]: libtorch/pytorch

### ISSUE THREAD

**Issue by guillaumevernieres** [JCSDA/spack-stack#994]
### Package name

torch/pytorch

### Package version/tag

2.2.0

### Build options

No cuda, cpu only for now

### Installation timeframe

The sooner the better!
Installed on Hera, Orion and container. Intel would be nice, but I have not been successful in completing an intel build. GNU was straight forward (for the most part).

### Other information

WCOSS2 support would be nice at some point.

### WCOSS2

- [x] Check this box if and only if your package should be installed on WCOSS2 Cactus and Dogwood (all spack-stack packages will be installed on Acorn). If not, you may disregard the rest of the items below and submit this request.

### WCOSS2: Technical & security review list

- [x] The code is mature, stable, and production ready
- [ ] The code is does not and cannot use the internet, and does not contain URLs (http, https, ftp, etc.) except in comments
- [ ] The package does not contain prebuilt binary files that have not been approved by NCO security review
- [ ] The code has no publicly disclosed cybersecurity vulnerabilities and exposures (search https://cve.mitre.org/cve/)
- [x] The code is not prohibited by DHS, DOC, NOAA, or NWS
- [ ] The code comes from a trusted source. Trusted sources include other NWS, NOAA, or DOC, agencies, or other Federal agencies that operate at a FISMA high or equivalent level. Additionally, trusted sources could be third-party agencies through which there is an existing SLA on file (such as RedHat).
- [x] The code is actively maintained and supported (it continues to get updates, patches, etc.)
- [x] The code is not maintained by a private entity operating in a foreign country (if it is, make a note below)
- [x] There is sufficient documentation to support maintenance
- [x] There are no known security vulnerabilities or weaknesses
- [x] Installing and running the code does not require privileged processes/users
- [ ] There are no software dependencies that are unapproved or have security concerns (if there are, make a note below)
- [ ] There are no concerns related to SA, SI, and SC NIST control families

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA @Hang-Lei-NOAA Note the "WCOSS2 support would be nice at some point" in the above request. Not urgent, but you may want to start the request once we have it in spack-stack for the RDHPCS machines.

@AlexanderRichert-NOAA Do you want to take this on or should I? It's for EMC and JCSDA likewise.

**Comment by guillaumevernieres** [comment]
I don't know if that's helpful, but these are the options I used on Orion/gnu:
```
cmake -DUSE_CUDA=OFF -DUSE_CUDNN=OFF -DUSE_NCCL=OFF -DBUILD_CAFFE2_OPS=OFF -DUSE_MKLDNN=OFF -DUSE_DISTRIBUTED=ON -DCMAKE_INSTALL_PREFIX=...
```
and the `build` / `CMakeCache.txt`:
```
/work/noaa/da/gvernier/ai/pytorch-v2.1.2/build/CMakeCache.txt
```

**Comment by AlexanderRichert-NOAA** [comment]
@guillaumevernieres to get things rolling for WCOSS2, can you please fill out the checklist to the best of your ability?
@Hang-Lei-NOAA FYI...

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres to get things rolling for WCOSS2, can you please fill out the checklist to the best of your ability? @Hang-Lei-NOAA FYI...

Will do @AlexanderRichert-NOAA .

**Comment by climbfuji** [comment]
As far as creating a test installation on one platform is concerned: my plan is to work on this after my current PR #993 is merged.

**Comment by guillaumevernieres** [comment]
> As far as creating a test installation on one platform is concerned: my plan is to work on this after my current PR #993 is merged.

Sounds good. Thanks @climbfuji .

**Comment by climbfuji** [comment]
@guillaumevernieres Just to let you know that I started working on this yesterday. I've hit some problems with incompatible py-protobuf versions for `py-torch` and `cylc-flow`, and also build errors on Ubuntu with Intel. I'll keep you posted.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres Just to let you know that I started working on this yesterday. I've hit some problems with incompatible py-protobuf versions for `py-torch` and `cylc-flow`, and also build errors on Ubuntu with Intel. I'll keep you posted.

Thanks for the update @climbfuji . How about not building the python API (-DBUILD_PYTHON=OFF)? I don't know why `cylc-flow` is part of the build, but I'm pretty sure we wouldn't need this feature.

**Comment by climbfuji** [comment]
I assume you refer to not building the Python API for `cylc`? Wouldn't that preclude building the `cylc` UI, which uses `py-jupyter-server`. `cylc` is in spack-stack because several of JCSDA's partners are using it or are looking into using it, and JCSDA is also considering switching to `cylc` due to its superior handling of cross-cycle dependencies.

Regardless, there are build errors for the particular version of `py-protobuf` that `py-torch` wants, so even if we get the two packages `cylc` and `py-torch` to coexist (which I think is quite possible), then we still can't build `py-torch`.

**Comment by guillaumevernieres** [comment]
No, I meant not building the python API at all.

**Comment by travissluka** [comment]
@climbfuji I think what @guillaumevernieres is trying to say is: can we build torch without the pytorch python API bindings? I think we are only using the C interface for torch (is that right G?). Having the Python part of torch would be handy in the future, but is not essential right now

**Comment by climbfuji** [comment]
I'll look into that. There's also an option to use an internal/vendored version of protobuf/py-protobuf, which might be a better solution.

**Comment by guillaumevernieres** [comment]
> I'll look into that. There's also an option to use an internal/vendored version of protobuf/py-protobuf, which might be a better solution.

Not sure why we don't see @travissluka 's message, a glitch in the matrix!
But yes to what he said. We don't need the python binding, at least not at first.

**Comment by travissluka** [comment]
> > I'll look into that. There's also an option to use an internal/vendored version of protobuf/py-protobuf, which might be a better solution.
> 
> Not sure why we don't see @travissluka 's message, a glitch in the matrix!
> But yes to what he said. We don't need the python binding, at least not at first. 

I think I accidentally hit delete... I clearly shouldn't check GitHub before 6am

**Comment by climbfuji** [comment]
FYI here is the spack bug I filed for protobuf: https://github.com/spack/spack/issues/43054

**Comment by Hang-Lei-NOAA** [comment]
Upon my inquiry of the libtorch/pytorch on wcoss2 with NCO. This has to be associated with the operational development. So, the frist step: we need a complete proof to show it is required for operational use, and get support from EMC federal side.  Then second, detailed code review can start.

**Comment by climbfuji** [comment]
Installed on all platforms that use the GNU compilers.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres to get things rolling for WCOSS2, can you please fill out the checklist to the best of your ability? @Hang-Lei-NOAA FYI...

Any updates on this @AlexanderRichert-NOAA ?

**Comment by Hang-Lei-NOAA** [comment]
@guillaumevernieres Upon our initial inquiry, this is not approved by NCO.
Therefore, we have to apply for the code review. 
Before going to that step, please prepare following questions, and make sure that is required in our operational models:
(1) Demonstrate the necessity of the requested code.  
The functionality provided by the software is irreplaceable for operations. It is used by operational models. There is currently no existing NCEP code that offers comparable capabilities. or Insufficient time to develop. 
(2) Verify the software license and developer credentials.
The software is developed by U.S. or security approved agencies. License is required and acceptable.
(3) Carefully go through the source code to check if it meets the requirements. (EE2, FISMA, additional requirements from NCO).
A line by line check to see if any outreach code or unnecessary functions need to be removed.
(4) Validate the building script to ensure compatibility with the operational machine environment.

**Comment by Hang-Lei-NOAA** [comment]
Since I used using py-torch on google's machines.
As I examined these issues, I feel very difficult to proceed. 
(1) I did not see any our operational model or ones under development use this package.
(2) It is working under Anaconda environment, which was not approved by NCO. (We used to push these python env to NCO, was declined). Then we have to think about install without [Anaconda]. 
(3) License, and outreach in code may not meet the EE2 and FISMA requirements. It has to been explained in the code review.

**Comment by aerorahul** [comment]
The requirements for pytorch are seen easily in [requirements.txt](https://github.com/pytorch/pytorch/blob/main/requirements.txt)
Pytorch recommends Anaconda, but it is not required.  It can be installed from source with instructions [here](https://github.com/pytorch/pytorch?tab=readme-ov-file#from-source)

**Comment by JacobCarley-NOAA** [comment]
@aerorahul thanks for sending those helpful details.
@Hang-Lei-NOAA pytorch/libtorch is almost certainly something that will be required for us to do AI/ML work. Even if the process is going to take some time to work through I think it's best we start now and chip away at it.

**Comment by guillaumevernieres** [comment]
> @aerorahul thanks for sending those helpful details. @Hang-Lei-NOAA pytorch/libtorch is almost certainly something that will be required for us to do AI/ML work. Even if the process is going to take some time to work through I think it's best we start now and chip away at it.

@JacobCarley-NOAA , the requirements that @aerorahul posted above are for python. In addition to that, we need to also look at the other problematic fractal of dependencies. It starts here:
 https://github.com/pytorch/pytorch/blob/main/.gitmodules
 
 Happy to help build a minimalist library with gcc if that can help. I remember turning off quite a few optional dependencies.

**Comment by Hang-Lei-NOAA** [comment]
@JacobCarley-NOAA @aerorahul Thanks, We can install that version. Our developers need to know what they can work and make sure that way will match their demands. This would be a unique solution to wcoss2 that differs from spack-stack on other RDHPCS. For a profound view, we may plan a long term python approach to follow. As I know in the past many years, NCO support python 3 series. However, our developers have requested many different python environment, like miniconda, Anaconda, etc. If our development work use a unified, e.g. python 3, that will be more consistent for future.  

@guillaumevernieres Please prepare the settings for the environment that you need. We may based all on python 3. We can have a meeting next Monday for details. The code review will have to answer a series of questions and we have to find out a solution to insert into current operational environment. You participation is important. Thanks.
