### ISSUE TITLE
Hera spack-stack-1.5.1 broken after update to Rocky 8

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [JCSDA/spack-stack#998]
**Describe the bug**
cmake and git commands installed through spack-stack-1.5.1 failing with undefined symbol errors after Rocky upgrade.

**To reproduce**
On hfe[09-12]: `/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.5.1/envs/unified-env/install/intel/2021.5.0/git-2.40.0-aaeeccm/libexec/git-core/git-remote-https`

I haven't yet checked other releases, I assume we will see similar issues. I can build a working git by removing the external curl and rebuilding on Rocky.

**Comment by climbfuji** [comment]
This is w/o rebuilding the code?

**Comment by AlexanderRichert-NOAA** [comment]
Correct (I clarified the description)

**Comment by ulmononian** [comment]
fyi @RatkoVasic-NOAA 

sounds like we will probably need to rebuild the stacks since all hera nodes will move to rocky 8 by april 2, 2024, but testing on hfe[09-12] would be a good start.

**Comment by AlexanderRichert-NOAA** [comment]
unified-env rebuilt as unified-env-rocky8 for 1.5.1. See https://github.com/JCSDA/spack-stack/issues/1005
